/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as TermsRouteImport } from './app/routes/terms'
import { Route as PrivacyRouteImport } from './app/routes/privacy'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthRouteImport } from './app/routes/_auth'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthWritingRouteImport } from './app/routes/_auth.writing'
import { Route as AuthVocabularyRouteImport } from './app/routes/_auth.vocabulary'
import { Route as AuthReadingRouteImport } from './app/routes/_auth.reading'
import { Route as AuthProfileRouteImport } from './app/routes/_auth.profile'
import { Route as AuthPlacementRouteImport } from './app/routes/_auth.placement'
import { Route as AuthListeningRouteImport } from './app/routes/_auth.listening'
import { Route as AuthGrammarRouteImport } from './app/routes/_auth.grammar'
import { Route as AuthFriendsRouteImport } from './app/routes/_auth.friends'
import { Route as AuthExploreRouteImport } from './app/routes/_auth.explore'
import { Route as AuthDrillsRouteImport } from './app/routes/_auth.drills'
import { Route as AuthDictionaryRouteImport } from './app/routes/_auth.dictionary'
import { Route as AuthDashboardRouteImport } from './app/routes/_auth.dashboard'
import { Route as AuthConversationRouteImport } from './app/routes/_auth.conversation'
import { Route as AuthConjugationRouteImport } from './app/routes/_auth.conjugation'
import { Route as AuthAdminRouteImport } from './app/routes/_auth.admin'
import { Route as AuthAchievementsRouteImport } from './app/routes/_auth.achievements'
import { Route as AuthWritingSlugRouteImport } from './app/routes/_auth.writing.$slug'
import { Route as AuthUTagRouteImport } from './app/routes/_auth.u.$tag'
import { Route as AuthReadingSlugRouteImport } from './app/routes/_auth.reading.$slug'
import { Route as AuthListeningIdRouteImport } from './app/routes/_auth.listening.$id'
import { Route as AuthGrammarSlugRouteImport } from './app/routes/_auth.grammar.$slug'
import { Route as AuthDrillsSlugRouteImport } from './app/routes/_auth.drills.$slug'
import { Route as AuthWritingResultIdRouteImport } from './app/routes/_auth.writing.result.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWritingRoute = AuthWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVocabularyRoute = AuthVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReadingRoute = AuthReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlacementRoute = AuthPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListeningRoute = AuthListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGrammarRoute = AuthGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFriendsRoute = AuthFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExploreRoute = AuthExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDrillsRoute = AuthDrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictionaryRoute = AuthDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationRoute = AuthConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConjugationRoute = AuthConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAchievementsRoute = AuthAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWritingSlugRoute = AuthWritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthWritingRoute,
} as any)
const AuthUTagRoute = AuthUTagRouteImport.update({
  id: '/u/$tag',
  path: '/u/$tag',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReadingSlugRoute = AuthReadingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthReadingRoute,
} as any)
const AuthListeningIdRoute = AuthListeningIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthListeningRoute,
} as any)
const AuthGrammarSlugRoute = AuthGrammarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthGrammarRoute,
} as any)
const AuthDrillsSlugRoute = AuthDrillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthDrillsRoute,
} as any)
const AuthWritingResultIdRoute = AuthWritingResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => AuthWritingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthAchievementsRoute
  '/admin': typeof AuthAdminRoute
  '/conjugation': typeof AuthConjugationRoute
  '/conversation': typeof AuthConversationRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionary': typeof AuthDictionaryRoute
  '/drills': typeof AuthDrillsRouteWithChildren
  '/explore': typeof AuthExploreRoute
  '/friends': typeof AuthFriendsRoute
  '/grammar': typeof AuthGrammarRouteWithChildren
  '/listening': typeof AuthListeningRouteWithChildren
  '/placement': typeof AuthPlacementRoute
  '/profile': typeof AuthProfileRoute
  '/reading': typeof AuthReadingRouteWithChildren
  '/vocabulary': typeof AuthVocabularyRoute
  '/writing': typeof AuthWritingRouteWithChildren
  '/drills/$slug': typeof AuthDrillsSlugRoute
  '/grammar/$slug': typeof AuthGrammarSlugRoute
  '/listening/$id': typeof AuthListeningIdRoute
  '/reading/$slug': typeof AuthReadingSlugRoute
  '/u/$tag': typeof AuthUTagRoute
  '/writing/$slug': typeof AuthWritingSlugRoute
  '/writing/result/$id': typeof AuthWritingResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthAchievementsRoute
  '/admin': typeof AuthAdminRoute
  '/conjugation': typeof AuthConjugationRoute
  '/conversation': typeof AuthConversationRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionary': typeof AuthDictionaryRoute
  '/drills': typeof AuthDrillsRouteWithChildren
  '/explore': typeof AuthExploreRoute
  '/friends': typeof AuthFriendsRoute
  '/grammar': typeof AuthGrammarRouteWithChildren
  '/listening': typeof AuthListeningRouteWithChildren
  '/placement': typeof AuthPlacementRoute
  '/profile': typeof AuthProfileRoute
  '/reading': typeof AuthReadingRouteWithChildren
  '/vocabulary': typeof AuthVocabularyRoute
  '/writing': typeof AuthWritingRouteWithChildren
  '/drills/$slug': typeof AuthDrillsSlugRoute
  '/grammar/$slug': typeof AuthGrammarSlugRoute
  '/listening/$id': typeof AuthListeningIdRoute
  '/reading/$slug': typeof AuthReadingSlugRoute
  '/u/$tag': typeof AuthUTagRoute
  '/writing/$slug': typeof AuthWritingSlugRoute
  '/writing/result/$id': typeof AuthWritingResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/achievements': typeof AuthAchievementsRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/conjugation': typeof AuthConjugationRoute
  '/_auth/conversation': typeof AuthConversationRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dictionary': typeof AuthDictionaryRoute
  '/_auth/drills': typeof AuthDrillsRouteWithChildren
  '/_auth/explore': typeof AuthExploreRoute
  '/_auth/friends': typeof AuthFriendsRoute
  '/_auth/grammar': typeof AuthGrammarRouteWithChildren
  '/_auth/listening': typeof AuthListeningRouteWithChildren
  '/_auth/placement': typeof AuthPlacementRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/reading': typeof AuthReadingRouteWithChildren
  '/_auth/vocabulary': typeof AuthVocabularyRoute
  '/_auth/writing': typeof AuthWritingRouteWithChildren
  '/_auth/drills/$slug': typeof AuthDrillsSlugRoute
  '/_auth/grammar/$slug': typeof AuthGrammarSlugRoute
  '/_auth/listening/$id': typeof AuthListeningIdRoute
  '/_auth/reading/$slug': typeof AuthReadingSlugRoute
  '/_auth/u/$tag': typeof AuthUTagRoute
  '/_auth/writing/$slug': typeof AuthWritingSlugRoute
  '/_auth/writing/result/$id': typeof AuthWritingResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/achievements'
    | '/admin'
    | '/conjugation'
    | '/conversation'
    | '/dashboard'
    | '/dictionary'
    | '/drills'
    | '/explore'
    | '/friends'
    | '/grammar'
    | '/listening'
    | '/placement'
    | '/profile'
    | '/reading'
    | '/vocabulary'
    | '/writing'
    | '/drills/$slug'
    | '/grammar/$slug'
    | '/listening/$id'
    | '/reading/$slug'
    | '/u/$tag'
    | '/writing/$slug'
    | '/writing/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/achievements'
    | '/admin'
    | '/conjugation'
    | '/conversation'
    | '/dashboard'
    | '/dictionary'
    | '/drills'
    | '/explore'
    | '/friends'
    | '/grammar'
    | '/listening'
    | '/placement'
    | '/profile'
    | '/reading'
    | '/vocabulary'
    | '/writing'
    | '/drills/$slug'
    | '/grammar/$slug'
    | '/listening/$id'
    | '/reading/$slug'
    | '/u/$tag'
    | '/writing/$slug'
    | '/writing/result/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_auth/achievements'
    | '/_auth/admin'
    | '/_auth/conjugation'
    | '/_auth/conversation'
    | '/_auth/dashboard'
    | '/_auth/dictionary'
    | '/_auth/drills'
    | '/_auth/explore'
    | '/_auth/friends'
    | '/_auth/grammar'
    | '/_auth/listening'
    | '/_auth/placement'
    | '/_auth/profile'
    | '/_auth/reading'
    | '/_auth/vocabulary'
    | '/_auth/writing'
    | '/_auth/drills/$slug'
    | '/_auth/grammar/$slug'
    | '/_auth/listening/$id'
    | '/_auth/reading/$slug'
    | '/_auth/u/$tag'
    | '/_auth/writing/$slug'
    | '/_auth/writing/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/writing': {
      id: '/_auth/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AuthWritingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vocabulary': {
      id: '/_auth/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthVocabularyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reading': {
      id: '/_auth/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AuthReadingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/placement': {
      id: '/_auth/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof AuthPlacementRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listening': {
      id: '/_auth/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthListeningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/grammar': {
      id: '/_auth/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthGrammarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/friends': {
      id: '/_auth/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthFriendsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/explore': {
      id: '/_auth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthExploreRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drills': {
      id: '/_auth/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof AuthDrillsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictionary': {
      id: '/_auth/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AuthDictionaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversation': {
      id: '/_auth/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof AuthConversationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conjugation': {
      id: '/_auth/conjugation'
      path: '/conjugation'
      fullPath: '/conjugation'
      preLoaderRoute: typeof AuthConjugationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/achievements': {
      id: '/_auth/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthAchievementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/writing/$slug': {
      id: '/_auth/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof AuthWritingSlugRouteImport
      parentRoute: typeof AuthWritingRoute
    }
    '/_auth/u/$tag': {
      id: '/_auth/u/$tag'
      path: '/u/$tag'
      fullPath: '/u/$tag'
      preLoaderRoute: typeof AuthUTagRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reading/$slug': {
      id: '/_auth/reading/$slug'
      path: '/$slug'
      fullPath: '/reading/$slug'
      preLoaderRoute: typeof AuthReadingSlugRouteImport
      parentRoute: typeof AuthReadingRoute
    }
    '/_auth/listening/$id': {
      id: '/_auth/listening/$id'
      path: '/$id'
      fullPath: '/listening/$id'
      preLoaderRoute: typeof AuthListeningIdRouteImport
      parentRoute: typeof AuthListeningRoute
    }
    '/_auth/grammar/$slug': {
      id: '/_auth/grammar/$slug'
      path: '/$slug'
      fullPath: '/grammar/$slug'
      preLoaderRoute: typeof AuthGrammarSlugRouteImport
      parentRoute: typeof AuthGrammarRoute
    }
    '/_auth/drills/$slug': {
      id: '/_auth/drills/$slug'
      path: '/$slug'
      fullPath: '/drills/$slug'
      preLoaderRoute: typeof AuthDrillsSlugRouteImport
      parentRoute: typeof AuthDrillsRoute
    }
    '/_auth/writing/result/$id': {
      id: '/_auth/writing/result/$id'
      path: '/result/$id'
      fullPath: '/writing/result/$id'
      preLoaderRoute: typeof AuthWritingResultIdRouteImport
      parentRoute: typeof AuthWritingRoute
    }
  }
}

interface AuthDrillsRouteChildren {
  AuthDrillsSlugRoute: typeof AuthDrillsSlugRoute
}

const AuthDrillsRouteChildren: AuthDrillsRouteChildren = {
  AuthDrillsSlugRoute: AuthDrillsSlugRoute,
}

const AuthDrillsRouteWithChildren = AuthDrillsRoute._addFileChildren(
  AuthDrillsRouteChildren,
)

interface AuthGrammarRouteChildren {
  AuthGrammarSlugRoute: typeof AuthGrammarSlugRoute
}

const AuthGrammarRouteChildren: AuthGrammarRouteChildren = {
  AuthGrammarSlugRoute: AuthGrammarSlugRoute,
}

const AuthGrammarRouteWithChildren = AuthGrammarRoute._addFileChildren(
  AuthGrammarRouteChildren,
)

interface AuthListeningRouteChildren {
  AuthListeningIdRoute: typeof AuthListeningIdRoute
}

const AuthListeningRouteChildren: AuthListeningRouteChildren = {
  AuthListeningIdRoute: AuthListeningIdRoute,
}

const AuthListeningRouteWithChildren = AuthListeningRoute._addFileChildren(
  AuthListeningRouteChildren,
)

interface AuthReadingRouteChildren {
  AuthReadingSlugRoute: typeof AuthReadingSlugRoute
}

const AuthReadingRouteChildren: AuthReadingRouteChildren = {
  AuthReadingSlugRoute: AuthReadingSlugRoute,
}

const AuthReadingRouteWithChildren = AuthReadingRoute._addFileChildren(
  AuthReadingRouteChildren,
)

interface AuthWritingRouteChildren {
  AuthWritingSlugRoute: typeof AuthWritingSlugRoute
  AuthWritingResultIdRoute: typeof AuthWritingResultIdRoute
}

const AuthWritingRouteChildren: AuthWritingRouteChildren = {
  AuthWritingSlugRoute: AuthWritingSlugRoute,
  AuthWritingResultIdRoute: AuthWritingResultIdRoute,
}

const AuthWritingRouteWithChildren = AuthWritingRoute._addFileChildren(
  AuthWritingRouteChildren,
)

interface AuthRouteChildren {
  AuthAchievementsRoute: typeof AuthAchievementsRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthConjugationRoute: typeof AuthConjugationRoute
  AuthConversationRoute: typeof AuthConversationRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDictionaryRoute: typeof AuthDictionaryRoute
  AuthDrillsRoute: typeof AuthDrillsRouteWithChildren
  AuthExploreRoute: typeof AuthExploreRoute
  AuthFriendsRoute: typeof AuthFriendsRoute
  AuthGrammarRoute: typeof AuthGrammarRouteWithChildren
  AuthListeningRoute: typeof AuthListeningRouteWithChildren
  AuthPlacementRoute: typeof AuthPlacementRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthReadingRoute: typeof AuthReadingRouteWithChildren
  AuthVocabularyRoute: typeof AuthVocabularyRoute
  AuthWritingRoute: typeof AuthWritingRouteWithChildren
  AuthUTagRoute: typeof AuthUTagRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAchievementsRoute: AuthAchievementsRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthConjugationRoute: AuthConjugationRoute,
  AuthConversationRoute: AuthConversationRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDictionaryRoute: AuthDictionaryRoute,
  AuthDrillsRoute: AuthDrillsRouteWithChildren,
  AuthExploreRoute: AuthExploreRoute,
  AuthFriendsRoute: AuthFriendsRoute,
  AuthGrammarRoute: AuthGrammarRouteWithChildren,
  AuthListeningRoute: AuthListeningRouteWithChildren,
  AuthPlacementRoute: AuthPlacementRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthReadingRoute: AuthReadingRouteWithChildren,
  AuthVocabularyRoute: AuthVocabularyRoute,
  AuthWritingRoute: AuthWritingRouteWithChildren,
  AuthUTagRoute: AuthUTagRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
