/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthRouteImport } from './app/routes/_auth'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthVocabularyRouteImport } from './app/routes/_auth.vocabulary'
import { Route as AuthProfileRouteImport } from './app/routes/_auth.profile'
import { Route as AuthPlacementRouteImport } from './app/routes/_auth.placement'
import { Route as AuthListeningRouteImport } from './app/routes/_auth.listening'
import { Route as AuthGrammarRouteImport } from './app/routes/_auth.grammar'
import { Route as AuthDictionaryRouteImport } from './app/routes/_auth.dictionary'
import { Route as AuthDashboardRouteImport } from './app/routes/_auth.dashboard'
import { Route as AuthConversationRouteImport } from './app/routes/_auth.conversation'
import { Route as AuthListeningIdRouteImport } from './app/routes/_auth.listening.$id'
import { Route as AuthGrammarSlugRouteImport } from './app/routes/_auth.grammar.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVocabularyRoute = AuthVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlacementRoute = AuthPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListeningRoute = AuthListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGrammarRoute = AuthGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictionaryRoute = AuthDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationRoute = AuthConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListeningIdRoute = AuthListeningIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthListeningRoute,
} as any)
const AuthGrammarSlugRoute = AuthGrammarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthGrammarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conversation': typeof AuthConversationRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionary': typeof AuthDictionaryRoute
  '/grammar': typeof AuthGrammarRouteWithChildren
  '/listening': typeof AuthListeningRouteWithChildren
  '/placement': typeof AuthPlacementRoute
  '/profile': typeof AuthProfileRoute
  '/vocabulary': typeof AuthVocabularyRoute
  '/grammar/$slug': typeof AuthGrammarSlugRoute
  '/listening/$id': typeof AuthListeningIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conversation': typeof AuthConversationRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionary': typeof AuthDictionaryRoute
  '/grammar': typeof AuthGrammarRouteWithChildren
  '/listening': typeof AuthListeningRouteWithChildren
  '/placement': typeof AuthPlacementRoute
  '/profile': typeof AuthProfileRoute
  '/vocabulary': typeof AuthVocabularyRoute
  '/grammar/$slug': typeof AuthGrammarSlugRoute
  '/listening/$id': typeof AuthListeningIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/conversation': typeof AuthConversationRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dictionary': typeof AuthDictionaryRoute
  '/_auth/grammar': typeof AuthGrammarRouteWithChildren
  '/_auth/listening': typeof AuthListeningRouteWithChildren
  '/_auth/placement': typeof AuthPlacementRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/vocabulary': typeof AuthVocabularyRoute
  '/_auth/grammar/$slug': typeof AuthGrammarSlugRoute
  '/_auth/listening/$id': typeof AuthListeningIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conversation'
    | '/dashboard'
    | '/dictionary'
    | '/grammar'
    | '/listening'
    | '/placement'
    | '/profile'
    | '/vocabulary'
    | '/grammar/$slug'
    | '/listening/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/conversation'
    | '/dashboard'
    | '/dictionary'
    | '/grammar'
    | '/listening'
    | '/placement'
    | '/profile'
    | '/vocabulary'
    | '/grammar/$slug'
    | '/listening/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/conversation'
    | '/_auth/dashboard'
    | '/_auth/dictionary'
    | '/_auth/grammar'
    | '/_auth/listening'
    | '/_auth/placement'
    | '/_auth/profile'
    | '/_auth/vocabulary'
    | '/_auth/grammar/$slug'
    | '/_auth/listening/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vocabulary': {
      id: '/_auth/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthVocabularyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/placement': {
      id: '/_auth/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof AuthPlacementRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listening': {
      id: '/_auth/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthListeningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/grammar': {
      id: '/_auth/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthGrammarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictionary': {
      id: '/_auth/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AuthDictionaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversation': {
      id: '/_auth/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof AuthConversationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listening/$id': {
      id: '/_auth/listening/$id'
      path: '/$id'
      fullPath: '/listening/$id'
      preLoaderRoute: typeof AuthListeningIdRouteImport
      parentRoute: typeof AuthListeningRoute
    }
    '/_auth/grammar/$slug': {
      id: '/_auth/grammar/$slug'
      path: '/$slug'
      fullPath: '/grammar/$slug'
      preLoaderRoute: typeof AuthGrammarSlugRouteImport
      parentRoute: typeof AuthGrammarRoute
    }
  }
}

interface AuthGrammarRouteChildren {
  AuthGrammarSlugRoute: typeof AuthGrammarSlugRoute
}

const AuthGrammarRouteChildren: AuthGrammarRouteChildren = {
  AuthGrammarSlugRoute: AuthGrammarSlugRoute,
}

const AuthGrammarRouteWithChildren = AuthGrammarRoute._addFileChildren(
  AuthGrammarRouteChildren,
)

interface AuthListeningRouteChildren {
  AuthListeningIdRoute: typeof AuthListeningIdRoute
}

const AuthListeningRouteChildren: AuthListeningRouteChildren = {
  AuthListeningIdRoute: AuthListeningIdRoute,
}

const AuthListeningRouteWithChildren = AuthListeningRoute._addFileChildren(
  AuthListeningRouteChildren,
)

interface AuthRouteChildren {
  AuthConversationRoute: typeof AuthConversationRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDictionaryRoute: typeof AuthDictionaryRoute
  AuthGrammarRoute: typeof AuthGrammarRouteWithChildren
  AuthListeningRoute: typeof AuthListeningRouteWithChildren
  AuthPlacementRoute: typeof AuthPlacementRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthVocabularyRoute: typeof AuthVocabularyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConversationRoute: AuthConversationRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDictionaryRoute: AuthDictionaryRoute,
  AuthGrammarRoute: AuthGrammarRouteWithChildren,
  AuthListeningRoute: AuthListeningRouteWithChildren,
  AuthPlacementRoute: AuthPlacementRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthVocabularyRoute: AuthVocabularyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
