/**
 * B1 expansion: +2258 words to reach Beacco hybrid ~3464.
 * Themes follow B1 CEFR: clear standard language on familiar matters,
 * basic abstract topics, opinions and arguments, society at surface.
 */
import type { Block } from './types.js';

export const blocks: Block[] = [
  { category: 'relationships', themeFr: 'Les relations humaines', description: 'Relationships at B1: friendship (ami proche, copain, connaissance, fidélité, confiance, soutien), romance (amour, couple, fiançailles, mariage, divorce, rupture, séparation), family dynamics (entente, conflit, dispute, réconciliation, soutien). Verbs: se confier, faire confiance, soutenir, trahir, pardonner, se réconcilier.', targetCount: 100 },
  { category: 'work-life', themeFr: 'La vie professionnelle', description: 'B1 work life: poste, fonction, responsabilité, mission, projet, équipe, collègue, supérieur, hiérarchie, promotion, formation continue, télétravail, présentiel, congés payés, RTT, primes, ambiance de travail, harcèlement, démission, licenciement, reconversion.', targetCount: 100 },
  { category: 'health-extended', themeFr: 'La santé (élargie)', description: 'B1 health: bien-être, prévention, dépistage, hygiène, alimentation équilibrée, sommeil, sport, stress, anxiété, dépression, thérapie, allergie, intolérance, asthme, diabète, hypertension, opération, anesthésie, consultation, urgences, médecine alternative.', targetCount: 100 },
  { category: 'media-press', themeFr: 'Les médias et la presse', description: 'B1 media: journal, magazine, hebdomadaire, mensuel, quotidien, rédaction, journaliste, reporter, chroniqueur, éditorial, gros titre, article, reportage, interview, enquête, scoop, rumeur, fake news, désinformation, source, vérification, censure.', targetCount: 100 },
  { category: 'tv-cinema-streaming', themeFr: 'La télévision, le cinéma, le streaming', description: 'B1 audiovisual: chaîne, programme, émission, série, feuilleton, documentaire, téléréalité, animateur, présentateur, candidat, audience, audimat, plateforme, abonnement, épisode, saison, suspense, intrigue, dénouement, acteur, réalisateur, scénariste, bande-annonce.', targetCount: 80 },
  { category: 'environment-basic', themeFr: 'L\'environnement (initiation)', description: 'B1 ecology: pollution, changement climatique, réchauffement, énergie renouvelable, tri sélectif, recyclage, déchets, plastique, biodiversité, espèce menacée, déforestation, océan, atmosphère, polluant, ozone, panneau solaire, éolienne, agriculture biologique, gaspillage.', targetCount: 80 },
  { category: 'technology-everyday', themeFr: 'La technologie au quotidien', description: 'B1 everyday tech: smartphone, application, mise à jour, connexion, wifi, données mobiles, écran tactile, charger, batterie, mot de passe, réseau social, publication, partage, abonné, message privé, notification, paramètre, confidentialité, piratage.', targetCount: 80 },
  { category: 'art-culture-intro', themeFr: 'Arts et culture (introduction)', description: 'B1 culture and arts: exposition, vernissage, galerie, musée, conservation, œuvre, tableau, sculpture, photographie, peintre, sculpteur, artiste, courant artistique, époque, antiquité, contemporain, classique, moderne, impressionniste, abstrait, figuratif, restauration.', targetCount: 80 },
  { category: 'sports-active', themeFr: 'Le sport (vie active)', description: 'B1 sports: entraînement, performance, compétition, tournoi, championnat, finale, victoire, défaite, équipe, supporter, arbitre, blessure, entorse, récupération, dopage, discipline, athlétisme, escalade, plongée, kayak, marathon, abonnement à la salle de sport.', targetCount: 70 },
  { category: 'food-cuisine-extended', themeFr: 'La cuisine et la gastronomie', description: 'B1 cuisine: recette, ingrédient, préparation, cuisson, friture, four, vapeur, mijoter, assaisonner, épice, condiment, sauce, marinade, dégustation, gourmand, copieux, équilibré, gourmet, terroir, spécialité régionale, vin, accord mets-vin.', targetCount: 80 },
  { category: 'shopping-consumption', themeFr: 'La consommation', description: 'B1 consumption: marque, label, qualité, garantie, service après-vente, livraison, retour, commerce en ligne, plateforme, comparateur, avis client, fidélité, programme, points, réduction, soldes, démarques, occasion, seconde main, neuf, durable.', targetCount: 70 },
  { category: 'housing-extended', themeFr: 'Le logement (élargi)', description: 'B1 housing: location, propriétaire, locataire, bail, loyer, caution, charges, copropriété, syndic, voisinage, immeuble, ascenseur, parking, cave, grenier, terrasse, jardin partagé, déménagement, emménagement, rénovation, isolation, chauffage central.', targetCount: 70 },
  { category: 'transport-extended-b1', themeFr: 'Les transports (B1)', description: 'B1 transport: itinéraire, embouteillage, déviation, péage, autoroute, nationale, départementale, code de la route, infraction, contravention, permis de conduire, assurance auto, location, véhicule électrique, hybride, covoiturage, vélo en libre-service.', targetCount: 70 },
  { category: 'travel-experience', themeFr: 'Le voyage (expérience)', description: 'B1 travel: hébergement, gîte, camping, location saisonnière, formule, tout compris, croisière, escale, circuit, guide, brochure, agence de voyage, assurance voyage, jet lag, mal des transports, dépaysement, découverte, immersion.', targetCount: 70 },
  { category: 'opinions-arguments', themeFr: 'Donner et défendre son avis', description: 'B1 opinions: argument, contre-argument, exemple, illustration, preuve, démonstration, conviction, certitude, doute, nuance, justifier, soutenir, défendre, contester, contredire, persuader, convaincre, nier, admettre, reconnaître.', targetCount: 80 },
  { category: 'society-issues', themeFr: 'Les problèmes de société', description: 'B1 social issues: chômage, précarité, pauvreté, inégalité, discrimination, racisme, sexisme, immigration, intégration, exclusion, sans-abri, solidarité, association, bénévolat, manifestation, grève, syndicat, revendication, réforme.', targetCount: 80 },
  { category: 'education-extended', themeFr: 'L\'éducation et la formation', description: 'B1 education: maternelle, primaire, collège, lycée, université, école supérieure, faculté, licence, master, doctorat, examen, diplôme, mention, redoublement, orientation, conseiller, filière, option, cursus, échec scolaire, décrochage, alternance.', targetCount: 80 },
  { category: 'leisure-extended', themeFr: 'Le temps libre (élargi)', description: 'B1 leisure: festival, concert, spectacle, comédie musicale, opéra, cabaret, soirée, rendez-vous, sortie, balade, escapade, week-end prolongé, club, association, bénévolat, troupe amateur, atelier créatif, cours collectif.', targetCount: 70 },
  { category: 'feelings-nuanced', themeFr: 'Sentiments et nuances', description: 'B1 nuanced feelings: ravi, comblé, soulagé, ému, troublé, perplexe, agacé, exaspéré, irrité, vexé, blessé, choqué, abasourdi, mécontent, indigné, révolté, indifférent, blasé, lassé, enthousiasmé, passionné, captivé, fasciné.', targetCount: 60 },
  { category: 'communication-styles', themeFr: 'La communication (styles)', description: 'B1 communication: langage soutenu, courant, familier, registre, ton, intonation, gestuelle, mimique, langage corporel, malentendu, quiproquo, sous-entendu, ironie, sarcasme, compliment, reproche, excuse, négociation, dialogue.', targetCount: 60 },
  { category: 'time-aspects', themeFr: 'Le temps et ses aspects', description: 'B1 time aspects: durée, fréquence, ponctualité, retard, avance, délai, échéance, planning, agenda, créneau, période, étape, phase, cycle, routine, habitude, exception, occasion, moment opportun, instant.', targetCount: 60 },
  { category: 'money-finance-intro', themeFr: 'L\'argent et les finances (intro)', description: 'B1 money introduction: revenus, dépenses, économies, budget, banque, compte, virement, prélèvement, carte bancaire, espèces, monnaie, devise, taux, emprunt, crédit, dette, épargne, placement, impôt, taxe, facture.', targetCount: 70 },
  { category: 'family-life-events', themeFr: 'Les événements familiaux', description: 'B1 life events: naissance, baptême, mariage, anniversaire, enterrement, deuil, héritage, séparation, divorce, garde, recomposition, adoption, grossesse, accouchement, parrain, marraine, témoin.', targetCount: 50 },
  { category: 'community-civic', themeFr: 'La vie associative et civique', description: 'B1 civic and community: voisinage, quartier, communauté, mairie, conseil municipal, élections, vote, citoyen, électeur, candidat, parti, droite, gauche, débat, démocratie, projet de loi, manifestation pacifique, pétition.', targetCount: 60 },
  { category: 'nature-everyday', themeFr: 'La nature au quotidien', description: 'B1 nature everyday: forêt, prairie, rivière, fleuve, lac, étang, marais, vallée, colline, sommet, sentier, randonnée, paysage, panorama, espèce, plante, fleur sauvage, arbuste, mousse, écorce, branche, racine.', targetCount: 60 },
  { category: 'verbs-thinking', themeFr: 'Verbes de pensée et raisonnement', description: 'B1 thinking verbs: penser, réfléchir, considérer, examiner, analyser, comparer, distinguer, identifier, reconnaître, supposer, imaginer, prévoir, deviner, conclure, déduire, hésiter, douter, choisir, décider, regretter.', targetCount: 50 },
  { category: 'adjectives-character', themeFr: 'Adjectifs de caractère', description: 'B1 character adjectives: ambitieux, modeste, généreux, égoïste, honnête, malhonnête, ouvert, fermé, tolérant, intolérant, patient, impatient, courageux, lâche, sincère, hypocrite, fidèle, infidèle, organisé, désordonné, ponctuel.', targetCount: 50 },
  { category: 'adjectives-quality', themeFr: 'Adjectifs de qualité et description', description: 'B1 quality adjectives: solide, fragile, résistant, durable, jetable, écologique, économique, pratique, confortable, inconfortable, esthétique, design, original, banal, unique, rare, courant, traditionnel, moderne.', targetCount: 50 },
  { category: 'verbs-social-interactions', themeFr: 'Verbes des interactions sociales', description: 'B1 social interaction verbs: saluer, présenter, accueillir, recevoir, inviter, refuser, accepter, proposer, suggérer, recommander, déconseiller, conseiller, féliciter, remercier, s\'excuser, encourager, soutenir, critiquer, juger.', targetCount: 60 },
  { category: 'abstract-basic', themeFr: 'Notions abstraites de base', description: 'Basic abstract notions B1: liberté, égalité, fraternité, justice, droit, devoir, respect, dignité, identité, culture, tradition, modernité, progrès, changement, évolution, révolution, paix, guerre, conflit, solution.', targetCount: 60 },
  { category: 'expressions-frequence', themeFr: 'Expressions de fréquence et temps', description: 'B1 time/frequency expressions: de temps en temps, de temps à autre, par moments, à l\'occasion, à plusieurs reprises, sans cesse, en permanence, à long terme, à court terme, à moyen terme, dans l\'immédiat, désormais, dorénavant.', targetCount: 50 },
];
