/**
 * B2 expansion: +5034 words to reach Beacco hybrid ~6017.
 * Themes follow B2 CEFR: complex texts, abstract topics, press register,
 * nuanced opinions, professional fields at general level.
 */
import type { Block } from './types.js';

export const blocks: Block[] = [
  // ── Society & politics (700) ──────────────────────────────────────────
  { category: 'politique-institutions', themeFr: 'La vie politique et les institutions', description: 'B2 politics: gouvernement, président, premier ministre, ministre, parlement, assemblée nationale, sénat, député, sénateur, suffrage, scrutin, mandat, législature, opposition, majorité, coalition, motion, amendement, projet de loi, promulgation, séparation des pouvoirs, exécutif, législatif, judiciaire, République, constitution, démocratie représentative.', targetCount: 150 },
  { category: 'societe-debats', themeFr: 'Les débats de société', description: 'B2 social debates: laïcité, féminisme, égalité hommes-femmes, parité, LGBTQ, mariage pour tous, PMA, GPA, fin de vie, euthanasie, peine de mort, abolition, mœurs, valeurs, idéologie, conservateur, progressiste, réactionnaire, libéral, populisme, extrémisme.', targetCount: 130 },
  { category: 'societe-actualites', themeFr: 'L\'actualité et les faits divers', description: 'B2 news and crime: actualité, événement, fait divers, accident, drame, tragédie, attentat, enquête policière, garde à vue, accusation, suspect, témoin, victime, preuve, jugement, procès, verdict, peine, prison, sursis, indemnisation.', targetCount: 130 },
  { category: 'immigration-integration', themeFr: 'Immigration et intégration', description: 'B2 immigration: migrant, immigré, réfugié, demandeur d\'asile, sans-papiers, régularisation, expulsion, naturalisation, citoyenneté, intégration, assimilation, multiculturalisme, communautarisme, ghetto, banlieue, mixité sociale, exclusion, discrimination.', targetCount: 100 },
  { category: 'travail-precarite', themeFr: 'Travail et précarité', description: 'B2 work and precarity: CDI, CDD, intérim, freelance, auto-entrepreneur, plateforme, ubérisation, gig economy, salaire minimum, SMIC, pouvoir d\'achat, inflation salariale, prime, intéressement, participation, retraite, pension, allocation, RSA, AAH, ASS, formation professionnelle.', targetCount: 100 },
  { category: 'justice-droit', themeFr: 'La justice et le droit', description: 'B2 justice: tribunal, cour, juge, procureur, avocat, plaignant, défendeur, jury, audience, plaidoirie, requête, recours, appel, cassation, jurisprudence, code pénal, code civil, contrat, clause, infraction, délit, crime, contravention.', targetCount: 90 },

  // ── Economy & business (800) ──────────────────────────────────────────
  { category: 'economie-macro', themeFr: 'L\'économie (macro)', description: 'B2 macroeconomics: croissance, récession, dépression, inflation, déflation, PIB, balance commerciale, importations, exportations, déficit, excédent, dette publique, austérité, relance, politique monétaire, banque centrale, taux directeur, taux de change, devises, monnaie unique.', targetCount: 130 },
  { category: 'economie-entreprise', themeFr: 'L\'entreprise', description: 'B2 business: PME, multinationale, start-up, scale-up, holding, filiale, fusion, acquisition, fusion-acquisition, conseil d\'administration, PDG, DG, DRH, cadre dirigeant, actionnaire, dividende, capitalisation, valorisation, levée de fonds, business angel, fonds d\'investissement.', targetCount: 130 },
  { category: 'finance-marches', themeFr: 'Finance et marchés', description: 'B2 finance: Bourse, action, obligation, indice, CAC 40, cotation, hausse, baisse, krach, bulle, spéculation, trader, courtier, portefeuille, rendement, plus-value, moins-value, taxe, fiscalité, niche fiscale, paradis fiscal, blanchiment.', targetCount: 100 },
  { category: 'marketing-commerce', themeFr: 'Marketing et commerce', description: 'B2 marketing: marque, image de marque, identité, positionnement, cible, segmentation, lancement, campagne, publicité, parrainage, sponsoring, placement de produit, influenceur, taux de conversion, panier moyen, fidélisation, expérience client.', targetCount: 100 },
  { category: 'numerique-economie', themeFr: 'Économie numérique', description: 'B2 digital economy: GAFAM, plateforme, monopole, abus de position dominante, RGPD, données personnelles, profilage, ciblage publicitaire, abonnement, modèle freemium, économie collaborative, ubérisation, désintermédiation.', targetCount: 90 },
  { category: 'commerce-international', themeFr: 'Commerce international', description: 'B2 trade: importation, exportation, douane, tarif douanier, quota, sanction, embargo, libre-échange, protectionnisme, OMC, traité commercial, partenariat, délocalisation, relocalisation, chaîne d\'approvisionnement, mondialisation, globalisation.', targetCount: 90 },

  // ── Environment (400) ──────────────────────────────────────────────────
  { category: 'environnement-climat', themeFr: 'Le climat et le réchauffement', description: 'B2 climate: gaz à effet de serre, émissions, neutralité carbone, COP, accord de Paris, transition écologique, sobriété, sobre, soutenabilité, durable, empreinte carbone, compensation, séquestration, énergies fossiles, charbon, pétrole, gaz, dépendance, indépendance énergétique.', targetCount: 130 },
  { category: 'environnement-biodiversite', themeFr: 'La biodiversité', description: 'B2 biodiversity: écosystème, habitat, espèce menacée, extinction, braconnage, déforestation, agroforesterie, permaculture, agriculture intensive, pesticides, engrais chimiques, monoculture, jachère, pollinisateur, abeille, papillon, ver de terre.', targetCount: 110 },
  { category: 'environnement-pollution', themeFr: 'Pollution et déchets', description: 'B2 pollution: particules fines, microplastique, métaux lourds, polluants, eaux usées, station d\'épuration, marée noire, décharge, incinérateur, compostage, économie circulaire, valorisation, biodégradable, recyclable, jetable, surconsommation.', targetCount: 100 },

  // ── Science & technology (500) ────────────────────────────────────────
  { category: 'sciences-introduction', themeFr: 'Les sciences (introduction)', description: 'B2 science introduction: hypothèse, théorie, expérience, expérimentation, observation, mesure, données, statistiques, échantillon, modèle, simulation, publication scientifique, peer-review, revue, laboratoire, chercheur, équipe de recherche, financement, brevet.', targetCount: 120 },
  { category: 'sciences-medecine', themeFr: 'Médecine et santé publique', description: 'B2 medicine: virus, bactérie, agent pathogène, infection, contamination, propagation, pandémie, épidémie, vaccin, immunité, sérologie, diagnostic, dépistage, traitement, protocole, essai clinique, médecin traitant, spécialiste, urgentiste, anesthésie, chirurgie.', targetCount: 120 },
  { category: 'sciences-techno', themeFr: 'Technologies émergentes', description: 'B2 emerging tech: intelligence artificielle, apprentissage automatique, algorithme, big data, blockchain, cryptomonnaie, NFT, métavers, réalité virtuelle, augmentée, internet des objets, 5G, fibre, cybersécurité, hameçonnage, rançongiciel, cyberattaque.', targetCount: 130 },
  { category: 'sciences-ingenierie', themeFr: 'Ingénierie et infrastructures', description: 'B2 engineering: génie civil, ouvrage, viaduc, tunnel, barrage, centrale (nucléaire, thermique, hydraulique), réseau électrique, smart grid, énergie renouvelable, panneau photovoltaïque, parc éolien, hydrogène, fusion nucléaire, ITER.', targetCount: 90 },

  // ── Culture, arts & media (700) ───────────────────────────────────────
  { category: 'culture-litterature', themeFr: 'Littérature', description: 'B2 literature: roman, nouvelle, novella, poésie, essai, autobiographie, biographie, théâtre, comédie, tragédie, drame, prose, vers, sonnet, alexandrin, narration, narrateur, protagoniste, personnage principal, antihéros, intrigue, thème, métaphore, allégorie, satire.', targetCount: 120 },
  { category: 'culture-cinema-extended', themeFr: 'Le cinéma (élargi)', description: 'B2 cinema: long-métrage, court-métrage, comédie romantique, thriller, polar, science-fiction, fantastique, blockbuster, film d\'auteur, festival, palme, ours, oscar, césar, scène culte, plan, séquence, montage, post-production, doublage, sous-titrage.', targetCount: 110 },
  { category: 'culture-musique', themeFr: 'La musique', description: 'B2 music: genre musical, classique, jazz, rock, pop, hip-hop, rap, électro, variété, chanson française, compositeur, parolier, interprète, soliste, chœur, orchestre, symphonie, concerto, album, single, tube, hit, palmarès, audience, streaming.', targetCount: 100 },
  { category: 'medias-journalisme', themeFr: 'Les médias et le journalisme', description: 'B2 media: rédacteur en chef, ligne éditoriale, indépendance journalistique, déontologie, source anonyme, droit de réponse, diffamation, censure, autocensure, journalisme d\'investigation, chronique, billet d\'humeur, éditorial, brève, dépêche, agence de presse.', targetCount: 100 },
  { category: 'medias-reseaux-sociaux', themeFr: 'Les réseaux sociaux', description: 'B2 social media: post, story, reel, fil d\'actualité, algorithme de recommandation, viralité, buzz, polémique, bashing, cyberharcèlement, troll, modération, signalement, suspension, ban, vérification, badge, abonné, influenceur, créateur de contenu.', targetCount: 100 },
  { category: 'culture-patrimoine', themeFr: 'Patrimoine et tradition', description: 'B2 heritage: patrimoine matériel, immatériel, classé, UNESCO, monument historique, vestige, ruine, château, cathédrale, abbaye, musée, conservation, restauration, tourisme culturel, savoir-faire traditionnel, transmission, folklore, costume, danse traditionnelle.', targetCount: 90 },
  { category: 'philosophie-introduction', themeFr: 'Philosophie (introduction)', description: 'B2 philosophy intro: pensée, raisonnement, logique, éthique, morale, dilemme, paradoxe, contradiction, principe, valeur, conscience, libre arbitre, déterminisme, scepticisme, doute, croyance, foi, religion, athéisme, spiritualité.', targetCount: 80 },

  // ── Education & academia (350) ────────────────────────────────────────
  { category: 'education-systeme', themeFr: 'Le système éducatif', description: 'B2 education system: parcoursup, sélection, classement, prépa, grande école, IUT, BTS, alternance, apprentissage, contrat de professionnalisation, stage, mémoire, thèse, soutenance, jury, validation, semestre, ECTS, Erasmus, mobilité, équivalence.', targetCount: 110 },
  { category: 'education-pedagogie', themeFr: 'La pédagogie', description: 'B2 pedagogy: méthode, didactique, programme, manuel, cours magistral, travaux dirigés, travaux pratiques, contrôle continu, partiel, examen final, devoir surveillé, dissertation, exposé, débat, projet, évaluation formative, sommative.', targetCount: 90 },
  { category: 'recherche-universitaire', themeFr: 'Recherche universitaire', description: 'B2 academia: doctorant, postdoctorant, maître de conférences, professeur, directeur de thèse, laboratoire, équipe de recherche, axe de recherche, problématique, état de l\'art, méthodologie, corpus, terrain, entretien semi-directif, données qualitatives, quantitatives.', targetCount: 80 },
  { category: 'education-numerique', themeFr: 'Numérique éducatif', description: 'B2 educational tech: e-learning, MOOC, plateforme pédagogique, classe inversée, ressource numérique, capsule vidéo, quiz interactif, exerciseur, accompagnement personnalisé, tutorat, soutien scolaire, fracture numérique.', targetCount: 70 },

  // ── Personal & psychological (450) ────────────────────────────────────
  { category: 'psychologie-emotions', themeFr: 'Émotions et psychologie', description: 'B2 psychology: angoisse, anxiété, panique, phobie, traumatisme, deuil, mélancolie, euphorie, exaltation, vulnérabilité, fragilité, résilience, complexe, estime de soi, confiance en soi, ego, narcissisme, empathie, compassion, indifférence.', targetCount: 110 },
  { category: 'psychologie-comportements', themeFr: 'Comportements et habitudes', description: 'B2 behavior: addiction, dépendance, compulsion, perfectionnisme, procrastination, charge mentale, burn-out, épuisement, surmenage, équilibre vie pro/perso, méditation, pleine conscience, sophrologie, hypnose, coaching de vie.', targetCount: 90 },
  { category: 'relations-conflits', themeFr: 'Relations et conflits', description: 'B2 relationships and conflict: dispute, querelle, malentendu, brouille, rancune, ressentiment, réconciliation, médiation, négociation, compromis, concession, ultimatum, rupture définitive, prise de recul, distance émotionnelle.', targetCount: 90 },
  { category: 'identite-soi', themeFr: 'Identité et soi', description: 'B2 identity: identité personnelle, identité culturelle, appartenance, racines, héritage culturel, déracinement, exil intérieur, quête de sens, accomplissement, réalisation, épanouissement, mal-être, crise existentielle, remise en question.', targetCount: 80 },
  { category: 'vie-quotidienne-nuance', themeFr: 'Vie quotidienne — nuances', description: 'B2 daily life nuances: tracas, soucis, contrariétés, agacements, satisfactions, plaisirs simples, petits bonheurs, déconvenue, désillusion, déception, soulagement, contentement, plénitude, sérénité, équilibre intérieur.', targetCount: 80 },

  // ── Press & opinion register (500) ────────────────────────────────────
  { category: 'opinions-nuancees', themeFr: 'Opinions nuancées', description: 'B2 nuanced opinions: il est indéniable que, force est de constater, on ne peut nier, certes…, néanmoins, toutefois, cependant, en revanche, à l\'inverse, par contre, en dépit de, malgré, quoique, bien que, à supposer que, dans la mesure où.', targetCount: 100 },
  { category: 'argumentation', themeFr: 'L\'argumentation', description: 'B2 argumentation: thèse, antithèse, synthèse, argument fort, argument faible, exemple frappant, illustration probante, contre-exemple, objection, réfutation, démonstration rigoureuse, sophisme, paralogisme, généralisation hâtive.', targetCount: 100 },
  { category: 'expressions-presse', themeFr: 'Expressions de presse', description: 'B2 press expressions: faire la une, tirer la sonnette d\'alarme, mettre en lumière, attirer l\'attention sur, soulever une polémique, faire débat, défrayer la chronique, faire scandale, susciter l\'indignation, provoquer un tollé.', targetCount: 100 },
  { category: 'verbes-presse-action', themeFr: 'Verbes d\'action de presse', description: 'B2 press verbs: dénoncer, condamner, fustiger, stigmatiser, déplorer, regretter, saluer, plébisciter, vanter, glorifier, prôner, préconiser, recommander, conseiller, exiger, réclamer, revendiquer, lutter contre.', targetCount: 100 },
  { category: 'pronoms-relatifs-soutenus', themeFr: 'Pronoms et tournures soutenus', description: 'B2 elevated pronouns and constructions: lequel, laquelle, lesquels, lesquelles, auquel, duquel, dont, ce qui, ce que, ce dont, ce à quoi, là où, par lequel, à travers lequel, par le biais de, au moyen de, en vue de, dans le but de.', targetCount: 100 },

  // ── International / world affairs (300) ───────────────────────────────
  { category: 'international-relations', themeFr: 'Relations internationales', description: 'B2 international relations: ONU, OTAN, UE, G7, G20, OMC, FMI, Banque mondiale, traité, accord, sommet, sanction économique, embargo, mission diplomatique, ambassadeur, consul, alliance, médiation, négociation de paix, casque bleu.', targetCount: 100 },
  { category: 'guerres-conflits-mondiaux', themeFr: 'Conflits et guerres', description: 'B2 conflicts: conflit armé, guerre civile, intervention militaire, occupation, résistance, insurrection, terrorisme, attentat, otage, crime de guerre, génocide, exode, déplacé interne, camp de réfugiés, aide humanitaire, ONG.', targetCount: 100 },
  { category: 'monde-globalisation', themeFr: 'Monde et globalisation', description: 'B2 globalisation: mondialisation, globalisation, déterritorialisation, géopolitique, soft power, hard power, puissance régionale, émergente, pays développés, pays en développement, Sud global, Nord global, fracture numérique, inégalités mondiales.', targetCount: 100 },
];
