import type { DrillSetSeed } from './drills.js';

export const drillsData2: DrillSetSeed[] = [
  // ─── A1 ──────────────────────────────────────────────────────────────────

  // 1. Être et Avoir au présent
  {
    slug: 'etre-avoir-present',
    titleRu: 'Être et Avoir — présent',
    titleEn: 'Être and Avoir — présent',
    descriptionRu: 'Спряги самые важные глаголы французского языка: être (быть) и avoir (иметь).',
    descriptionEn: 'Conjugate the two most essential French verbs: être (to be) and avoir (to have).',
    level: 'A1',
    category: 'verbes',
    difficulty: 1,
    icon: 'Star',
    questions: [
      { type: 'fill_blank', question: { text: 'Je ___ étudiant.', blanks: 1 }, answer: { values: ['suis'] }, explanation: 'être → je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont.' },
      { type: 'fill_blank', question: { text: 'Tu ___ faim ?', blanks: 1 }, answer: { values: ['as'] }, explanation: 'avoir → j\'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.' },
      { type: 'fill_blank', question: { text: 'Elle ___ française.', blanks: 1 }, answer: { values: ['est'] }, explanation: 'être → il/elle est.' },
      { type: 'fill_blank', question: { text: 'Nous ___ un chien.', blanks: 1 }, answer: { values: ['avons'] }, explanation: 'avoir → nous avons.' },
      { type: 'fill_blank', question: { text: 'Vous ___ prêts ?', blanks: 1 }, answer: { values: ['êtes'] }, explanation: 'être → vous êtes.' },
      { type: 'fill_blank', question: { text: 'Ils ___ contents.', blanks: 1 }, answer: { values: ['sont'] }, explanation: 'être → ils/elles sont.' },
      { type: 'fill_blank', question: { text: 'J\'___ froid.', blanks: 1 }, answer: { values: ['ai'] }, explanation: 'avoir → j\'ai. Expressions avec avoir: avoir froid/chaud/faim/soif/peur.' },
      { type: 'fill_blank', question: { text: 'Vous ___ un appartement ?', blanks: 1 }, answer: { values: ['avez'] }, explanation: 'avoir → vous avez.' },
      { type: 'fill_blank', question: { text: 'Elles ___ occupées.', blanks: 1 }, answer: { values: ['sont'] }, explanation: 'être → elles sont (même forme que ils sont).' },
      { type: 'fill_blank', question: { text: 'Il ___ soif.', blanks: 1 }, answer: { values: ['a'] }, explanation: 'avoir → il/elle a. « Avoir soif » = to be thirsty.' },
      { type: 'fill_blank', question: { text: 'Tu ___ grand !', blanks: 1 }, answer: { values: ['es'] }, explanation: 'être → tu es.' },
      { type: 'fill_blank', question: { text: 'Nous ___ fatigués.', blanks: 1 }, answer: { values: ['sommes'] }, explanation: 'être → nous sommes.' },
      { type: 'fill_blank', question: { text: 'Ils ___ deux voitures.', blanks: 1 }, answer: { values: ['ont'] }, explanation: 'avoir → ils/elles ont.' },
      { type: 'multiple_choice', question: { text: 'Il ___ vingt ans.', options: ['est', 'a'] }, answer: { correct: 'a' }, explanation: 'L\'âge s\'exprime avec avoir : avoir X ans.' },
      { type: 'multiple_choice', question: { text: 'Elle ___ infirmière.', options: ['est', 'a'] }, answer: { correct: 'est' }, explanation: 'La profession s\'exprime avec être. Pas d\'article : elle est infirmière.' },
      { type: 'multiple_choice', question: { text: 'Nous ___ en France.', options: ['sommes', 'avons'] }, answer: { correct: 'sommes' }, explanation: 'Localisation → être : nous sommes en France.' },
      { type: 'multiple_choice', question: { text: 'Tu ___ peur ?', options: ['es', 'as'] }, answer: { correct: 'as' }, explanation: 'Avoir peur = to be afraid. Expression fixe avec avoir.' },
      { type: 'multiple_choice', question: { text: 'Ils ___ à Paris.', options: ['sont', 'ont'] }, answer: { correct: 'sont' }, explanation: 'Localisation → être.' },
      { type: 'multiple_choice', question: { text: 'J\'___ un frère et une sœur.', options: ['suis', 'ai'] }, answer: { correct: 'ai' }, explanation: 'Possession → avoir : j\'ai un frère.' },
      { type: 'multiple_choice', question: { text: 'Vous ___ médecin ?', options: ['êtes', 'avez'] }, answer: { correct: 'êtes' }, explanation: 'Profession → être.' },
      { type: 'multiple_choice', question: { text: 'Elle ___ les yeux bleus.', options: ['est', 'a'] }, answer: { correct: 'a' }, explanation: 'Description physique avec parties du corps → avoir.' },
      { type: 'multiple_choice', question: { text: 'Nous ___ raison.', options: ['sommes', 'avons'] }, answer: { correct: 'avons' }, explanation: 'Avoir raison/tort = to be right/wrong. Expression fixe avec avoir.' },
      { type: 'multiple_choice', question: { text: 'Tu ___ content ?', options: ['es', 'as'] }, answer: { correct: 'es' }, explanation: 'Adjectif d\'état → être.' },
      { type: 'fill_blank', question: { text: 'Il ___ chaud aujourd\'hui.', blanks: 1 }, answer: { values: ['fait'] }, explanation: 'Attention : la météo utilise faire — il fait chaud/froid. Pas être ni avoir.' },
      { type: 'fill_blank', question: { text: 'Les enfants ___ heureux.', blanks: 1 }, answer: { values: ['sont'] }, explanation: 'État, qualité → être : ils sont heureux.' },
    ],
  },

  // 2. Mots interrogatifs
  {
    slug: 'mots-interrogatifs',
    titleRu: 'Вопросительные слова',
    titleEn: 'Question words',
    descriptionRu: 'Qui, que, où, quand, comment, pourquoi, combien — выбери правильное вопросительное слово.',
    descriptionEn: 'Qui, que, où, quand, comment, pourquoi, combien — choose the correct question word.',
    level: 'A1',
    category: 'grammaire',
    difficulty: 1,
    icon: 'HelpCircle',
    questions: [
      { type: 'multiple_choice', question: { text: '___ est-ce que tu habites ? — À Lyon.', options: ['Où', 'Quand', 'Comment'] }, answer: { correct: 'Où' }, explanation: 'Où = where. Pour demander un lieu.' },
      { type: 'multiple_choice', question: { text: '___ s\'appelle-t-il ? — Marc.', options: ['Où', 'Comment', 'Combien'] }, answer: { correct: 'Comment' }, explanation: 'Comment t\'appelles-tu ? / Comment s\'appelle-t-il ? = What is his name?' },
      { type: 'multiple_choice', question: { text: '___ est-ce que tu pars ? — Demain.', options: ['Quand', 'Pourquoi', 'Qui'] }, answer: { correct: 'Quand' }, explanation: 'Quand = when. Pour demander un moment.' },
      { type: 'multiple_choice', question: { text: '___ tu ne viens pas ? — J\'ai du travail.', options: ['Pourquoi', 'Quand', 'Combien'] }, answer: { correct: 'Pourquoi' }, explanation: 'Pourquoi = why. Réponse attendue avec « parce que ».' },
      { type: 'multiple_choice', question: { text: '___ coûte ce livre ? — Dix euros.', options: ['Combien', 'Quand', 'Où'] }, answer: { correct: 'Combien' }, explanation: 'Combien = how much / how many. Pour demander un prix ou une quantité.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que tu appelles ? — Ma mère.', options: ['Qui', 'Que', 'Comment'] }, answer: { correct: 'Qui' }, explanation: 'Qui = who. Pour demander une personne.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que tu fais ? — Je lis.', options: ['Que', 'Qui', 'Où'] }, answer: { correct: 'Que' }, explanation: 'Que / Qu\'est-ce que = what. Pour demander une action ou une chose.' },
      { type: 'multiple_choice', question: { text: '___ est ton professeur ? — M. Dupont.', options: ['Qui', 'Que', 'Quand'] }, answer: { correct: 'Qui' }, explanation: 'Qui est... = Who is... Pour identifier une personne.' },
      { type: 'multiple_choice', question: { text: '___ tu vas à l\'école ? — En bus.', options: ['Comment', 'Combien', 'Que'] }, answer: { correct: 'Comment' }, explanation: 'Comment = how. Pour demander la manière ou le moyen.' },
      { type: 'multiple_choice', question: { text: '___ personnes y a-t-il dans ta famille ? — Cinq.', options: ['Combien de', 'Pourquoi de', 'Comment de'] }, answer: { correct: 'Combien de' }, explanation: 'Combien de + nom = how many + noun.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que tu aimes faire ? — La musique.', options: ['Qu\'', 'Qui', 'Quand'] }, answer: { correct: 'Qu\'' }, explanation: 'Que → Qu\' devant une voyelle. Qu\'est-ce que tu aimes faire ?' },
      { type: 'multiple_choice', question: { text: '___ est-ce que le film commence ? — À 20h.', options: ['Quand', 'Combien', 'Pourquoi'] }, answer: { correct: 'Quand' }, explanation: 'Quand = when. Heure ou moment.' },
      { type: 'multiple_choice', question: { text: '___ vient avec nous ? — Pierre et Sophie.', options: ['Qui', 'Que', 'Comment'] }, answer: { correct: 'Qui' }, explanation: 'Qui = who. Sujet de la question.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que vous travaillez ? — À Paris.', options: ['Où', 'Comment', 'Combien'] }, answer: { correct: 'Où' }, explanation: 'Où = where. Lieu de travail.' },
      { type: 'multiple_choice', question: { text: '___ tu t\'es couché si tard ? — J\'avais du travail.', options: ['Pourquoi', 'Quand', 'Combien'] }, answer: { correct: 'Pourquoi' }, explanation: 'Pourquoi = why. Cause, raison.' },
      { type: 'multiple_choice', question: { text: '___ coûtent ces chaussures ? — Soixante euros.', options: ['Combien', 'Comment', 'Qui'] }, answer: { correct: 'Combien' }, explanation: 'Combien coûte/coûtent = how much does it cost.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que vous parlez ? — Le français.', options: ['Quelle langue', 'Combien langue', 'Quand langue'] }, answer: { correct: 'Quelle langue' }, explanation: 'Quel/Quelle + nom = which/what + noun. Quelle langue parlez-vous ?' },
      { type: 'multiple_choice', question: { text: '___ tu aimes mieux — le café ou le thé ?', options: ['Qu\'est-ce que', 'Qui est-ce que', 'Combien'] }, answer: { correct: 'Qu\'est-ce que' }, explanation: 'Qu\'est-ce que tu aimes mieux = What do you prefer.' },
      { type: 'multiple_choice', question: { text: '___ heure est-il ? — Il est midi.', options: ['Quelle', 'Combien', 'Comment'] }, answer: { correct: 'Quelle' }, explanation: 'Quelle heure est-il ? = What time is it? Expression fixe.' },
      { type: 'multiple_choice', question: { text: '___ est née Marie Curie ? — En Pologne.', options: ['Où', 'Quand', 'Qui'] }, answer: { correct: 'Où' }, explanation: 'Où = where. Lieu de naissance.' },
      { type: 'multiple_choice', question: { text: 'Tu reviens ___? — Dans une semaine.', options: ['quand', 'pourquoi', 'combien'] }, answer: { correct: 'quand' }, explanation: 'Quand reviens-tu ? / Tu reviens quand ? — deux formes correctes.' },
      { type: 'multiple_choice', question: { text: '___ est-ce que vous faites ce soir ? — Nous allons au cinéma.', options: ['Qu\'', 'Qui', 'Combien'] }, answer: { correct: 'Qu\'' }, explanation: 'Qu\'est-ce que vous faites = What are you doing.' },
      { type: 'multiple_choice', question: { text: '___ tu viens ? — Je viens du Canada.', options: ['D\'où', 'Quand', 'Pourquoi'] }, answer: { correct: 'D\'où' }, explanation: 'D\'où viens-tu ? = Where are you from? Préposition de + où.' },
      { type: 'multiple_choice', question: { text: '___ est ton plat préféré ? — La ratatouille.', options: ['Quel', 'Combien', 'Comment'] }, answer: { correct: 'Quel' }, explanation: 'Quel/Quelle = which/what (before a noun). Quel est ton plat préféré ?' },
      { type: 'multiple_choice', question: { text: 'Il parle ___ ? — Il parle bien.', options: ['comment', 'quand', 'pourquoi'] }, answer: { correct: 'comment' }, explanation: 'Comment parle-t-il ? = How does he speak? Manière.' },
    ],
  },

  // 3. Pluriel des noms
  {
    slug: 'pluriel-noms',
    titleRu: 'Множественное число существительных',
    titleEn: 'Plural of nouns',
    descriptionRu: 'Образуй правильную форму множественного числа: -s, -x, -aux и исключения.',
    descriptionEn: 'Form the correct plural: -s, -x, -aux and exceptions.',
    level: 'A1',
    category: 'noms',
    difficulty: 2,
    icon: 'List',
    questions: [
      { type: 'multiple_choice', question: { text: 'un chat → des ___', options: ['chats', 'chaux', 'chates'] }, answer: { correct: 'chats' }, explanation: 'Règle générale : on ajoute -s au singulier. chat → chats.' },
      { type: 'multiple_choice', question: { text: 'un gâteau → des ___', options: ['gâteaux', 'gâteaus', 'gâteauz'] }, answer: { correct: 'gâteaux' }, explanation: 'Les noms en -eau forment leur pluriel en -eaux. gâteau → gâteaux.' },
      { type: 'multiple_choice', question: { text: 'un animal → des ___', options: ['animaux', 'animals', 'animales'] }, answer: { correct: 'animaux' }, explanation: 'La plupart des noms en -al font leur pluriel en -aux. animal → animaux.' },
      { type: 'multiple_choice', question: { text: 'un jeu → des ___', options: ['jeux', 'jeus', 'jeaux'] }, answer: { correct: 'jeux' }, explanation: 'Les noms en -eu font -eux au pluriel. jeu → jeux (exception : pneu → pneus).' },
      { type: 'multiple_choice', question: { text: 'un pays → des ___', options: ['pays', 'payss', 'payx'] }, answer: { correct: 'pays' }, explanation: 'Les noms déjà terminés en -s, -x ou -z ne changent pas au pluriel. pays → pays.' },
      { type: 'multiple_choice', question: { text: 'un œil → des ___', options: ['yeux', 'œils', 'œilx'] }, answer: { correct: 'yeux' }, explanation: 'Pluriel irrégulier : un œil → des yeux.' },
      { type: 'multiple_choice', question: { text: 'un journal → des ___', options: ['journaux', 'journals', 'journales'] }, answer: { correct: 'journaux' }, explanation: 'journal → journaux (règle -al → -aux).' },
      { type: 'multiple_choice', question: { text: 'une voix → des ___', options: ['voix', 'voixs', 'voices'] }, answer: { correct: 'voix' }, explanation: 'Les noms en -x ne changent pas au pluriel. voix → voix.' },
      { type: 'multiple_choice', question: { text: 'un bal → des ___', options: ['bals', 'baux', 'balx'] }, answer: { correct: 'bals' }, explanation: 'Exceptions à la règle -al → -aux : bal → bals, carnaval → carnavals, festival → festivals.' },
      { type: 'multiple_choice', question: { text: 'un feu → des ___', options: ['feux', 'feus', 'feaux'] }, answer: { correct: 'feux' }, explanation: 'feu → feux (règle -eu → -eux). Exception : bleu → bleus.' },
      { type: 'multiple_choice', question: { text: 'un bijou → des ___', options: ['bijoux', 'bijous', 'bijoues'] }, answer: { correct: 'bijoux' }, explanation: 'Sept noms en -ou font -oux : bijou, caillou, chou, genou, hibou, joujou, pou.' },
      { type: 'multiple_choice', question: { text: 'une maison → des ___', options: ['maisons', 'maisoux', 'maisonx'] }, answer: { correct: 'maisons' }, explanation: 'Règle générale : maison + s = maisons.' },
      { type: 'multiple_choice', question: { text: 'un travail → des ___', options: ['travaux', 'travails', 'travailles'] }, answer: { correct: 'travaux' }, explanation: 'travail → travaux. Irrégulier (pas de -ail → -aux en général mais travail fait exception).' },
      { type: 'multiple_choice', question: { text: 'un festival → des ___', options: ['festivals', 'festivaux', 'festivales'] }, answer: { correct: 'festivals' }, explanation: 'Exception : festival → festivals (pas festivaux).' },
      { type: 'multiple_choice', question: { text: 'un neveu → des ___', options: ['neveux', 'neveus', 'neveaux'] }, answer: { correct: 'neveux' }, explanation: 'neveu → neveux (règle -eu → -eux).' },
      { type: 'multiple_choice', question: { text: 'un nez → des ___', options: ['nez', 'nezs', 'nezx'] }, answer: { correct: 'nez' }, explanation: 'Les noms en -z ne changent pas au pluriel. nez → nez.' },
      { type: 'multiple_choice', question: { text: 'un bateau → des ___', options: ['bateaux', 'bateaus', 'bateauz'] }, answer: { correct: 'bateaux' }, explanation: 'bateau → bateaux (règle -eau → -eaux).' },
      { type: 'multiple_choice', question: { text: 'un genou → des ___', options: ['genoux', 'genous', 'genoues'] }, answer: { correct: 'genoux' }, explanation: 'genou → genoux (fait partie des 7 noms en -ou → -oux).' },
      { type: 'multiple_choice', question: { text: 'un cheval → des ___', options: ['chevaux', 'chevals', 'chevales'] }, answer: { correct: 'chevaux' }, explanation: 'cheval → chevaux (règle -al → -aux).' },
      { type: 'multiple_choice', question: { text: 'une croix → des ___', options: ['croix', 'croixs', 'croixt'] }, answer: { correct: 'croix' }, explanation: 'Les noms en -x ne changent pas. croix → croix.' },
      { type: 'multiple_choice', question: { text: 'un landau → des ___', options: ['landaus', 'landaux', 'landauz'] }, answer: { correct: 'landaus' }, explanation: 'Exception : landau → landaus (pas landaux). Aussi : sarrau, grau.' },
      { type: 'multiple_choice', question: { text: 'un tuyau → des ___', options: ['tuyaux', 'tuyaus', 'tuyaues'] }, answer: { correct: 'tuyaux' }, explanation: 'tuyau → tuyaux (règle -au → -aux).' },
      { type: 'multiple_choice', question: { text: 'un pneu → des ___', options: ['pneus', 'pneux', 'pneaux'] }, answer: { correct: 'pneus' }, explanation: 'Exception : pneu → pneus (pas pneux). Bleu → bleus aussi.' },
      { type: 'multiple_choice', question: { text: 'un vitrail → des ___', options: ['vitraux', 'vitrails', 'vitralx'] }, answer: { correct: 'vitraux' }, explanation: 'vitrail → vitraux. Comme travail, ce mot suit la règle -al → -aux.' },
      { type: 'multiple_choice', question: { text: 'un chou → des ___', options: ['choux', 'chous', 'choues'] }, answer: { correct: 'choux' }, explanation: 'chou → choux (l\'un des 7 noms en -ou → -oux).' },
    ],
  },

  // ─── A2 ──────────────────────────────────────────────────────────────────

  // 4. Futur simple
  {
    slug: 'futur-simple',
    titleRu: 'Futur simple — спряжение',
    titleEn: 'Futur simple — conjugation',
    descriptionRu: 'Образуй будущее время: правильные глаголы и основные иррегулярные основы.',
    descriptionEn: 'Form the future tense: regular verbs and key irregular stems.',
    level: 'A2',
    category: 'temps',
    difficulty: 2,
    icon: 'ArrowRight',
    questions: [
      { type: 'fill_blank', question: { text: 'Demain, je ___ (parler) à mon patron.', blanks: 1 }, answer: { values: ['parlerai'] }, explanation: 'Futur simple des verbes en -er : infinitif + -ai, -as, -a, -ons, -ez, -ont. parler → parlerai.' },
      { type: 'fill_blank', question: { text: 'Elle ___ (finir) le projet la semaine prochaine.', blanks: 1 }, answer: { values: ['finira'] }, explanation: 'finir → finira. Verbes en -ir : infinitif + terminaisons du futur.' },
      { type: 'fill_blank', question: { text: 'Nous ___ (aller) en vacances en juillet.', blanks: 1 }, answer: { values: ['irons'] }, explanation: 'aller → futur irrégulier : ir-. irons.' },
      { type: 'fill_blank', question: { text: 'Tu ___ (être) surpris !', blanks: 1 }, answer: { values: ['seras'] }, explanation: 'être → futur irrégulier : ser-. seras.' },
      { type: 'fill_blank', question: { text: 'Ils ___ (avoir) beaucoup de travail.', blanks: 1 }, answer: { values: ['auront'] }, explanation: 'avoir → futur irrégulier : aur-. auront.' },
      { type: 'fill_blank', question: { text: 'Vous ___ (faire) attention, s\'il vous plaît.', blanks: 1 }, answer: { values: ['ferez'] }, explanation: 'faire → futur irrégulier : fer-. ferez.' },
      { type: 'fill_blank', question: { text: 'Il ___ (pouvoir) venir ce soir.', blanks: 1 }, answer: { values: ['pourra'] }, explanation: 'pouvoir → futur irrégulier : pourr-. pourra.' },
      { type: 'fill_blank', question: { text: 'Je ___ (venir) te chercher à 18h.', blanks: 1 }, answer: { values: ['viendrai'] }, explanation: 'venir → futur irrégulier : viendr-. viendrai.' },
      { type: 'fill_blank', question: { text: 'Elles ___ (savoir) la vérité demain.', blanks: 1 }, answer: { values: ['sauront'] }, explanation: 'savoir → futur irrégulier : saur-. sauront.' },
      { type: 'fill_blank', question: { text: 'Tu ___ (vouloir) bien m\'aider ?', blanks: 1 }, answer: { values: ['voudras'] }, explanation: 'vouloir → futur irrégulier : voudr-. voudras.' },
      { type: 'fill_blank', question: { text: 'Il ___ (falloir) partir tôt.', blanks: 1 }, answer: { values: ['faudra'] }, explanation: 'falloir → futur irrégulier : faudr-. Il faudra (toujours à la 3ème personne sing.).' },
      { type: 'fill_blank', question: { text: 'Nous ___ (recevoir) les résultats demain.', blanks: 1 }, answer: { values: ['recevrons'] }, explanation: 'recevoir → futur irrégulier : recevr-. recevrons.' },
      { type: 'fill_blank', question: { text: 'Elle ___ (voir) ses amis ce week-end.', blanks: 1 }, answer: { values: ['verra'] }, explanation: 'voir → futur irrégulier : verr-. verra.' },
      { type: 'fill_blank', question: { text: 'Vous ___ (prendre) le train de 9h.', blanks: 1 }, answer: { values: ['prendrez'] }, explanation: 'prendre → futur régulier sur l\'infinitif : prendrez.' },
      { type: 'fill_blank', question: { text: 'Je ___ (envoyer) le mail demain.', blanks: 1 }, answer: { values: ['enverrai'] }, explanation: 'envoyer → futur irrégulier : enverr-. enverrai.' },
      { type: 'multiple_choice', question: { text: 'Dans dix ans, il ___ médecin.', options: ['sera', 'est', 'était'] }, answer: { correct: 'sera' }, explanation: 'Future prediction → futur simple. être → sera.' },
      { type: 'multiple_choice', question: { text: 'Si tu travailles, tu ___.' , options: ['réussiras', 'réussis', 'réussirais'] }, answer: { correct: 'réussiras' }, explanation: 'Si + présent → futur simple. réussir → réussiras.' },
      { type: 'multiple_choice', question: { text: 'Elles ___ à Paris la semaine prochaine.', options: ['iront', 'vont', 'allaient'] }, answer: { correct: 'iront' }, explanation: 'La semaine prochaine → futur simple. aller → iront.' },
      { type: 'multiple_choice', question: { text: 'Quand il ___ grand, il ___ footballeur.', options: ['sera / deviendra', 'est / devient', 'sera / devint'] }, answer: { correct: 'sera / deviendra' }, explanation: 'Quand + futur simple dans les deux propositions (pas si).' },
      { type: 'multiple_choice', question: { text: 'Vous ___ les résultats par email.', options: ['recevrez', 'receviez', 'reçûtes'] }, answer: { correct: 'recevrez' }, explanation: 'recevoir → recevrez. Futur simple pour annonce future.' },
      { type: 'fill_blank', question: { text: 'Il ___ (pleuvoir) demain selon la météo.', blanks: 1 }, answer: { values: ['pleuvra'] }, explanation: 'pleuvoir → futur irrégulier : pleuvr-. Il pleuvra.' },
      { type: 'fill_blank', question: { text: 'Tu ___ (tenir) ta promesse ?', blanks: 1 }, answer: { values: ['tiendras'] }, explanation: 'tenir → futur irrégulier : tiendr-. tiendras.' },
      { type: 'fill_blank', question: { text: 'Nous ___ (courir) le marathon en mai.', blanks: 1 }, answer: { values: ['courrons'] }, explanation: 'courir → futur irrégulier : courr-. courrons.' },
      { type: 'fill_blank', question: { text: 'J\'___ (appeler) ma mère ce soir.', blanks: 1 }, answer: { values: ['appellerai'] }, explanation: 'appeler → doublement du l au futur : appellerai.' },
      { type: 'fill_blank', question: { text: 'Il ___ (mourir) s\'il ne mange pas.', blanks: 1 }, answer: { values: ['mourra'] }, explanation: 'mourir → futur irrégulier : mourr-. mourra.' },
    ],
  },

  // 5. Comparatif et superlatif
  {
    slug: 'comparatif-superlatif',
    titleRu: 'Сравнительные степени',
    titleEn: 'Comparative and superlative',
    descriptionRu: 'Plus, moins, aussi, le plus, le moins — выбери правильную форму сравнения.',
    descriptionEn: 'Plus, moins, aussi, le plus, le moins — choose the correct comparative or superlative form.',
    level: 'A2',
    category: 'adjectifs',
    difficulty: 2,
    icon: 'TrendingUp',
    questions: [
      { type: 'multiple_choice', question: { text: 'Marie est ___ grande ___ Paul.', options: ['plus ... que', 'aussi ... que', 'moins ... que'] }, answer: { correct: 'plus ... que' }, explanation: 'Comparatif de supériorité : plus + adjectif + que.' },
      { type: 'multiple_choice', question: { text: 'Ce film est ___ intéressant ___ l\'autre.', options: ['moins ... que', 'plus ... que', 'le moins ... de'] }, answer: { correct: 'moins ... que' }, explanation: 'Comparatif d\'infériorité : moins + adjectif + que.' },
      { type: 'multiple_choice', question: { text: 'Sophie est ___ intelligente ___ sa sœur.', options: ['aussi ... que', 'plus ... que', 'le plus ... de'] }, answer: { correct: 'aussi ... que' }, explanation: 'Comparatif d\'égalité : aussi + adjectif + que.' },
      { type: 'multiple_choice', question: { text: 'C\'est ___ restaurant ___ la ville.', options: ['le meilleur ... de', 'le plus bon ... de', 'le mieux ... de'] }, answer: { correct: 'le meilleur ... de' }, explanation: 'Superlatif irrégulier de bon → le meilleur (jamais "le plus bon").' },
      { type: 'multiple_choice', question: { text: 'C\'est ___ film ___ l\'année.', options: ['le plus beau ... de', 'le plus beau ... que', 'plus beau ... de'] }, answer: { correct: 'le plus beau ... de' }, explanation: 'Superlatif de supériorité : le/la/les plus + adj + de (pas "que").' },
      { type: 'multiple_choice', question: { text: 'Il court ___ vite ___ moi.', options: ['plus ... que', 'le plus ... de', 'aussi ... comme'] }, answer: { correct: 'plus ... que' }, explanation: 'Comparatif d\'adverbe aussi : plus + adverbe + que.' },
      { type: 'multiple_choice', question: { text: 'Cette voiture est ___ chère ___ la classe.', options: ['la moins ... de', 'la moins ... que', 'moins ... de'] }, answer: { correct: 'la moins ... de' }, explanation: 'Superlatif d\'infériorité : le/la/les moins + adj + de.' },
      { type: 'multiple_choice', question: { text: 'Il mange ___ que moi.', options: ['plus', 'le plus', 'plus de'] }, answer: { correct: 'plus' }, explanation: 'Comparatif d\'un verbe : verbe + plus/moins/autant + que.' },
      { type: 'multiple_choice', question: { text: 'C\'est elle qui travaille ___ de l\'équipe.', options: ['le plus', 'la plus', 'plus'] }, answer: { correct: 'le plus' }, explanation: 'Superlatif d\'un verbe → le plus (invariable, même pour "elle").' },
      { type: 'multiple_choice', question: { text: 'Ce vin est ___ que le précédent.', options: ['meilleur', 'le meilleur', 'mieux'] }, answer: { correct: 'meilleur' }, explanation: 'meilleur = comparatif de bon (adjectif). Mieux = comparatif de bien (adverbe).' },
      { type: 'multiple_choice', question: { text: 'Elle parle français ___ que lui.', options: ['mieux', 'meilleur', 'le mieux'] }, answer: { correct: 'mieux' }, explanation: 'mieux = comparatif de l\'adverbe bien. Il parle bien → elle parle mieux.' },
      { type: 'multiple_choice', question: { text: 'Il y a ___ monde aujourd\'hui ___ hier.', options: ['plus de ... que', 'plus ... que', 'plus de ... de'] }, answer: { correct: 'plus de ... que' }, explanation: 'Comparatif de quantité (nom) : plus de + nom + que.' },
      { type: 'multiple_choice', question: { text: 'C\'est le ___ endroit que je connaisse.', options: ['plus beau', 'plus bien', 'meilleur'] }, answer: { correct: 'plus beau' }, explanation: 'Superlatif de beau → le plus beau. (meilleur est pour bon, pas beau).' },
      { type: 'multiple_choice', question: { text: 'Paris est ___ grande ___ Lyon.', options: ['plus ... que', 'le plus ... de', 'aussi ... comme'] }, answer: { correct: 'plus ... que' }, explanation: 'Comparatif entre deux éléments → plus ... que (pas "de").' },
      { type: 'multiple_choice', question: { text: 'C\'est le ___ résultat possible.', options: ['pire', 'plus mauvais', 'le pire'] }, answer: { correct: 'pire' }, explanation: 'pire = superlatif/comparatif de mauvais (langue soutenue). Plus mauvais aussi acceptable.' },
      { type: 'multiple_choice', question: { text: 'J\'ai ___ patience ___ toi.', options: ['autant de ... que', 'autant ... que', 'aussi de ... que'] }, answer: { correct: 'autant de ... que' }, explanation: 'Égalité de quantité (nom) : autant de + nom + que.' },
      { type: 'multiple_choice', question: { text: 'Il est ___ fatigué ___ prévu.', options: ['plus ... que', 'le plus ... de', 'plus ... de'] }, answer: { correct: 'plus ... que' }, explanation: 'Comparatif de supériorité avec un participe/adj : plus + adj + que.' },
      { type: 'multiple_choice', question: { text: 'C\'est ___ du magasin.', options: ['le produit le plus cher', 'le produit plus cher', 'le produit le plus chère'] }, answer: { correct: 'le produit le plus cher' }, explanation: 'Le superlatif s\'accorde avec le nom : produit (masc. sing.) → cher.' },
      { type: 'multiple_choice', question: { text: 'Elle est ___ sérieuse ___ son frère.', options: ['aussi ... que', 'aussi ... de', 'autant ... que'] }, answer: { correct: 'aussi ... que' }, explanation: 'Égalité d\'adjectif : aussi + adj + que (pas "autant" pour les adjectifs).' },
      { type: 'multiple_choice', question: { text: 'Il travaille ___ que sa femme.', options: ['autant', 'aussi', 'autant de'] }, answer: { correct: 'autant' }, explanation: 'Égalité d\'un verbe : verbe + autant (pas "aussi") + que.' },
      { type: 'multiple_choice', question: { text: 'Ce modèle est ___ performant.', options: ['le moins', 'le moins le', 'moins le'] }, answer: { correct: 'le moins' }, explanation: 'Superlatif d\'infériorité : le/la/les moins + adj (sans deuxième article).' },
      { type: 'multiple_choice', question: { text: 'C\'est ___ que j\'aie jamais vu.', options: ['le pire', 'pire', 'le plus mauvais'] }, answer: { correct: 'le pire' }, explanation: 'le pire = superlatif de mauvais (langue courante et soutenue).' },
      { type: 'multiple_choice', question: { text: 'Il a ___ argent ___ moi.', options: ['moins d\'... que', 'moins ... que', 'moins de ... de'] }, answer: { correct: 'moins d\'... que' }, explanation: 'Infériorité de quantité : moins de + nom + que. Élision devant voyelle : moins d\'.' },
      { type: 'multiple_choice', question: { text: 'Elle va ___ depuis qu\'elle a changé de travail.', options: ['mieux', 'meilleure', 'le mieux'] }, answer: { correct: 'mieux' }, explanation: 'aller mieux = to feel better. Adverbe mieux, pas adjectif.' },
      { type: 'multiple_choice', question: { text: 'Ce sont ___ chaussures ___ magasin.', options: ['les plus belles ... du', 'les plus belles ... de le', 'le plus belles ... du'] }, answer: { correct: 'les plus belles ... du' }, explanation: 'Superlatif accordé au pluriel féminin (chaussures = f. plur.) → les plus belles. Superlatif + de + le = du.' },
    ],
  },

  // 6. Homophones courants
  {
    slug: 'homophones-courants',
    titleRu: 'Омофоны — распространённые ошибки',
    titleEn: 'Common homophones',
    descriptionRu: 'ou/où, a/à, et/est, son/sont, ces/ses — выбери правильное написание.',
    descriptionEn: 'ou/où, a/à, et/est, son/sont, ces/ses — choose the correct spelling.',
    level: 'A2',
    category: 'orthographe',
    difficulty: 2,
    icon: 'Spellcheck',
    questions: [
      { type: 'multiple_choice', question: { text: 'Il va ___ Paris.', options: ['à', 'a'] }, answer: { correct: 'à' }, explanation: 'à = préposition (lieu). a = verbe avoir (3ème pers. sing.) : il a mangé.' },
      { type: 'multiple_choice', question: { text: 'Elle ___ fini son travail.', options: ['a', 'à'] }, answer: { correct: 'a' }, explanation: 'a = verbe avoir conjugué (elle a fini). Trick : si on peut remplacer par "avait", c\'est le verbe.' },
      { type: 'multiple_choice', question: { text: 'Tu veux du café ___ du thé ?', options: ['ou', 'où'] }, answer: { correct: 'ou' }, explanation: 'ou = or (choix). Trick : remplacer par "ou bien" → si ça marche, c\'est "ou" sans accent.' },
      { type: 'multiple_choice', question: { text: '___ habites-tu ?', options: ['Où', 'Ou'] }, answer: { correct: 'Où' }, explanation: 'où = where (lieu, interrogation). Trick : remplacer par "en quel endroit".' },
      { type: 'multiple_choice', question: { text: 'Il ___ parti hier.', options: ['est', 'et'] }, answer: { correct: 'est' }, explanation: 'est = verbe être (il est parti). et = and. Trick : remplacer par "était" → si ça marche, c\'est "est".' },
      { type: 'multiple_choice', question: { text: 'Elle aime la musique ___ la danse.', options: ['et', 'est'] }, answer: { correct: 'et' }, explanation: 'et = and (conjonction de coordination). Trick : remplacer par "et puis" → si ça marche, c\'est "et".' },
      { type: 'multiple_choice', question: { text: 'C\'est ___ livre préféré.', options: ['son', 'sont'] }, answer: { correct: 'son' }, explanation: 'son = possessif (his/her book). sont = verbe être pluriel (ils sont). Trick : remplacer par "ma" → si ça marche, c\'est "son".' },
      { type: 'multiple_choice', question: { text: 'Ils ___ très fatigués.', options: ['sont', 'son'] }, answer: { correct: 'sont' }, explanation: 'sont = verbe être (ils sont). Trick : remplacer par "étaient" → si ça marche, c\'est "sont".' },
      { type: 'multiple_choice', question: { text: 'Je prends ___ affaires et je pars.', options: ['mes', 'mais', 'mets'] }, answer: { correct: 'mes' }, explanation: 'mes = pluriel de mon/ma (possessif). mais = but. mets = mettre (verbe).' },
      { type: 'multiple_choice', question: { text: 'J\'aime la mer ___ j\'ai peur des vagues.', options: ['mais', 'mes', 'mets'] }, answer: { correct: 'mais' }, explanation: 'mais = but (opposition). Trick : remplacer par "cependant".' },
      { type: 'multiple_choice', question: { text: '___ enfants jouent dans le jardin.', options: ['Ces', 'Ses', 'C\'est'] }, answer: { correct: 'Ces' }, explanation: 'Ces = adjectif démonstratif pluriel (these/those). Ses = possessif pluriel (his/her). Trick : remplacer par "les" → si ça marche, c\'est "ces".' },
      { type: 'multiple_choice', question: { text: 'Il a rangé ___ affaires.', options: ['ses', 'ces', 'c\'est'] }, answer: { correct: 'ses' }, explanation: 'ses = possessif (his/her things). Trick : remplacer par "mes" → si ça marche, c\'est "ses".' },
      { type: 'multiple_choice', question: { text: 'Il ___ venu ___ pied.', options: ['est ... à', 'et ... a', 'est ... a'] }, answer: { correct: 'est ... à' }, explanation: 'est = verbe être. à pied = préposition fixe (on foot).' },
      { type: 'multiple_choice', question: { text: '___ bien de travailler ici.', options: ['C\'est', 'Ses', 'Ces'] }, answer: { correct: 'C\'est' }, explanation: 'C\'est = it is (c\'est + adjectif). Ces = démonstratif. Ses = possessif.' },
      { type: 'multiple_choice', question: { text: 'Marie ___ Sophie ___ parties ensemble.', options: ['et ... sont', 'est ... sont', 'et ... son'] }, answer: { correct: 'et ... sont' }, explanation: 'et = and (relie deux sujets). sont = verbe être pluriel.' },
      { type: 'multiple_choice', question: { text: 'Il lit ___ dort en même temps.', options: ['et', 'est'] }, answer: { correct: 'et' }, explanation: 'et = and. Relie deux verbes d\'une même personne.' },
      { type: 'multiple_choice', question: { text: 'Elle ___ allée ___ marché.', options: ['est ... au', 'et ... au', 'est ... à'] }, answer: { correct: 'est ... au' }, explanation: 'est = verbe être. au marché = au (à + le) devant nom masc. sing.' },
      { type: 'multiple_choice', question: { text: '___ tu veux manger ?', options: ['Qu\'est-ce que', 'Ou', 'Où'] }, answer: { correct: 'Qu\'est-ce que' }, explanation: 'Qu\'est-ce que = what. Question sur l\'objet de l\'action.' },
      { type: 'multiple_choice', question: { text: 'Ils ___ fatigués ___ ils ont bien dormi.', options: ['sont ... mais', 'son ... mais', 'sont ... et'] }, answer: { correct: 'sont ... mais' }, explanation: 'sont = verbe être. mais = but (opposition : fatigué → bien dormi).' },
      { type: 'multiple_choice', question: { text: 'Elle ___ souvenu ___ nous avions dit.', options: ['s\'est ... de ce que', 'c\'est ... que', 's\'est ... qu\''] }, answer: { correct: 's\'est ... de ce que' }, explanation: 'se souvenir de = to remember. s\'est = verbe pronominal. de ce que = of what.' },
      { type: 'multiple_choice', question: { text: 'Il habite ___ Bordeaux ___ à Lyon.', options: ['ou ... ou', 'où ... ou', 'ou ... où'] }, answer: { correct: 'ou ... ou' }, explanation: 'ou...ou = either...or (choix). Pas de question de lieu ici.' },
      { type: 'multiple_choice', question: { text: 'Le film ___ elle parle ___ sorti hier.', options: ['dont ... est', 'dont ... et', 'que ... est'] }, answer: { correct: 'dont ... est' }, explanation: 'dont = relative pronoun (about which). est = verbe être (le film est sorti).' },
      { type: 'multiple_choice', question: { text: 'Je ne sais pas ___ il est allé.', options: ['où', 'ou'] }, answer: { correct: 'où' }, explanation: 'où = where (pronom relatif de lieu ici). Pas de choix, donc pas "ou".' },
      { type: 'multiple_choice', question: { text: '___ chaussures ___ ___ manteau ?', options: ['Ces ... ou ... ce', 'Ses ... ou ... ce', 'Ces ... où ... ce'] }, answer: { correct: 'Ces ... ou ... ce' }, explanation: 'Ces = démonstratif pluriel. ou = or (choix). ce = démonstratif singulier.' },
      { type: 'multiple_choice', question: { text: 'On/Ont : Les enfants ___ mangé.', options: ['ont', 'on'] }, answer: { correct: 'ont' }, explanation: 'ont = verbe avoir pluriel (ils ont mangé). on = pronom indéfini (one/we). Trick : remplacer le sujet par "ils" → "ils ont mangé" ✓ → "ont".' },
    ],
  },

  // ─── B1 ──────────────────────────────────────────────────────────────────

  // 7. Hypothèse avec si
  {
    slug: 'si-hypothese',
    titleRu: 'Гипотезы с si',
    titleEn: 'Hypothetical si clauses',
    descriptionRu: 'Выбери правильное сочетание времён в предложениях с si: реальные и нереальные условия.',
    descriptionEn: 'Choose the correct tense combination in si clauses: real and hypothetical conditions.',
    level: 'B1',
    category: 'grammaire',
    difficulty: 2,
    icon: 'GitMerge',
    questions: [
      { type: 'multiple_choice', question: { text: 'Si tu ___ (venir), je serai content.', options: ['viens', 'venais', 'serais venu'] }, answer: { correct: 'viens' }, explanation: 'Si + présent → futur simple (hypothèse réalisable). Si tu viens → je serai content.' },
      { type: 'multiple_choice', question: { text: 'Si j\'___ (avoir) de l\'argent, j\'achèterais cette voiture.', options: ['avais', 'ai', 'aurais'] }, answer: { correct: 'avais' }, explanation: 'Si + imparfait → conditionnel présent (hypothèse peu probable ou imaginaire).' },
      { type: 'multiple_choice', question: { text: 'Si elle ___ (étudier) plus, elle aurait réussi.', options: ['avait étudié', 'étudiait', 'aura étudié'] }, answer: { correct: 'avait étudié' }, explanation: 'Si + plus-que-parfait → conditionnel passé (hypothèse irréelle dans le passé).' },
      { type: 'multiple_choice', question: { text: 'Si vous travaillez bien, vous ___ une prime.', options: ['recevrez', 'recevriez', 'avez reçu'] }, answer: { correct: 'recevrez' }, explanation: 'Si + présent → futur simple. Condition réelle et probable.' },
      { type: 'multiple_choice', question: { text: 'S\'il ___ (faire) beau, nous irions à la plage.', options: ['faisait', 'fait', 'aurait fait'] }, answer: { correct: 'faisait' }, explanation: 'Si + imparfait → conditionnel présent (wish/hypothetical). Il ne fait pas beau, mais si…' },
      { type: 'multiple_choice', question: { text: 'Si j\'___ (naître) en France, je parlerais mieux.', options: ['étais né', 'naissais', 'suis né'] }, answer: { correct: 'étais né' }, explanation: 'Hypothèse irréelle sur le passé → si + plus-que-parfait. Conséquence présente → conditionnel présent.' },
      { type: 'multiple_choice', question: { text: 'Si tu ___ (partir) maintenant, tu arriveras à l\'heure.', options: ['pars', 'partais', 'serais parti'] }, answer: { correct: 'pars' }, explanation: 'Conseil ou condition réelle → si + présent + futur (ou impératif).' },
      { type: 'multiple_choice', question: { text: 'Si j\'avais su, je n\'___ pas accepté.', options: ['aurais', 'avais', 'aurai'] }, answer: { correct: 'aurais' }, explanation: 'Si + plus-que-parfait → conditionnel passé. J\'aurais accepté = conditionnel passé.' },
      { type: 'multiple_choice', question: { text: 'Si on ___ (réduire) la pollution, la planète irait mieux.', options: ['réduisait', 'réduit', 'a réduit'] }, answer: { correct: 'réduisait' }, explanation: 'Hypothèse souhaitée mais incertaine → si + imparfait → conditionnel.' },
      { type: 'multiple_choice', question: { text: 'Si tu ___ (être) là hier, tu aurais compris.', options: ['avais été', 'étais', 'auras été'] }, answer: { correct: 'avais été' }, explanation: 'Regret ou reproche sur le passé → si + plus-que-parfait + conditionnel passé.' },
      { type: 'multiple_choice', question: { text: 'Si elle est libre, elle ___ (appeler) demain.', options: ['appellera', 'appellerait', 'appelait'] }, answer: { correct: 'appellera' }, explanation: 'Si + présent → futur simple. Condition probable dans le futur.' },
      { type: 'multiple_choice', question: { text: 'À ta place, si j\'___ (pouvoir), je partirais tout de suite.', options: ['pouvais', 'peux', 'ai pu'] }, answer: { correct: 'pouvais' }, explanation: 'Conseil hypothétique : si j\'étais à ta place (imparfait) → je partirais (cond. présent).' },
      { type: 'multiple_choice', question: { text: 'Si vous ___ (ne pas faire) de bruit, le bébé dormira.', options: ['ne faites pas', 'ne feriez pas', 'n\'aviez pas fait'] }, answer: { correct: 'ne faites pas' }, explanation: 'Condition réelle → si + présent → futur. Instruction ou prédiction.' },
      { type: 'multiple_choice', question: { text: 'Que ferait-il s\'il ___ (perdre) son emploi ?', options: ['perdait', 'perd', 'a perdu'] }, answer: { correct: 'perdait' }, explanation: 'Question sur une hypothèse imaginaire → si + imparfait → conditionnel présent.' },
      { type: 'multiple_choice', question: { text: 'Si tu l\'___ (dire) plus tôt, on aurait pu régler ça.', options: ['avais dit', 'disais', 'as dit'] }, answer: { correct: 'avais dit' }, explanation: 'Regret passé → si + plus-que-parfait → conditionnel passé.' },
      { type: 'multiple_choice', question: { text: 'Si j\'___ riche, je voyagerais partout.', options: ['étais', 'suis', 'aurais été'] }, answer: { correct: 'étais' }, explanation: 'Je ne suis pas riche, mais si j\'étais (imparfait) → je voyagerais (conditionnel présent).' },
      { type: 'multiple_choice', question: { text: 'Si l\'accord ___ (être) signé, la paix reviendra.', options: ['est', 'était', 'aura été'] }, answer: { correct: 'est' }, explanation: 'Condition réelle/probable → si + présent + futur.' },
      { type: 'multiple_choice', question: { text: 'Tu aurais dû l\'écouter si tu ___ (vouloir) comprendre.', options: ['avais voulu', 'voulais', 'veux'] }, answer: { correct: 'avais voulu' }, explanation: 'Reproche passé → conditionnel passé + si + plus-que-parfait.' },
      { type: 'multiple_choice', question: { text: 'Si ___ possible, il viendrait.', options: ['c\'était', 'c\'est', 'c\'aura été'] }, answer: { correct: 'c\'était' }, explanation: 'Hypothèse irréelle présente → si c\'était + conditionnel présent.' },
      { type: 'multiple_choice', question: { text: 'Si tu étudies régulièrement, tu ___ (progresser).', options: ['progresseras', 'progresserais', 'as progressé'] }, answer: { correct: 'progresseras' }, explanation: 'Si + présent → futur simple. Règle générale vraie.' },
      { type: 'multiple_choice', question: { text: 'On ___ (partir) si le temps le permettait.', options: ['partirait', 'partira', 'est parti'] }, answer: { correct: 'partirait' }, explanation: 'si le temps le permettait (imparfait) → conditionnel présent.' },
      { type: 'multiple_choice', question: { text: 'Si j\'avais travaillé plus, j\'___ (obtenir) ce poste.', options: ['aurais obtenu', 'obtenais', 'obtiendrai'] }, answer: { correct: 'aurais obtenu' }, explanation: 'Plus-que-parfait → conditionnel passé (regret sur une occasion passée manquée).' },
      { type: 'multiple_choice', question: { text: 'S\'il vient, ___ lui parler.', options: ['dis-lui / parle-lui', 'tu lui diras', 'tu lui disais'] }, answer: { correct: 'dis-lui / parle-lui' }, explanation: 'Si + présent → impératif aussi possible (instruction directe).' },
      { type: 'multiple_choice', question: { text: 'Si nous ___ (prendre) le train de 6h, on arriverait à l\'heure.', options: ['prenions', 'prenons', 'avons pris'] }, answer: { correct: 'prenions' }, explanation: 'Hypothèse peu probable ou alternative → si + imparfait → conditionnel.' },
      { type: 'multiple_choice', question: { text: 'Si tu ___ (lire) davantage, ton vocabulaire serait riche.', options: ['lisais', 'lis', 'as lu'] }, answer: { correct: 'lisais' }, explanation: 'Conseil hypothétique → si + imparfait + conditionnel présent.' },
    ],
  },

  // 8. Connecteurs logiques
  {
    slug: 'connecteurs-logiques',
    titleRu: 'Логические связки',
    titleEn: 'Logical connectors',
    descriptionRu: 'Cause, conséquence, opposition, concession — выбери правильный связующий элемент.',
    descriptionEn: 'Cause, consequence, opposition, concession — choose the correct connector.',
    level: 'B1',
    category: 'syntaxe',
    difficulty: 3,
    icon: 'Link',
    questions: [
      { type: 'multiple_choice', question: { text: 'Il est resté chez lui ___ il était malade.', options: ['parce qu\'', 'donc', 'pourtant'] }, answer: { correct: 'parce qu\'' }, explanation: 'parce que = because (cause). Répond à la question "pourquoi ?".' },
      { type: 'multiple_choice', question: { text: 'Il a beaucoup travaillé, ___ il a réussi.', options: ['donc', 'pourtant', 'bien que'] }, answer: { correct: 'donc' }, explanation: 'donc = therefore, so (conséquence). Cause → conséquence logique.' },
      { type: 'multiple_choice', question: { text: 'Elle est fatiguée ; ___, elle continue.', options: ['pourtant', 'donc', 'puisque'] }, answer: { correct: 'pourtant' }, explanation: 'pourtant = however, yet (opposition/concession). Attente déçue.' },
      { type: 'multiple_choice', question: { text: '___ tu es là, aide-moi !', options: ['Puisque', 'Parce que', 'Donc'] }, answer: { correct: 'Puisque' }, explanation: 'puisque = since (cause évidente/connue des deux). Pas une question, une conclusion logique.' },
      { type: 'multiple_choice', question: { text: 'Il fait froid, ___ je mets mon manteau.', options: ['c\'est pourquoi', 'pourtant', 'bien que'] }, answer: { correct: 'c\'est pourquoi' }, explanation: 'c\'est pourquoi = that\'s why (conséquence, plus formel que "donc").' },
      { type: 'multiple_choice', question: { text: 'Je suis allé au travail ___ j\'avais de la fièvre.', options: ['bien que', 'donc', 'car'] }, answer: { correct: 'bien que' }, explanation: 'bien que + subjonctif = although (concession). Bien que j\'aie de la fièvre → subjonctif.' },
      { type: 'multiple_choice', question: { text: 'Il ne viendra pas ___ il a d\'autres engagements.', options: ['car', 'donc', 'cependant'] }, answer: { correct: 'car' }, explanation: 'car = for/because (cause, plus formel/écrit que "parce que"). Car ne commence pas une phrase.' },
      { type: 'multiple_choice', question: { text: 'Elle est brillante ; ___, elle manque de confiance.', options: ['cependant', 'donc', 'puisque'] }, answer: { correct: 'cependant' }, explanation: 'cependant = however (opposition entre deux constats). Registre soutenu.' },
      { type: 'multiple_choice', question: { text: 'Il mange peu, ___ il est en bonne santé.', options: ['et pourtant', 'donc', 'car'] }, answer: { correct: 'et pourtant' }, explanation: 'et pourtant = and yet (concession surprised). Résultat inattendu.' },
      { type: 'multiple_choice', question: { text: 'Le projet a échoué ___ d\'un manque de communication.', options: ['à cause', 'grâce à', 'donc'] }, answer: { correct: 'à cause' }, explanation: 'à cause de = because of (cause négative). grâce à = thanks to (cause positive).' },
      { type: 'multiple_choice', question: { text: 'Il a réussi ___ ton aide.', options: ['grâce à', 'à cause de', 'malgré'] }, answer: { correct: 'grâce à' }, explanation: 'grâce à = thanks to (cause positive). à cause de = cause négative.' },
      { type: 'multiple_choice', question: { text: '___ la pluie, nous sommes sortis.', options: ['Malgré', 'À cause de', 'Grâce à'] }, answer: { correct: 'Malgré' }, explanation: 'malgré = despite, in spite of (concession). Malgré + nom (pas de verbe).' },
      { type: 'multiple_choice', question: { text: 'Il est parti ___ finir son travail.', options: ['sans', 'pour', 'donc'] }, answer: { correct: 'sans' }, explanation: 'sans + infinitif = without + -ing. Opposition entre l\'action attendue et l\'action réalisée.' },
      { type: 'multiple_choice', question: { text: 'Il travaille dur ___ avoir une belle carrière.', options: ['pour', 'donc', 'pourtant'] }, answer: { correct: 'pour' }, explanation: 'pour + infinitif = in order to (but, objectif). Exprime la finalité.' },
      { type: 'multiple_choice', question: { text: 'Elle est compétente, ___ elle ne passe jamais les entretiens.', options: ['néanmoins', 'donc', 'puisque'] }, answer: { correct: 'néanmoins' }, explanation: 'néanmoins = nevertheless (opposition, registre soutenu). Synonymes : cependant, pourtant.' },
      { type: 'multiple_choice', question: { text: 'Il est arrivé en retard ___ il y avait un embouteillage.', options: ['parce qu\'', 'c\'est pourquoi', 'cependant'] }, answer: { correct: 'parce qu\'' }, explanation: 'parce que = because. Répond directement à une cause.' },
      { type: 'multiple_choice', question: { text: 'Je n\'aime pas ce film, ___ je vais le regarder jusqu\'au bout.', options: ['mais', 'donc', 'car'] }, answer: { correct: 'mais' }, explanation: 'mais = but (opposition simple et directe). C\'est le connecteur d\'opposition le plus courant.' },
      { type: 'multiple_choice', question: { text: '___ il travaille beaucoup, il n\'est jamais stressé.', options: ['Bien qu\'', 'Parce qu\'', 'Donc'] }, answer: { correct: 'Bien qu\'' }, explanation: 'Bien que + subjonctif = although. Bien qu\'il travaille (subjonctif présent).' },
      { type: 'multiple_choice', question: { text: 'Le match a été annulé ___ le mauvais temps.', options: ['en raison du', 'grâce au', 'pour le'] }, answer: { correct: 'en raison du' }, explanation: 'en raison de = due to, because of (cause, style administratif/formel).' },
      { type: 'multiple_choice', question: { text: '___ que je sois fatigué, je dois finir ce rapport.', options: ['Quoique', 'Puisque', 'Car'] }, answer: { correct: 'Quoique' }, explanation: 'Quoique + subjonctif = although (synonyme de bien que, légèrement plus soutenu).' },
      { type: 'multiple_choice', question: { text: 'Il n\'a pas étudié, ___ a-t-il eu une bonne note.', options: ['pourtant', 'donc', 'puisque'] }, answer: { correct: 'pourtant' }, explanation: 'pourtant = yet/however. Résultat contraire aux attentes.' },
      { type: 'multiple_choice', question: { text: 'Elle a pris un parapluie ___ il pourrait pleuvoir.', options: ['au cas où', 'parce que', 'donc'] }, answer: { correct: 'au cas où' }, explanation: 'au cas où + conditionnel = in case. Précaution pour une éventualité.' },
      { type: 'multiple_choice', question: { text: 'Plus tu pratiques, ___ tu progresses.', options: ['plus', 'moins', 'autant'] }, answer: { correct: 'plus' }, explanation: 'Plus...plus = the more...the more. Corrélation de progression.' },
      { type: 'multiple_choice', question: { text: 'Il a réussi ___ les obstacles.', options: ['malgré', 'à cause des', 'pourtant'] }, answer: { correct: 'malgré' }, explanation: 'malgré = despite (+ nom). Réussite inattendue face aux difficultés.' },
      { type: 'multiple_choice', question: { text: 'Le projet n\'a pas abouti, ___ nous abandonnons.', options: ['par conséquent', 'pourtant', 'bien que'] }, answer: { correct: 'par conséquent' }, explanation: 'par conséquent = as a result, consequently (conséquence, registre formel).' },
    ],
  },

  // ─── B2 ──────────────────────────────────────────────────────────────────

  // 9. Subjonctif passé
  {
    slug: 'subjonctif-passe',
    titleRu: 'Сослагательное прошедшее время',
    titleEn: 'Subjonctif passé',
    descriptionRu: 'Образуй форму subjonctif passé: que + avoir/être au subjonctif + participe passé.',
    descriptionEn: 'Form the subjonctif passé: que + avoir/être in subjunctive + past participle.',
    level: 'B2',
    category: 'subjonctif',
    difficulty: 3,
    icon: 'Clock',
    questions: [
      { type: 'multiple_choice', question: { text: 'Je suis content qu\'il ___ (venir).', options: ['soit venu', 'est venu', 'viendrait'] }, answer: { correct: 'soit venu' }, explanation: 'Subjonctif passé : être au subj. présent + participe passé. venir → soit venu (verbe de mouvement, être).' },
      { type: 'multiple_choice', question: { text: 'Il est dommage que tu n\'___ (comprendre) pas.', options: ['aies compris', 'as compris', 'aurais compris'] }, answer: { correct: 'aies compris' }, explanation: 'avoir au subj. présent (aies) + compris. Après "il est dommage que" → subjonctif.' },
      { type: 'multiple_choice', question: { text: 'Bien qu\'elle ___ (travailler) dur, elle n\'a pas réussi.', options: ['ait travaillé', 'a travaillé', 'avait travaillé'] }, answer: { correct: 'ait travaillé' }, explanation: 'Bien que + subjonctif. Passé → subjonctif passé : ait travaillé.' },
      { type: 'multiple_choice', question: { text: 'Je doute qu\'ils ___ (partir) sans prévenir.', options: ['soient partis', 'sont partis', 'seraient partis'] }, answer: { correct: 'soient partis' }, explanation: 'partir → auxiliaire être. Subjonctif passé : soient partis.' },
      { type: 'multiple_choice', question: { text: 'C\'est le meilleur film que j\'___ (voir).', options: ['aie vu', 'ai vu', 'aurais vu'] }, answer: { correct: 'aie vu' }, explanation: 'Superlatif + que → subjonctif. Passé → subj. passé : aie vu.' },
      { type: 'multiple_choice', question: { text: 'Je regrette qu\'il ___ (ne pas venir).', options: ['ne soit pas venu', 'n\'est pas venu', 'ne serait pas venu'] }, answer: { correct: 'ne soit pas venu' }, explanation: 'regretter que → subjonctif. Passé négatif : ne soit pas venu.' },
      { type: 'multiple_choice', question: { text: 'Il est impossible qu\'elle ___ (faire) ça intentionnellement.', options: ['ait fait', 'a fait', 'aurait fait'] }, answer: { correct: 'ait fait' }, explanation: 'Il est impossible que → subjonctif. faire (avoir) → ait fait.' },
      { type: 'multiple_choice', question: { text: 'Quoique vous ___ (prendre) cette décision, elle reste discutable.', options: ['ayez pris', 'avez pris', 'auriez pris'] }, answer: { correct: 'ayez pris' }, explanation: 'Quoique + subjonctif. prendre → avoir. ayez pris.' },
      { type: 'multiple_choice', question: { text: 'Je cherche quelqu\'un qui ___ (vivre) en Chine.', options: ['ait vécu', 'a vécu', 'aurait vécu'] }, answer: { correct: 'ait vécu' }, explanation: 'Chercher quelqu\'un qui + subjonctif (personne hypothétique). Passé → ait vécu.' },
      { type: 'multiple_choice', question: { text: 'C\'est la première fois qu\'il ___ (mentir).', options: ['ait menti', 'a menti', 'avait menti'] }, answer: { correct: 'ait menti' }, explanation: 'C\'est la première fois que → subjonctif dans langue soutenue. ait menti.' },
      { type: 'multiple_choice', question: { text: 'Elle est triste que son ami ___ (tomber) malade.', options: ['soit tombé', 'est tombé', 'serait tombé'] }, answer: { correct: 'soit tombé' }, explanation: 'tomber → auxiliaire être. Subjonctif passé : soit tombé.' },
      { type: 'multiple_choice', question: { text: 'Avant qu\'ils ___ (décider), consultons-les.', options: ['aient décidé', 'ont décidé', 'auront décidé'] }, answer: { correct: 'aient décidé' }, explanation: 'Avant que + subjonctif. Passé → subj. passé : aient décidé.' },
      { type: 'multiple_choice', question: { text: 'Je suis surpris que vous ___ (ne rien dire).', options: ['n\'ayez rien dit', 'n\'avez rien dit', 'n\'auriez rien dit'] }, answer: { correct: 'n\'ayez rien dit' }, explanation: 'Après "être surpris que" → subjonctif. dire (avoir) → n\'ayez rien dit.' },
      { type: 'multiple_choice', question: { text: 'Il est peu probable qu\'elle ___ (réussir) du premier coup.', options: ['ait réussi', 'a réussi', 'aurait réussi'] }, answer: { correct: 'ait réussi' }, explanation: 'Il est peu probable que → subjonctif. Passé → ait réussi.' },
      { type: 'multiple_choice', question: { text: 'Je suis fier que tu ___ (obtenir) ce prix.', options: ['aies obtenu', 'as obtenu', 'aurais obtenu'] }, answer: { correct: 'aies obtenu' }, explanation: 'Être fier que → subjonctif. obtenir → avoir. aies obtenu.' },
      { type: 'multiple_choice', question: { text: 'Bien qu\'il ___ (ne pas dormir), il est en forme.', options: ['n\'ait pas dormi', 'n\'a pas dormi', 'n\'aurait pas dormi'] }, answer: { correct: 'n\'ait pas dormi' }, explanation: 'Bien que + subjonctif passé négatif. dormir → avoir. n\'ait pas dormi.' },
      { type: 'multiple_choice', question: { text: 'C\'est regrettable qu\'on ___ (ne pas trouver) de solution.', options: ['n\'ait pas trouvé', 'n\'a pas trouvé', 'ne trouvait pas'] }, answer: { correct: 'n\'ait pas trouvé' }, explanation: 'C\'est regrettable que → subjonctif. trouver → avoir. n\'ait pas trouvé.' },
      { type: 'multiple_choice', question: { text: 'Il faut qu\'il ___ (revenir) avant minuit.', options: ['soit revenu', 'est revenu', 'serait revenu'] }, answer: { correct: 'soit revenu' }, explanation: 'Il faut que → subjonctif. revenir → être. soit revenu.' },
      { type: 'multiple_choice', question: { text: 'Je ne pense pas qu\'ils ___ (partir) sans raison.', options: ['soient partis', 'sont partis', 'seraient partis'] }, answer: { correct: 'soient partis' }, explanation: 'Ne pas penser que → subjonctif. partir → être. soient partis.' },
      { type: 'multiple_choice', question: { text: 'Sans que nous ___ (se rendre compte), l\'heure a passé.', options: ['nous en soyons rendu compte', 'nous en sommes rendu compte', 'nous en serions rendu compte'] }, answer: { correct: 'nous en soyons rendu compte' }, explanation: 'Sans que + subjonctif. se rendre compte → être. soyons rendu compte.' },
      { type: 'multiple_choice', question: { text: 'Elle est la seule qui ___ (comprendre) ce problème.', options: ['ait compris', 'a compris', 'aurait compris'] }, answer: { correct: 'ait compris' }, explanation: 'La seule qui → subjonctif. comprendre → avoir. ait compris.' },
      { type: 'multiple_choice', question: { text: 'Pourvu qu\'il ___ (ne pas oublier) !', options: ['n\'ait pas oublié', 'n\'a pas oublié', 'n\'aurait pas oublié'] }, answer: { correct: 'n\'ait pas oublié' }, explanation: 'Pourvu que + subjonctif (souhait). Passé → n\'ait pas oublié.' },
      { type: 'multiple_choice', question: { text: 'Je suis désolé que tu ___ (attendre) si longtemps.', options: ['aies attendu', 'as attendu', 'aurais attendu'] }, answer: { correct: 'aies attendu' }, explanation: 'Être désolé que → subjonctif. attendre → avoir. aies attendu.' },
      { type: 'multiple_choice', question: { text: 'À moins qu\'il ___ (changer) d\'avis, le projet est annulé.', options: ['ait changé', 'a changé', 'aurait changé'] }, answer: { correct: 'ait changé' }, explanation: 'À moins que + subjonctif. Passé → ait changé.' },
      { type: 'multiple_choice', question: { text: 'C\'est la pire erreur que tu ___ (commettre).', options: ['aies commise', 'as commise', 'aurais commise'] }, answer: { correct: 'aies commise' }, explanation: 'Superlatif + que → subjonctif. commettre → avoir. Accord : erreur (fém.) → commise.' },
    ],
  },

  // 10. Concordance des temps
  {
    slug: 'concordance-temps',
    titleRu: 'Согласование времён',
    titleEn: 'Sequence of tenses',
    descriptionRu: 'Выбери правильное время в косвенной речи и в придаточных предложениях.',
    descriptionEn: 'Choose the correct tense in reported speech and subordinate clauses.',
    level: 'B2',
    category: 'syntaxe',
    difficulty: 3,
    icon: 'Timer',
    questions: [
      { type: 'multiple_choice', question: { text: 'Il m\'a dit qu\'il ___ (venir) le lendemain.', options: ['viendrait', 'viendra', 'est venu'] }, answer: { correct: 'viendrait' }, explanation: 'Discours indirect au passé : futur → conditionnel présent. "Il viendra" → "il viendrait".' },
      { type: 'multiple_choice', question: { text: 'Elle a expliqué qu\'elle ___ (être) fatiguée.', options: ['était', 'est', 'serait'] }, answer: { correct: 'était' }, explanation: 'Discours indirect passé : présent → imparfait. "Je suis fatiguée" → "elle était fatiguée".' },
      { type: 'multiple_choice', question: { text: 'Il a avoué qu\'il ___ (mentir).', options: ['avait menti', 'a menti', 'mentait'] }, answer: { correct: 'avait menti' }, explanation: 'Discours indirect passé : passé composé → plus-que-parfait. "J\'ai menti" → "il avait menti".' },
      { type: 'multiple_choice', question: { text: 'Elle pensait que nous ___ (rentrer) la veille.', options: ['étions rentrés', 'sommes rentrés', 'serions rentrés'] }, answer: { correct: 'étions rentrés' }, explanation: 'Passé composé → plus-que-parfait dans le discours indirect au passé.' },
      { type: 'multiple_choice', question: { text: 'Je savais qu\'il ___ (ne pas réussir).', options: ['ne réussirait pas', 'ne réussira pas', 'n\'a pas réussi'] }, answer: { correct: 'ne réussirait pas' }, explanation: 'Futur → conditionnel présent dans la subordonnée d\'un verbe au passé.' },
      { type: 'multiple_choice', question: { text: 'Il espérait qu\'elle ___ (venir) à temps.', options: ['viendrait', 'vient', 'viendra'] }, answer: { correct: 'viendrait' }, explanation: 'espérer que + futur au discours direct → conditionnel présent au discours indirect passé.' },
      { type: 'multiple_choice', question: { text: 'Il a demandé si nous ___ (avoir) le temps.', options: ['avions', 'avons', 'aurions'] }, answer: { correct: 'avions' }, explanation: 'Interrogation indirecte au passé : présent → imparfait. "Avez-vous le temps ?" → "si nous avions le temps".' },
      { type: 'multiple_choice', question: { text: 'Elle croyait qu\'il ___ (déjà partir).', options: ['était déjà parti', 'est déjà parti', 'serait déjà parti'] }, answer: { correct: 'était déjà parti' }, explanation: 'Passé composé → plus-que-parfait dans la subordonnée.' },
      { type: 'multiple_choice', question: { text: 'Quand elle est arrivée, il ___ (déjà manger).', options: ['avait déjà mangé', 'a déjà mangé', 'mange'] }, answer: { correct: 'avait déjà mangé' }, explanation: 'Plus-que-parfait pour une action antérieure à une autre action passée.' },
      { type: 'multiple_choice', question: { text: 'Il m\'a dit qu\'il ___ (travailler) toute la nuit précédente.', options: ['avait travaillé', 'a travaillé', 'travaillerait'] }, answer: { correct: 'avait travaillé' }, explanation: 'Action antérieure dans le discours indirect passé → plus-que-parfait.' },
      { type: 'multiple_choice', question: { text: 'Je ne savais pas qu\'il ___ (habiter) ici.', options: ['habitait', 'habite', 'habiterait'] }, answer: { correct: 'habitait' }, explanation: 'Présent dans la subordonnée d\'un verbe de connaissance au passé → imparfait.' },
      { type: 'multiple_choice', question: { text: 'Elle m\'a confirmé qu\'elle ___ (envoyer) le rapport.', options: ['avait envoyé', 'a envoyé', 'enverrait'] }, answer: { correct: 'avait envoyé' }, explanation: 'Action déjà accomplie rapportée au passé → plus-que-parfait.' },
      { type: 'multiple_choice', question: { text: 'Ils ont annoncé qu\'ils ___ (augmenter) les prix.', options: ['allaient augmenter', 'vont augmenter', 'augmenteront'] }, answer: { correct: 'allaient augmenter' }, explanation: 'Futur proche (aller + inf) → imparfait + infinitif dans le discours indirect passé.' },
      { type: 'multiple_choice', question: { text: 'Il paraissait que tout ___ (bien se passer).', options: ['s\'était bien passé', 'se passe bien', 's\'est bien passé'] }, answer: { correct: 's\'était bien passé' }, explanation: 'Verbe de perception au passé → plus-que-parfait pour l\'action antérieure.' },
      { type: 'multiple_choice', question: { text: 'Si j\'___ (savoir), je t\'aurais aidé.', options: ['avais su', 'savais', 'ai su'] }, answer: { correct: 'avais su' }, explanation: 'Hypothèse irréelle passée : si + plus-que-parfait → conditionnel passé.' },
      { type: 'multiple_choice', question: { text: 'Il a dit : "Je viendrai." → Il a dit qu\'il ___.', options: ['viendrait', 'viendra', 'était venu'] }, answer: { correct: 'viendrait' }, explanation: 'Transformation discours direct → indirect. Futur simple → conditionnel présent.' },
      { type: 'multiple_choice', question: { text: 'Elle a dit : "J\'ai fini." → Elle a dit qu\'elle ___.', options: ['avait fini', 'a fini', 'finissait'] }, answer: { correct: 'avait fini' }, explanation: 'Passé composé dans le discours direct → plus-que-parfait dans l\'indirect.' },
      { type: 'multiple_choice', question: { text: 'Il a demandé : "Pars-tu demain ?" → Il a demandé si ___.', options: ['je partais le lendemain', 'je pars demain', 'je partirais demain'] }, answer: { correct: 'je partais le lendemain' }, explanation: 'Présent → imparfait. demain → le lendemain dans le discours indirect.' },
      { type: 'multiple_choice', question: { text: 'Elle prétendait ne jamais ___ (voir) cet homme.', options: ['avoir vu', 'voir', 'avoir été vue'] }, answer: { correct: 'avoir vu' }, explanation: 'Après un verbe au passé + infinitif passé pour une action antérieure. prétendre avoir vu.' },
      { type: 'multiple_choice', question: { text: 'Je ___ (téléphoner) quand tu ___ (rentrer).', options: ['téléphonerai ... rentreras', 'téléphonerai ... rentres', 'téléphonerais ... rentrais'] }, answer: { correct: 'téléphonerai ... rentreras' }, explanation: 'Quand + futur dans les deux propositions (pas présent après quand dans un contexte futur).' },
      { type: 'multiple_choice', question: { text: 'Nous ___ (partir) dès qu\'il ___ (arriver).', options: ['partirons ... sera arrivé', 'partirons ... arrive', 'partirions ... arrive'] }, answer: { correct: 'partirons ... sera arrivé' }, explanation: 'Dès que → futur antérieur pour l\'action qui se complète en premier, futur simple pour la suivante.' },
      { type: 'multiple_choice', question: { text: 'Après qu\'il ___ (finir), nous sortirons.', options: ['aura fini', 'finit', 'finira'] }, answer: { correct: 'aura fini' }, explanation: 'Après que → futur antérieur (action achevée avant l\'autre action future).' },
      { type: 'multiple_choice', question: { text: 'Il dit qu\'il ___ là demain. (aujourd\'hui)', options: ['sera', 'serait', 'est'] }, answer: { correct: 'sera' }, explanation: 'Si le verbe principal est au présent, les temps ne changent pas dans la subordonnée.' },
      { type: 'multiple_choice', question: { text: 'Je pensais qu\'il ___ (venir) hier.', options: ['serait venu', 'sera venu', 'viendrait'] }, answer: { correct: 'serait venu' }, explanation: 'Futur antérieur → conditionnel passé dans le discours indirect passé.' },
      { type: 'multiple_choice', question: { text: 'Lorsqu\'elle ___ (terminer) ses études, elle voyagera.', options: ['aura terminé', 'terminera', 'termine'] }, answer: { correct: 'aura terminé' }, explanation: 'Lorsque = quand dans un contexte futur → futur antérieur pour l\'action préalable.' },
    ],
  },
];
