import type { ExerciseSeed } from './grammar-exercises-a1.js';

export const grammarExercisesB2: ExerciseSeed[] = [

  // ═══════════════════════════════════════════════════════════
  // subjonctif-passe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'subjonctif-passe',
    type: 'fill_blank',
    question: { text: 'Je suis ravi qu\'elle ___ (réussir) son examen.', blanks: 1 },
    answer: { values: ['ait réussi'] },
    explanation: 'После être ravi que — субжонктив. Действие завершено → субжонктив прошедшего: avoir (subj.) + participe → ait réussi.',
    explanationEn: 'After être ravi que, use the subjunctive. Completed action → past subjunctive: ait réussi.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'fill_blank',
    question: { text: 'Il est dommage que vous n\'___ pas ___ (voir) ce spectacle.', blanks: 2 },
    answer: { values: ['ayez', 'vu'] },
    explanation: 'Il est dommage que → субжонктив прошедшего с avoir: ayez vu. ne…pas охватывает оба элемента.',
    explanationEn: 'Il est dommage que → past subjunctive with avoir: ayez vu.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'fill_blank',
    question: { text: 'Bien qu\'il ___ (partir) tôt, il est arrivé en retard.', blanks: 1 },
    answer: { values: ['soit parti'] },
    explanation: 'Bien que → субжонктив. partir спрягается с être → soit parti.',
    explanationEn: 'Bien que requires the subjunctive. partir uses être → soit parti.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'multiple_choice',
    question: { text: 'Je doute qu\'ils ___ déjà ___ une décision.', options: ['aient pris', 'ont pris', 'prenaient', 'auraient pris'] },
    answer: { correct: 'aient pris' },
    explanation: 'Douter que → субжонктив. Действие предшествует → субжонктив прошедшего: aient pris.',
    explanationEn: 'Douter que triggers the subjunctive. Anterior action → past subjunctive: aient pris.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'fill_blank',
    question: { text: 'C\'est la meilleure décision qu\'il ___ (prendre) dans sa vie.', blanks: 1 },
    answer: { values: ['ait prise'] },
    explanation: 'Superlatif (la meilleure) → субжонктив. Действие завершено → субжонктив прошедшего. Согласование: décision (f.) → prise.',
    explanationEn: 'Superlative triggers subjunctive. Past subjunctive + agreement with décision (f.) → ait prise.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'multiple_choice',
    question: { text: 'Il est peu probable qu\'elle ___ la vérité hier.', options: ['ait dit', 'a dit', 'disait', 'dirait'] },
    answer: { correct: 'ait dit' },
    explanation: 'Il est peu probable que → субжонктив. Действие вчера = завершено → ait dit (субжонктив прошедшего).',
    explanationEn: 'Il est peu probable que → subjunctive. Past completed action → ait dit (past subjunctive).',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'fill_blank',
    question: { text: 'Je regrette de ne pas ___ (venir) à ta fête. (même sujet)', blanks: 1 },
    answer: { values: ['être venu'] },
    explanation: 'Même sujet → infinitif passé (pas de субжонктив). Venir → être + participe → être venu.',
    explanationEn: 'Same subject → past infinitive (not subjunctive). Venir uses être → être venu.',
  },
  {
    topicSlug: 'subjonctif-passe',
    type: 'multiple_choice',
    question: { text: 'Quoiqu\'il ___ beaucoup de talent, il n\'a pas réussi.', options: ['ait eu', 'avait', 'a eu', 'aurait eu'] },
    answer: { correct: 'ait eu' },
    explanation: 'Quoique → субжонктив. Avoir → ait eu (субжонктив прошедшего).',
    explanationEn: 'Quoique requires the subjunctive. avoir → ait eu (past subjunctive).',
  },

  // ═══════════════════════════════════════════════════════════
  // concordance-des-temps
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'concordance-des-temps',
    type: 'fill_blank',
    question: { text: 'Il a annoncé qu\'il ___ (venir) le lendemain.', blanks: 1 },
    answer: { values: ['viendrait'] },
    explanation: 'Глагол речи в passé composé → futur смещается в conditionnel présent: viendrait.',
    explanationEn: 'Reporting verb in past → futur shifts to conditionnel présent: viendrait.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'fill_blank',
    question: { text: 'Elle m\'a dit qu\'elle ___ (finir) son rapport la veille.', blanks: 1 },
    answer: { values: ['avait fini'] },
    explanation: 'Глагол речи в passé → passé composé смещается в plus-que-parfait: avait fini.',
    explanationEn: 'Reporting verb in past → passé composé shifts to plus-que-parfait: avait fini.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'fill_blank',
    question: { text: 'Le professeur a expliqué que la Terre ___ (tourner) autour du Soleil.', blanks: 1 },
    answer: { values: ['tourne'] },
    explanation: 'Вечная истина не подвергается согласованию — présent остаётся: tourne.',
    explanationEn: 'Universal truths do not backshift — présent stays: tourne.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'multiple_choice',
    question: { text: 'Si tu ___ plus tôt, tu aurais pu le voir.', options: ['étais arrivé', 'arrives', 'arrivais', 'seras arrivé'] },
    answer: { correct: 'étais arrivé' },
    explanation: 'Нереальное условие в прошлом: si + plus-que-parfait → conditionnel passé. étais arrivé = plus-que-parfait.',
    explanationEn: 'Unreal past conditional: si + plus-que-parfait → conditionnel passé. étais arrivé = plus-que-parfait.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'fill_blank',
    question: { text: 'Les témoins ont déclaré qu\'ils n\'___ (voir) rien d\'inhabituel ce soir-là.', blanks: 1 },
    answer: { values: ['avaient vu'] },
    explanation: 'Déclaré (passé) → passé composé смещается в plus-que-parfait: avaient vu.',
    explanationEn: 'Reporting verb in past → passé composé shifts to plus-que-parfait: avaient vu.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'multiple_choice',
    question: { text: 'Elle a affirmé qu\'elle ___ toujours la vérité.', options: ['disait', 'dit', 'dira', 'dirait'] },
    answer: { correct: 'disait' },
    explanation: 'Глагол речи в passé → présent смещается в imparfait: disait.',
    explanationEn: 'Reporting verb in past → présent shifts to imparfait: disait.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'fill_blank',
    question: { text: 'Si j\'___ (savoir) la réponse, je te l\'aurais dit.', blanks: 1 },
    answer: { values: ['avais su'] },
    explanation: 'Нереальное условие в прошлом: si + plus-que-parfait → conditionnel passé. Savoir → avais su.',
    explanationEn: 'Unreal past conditional: si + plus-que-parfait. savoir → avais su.',
  },
  {
    topicSlug: 'concordance-des-temps',
    type: 'multiple_choice',
    question: { text: 'Il m\'a demandé si je ___ libre le soir même.', options: ['étais', 'suis', 'serais', 'serai'] },
    answer: { correct: 'étais' },
    explanation: 'Косвенный вопрос после глагола в passé: présent → imparfait. suis → étais.',
    explanationEn: 'Indirect question after a past reporting verb: présent → imparfait. suis → étais.',
  },

  // ═══════════════════════════════════════════════════════════
  // pronoms-relatifs-composes
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'multiple_choice',
    question: { text: 'C\'est le projet ___ je travaille depuis six mois.', options: ['auquel', 'duquel', 'lequel', 'dont'] },
    answer: { correct: 'auquel' },
    explanation: 'Travailler à quelque chose → à + lequel → auquel (masculin singulier).',
    explanationEn: 'Travailler à → à + lequel → auquel (masculine singular).',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'multiple_choice',
    question: { text: 'Voilà la raison ___ je suis venu.', options: ['pour laquelle', 'pour lequel', 'pourquoi', 'dont'] },
    answer: { correct: 'pour laquelle' },
    explanation: 'La raison pour laquelle — raison feminine, предлог pour → pour laquelle.',
    explanationEn: 'La raison (f.) + pour → pour laquelle.',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'fill_blank',
    question: { text: 'Les collègues avec ___ je collabore sont très compétents. (collègues — m.pl.)', blanks: 1 },
    answer: { values: ['lesquels'] },
    explanation: 'Avec + collègues (m.pl.) → avec lesquels.',
    explanationEn: 'Avec + collègues (m.pl.) → avec lesquels.',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'multiple_choice',
    question: { text: 'Le bâtiment à côté ___ il habite est très ancien.', options: ['duquel', 'auquel', 'lequel', 'dont'] },
    answer: { correct: 'duquel' },
    explanation: 'À côté de + lequel → à côté duquel (masculin singulier).',
    explanationEn: 'À côté de + lequel → à côté duquel (masculine singular).',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'fill_blank',
    question: { text: 'Ce sont des questions ___ nous devons réfléchir. (réfléchir à)', blanks: 1 },
    answer: { values: ['auxquelles'] },
    explanation: 'Réfléchir à + questions (f.pl.) → à + lesquelles → auxquelles.',
    explanationEn: 'Réfléchir à + questions (f.pl.) → à + lesquelles → auxquelles.',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'multiple_choice',
    question: { text: 'La table sur ___ il a posé ses clés est dans l\'entrée.', options: ['laquelle', 'lequel', 'lesquelles', 'auquel'] },
    answer: { correct: 'laquelle' },
    explanation: 'Sur + table (f.sg.) → sur laquelle.',
    explanationEn: 'Sur + table (f.sg.) → sur laquelle.',
  },
  {
    topicSlug: 'pronoms-relatifs-composes',
    type: 'fill_blank',
    question: { text: 'C\'est un sujet ___ il est difficile de parler. (parler de)', blanks: 1 },
    answer: { values: ['dont'] },
    explanation: 'Parler de → dont. Dont = de qui / duquel. C\'est un sujet dont il est difficile de parler.',
    explanationEn: 'Parler de → dont (replaces de + noun).',
  },

  // ═══════════════════════════════════════════════════════════
  // discours-indirect-passe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'discours-indirect-passe',
    type: 'fill_blank',
    question: { text: '«Je partirai demain.» → Il a dit qu\'il ___ le lendemain.', blanks: 1 },
    answer: { values: ['partirait'] },
    explanation: 'Глагол речи в passé → futur simple смещается в conditionnel présent: partirait.',
    explanationEn: 'Past reporting verb → futur simple shifts to conditionnel présent: partirait.',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'fill_blank',
    question: { text: '«Nous avons fini le projet.» → Ils ont annoncé qu\'ils ___ le projet.', blanks: 1 },
    answer: { values: ['avaient fini'] },
    explanation: 'Глагол речи в passé → passé composé смещается в plus-que-parfait: avaient fini.',
    explanationEn: 'Past reporting verb → passé composé shifts to plus-que-parfait: avaient fini.',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'multiple_choice',
    question: { text: '«Viens me voir!» → Elle m\'a demandé ___ la voir.', options: ['de venir', 'que je vienne', 'si je venais', 'venir'] },
    answer: { correct: 'de venir' },
    explanation: 'Impératif в косвенной речи → de + infinitif: elle m\'a demandé de venir.',
    explanationEn: 'Imperative in reported speech → de + infinitive: elle m\'a demandé de venir.',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'fill_blank',
    question: { text: '«Est-ce que tu es prêt?» → Il m\'a demandé si j\'___ prêt.', blanks: 1 },
    answer: { values: ['étais'] },
    explanation: 'Косвенный вопрос после глагола в passé: es (présent) → étais (imparfait).',
    explanationEn: 'Indirect question after past verb: es (présent) → étais (imparfait).',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'multiple_choice',
    question: { text: '«Je travaille ici.» → Il a dit qu\'il travaillait ___.', options: ['là', 'ici', 'là-bas', 'près'] },
    answer: { correct: 'là' },
    explanation: 'В косвенной речи ici → là (сдвиг пространственного маркера).',
    explanationEn: 'In reported speech, ici shifts to là.',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'fill_blank',
    question: { text: '«J\'irai chez le médecin aujourd\'hui.» → Elle a dit qu\'elle irait chez le médecin ___.', blanks: 1 },
    answer: { values: ['ce jour-là'] },
    explanation: 'Aujourd\'hui в косвенной речи (прошлое) → ce jour-là.',
    explanationEn: 'Aujourd\'hui in past reported speech shifts to ce jour-là.',
  },
  {
    topicSlug: 'discours-indirect-passe',
    type: 'multiple_choice',
    question: { text: '«Nous viendrons demain.» → Ils ont promis qu\'ils viendraient ___.', options: ['le lendemain', 'demain', 'le jour d\'après', 'bientôt'] },
    answer: { correct: 'le lendemain' },
    explanation: 'Demain в косвенной речи в прошлом → le lendemain.',
    explanationEn: 'Demain in past reported speech → le lendemain.',
  },

  // ═══════════════════════════════════════════════════════════
  // condition-irreelle
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'condition-irreelle',
    type: 'fill_blank',
    question: { text: 'Si j\'___ (savoir) la vérité, je ne t\'aurais rien dit.', blanks: 1 },
    answer: { values: ['avais su'] },
    explanation: 'Нереальное условие в прошлом: si + plus-que-parfait. Savoir → avais su.',
    explanationEn: 'Unreal past condition: si + plus-que-parfait. savoir → avais su.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'fill_blank',
    question: { text: 'Tu ___ (réussir) si tu avais travaillé davantage.', blanks: 1 },
    answer: { values: ['aurais réussi'] },
    explanation: 'Нереальное условие в прошлом: главное предложение → conditionnel passé: aurais réussi.',
    explanationEn: 'Unreal past conditional: main clause → conditionnel passé: aurais réussi.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'multiple_choice',
    question: { text: 'Si elle avait pris ses médicaments, elle ___ bien maintenant.', options: ['irait', 'serait allée', 'allait', 'ira'] },
    answer: { correct: 'irait' },
    explanation: 'Смешанное условие: si + plus-que-parfait (прошлое) → conditionnel présent (следствие в настоящем): irait.',
    explanationEn: 'Mixed conditional: si + plus-que-parfait → conditionnel présent for present consequence: irait.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'fill_blank',
    question: { text: 'S\'il n\'___ pas (pleuvoir), nous aurions fait un pique-nique.', blanks: 1 },
    answer: { values: ['avait plu'] },
    explanation: 'Si + plus-que-parfait нереального условия: pleuvoir → avait plu.',
    explanationEn: 'Unreal past condition: si + plus-que-parfait. pleuvoir → avait plu.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'multiple_choice',
    question: { text: 'Laquelle de ces phrases est CORRECTE?', options: ['Si j\'avais su, je ne serais pas venu.', 'Si j\'aurais su, je ne serais pas venu.', 'Si je savais, je ne suis pas venu.', 'Si j\'ai su, je ne venais pas.'] },
    answer: { correct: 'Si j\'avais su, je ne serais pas venu.' },
    explanation: 'Нереальное условие: si + plus-que-parfait → conditionnel passé. Никогда не conditionnel после si.',
    explanationEn: 'Unreal condition: si + plus-que-parfait → conditionnel passé. Never use conditionnel after si.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'fill_blank',
    question: { text: 'Si nous ___ (partir) plus tôt, nous aurions évité les embouteillages.', blanks: 1 },
    answer: { values: ['étions partis'] },
    explanation: 'Si + plus-que-parfait: partir (avec être) → étions partis.',
    explanationEn: 'Si + plus-que-parfait: partir (with être) → étions partis.',
  },
  {
    topicSlug: 'condition-irreelle',
    type: 'multiple_choice',
    question: { text: 'Si tu avais appris le français, tu ___ mieux maintenant.', options: ['parlerais', 'aurais parlé', 'parlais', 'parleras'] },
    answer: { correct: 'parlerais' },
    explanation: 'Смешанное условие: passé → présent. Si + plus-que-parfait → conditionnel présent: parlerais.',
    explanationEn: 'Mixed conditional: past condition → present result. conditionnel présent: parlerais.',
  },

  // ═══════════════════════════════════════════════════════════
  // mise-en-relief
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'mise-en-relief',
    type: 'fill_blank',
    question: { text: 'Pierre a organisé la réunion. → C\'est Pierre ___ a organisé la réunion.', blanks: 1 },
    answer: { values: ['qui'] },
    explanation: 'Выделение подлежащего: c\'est [sujet] qui + verbe.',
    explanationEn: 'Subject cleft: c\'est [subject] qui + verb.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'fill_blank',
    question: { text: 'Je cherche ce livre. → C\'est ce livre ___ je cherche.', blanks: 1 },
    answer: { values: ['que'] },
    explanation: 'Выделение прямого дополнения: c\'est [objet] que + суjet + verbe.',
    explanationEn: 'Object cleft: c\'est [object] que + subject + verb.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'multiple_choice',
    question: { text: 'C\'est elle ___ a pris cette décision, pas moi.', options: ['qui', 'que', 'dont', 'où'] },
    answer: { correct: 'qui' },
    explanation: 'Elle = подлежащее → c\'est elle qui.',
    explanationEn: 'Elle = subject → c\'est elle qui.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'fill_blank',
    question: { text: 'J\'ai besoin de lui. → C\'est de lui ___ j\'ai besoin.', blanks: 1 },
    answer: { values: ['dont'] },
    explanation: 'Avoir besoin de → dont в выделительной конструкции: c\'est de lui dont j\'ai besoin.',
    explanationEn: 'Avoir besoin de → dont in cleft: c\'est de lui dont j\'ai besoin.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'multiple_choice',
    question: { text: 'C\'est ___ les enfants qui ont fait ce bruit.', options: ['bien', 'même', 'déjà', 'encore'] },
    answer: { correct: 'bien' },
    explanation: 'C\'est bien... qui — усилительная конструкция. «Именно дети»: C\'est bien les enfants qui ont fait ce bruit.',
    explanationEn: 'C\'est bien... qui is an emphatic cleft construction.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'fill_blank',
    question: { text: 'Il habite à Paris. → C\'est à Paris ___ il habite.', blanks: 1 },
    answer: { values: ['qu\''] },
    explanation: 'Выделение обстоятельства места: c\'est [lieu] que + sujet + verbe.',
    explanationEn: 'Adverbial cleft (place): c\'est [place] que + subject + verb.',
  },
  {
    topicSlug: 'mise-en-relief',
    type: 'multiple_choice',
    question: { text: 'Laquelle est correcte pour souligner «hier»: «Je l\'ai vu hier.»', options: ['C\'est hier que je l\'ai vu.', 'C\'est hier qui je l\'ai vu.', 'C\'est hier où je l\'ai vu.', 'C\'est hier dont je l\'ai vu.'] },
    answer: { correct: 'C\'est hier que je l\'ai vu.' },
    explanation: 'Выделение наречия времени: c\'est [temps] que + суjet + verbe.',
    explanationEn: 'Time adverbial cleft: c\'est [time] que + subject + verb.',
  },

  // ═══════════════════════════════════════════════════════════
  // negation-complexe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'negation-complexe',
    type: 'fill_blank',
    question: { text: 'Il ne mange ___ viande ___ poisson.', blanks: 2 },
    answer: { values: ['ni', 'ni'] },
    explanation: 'ne...ni...ni = ни...ни. Артикль после ni отсутствует.',
    explanationEn: 'ne...ni...ni = neither...nor. No article after ni.',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'multiple_choice',
    question: { text: 'Ce rapport ne m\'a ___ convaincu. (почти не)', options: ['guère', 'nullement', 'point', 'ni'] },
    answer: { correct: 'guère' },
    explanation: 'ne...guère = «почти не» (книжное). Ne...nullement/aucunement = совсем не.',
    explanationEn: 'ne...guère = "hardly/scarcely" (literary). ne...nullement = "not at all".',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'fill_blank',
    question: { text: 'Il a décidé de ne ___ revenir dans cette ville. (никогда)', blanks: 1 },
    answer: { values: ['jamais'] },
    explanation: 'При инфинитиве оба элемента отрицания стоят перед инфинитивом: ne jamais + infinitif.',
    explanationEn: 'With an infinitive, both negation elements go before it: ne jamais + infinitif.',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'multiple_choice',
    question: { text: 'Je ne suis ___ responsable de cette erreur. (совсем не)', options: ['nullement', 'guère', 'point', 'ni'] },
    answer: { correct: 'nullement' },
    explanation: 'ne...nullement = «совсем не, ничуть». Более книжно, чем ne...pas du tout.',
    explanationEn: 'ne...nullement = "not at all" (formal/literary).',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'fill_blank',
    question: { text: 'Elle n\'a ___ mangé ___ dormi de la nuit.', blanks: 2 },
    answer: { values: ['ni', 'ni'] },
    explanation: 'ne...ni...ni: elle n\'a ni mangé ni dormi. Глаголы перечисляются через ni.',
    explanationEn: 'ne...ni...ni with verbs: elle n\'a ni mangé ni dormi.',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'multiple_choice',
    question: { text: 'Il préfère ___ participer à cette discussion. (форма с инфинитивом)', options: ['ne pas', 'pas ne', 'ne jamais pas', 'non pas'] },
    answer: { correct: 'ne pas' },
    explanation: 'При инфинитиве: ne pas + infinitif. Оба элемента стоят перед инфинитивом: il préfère ne pas participer.',
    explanationEn: 'With infinitive: ne pas goes before the infinitive: il préfère ne pas participer.',
  },
  {
    topicSlug: 'negation-complexe',
    type: 'fill_blank',
    question: { text: 'Il n\'a ___ rien compris à cette explication. (двойное отрицание)', blanks: 1 },
    answer: { values: ['jamais'] },
    explanation: 'ne...jamais...rien = двойное отрицание: никогда ничего. Il n\'a jamais rien compris.',
    explanationEn: 'Double negation: ne...jamais...rien = never anything.',
  },

  // ═══════════════════════════════════════════════════════════
  // nominalisation
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'nominalisation',
    type: 'multiple_choice',
    question: { text: 'Quel nom correspond au verbe «développer»?', options: ['le développement', 'la développation', 'le développage', 'la développée'] },
    answer: { correct: 'le développement' },
    explanation: 'Développer → le développement (суффикс -ment, masculin).',
    explanationEn: 'développer → le développement (suffix -ment, masculine).',
  },
  {
    topicSlug: 'nominalisation',
    type: 'fill_blank',
    question: { text: 'Parce qu\'il est absent → En raison de son ___', blanks: 1 },
    answer: { values: ['absence'] },
    explanation: 'Absent → l\'absence. Номинализация заменяет причинное придаточное: en raison de son absence.',
    explanationEn: 'absent → l\'absence. Nominalisation replaces causal clause: en raison de son absence.',
  },
  {
    topicSlug: 'nominalisation',
    type: 'multiple_choice',
    question: { text: 'Il a décidé de partir. → Sa ___ de partir a surpris tout le monde.', options: ['décision', 'décidement', 'décidage', 'décidance'] },
    answer: { correct: 'décision' },
    explanation: 'Décider → la décision (суффикс -sion, féminin).',
    explanationEn: 'décider → la décision (suffix -sion, feminine).',
  },
  {
    topicSlug: 'nominalisation',
    type: 'fill_blank',
    question: { text: 'Les inégalités augmentent. → L\'___ des inégalités est préoccupante.', blanks: 1 },
    answer: { values: ['augmentation'] },
    explanation: 'Augmenter → l\'augmentation (суффикс -ation, féminin).',
    explanationEn: 'augmenter → l\'augmentation (suffix -ation, feminine).',
  },
  {
    topicSlug: 'nominalisation',
    type: 'multiple_choice',
    question: { text: 'Quel nom correspond à l\'adjectif «libre»?', options: ['la liberté', 'la libration', 'le librement', 'la librance'] },
    answer: { correct: 'la liberté' },
    explanation: 'Libre → la liberté (суффикс -té, féminin).',
    explanationEn: 'libre → la liberté (suffix -té, feminine).',
  },
  {
    topicSlug: 'nominalisation',
    type: 'fill_blank',
    question: { text: 'Il a refusé de participer. → Son ___ de participer a déçu le groupe.', blanks: 1 },
    answer: { values: ['refus'] },
    explanation: 'Refuser → le refus (déverbal, masculin).',
    explanationEn: 'refuser → le refus (deverbal noun, masculine).',
  },
  {
    topicSlug: 'nominalisation',
    type: 'multiple_choice',
    question: { text: 'Reformulez: «Parce qu\'il est arrivé en retard, la réunion a été reportée.»', options: ['En raison de son retard, la réunion a été reportée.', 'En raison qu\'il est arrivé en retard, la réunion a été reportée.', 'À cause de qu\'il était en retard, la réunion a été reportée.', 'Dû à son arrivée retardée, la réunion a été reportée.'] },
    answer: { correct: 'En raison de son retard, la réunion a été reportée.' },
    explanation: 'Номинализация: parce qu\'il est arrivé en retard → en raison de son retard.',
    explanationEn: 'Nominalisation: parce qu\'il est arrivé en retard → en raison de son retard.',
  },

  // ═══════════════════════════════════════════════════════════
  // expression-temps-avancee
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'expression-temps-avancee',
    type: 'fill_blank',
    question: { text: 'Dès que tu ___ (finir) tes devoirs, tu pourras regarder la télé.', blanks: 1 },
    answer: { values: ['auras fini'] },
    explanation: 'Dès que + futur antérieur (завершённое действие в будущем): auras fini.',
    explanationEn: 'Dès que + futur antérieur (completed future action): auras fini.',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'fill_blank',
    question: { text: 'Nous attendrons jusqu\'à ce qu\'il ___ (arriver).', blanks: 1 },
    answer: { values: ['arrive'] },
    explanation: 'Jusqu\'à ce que → всегда субжонктив настоящего: arrive.',
    explanationEn: 'Jusqu\'à ce que → always present subjunctive: arrive.',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'multiple_choice',
    question: { text: 'Partez ___ qu\'il ne soit trop tard.', options: ['avant', 'après', 'pendant', 'depuis'] },
    answer: { correct: 'avant' },
    explanation: 'Avant que + субжонктив: partez avant qu\'il ne soit trop tard.',
    explanationEn: 'Avant que + subjunctive: partez avant qu\'il ne soit trop tard.',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'fill_blank',
    question: { text: 'Depuis qu\'il ___ (changer) de travail, il est beaucoup plus heureux.', blanks: 1 },
    answer: { values: ['a changé'] },
    explanation: 'Depuis que + présent ou passé composé (action ponctuelle). Il a changé → état continu maintenant.',
    explanationEn: 'Depuis que + passé composé (punctual action with ongoing result).',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'multiple_choice',
    question: { text: 'Après qu\'il ___ parti, nous avons discuté du problème.', options: ['est', 'soit', 'était', 'serait'] },
    answer: { correct: 'est' },
    explanation: 'Après que → изъявительное наклонение (НЕ субжонктив): est parti.',
    explanationEn: 'Après que → indicative (NOT subjunctive): est parti.',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'fill_blank',
    question: { text: 'Au moment ___ elle est entrée, tout le monde s\'est tu.', blanks: 1 },
    answer: { values: ['où'] },
    explanation: 'Au moment où = в тот момент когда (конструкция с où для времени).',
    explanationEn: 'Au moment où = the moment when (où used for time reference).',
  },
  {
    topicSlug: 'expression-temps-avancee',
    type: 'multiple_choice',
    question: { text: 'Dès qu\'il ___ son rapport, le directeur le lira.', options: ['aura soumis', 'a soumis', 'soumet', 'soumettait'] },
    answer: { correct: 'aura soumis' },
    explanation: 'Dès que dans un contexte futur → futur antérieur (действие завершится первым): aura soumis.',
    explanationEn: 'Dès que in a future context → futur antérieur (first completed action): aura soumis.',
  },

  // ═══════════════════════════════════════════════════════════
  // infinitif-passe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'infinitif-passe',
    type: 'fill_blank',
    question: { text: 'Après ___ (terminer) ses études, elle a trouvé un emploi.', blanks: 1 },
    answer: { values: ['avoir terminé'] },
    explanation: 'Après + инфинитив прошедшего (avoir + participe): après avoir terminé.',
    explanationEn: 'Après + past infinitive (avoir + participle): après avoir terminé.',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'fill_blank',
    question: { text: 'Après ___ (partir), ils ont réalisé qu\'ils avaient oublié les clés.', blanks: 1 },
    answer: { values: ['être partis'] },
    explanation: 'Partir → être + participe. Après être partis (ils = m.pl. → partis).',
    explanationEn: 'partir uses être → après être partis (ils, masculine plural → partis).',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'multiple_choice',
    question: { text: 'Il regrette de ne pas ___ à la cérémonie.', options: ['être venu', 'avoir venu', 'venir', 'être venue'] },
    answer: { correct: 'être venu' },
    explanation: 'Venir → être + participe. Regretter de → инфинитив прошедшего: de ne pas être venu (il → venu).',
    explanationEn: 'Venir uses être. regretter de + past infinitive: de ne pas être venu.',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'fill_blank',
    question: { text: 'Elle a été félicitée pour ___ (sauver) l\'enfant.', blanks: 1 },
    answer: { values: ['avoir sauvé'] },
    explanation: 'Pour + инфинитив прошедшего (завершённое действие): pour avoir sauvé.',
    explanationEn: 'Pour + past infinitive (completed action): pour avoir sauvé.',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'multiple_choice',
    question: { text: 'Il est parti sans ___ personne.', options: ['avoir prévenu', 'prévenir', 'avoir prévenir', 'être prévenu'] },
    answer: { correct: 'avoir prévenu' },
    explanation: 'Sans + инфинитив прошедшего (действие не совершилось): sans avoir prévenu.',
    explanationEn: 'Sans + past infinitive (action that did not happen): sans avoir prévenu.',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'fill_blank',
    question: { text: 'Après ___ (se lever), il a préparé le café. (sujet: il)', blanks: 1 },
    answer: { values: ['s\'être levé'] },
    explanation: 'Возвратный глагол: s\'être + participe passé. Après s\'être levé (il → levé).',
    explanationEn: 'Reflexive verb: s\'être + past participle. Après s\'être levé.',
  },
  {
    topicSlug: 'infinitif-passe',
    type: 'multiple_choice',
    question: { text: 'Après ___ toute la nuit, elles étaient épuisées.', options: ['avoir travaillé', 'travailler', 'être travaillées', 'avoir travaillées'] },
    answer: { correct: 'avoir travaillé' },
    explanation: 'Travailler → avoir + participe. Après avoir travaillé (pas d\'accord avec avoir).',
    explanationEn: 'travailler uses avoir. After avoir, no agreement: après avoir travaillé.',
  },

  // ═══════════════════════════════════════════════════════════
  // tournures-impersonnelles
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'multiple_choice',
    question: { text: 'Il ___ que cette information était incorrecte. (оказалось)', options: ['s\'est avéré', 'est apparu', 'se trouve', 'paraît'] },
    answer: { correct: 's\'est avéré' },
    explanation: 'Il s\'avère que = «оказывается, что». В прошлом: il s\'est avéré que.',
    explanationEn: 'Il s\'avère que = "it turns out that". Past: il s\'est avéré que.',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'fill_blank',
    question: { text: 'Il ___ que vous arriviez avant midi. (важно, необходимо)', blanks: 1 },
    answer: { values: ['importe que'] },
    explanation: 'Il importe que + субжонктив = «важно, чтобы».',
    explanationEn: 'Il importe que + subjunctive = "it is important that".',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'multiple_choice',
    question: { text: 'Il ___ d\'ouvrir une nouvelle filiale à Lyon.', options: ['est question', 'est parlé', 'se dit', 'est mentionné'] },
    answer: { correct: 'est question' },
    explanation: 'Il est question de = «речь идёт о, планируется» + nom ou infinitif.',
    explanationEn: 'Il est question de = "there is talk of / it is a matter of" + noun or infinitive.',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'fill_blank',
    question: { text: 'Il ___ de vérifier les données avant publication. (следует)', blanks: 1 },
    answer: { values: ['convient'] },
    explanation: 'Il convient de + infinitif = «следует, уместно».',
    explanationEn: 'Il convient de + infinitive = "it is advisable to".',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'multiple_choice',
    question: { text: 'Il se ___ qu\'il y ait un problème dans le système.', options: ['peut', 'doit', 'faut', 'semble'] },
    answer: { correct: 'peut' },
    explanation: 'Il se peut que + субжонктив = «возможно, что».',
    explanationEn: 'Il se peut que + subjunctive = "it is possible that".',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'fill_blank',
    question: { text: 'Il va ___ dire que vous êtes le bienvenu.', blanks: 1 },
    answer: { values: ['sans'] },
    explanation: 'Il va sans dire que = «само собой разумеется, что» + изъявительное наклонение.',
    explanationEn: 'Il va sans dire que = "it goes without saying that" + indicative.',
  },
  {
    topicSlug: 'tournures-impersonnelles',
    type: 'multiple_choice',
    question: { text: 'Il ___ que les résultats soient publiés demain.', options: ['est prévu', 'est question', 'convient', 's\'avère'] },
    answer: { correct: 'est prévu' },
    explanation: 'Il est prévu que = «планируется, что» + субжонктив или indicatif.',
    explanationEn: 'Il est prévu que = "it is planned that" + subjunctive or indicative.',
  },

  // ═══════════════════════════════════════════════════════════
  // connecteurs-b2
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'connecteurs-b2',
    type: 'multiple_choice',
    question: { text: 'La situation est grave. ___, les chiffres le confirment. (подтверждение)', options: ['En effet', 'En fait', 'Or', 'Pourtant'] },
    answer: { correct: 'En effet' },
    explanation: 'En effet подтверждает предыдущее утверждение. En fait = «на самом деле» (противопоставление).',
    explanationEn: 'En effet confirms the preceding statement. En fait introduces a contrasting "actually".',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'fill_blank',
    question: { text: 'La tâche est complexe, ___ plus qu\'il n\'existe pas de solution simple.', blanks: 1 },
    answer: { values: ['d\'autant'] },
    explanation: 'D\'autant plus que = «тем более что»: усиливает предыдущую мысль.',
    explanationEn: 'd\'autant plus que = "all the more so because".',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'multiple_choice',
    question: { text: 'Il est brillant ; ___, il manque d\'organisation.', options: ['en revanche', 'en effet', 'd\'autant plus', 'or'] },
    answer: { correct: 'en revanche' },
    explanation: 'En revanche / par contre = «с другой стороны, тогда как». Противопоставление.',
    explanationEn: 'En revanche = "on the other hand". Contrast connector.',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'fill_blank',
    question: { text: 'Il s\'est trompé ; ___, il ne l\'admettra jamais. (однако, между тем)', blanks: 1 },
    answer: { values: ['or'] },
    explanation: 'Or = «однако, между тем» — коннектор уступки/перехода. Не путать с «ou» (или).',
    explanationEn: 'Or = "however/yet" — transition/concessive connector. Not to be confused with ou (or).',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'multiple_choice',
    question: { text: '___ bien même tu insisterais, je ne changerais pas d\'avis.', options: ['Quand', 'Si', 'Même', 'Bien'] },
    answer: { correct: 'Quand' },
    explanation: 'Quand bien même + conditionnel = «даже если бы» (нереальное условие с уступкой).',
    explanationEn: 'Quand bien même + conditional = "even if" (concessive unreal condition).',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'fill_blank',
    question: { text: '___ donné que le budget est limité, nous devons faire des choix.', blanks: 1 },
    answer: { values: ['Étant'] },
    explanation: 'Étant donné que = «учитывая, что; принимая во внимание, что» (причина).',
    explanationEn: 'Étant donné que = "given that / considering that" (causal connector).',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'multiple_choice',
    question: { text: 'Il a perdu la compétition, sans ___ se décourager.', options: ['pour autant', 'en revanche', 'or', 'en effet'] },
    answer: { correct: 'pour autant' },
    explanation: 'Sans pour autant = «не при этом, тем не менее». Используется в отрицательных конструкциях.',
    explanationEn: 'Sans pour autant = "without thereby / even so". Used in negative contexts.',
  },
  {
    topicSlug: 'connecteurs-b2',
    type: 'fill_blank',
    question: { text: 'Il travaillait dur, ___ bien qu\'il ne réussisse pas toujours.', blanks: 1 },
    answer: { values: ['quoique'] },
    explanation: 'Quoique / bien que + субжонктив = «хотя, несмотря на то что» (уступка).',
    explanationEn: 'Quoique / bien que + subjunctive = "although" (concession).',
  },
];
