import type { ExerciseSeed } from './grammar-exercises-a1.js';

export const grammarExercisesB1: ExerciseSeed[] = [

  // ═══════════════════════════════════════════════════════════
  // subjonctif-present
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'subjonctif-present',
    type: 'fill_blank',
    question: { text: 'Il faut que tu ___ (finir) tes devoirs avant de sortir.', blanks: 1 },
    answer: { values: ['finisses'] },
    explanation: 'После il faut que — субжонктив. finir: основа ils finissent → finiss- + -es → finisses.',
    explanationEn: 'After il faut que, use the subjunctive. finir: ils finissent stem finiss- + -es → finisses.',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'fill_blank',
    question: { text: 'Je veux que vous ___ (être) à l\'heure demain.', blanks: 1 },
    answer: { values: ['soyez'] },
    explanation: 'После vouloir que — субжонктив. être — неправильный: sois, sois, soit, soyons, soyez, soient.',
    explanationEn: 'After vouloir que, use the subjunctive. être is irregular: sois, sois, soit, soyons, soyez, soient.',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'fill_blank',
    question: { text: 'Il est possible que Marie ___ (avoir) raison.', blanks: 1 },
    answer: { values: ['ait'] },
    explanation: 'Il est possible que требует субжонктива. avoir — неправильный: aie, aies, ait, ayons, ayez, aient.',
    explanationEn: 'Il est possible que requires the subjunctive. avoir is irregular: aie, aies, ait, ayons, ayez, aient.',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'multiple_choice',
    question: { text: 'Bien qu\'il ___ fatigué, il continue à travailler.', options: ['soit', 'est', 'sera', 'était'] },
    answer: { correct: 'soit' },
    explanation: 'Bien que всегда требует субжонктива. être → soit (3-е лицо ед.ч. субжонктив).',
    explanationEn: 'Bien que always requires the subjunctive. être → soit (3rd person singular subjunctive).',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'multiple_choice',
    question: { text: 'Pour que tu ___ comprendre, je vais expliquer plus lentement.', options: ['puisses', 'peux', 'pourras', 'pouvais'] },
    answer: { correct: 'puisses' },
    explanation: 'Pour que требует субжонктива. pouvoir — неправильный: puisse, puisses, puisse...',
    explanationEn: 'Pour que requires the subjunctive. pouvoir is irregular: puisse, puisses, puisse...',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'translate',
    question: { text: 'Нужно, чтобы он пришёл вовремя.', from: 'ru', to: 'fr' },
    answer: { text: 'Il faut qu\'il vienne à l\'heure.' },
    explanation: 'Il faut que + субжонктив. venir → неправильный: vienne, viennes, vienne, venions, veniez, viennent.',
    explanationEn: 'Il faut que + subjunctive. venir is irregular: vienne, viennes, vienne, venions, veniez, viennent.',
  },
  {
    topicSlug: 'subjonctif-present',
    type: 'translate',
    question: { text: 'Я рад, что ты здесь.', from: 'ru', to: 'fr' },
    answer: { text: 'Je suis content que tu sois là.' },
    explanation: 'Être content que требует субжонктива. être → sois (2-е лицо ед.ч.).',
    explanationEn: 'Être content que requires the subjunctive. être → sois (2nd person singular).',
  },

  // ═══════════════════════════════════════════════════════════
  // conditionnel-present
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'conditionnel-present',
    type: 'fill_blank',
    question: { text: 'Si j\'avais plus de temps, je ___ (voyager) davantage.', blanks: 1 },
    answer: { values: ['voyagerais'] },
    explanation: 'Si + imparfait → conditionnel présent. voyager: основа voyager + -ais → voyagerais.',
    explanationEn: 'Si + imparfait → conditionnel présent. voyager + -ais → voyagerais.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'fill_blank',
    question: { text: '___ (pouvoir)-vous m\'aider, s\'il vous plaît ?', blanks: 1 },
    answer: { values: ['Pourriez'] },
    explanation: 'Вежливая просьба в кондисьонале. pouvoir: неправильная основа pourr- + -iez → Pourriez.',
    explanationEn: 'Polite request in conditional. pouvoir: irregular stem pourr- + -iez → Pourriez.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'fill_blank',
    question: { text: 'Il a dit qu\'il ___ (venir) demain.', blanks: 1 },
    answer: { values: ['viendrait'] },
    explanation: 'Косвенная речь: futur → conditionnel présent. venir: неправильная основа viendr- + -ait → viendrait.',
    explanationEn: 'Indirect speech: future becomes conditional. venir: irregular stem viendr- + -ait → viendrait.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'multiple_choice',
    question: { text: 'Je ___ un café, s\'il vous plaît.', options: ['voudrais', 'veux', 'voulais', 'voudrai'] },
    answer: { correct: 'voudrais' },
    explanation: 'Вежливое желание → кондисьональ. vouloir: основа voudr- + -ais → voudrais.',
    explanationEn: 'Polite wish → conditional. vouloir: stem voudr- + -ais → voudrais.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'multiple_choice',
    question: { text: 'Si nous avions de l\'argent, nous ___ une grande maison.', options: ['achèterions', 'achèterons', 'avons acheté', 'achetions'] },
    answer: { correct: 'achèterions' },
    explanation: 'Si + imparfait → conditionnel présent. acheter: achèter- + -ions → achèterions.',
    explanationEn: 'Si + imparfait → conditionnel présent. acheter: stem achèter- + -ions → achèterions.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'translate',
    question: { text: 'Если бы он знал правду, он бы не пришёл.', from: 'ru', to: 'fr' },
    answer: { text: 'S\'il savait la vérité, il ne viendrait pas.' },
    explanation: 'Si + imparfait (savait) → conditionnel présent (viendrait). Отрицание: ne...pas.',
    explanationEn: 'Si + imparfait (savait) → conditionnel présent (viendrait). Negation: ne...pas.',
  },
  {
    topicSlug: 'conditionnel-present',
    type: 'translate',
    question: { text: 'Ты мог бы открыть окно?', from: 'ru', to: 'fr' },
    answer: { text: 'Tu pourrais ouvrir la fenêtre ?' },
    explanation: 'Вежливая просьба → кондисьональ. pouvoir: pourr- + -ais → pourrais (для tu).',
    explanationEn: 'Polite request → conditional. pouvoir: pourr- + -ais → pourrais (for tu).',
  },

  // ═══════════════════════════════════════════════════════════
  // conditionnel-passe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'conditionnel-passe',
    type: 'fill_blank',
    question: { text: 'Si j\'avais su, je ___ (ne pas partir).', blanks: 1 },
    answer: { values: ['ne serais pas parti', 'ne serais pas partie'] },
    explanation: 'Si + plus-que-parfait → conditionnel passé. partir → être. Conditionnel passé: ne serais pas parti.',
    explanationEn: 'Si + plus-que-parfait → conditionnel passé. partir uses être. Conditionnel passé: ne serais pas parti.',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'fill_blank',
    question: { text: 'Nous ___ (devoir) réserver les billets à l\'avance.', blanks: 1 },
    answer: { values: ['aurions dû'] },
    explanation: 'Сожаление о прошлом → conditionnel passé. devoir → participe: dû. nous aurions dû.',
    explanationEn: 'Regret about the past → conditionnel passé. devoir → past participle: dû. nous aurions dû.',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'fill_blank',
    question: { text: 'Si elle avait étudié, elle ___ (réussir) l\'examen.', blanks: 1 },
    answer: { values: ['aurait réussi'] },
    explanation: 'Si + plus-que-parfait → conditionnel passé. réussir → réussi. elle aurait réussi.',
    explanationEn: 'Si + plus-que-parfait → conditionnel passé. réussir → réussi. elle aurait réussi.',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'multiple_choice',
    question: { text: 'Tu ___ me prévenir ! Je t\'ai attendu deux heures.', options: ['aurais pu', 'pourrais', 'as pu', 'avais pu'] },
    answer: { correct: 'aurais pu' },
    explanation: 'Упрёк о прошлом → conditionnel passé. pouvoir: aurais pu.',
    explanationEn: 'Reproach about the past → conditionnel passé. pouvoir: aurais pu.',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'multiple_choice',
    question: { text: 'Si vous ___ plus tôt, vous n\'auriez pas raté le train.', options: ['étiez partis', 'seriez partis', 'partiez', 'êtes partis'] },
    answer: { correct: 'étiez partis' },
    explanation: 'Si + plus-que-parfait → conditionnel passé. partir (être): étiez partis (plus-que-parfait, 2 мн.ч.).',
    explanationEn: 'Si + plus-que-parfait → conditionnel passé. partir (être): étiez partis (pluperfect, 2nd plural).',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'translate',
    question: { text: 'Нам следовало взять зонтик.', from: 'ru', to: 'fr' },
    answer: { text: 'Nous aurions dû prendre un parapluie.' },
    explanation: 'Devoir au conditionnel passé: aurions dû. prendre → infinitif après devoir.',
    explanationEn: 'Devoir in conditionnel passé: aurions dû. prendre stays as infinitive after devoir.',
  },
  {
    topicSlug: 'conditionnel-passe',
    type: 'translate',
    question: { text: 'Если бы ты пришёл раньше, ты бы увидел его.', from: 'ru', to: 'fr' },
    answer: { text: 'Si tu étais arrivé plus tôt, tu l\'aurais vu.' },
    explanation: 'Si + plus-que-parfait (étais arrivé) → conditionnel passé (aurais vu).',
    explanationEn: 'Si + pluperfect (étais arrivé) → conditionnel passé (aurais vu).',
  },

  // ═══════════════════════════════════════════════════════════
  // plus-que-parfait
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'plus-que-parfait',
    type: 'fill_blank',
    question: { text: 'Quand je suis arrivé, il ___ (partir) déjà.', blanks: 1 },
    answer: { values: ['était déjà parti'] },
    explanation: 'Действие до другого прошедшего → plus-que-parfait. partir + être: était parti.',
    explanationEn: 'Action before another past action → plus-que-parfait. partir + être: était parti.',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'fill_blank',
    question: { text: 'Elle ne savait pas que tu ___ (appeler) hier.', blanks: 1 },
    answer: { values: ['avais appelé'] },
    explanation: 'Действие предшествует «не знала» → plus-que-parfait. appeler + avoir: avais appelé.',
    explanationEn: 'Action before "she didn\'t know" → plus-que-parfait. appeler + avoir: avais appelé.',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'fill_blank',
    question: { text: 'Ils ont mangé le gâteau que leur mère ___ (préparer).', blanks: 1 },
    answer: { values: ['avait préparé'] },
    explanation: 'Приготовление произошло раньше поедания → plus-que-parfait. préparer + avoir: avait préparé.',
    explanationEn: 'Preparation happened before eating → plus-que-parfait. préparer + avoir: avait préparé.',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'multiple_choice',
    question: { text: 'Il n\'a pas pu entrer parce qu\'il ___ sa clé.', options: ['avait perdu', 'a perdu', 'perdait', 'perd'] },
    answer: { correct: 'avait perdu' },
    explanation: 'Потеря ключа произошла до невозможности войти → plus-que-parfait: avait perdu.',
    explanationEn: 'Losing the key happened before being unable to enter → plus-que-parfait: avait perdu.',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'multiple_choice',
    question: { text: 'Nous ___ déjà commandé quand le serveur est revenu.', options: ['avions', 'avons', 'aurions', 'avions eu'] },
    answer: { correct: 'avions' },
    explanation: 'Plus-que-parfait с avoir: avions + commandé. Полная форма: avions commandé.',
    explanationEn: 'Pluperfect with avoir: avions + commandé. Full form: avions commandé.',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'translate',
    question: { text: 'Когда она открыла письмо, она уже слышала эту новость.', from: 'ru', to: 'fr' },
    answer: { text: 'Quand elle a ouvert la lettre, elle avait déjà entendu la nouvelle.' },
    explanation: 'Услышала раньше → plus-que-parfait (avait entendu). Открыла → passé composé (a ouvert).',
    explanationEn: 'Heard earlier → plus-que-parfait (avait entendu). Opened → passé composé (a ouvert).',
  },
  {
    topicSlug: 'plus-que-parfait',
    type: 'translate',
    question: { text: 'Он не знал, что она уехала.', from: 'ru', to: 'fr' },
    answer: { text: 'Il ne savait pas qu\'elle était partie.' },
    explanation: 'Отъезд предшествует «не знал» → plus-que-parfait с être. partir: était partie (ж.р.).',
    explanationEn: 'Departure precedes "he didn\'t know" → pluperfect with être. partir: était partie (feminine).',
  },

  // ═══════════════════════════════════════════════════════════
  // futur-anterieur
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'futur-anterieur',
    type: 'fill_blank',
    question: { text: 'Dès que tu ___ (finir) ton travail, on pourra partir.', blanks: 1 },
    answer: { values: ['auras fini'] },
    explanation: 'После dès que с двумя будущими действиями — futur antérieur. finir + avoir: auras fini.',
    explanationEn: 'After dès que with two future actions → futur antérieur. finir + avoir: auras fini.',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'fill_blank',
    question: { text: 'Quand elle ___ (arriver), nous commencerons à manger.', blanks: 1 },
    answer: { values: ['sera arrivée'] },
    explanation: 'После quand с двумя будущими действиями — futur antérieur. arriver + être, ж.р.: sera arrivée.',
    explanationEn: 'After quand with two future actions → futur antérieur. arriver + être, feminine: sera arrivée.',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'fill_blank',
    question: { text: 'Dans cinq ans, j\'___ (obtenir) mon doctorat.', blanks: 1 },
    answer: { values: ['aurai obtenu'] },
    explanation: 'Действие завершится в будущем → futur antérieur. obtenir → obtenu. j\'aurai obtenu.',
    explanationEn: 'Action will be completed in the future → futur antérieur. obtenir → obtenu. j\'aurai obtenu.',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'multiple_choice',
    question: { text: 'Téléphone-moi dès que tu ___ à la gare.', options: ['seras arrivé', 'arrives', 'es arrivé', 'arriveras'] },
    answer: { correct: 'seras arrivé' },
    explanation: 'Dès que + futur antérieur (действие завершится раньше). arriver + être: seras arrivé.',
    explanationEn: 'Dès que + futur antérieur (completed action). arriver + être: seras arrivé.',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'multiple_choice',
    question: { text: 'Il n\'est toujours pas rentré — il ___ raté son train.', options: ['aura raté', 'aurait raté', 'a raté', 'avait raté'] },
    answer: { correct: 'aura raté' },
    explanation: 'Предположение о прошедшем с точки зрения настоящего → futur antérieur. rater: aura raté.',
    explanationEn: 'Supposition about a past event from the present perspective → futur antérieur. rater: aura raté.',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'translate',
    question: { text: 'Как только он вернётся домой, он тебе позвонит.', from: 'ru', to: 'fr' },
    answer: { text: 'Dès qu\'il sera rentré, il te téléphonera.' },
    explanation: 'Dès que + futur antérieur (sera rentré) + futur simple (téléphonera).',
    explanationEn: 'Dès que + futur antérieur (sera rentré) + futur simple (téléphonera).',
  },
  {
    topicSlug: 'futur-anterieur',
    type: 'translate',
    question: { text: 'Через год мы уже закончим этот проект.', from: 'ru', to: 'fr' },
    answer: { text: 'Dans un an, nous aurons terminé ce projet.' },
    explanation: 'Futur antérieur для завершённого будущего. terminer + avoir: aurons terminé.',
    explanationEn: 'Futur antérieur for a completed future action. terminer + avoir: aurons terminé.',
  },

  // ═══════════════════════════════════════════════════════════
  // pronoms-y-en
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'pronoms-y-en',
    type: 'fill_blank',
    question: { text: 'Tu vas au marché ? — Oui, j\'___ vais cet après-midi.', blanks: 1 },
    answer: { values: ['y'] },
    explanation: 'Y заменяет место (au marché = à + lieu). J\'y vais.',
    explanationEn: 'Y replaces a location (au marché = à + place). J\'y vais.',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'fill_blank',
    question: { text: 'Il parle souvent de son voyage. — Oui, il ___ parle tout le temps !', blanks: 1 },
    answer: { values: ['en'] },
    explanation: 'En заменяет de + вещь (de son voyage). Il en parle.',
    explanationEn: 'En replaces de + thing (de son voyage). Il en parle.',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'fill_blank',
    question: { text: 'Combien de croissants veux-tu ? — J\'___ veux trois.', blanks: 1 },
    answer: { values: ['en'] },
    explanation: 'En заменяет существительное при числовом выражении. J\'en veux trois.',
    explanationEn: 'En replaces a noun in a quantity expression. J\'en veux trois.',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'multiple_choice',
    question: { text: 'Tu as besoin de ce document ? — Oui, j\'___ ai besoin.', options: ['en', 'y', 'le', 'lui'] },
    answer: { correct: 'en' },
    explanation: 'Avoir besoin de → en. J\'en ai besoin. (en заменяет de + вещь)',
    explanationEn: 'Avoir besoin de → en. J\'en ai besoin. (en replaces de + thing)',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'multiple_choice',
    question: { text: 'Il pense à ses vacances tout le temps. Il ___ pense tout le temps.', options: ['y', 'en', 'les', 'lui'] },
    answer: { correct: 'y' },
    explanation: 'Penser à + вещь → y. Il y pense. (y заменяет à + вещь)',
    explanationEn: 'Penser à + thing → y. Il y pense. (y replaces à + thing)',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'translate',
    question: { text: 'У тебя есть молоко? — Да, я купил немного.', from: 'ru', to: 'fr' },
    answer: { text: 'Tu as du lait ? — Oui, j\'en ai acheté.' },
    explanation: 'En заменяет du lait (количество без числа). В passé composé: j\'en ai acheté.',
    explanationEn: 'En replaces du lait (quantity without number). In passé composé: j\'en ai acheté.',
  },
  {
    topicSlug: 'pronoms-y-en',
    type: 'translate',
    question: { text: 'Ты был в Италии? — Да, я был там в прошлом году.', from: 'ru', to: 'fr' },
    answer: { text: 'Tu es allé en Italie ? — Oui, j\'y suis allé l\'année dernière.' },
    explanation: 'Y заменяет место (en Italie). Passé composé: j\'y suis allé.',
    explanationEn: 'Y replaces a place (en Italie). Passé composé: j\'y suis allé.',
  },

  // ═══════════════════════════════════════════════════════════
  // pronoms-relatifs-dont-ou
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'fill_blank',
    question: { text: 'C\'est le film ___ tout le monde parle en ce moment.', blanks: 1 },
    answer: { values: ['dont'] },
    explanation: 'parler de → dont. C\'est le film dont tout le monde parle.',
    explanationEn: 'parler de → dont. C\'est le film dont tout le monde parle.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'fill_blank',
    question: { text: 'La ville ___ je suis né est très petite.', blanks: 1 },
    answer: { values: ['où'] },
    explanation: 'Où заменяет lieu (dans laquelle). La ville où je suis né.',
    explanationEn: 'Où replaces a place (dans laquelle). La ville où je suis né.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'fill_blank',
    question: { text: 'C\'est un ami ___ j\'ai vraiment besoin en ce moment.', blanks: 1 },
    answer: { values: ['dont'] },
    explanation: 'avoir besoin de → dont. un ami dont j\'ai besoin.',
    explanationEn: 'avoir besoin de → dont. un ami dont j\'ai besoin.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'multiple_choice',
    question: { text: 'C\'est la maison ___ les fenêtres sont bleues.', options: ['dont', 'où', 'que', 'qui'] },
    answer: { correct: 'dont' },
    explanation: 'Принадлежность (les fenêtres de la maison) → dont. La maison dont les fenêtres sont bleues.',
    explanationEn: 'Possession (les fenêtres de la maison) → dont. La maison dont les fenêtres sont bleues.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'multiple_choice',
    question: { text: 'Je me souviens du jour ___ nous nous sommes rencontrés.', options: ['où', 'dont', 'que', 'qui'] },
    answer: { correct: 'où' },
    explanation: 'Où заменяет момент времени (ce jour-là). Le jour où nous nous sommes rencontrés.',
    explanationEn: 'Où replaces a time expression. Le jour où nous nous sommes rencontrés.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'translate',
    question: { text: 'Это книга, о которой я тебе говорил.', from: 'ru', to: 'fr' },
    answer: { text: 'C\'est le livre dont je t\'ai parlé.' },
    explanation: 'parler de → dont. Passé composé: dont je t\'ai parlé.',
    explanationEn: 'parler de → dont. Passé composé: dont je t\'ai parlé.',
  },
  {
    topicSlug: 'pronoms-relatifs-dont-ou',
    type: 'translate',
    question: { text: 'Это эпоха, когда всё было иначе.', from: 'ru', to: 'fr' },
    answer: { text: 'C\'est l\'époque où tout était différent.' },
    explanation: 'Où для момента времени (cette époque). l\'époque où tout était différent.',
    explanationEn: 'Où for a time period. l\'époque où tout était différent.',
  },

  // ═══════════════════════════════════════════════════════════
  // pronoms-demonstratifs
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'fill_blank',
    question: { text: 'Tu préfères quel stylo ? ___ -ci ou ___ -là ?', blanks: 2 },
    answer: { values: ['Celui', 'celui'] },
    explanation: 'Stylo — мужского рода → celui. Celui-ci (этот) ou celui-là (тот).',
    explanationEn: 'Stylo is masculine → celui. Celui-ci (this one) ou celui-là (that one).',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'fill_blank',
    question: { text: 'Ma voiture est plus rapide que ___ de mon frère.', blanks: 1 },
    answer: { values: ['celle'] },
    explanation: 'Voiture — женского рода → celle. Celle de mon frère (машина моего брата).',
    explanationEn: 'Voiture is feminine → celle. Celle de mon frère (my brother\'s car).',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'fill_blank',
    question: { text: '___ qui arrive en retard devra rester après la classe.', blanks: 1 },
    answer: { values: ['Celui'] },
    explanation: 'Celui qui = тот, кто (м.р. ед.ч.). Указательное с придаточным.',
    explanationEn: 'Celui qui = the one who (masculine singular) with a relative clause.',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'multiple_choice',
    question: { text: 'J\'aime ces deux robes mais je préfère ___ que tu portais hier.', options: ['celle', 'celui', 'ceux', 'celles'] },
    answer: { correct: 'celle' },
    explanation: 'Robe — женского рода ед.ч. → celle. Celle que tu portais hier.',
    explanationEn: 'Robe is feminine singular → celle. Celle que tu portais hier.',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'multiple_choice',
    question: { text: 'Ces chaussures sont confortables, mais ___ d\'hier étaient mieux.', options: ['celles', 'ceux', 'celle', 'celui'] },
    answer: { correct: 'celles' },
    explanation: 'Chaussures — женского рода мн.ч. → celles. Celles d\'hier.',
    explanationEn: 'Chaussures is feminine plural → celles. Celles d\'hier.',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'translate',
    question: { text: 'Эта сумка красивее, чем сумка Марии.', from: 'ru', to: 'fr' },
    answer: { text: 'Ce sac est plus beau que celui de Marie.' },
    explanation: 'Sac — мужского рода → celui. Сравнение с принадлежностью: celui de Marie.',
    explanationEn: 'Sac is masculine → celui. Comparison with possession: celui de Marie.',
  },
  {
    topicSlug: 'pronoms-demonstratifs',
    type: 'translate',
    question: { text: 'Те, кто хочет участвовать, должны записаться.', from: 'ru', to: 'fr' },
    answer: { text: 'Ceux qui veulent participer doivent s\'inscrire.' },
    explanation: 'Ceux qui (м.р. мн.ч.) для неопределённой группы. vouloir → veulent.',
    explanationEn: 'Ceux qui (masculine plural) for an unspecified group. vouloir → veulent.',
  },

  // ═══════════════════════════════════════════════════════════
  // voix-passive
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'voix-passive',
    type: 'fill_blank',
    question: { text: 'Ce roman ___ (écrire) par Victor Hugo en 1862.', blanks: 1 },
    answer: { values: ['a été écrit'] },
    explanation: 'Пассив в passé composé: a été + participe passé. écrire → écrit. roman (м.р.) → écrit.',
    explanationEn: 'Passive in passé composé: a été + past participle. écrire → écrit. roman (masculine) → écrit.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'fill_blank',
    question: { text: 'Les résultats ___ (annoncer) demain matin.', blanks: 1 },
    answer: { values: ['seront annoncés'] },
    explanation: 'Пассив в futur simple: seront + participe passé. résultats (м.р., мн.ч.) → annoncés.',
    explanationEn: 'Passive in futur simple: seront + past participle. résultats (masculine plural) → annoncés.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'fill_blank',
    question: { text: 'La maison ___ (construire) par des ouvriers italiens.', blanks: 1 },
    answer: { values: ['a été construite'] },
    explanation: 'Пассив в passé composé. construire → construite. maison (ж.р.) → construite.',
    explanationEn: 'Passive in passé composé. construire → construite. maison (feminine) → construite.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'multiple_choice',
    question: { text: 'Le gâteau ___ par les enfants en dix minutes.', options: ['a été mangé', 'est mangé', 'était mangé', 'sera mangé'] },
    answer: { correct: 'a été mangé' },
    explanation: 'Завершённое прошедшее действие в пассиве → passé composé пассива: a été mangé.',
    explanationEn: 'Completed past passive action → passé composé of the passive: a été mangé.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'multiple_choice',
    question: { text: 'Elle ___ de tous ses collègues pour sa gentillesse.', options: ['est appréciée', 'a été appréciée', 'est apprécié', 'sont appréciés'] },
    answer: { correct: 'est appréciée' },
    explanation: 'С глаголом состояния (apprécier) в présent. elle (ж.р.) → appréciée. Par → de для состояний.',
    explanationEn: 'State verb (apprécier) in présent passive. elle (feminine) → appréciée. Note de for state verbs.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'translate',
    question: { text: 'Этот закон был принят в прошлом году.', from: 'ru', to: 'fr' },
    answer: { text: 'Cette loi a été adoptée l\'année dernière.' },
    explanation: 'Пассив в passé composé. loi (ж.р.) → adoptée. a été adoptée.',
    explanationEn: 'Passive in passé composé. loi (feminine) → adoptée. a été adoptée.',
  },
  {
    topicSlug: 'voix-passive',
    type: 'translate',
    question: { text: 'Новый мост будет построен через два года.', from: 'ru', to: 'fr' },
    answer: { text: 'Un nouveau pont sera construit dans deux ans.' },
    explanation: 'Пассив в futur simple. pont (м.р.) → construit. sera construit.',
    explanationEn: 'Passive in futur simple. pont (masculine) → construit. sera construit.',
  },

  // ═══════════════════════════════════════════════════════════
  // gerondif
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'gerondif',
    type: 'fill_blank',
    question: { text: 'Il a appris la nouvelle ___ (lire) son journal du matin.', blanks: 1 },
    answer: { values: ['en lisant'] },
    explanation: 'Герундий: en + participe présent. lire → nous lisons → lis- + -ant → lisant → en lisant.',
    explanationEn: 'Gerund: en + present participle. lire → nous lisons → lis- + -ant → lisant → en lisant.',
  },
  {
    topicSlug: 'gerondif',
    type: 'fill_blank',
    question: { text: '___ (travailler) régulièrement, tu progresseras rapidement.', blanks: 1 },
    answer: { values: ['En travaillant'] },
    explanation: 'Герундий в начале предложения (условие). travailler → travaillant → En travaillant.',
    explanationEn: 'Gerund at the start of a sentence (condition). travailler → travaillant → En travaillant.',
  },
  {
    topicSlug: 'gerondif',
    type: 'fill_blank',
    question: { text: 'Elle écoute de la musique ___ (faire) le ménage.', blanks: 1 },
    answer: { values: ['en faisant'] },
    explanation: 'Герундий для одновременности. faire → nous faisons → fais- + -ant → faisant → en faisant.',
    explanationEn: 'Gerund for simultaneity. faire → nous faisons → fais- + -ant → faisant → en faisant.',
  },
  {
    topicSlug: 'gerondif',
    type: 'multiple_choice',
    question: { text: 'Il s\'est cassé la jambe ___ du ski.', options: ['en faisant', 'faisant', 'pour faire', 'à faire'] },
    answer: { correct: 'en faisant' },
    explanation: 'Герундий = en + participe présent. Обстоятельство при котором произошло действие.',
    explanationEn: 'Gerund = en + present participle. Describes the circumstances of the action.',
  },
  {
    topicSlug: 'gerondif',
    type: 'multiple_choice',
    question: { text: 'Tout ___ d\'accord, elle a exprimé quelques réserves.', options: ['en étant', 'étant', 'en été', 'à être'] },
    answer: { correct: 'en étant' },
    explanation: 'Tout en + герундий = уступка. être → étant → en étant. Tout en étant d\'accord = хотя и соглашаясь.',
    explanationEn: 'Tout en + gerund = concession. être → étant → en étant. Tout en étant d\'accord = while agreeing.',
  },
  {
    topicSlug: 'gerondif',
    type: 'translate',
    question: { text: 'Он отвечал на вопросы, улыбаясь.', from: 'ru', to: 'fr' },
    answer: { text: 'Il répondait aux questions en souriant.' },
    explanation: 'Герундий для сопутствующего образа действия. sourire → nous sourions → souri- + -ant → souriant.',
    explanationEn: 'Gerund for accompanying manner. sourire → nous sourions → souri- + -ant → souriant.',
  },
  {
    topicSlug: 'gerondif',
    type: 'translate',
    question: { text: 'Смотря французские фильмы, я улучшаю свой язык.', from: 'ru', to: 'fr' },
    answer: { text: 'En regardant des films français, j\'améliore mon niveau de langue.' },
    explanation: 'Герундий в начале предложения. regarder → regardant → En regardant.',
    explanationEn: 'Gerund at the start. regarder → regardant → En regardant.',
  },

  // ═══════════════════════════════════════════════════════════
  // accord-participe-passe
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'accord-participe-passe',
    type: 'fill_blank',
    question: { text: 'Les lettres que j\'ai ___ (écrire) sont sur la table.', blanks: 1 },
    answer: { values: ['écrites'] },
    explanation: 'COD (les lettres = que) стоит перед глаголом → согласование. lettres (ж.р., мн.ч.) → écrites.',
    explanationEn: 'COD (les lettres = que) precedes the verb → agreement. lettres (feminine plural) → écrites.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'fill_blank',
    question: { text: 'Marie s\'est ___ (lever) très tôt ce matin.', blanks: 1 },
    answer: { values: ['levée'] },
    explanation: 'Возвратный глагол с être: причастие согласуется с субъектом. Marie (ж.р.) → levée.',
    explanationEn: 'Reflexive verb with être: participle agrees with the subject. Marie (feminine) → levée.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'fill_blank',
    question: { text: 'Ils se sont ___ (laver) les mains avant de manger.', blanks: 1 },
    answer: { values: ['lavé'] },
    explanation: 'Se = COI (les mains = COD, стоит после глагола) → нет согласования. lavé без изменений.',
    explanationEn: 'Se = COI (les mains = COD after the verb) → no agreement. lavé stays unchanged.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'multiple_choice',
    question: { text: 'Quelle robe as-tu ___  ?', options: ['choisie', 'choisi', 'choisies', 'choisit'] },
    answer: { correct: 'choisie' },
    explanation: 'COD (quelle robe) стоит перед глаголом. robe (ж.р. ед.ч.) → choisie.',
    explanationEn: 'COD (quelle robe) precedes the verb. robe (feminine singular) → choisie.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'multiple_choice',
    question: { text: 'Nous avons visité les musées que notre guide nous avait ___.', options: ['recommandés', 'recommandé', 'recommandées', 'recommandé'] },
    answer: { correct: 'recommandés' },
    explanation: 'COD (les musées = que) предшествует авуар. musées (м.р., мн.ч.) → recommandés.',
    explanationEn: 'COD (les musées = que) precedes avoir. musées (masculine plural) → recommandés.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'translate',
    question: { text: 'Она купила книги, которые ей нравились.', from: 'ru', to: 'fr' },
    answer: { text: 'Elle a acheté les livres qui lui plaisaient.' },
    explanation: 'COD (les livres) следует после глагола → нет согласования. qui (субъект придаточного) → нет согласования с глаголом.',
    explanationEn: 'COD (les livres) follows the verb → no agreement. qui is subject of the relative clause.',
  },
  {
    topicSlug: 'accord-participe-passe',
    type: 'translate',
    question: { text: 'Девочки, которых я встретил, были очень симпатичными.', from: 'ru', to: 'fr' },
    answer: { text: 'Les filles que j\'ai rencontrées étaient très sympathiques.' },
    explanation: 'COD (les filles = que) перед avons → согласование. filles (ж.р., мн.ч.) → rencontrées.',
    explanationEn: 'COD (les filles = que) before avoir → agreement. filles (feminine plural) → rencontrées.',
  },

  // ═══════════════════════════════════════════════════════════
  // verbes-subjonctif-infinitif
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'fill_blank',
    question: { text: 'Je veux ___ (partir) en vacances. / Je veux que tu ___ (partir) aussi.', blanks: 2 },
    answer: { values: ['partir', 'partes'] },
    explanation: 'Один субъект → инфинитив (partir). Разные субъекты → субжонктив (que tu partes).',
    explanationEn: 'Same subject → infinitive (partir). Different subjects → subjunctive (que tu partes).',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'fill_blank',
    question: { text: 'Il est important d\'___ (étudier) régulièrement.', blanks: 1 },
    answer: { values: ['étudier'] },
    explanation: 'Il est important de + infinitif (общее правило без указания субъекта). Инфинитив.',
    explanationEn: 'Il est important de + infinitive (general rule without specified subject). Infinitive.',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'fill_blank',
    question: { text: 'Il est important que tu ___ (étudier) régulièrement.', blanks: 1 },
    answer: { values: ['étudies'] },
    explanation: 'Il est important que + субжонктив (указан субъект — tu). étudier → étudies.',
    explanationEn: 'Il est important que + subjunctive (subject specified — tu). étudier → étudies.',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'multiple_choice',
    question: { text: 'J\'espère que tu ___ demain.', options: ['viendras', 'viennes', 'viens', 'serais venu'] },
    answer: { correct: 'viendras' },
    explanation: 'Espérer que требует индикатива (НЕ субжонктива). Futur simple: viendras.',
    explanationEn: 'Espérer que takes the indicative (NOT subjunctive). Future tense: viendras.',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'multiple_choice',
    question: { text: 'Elle souhaite que son fils ___ médecin.', options: ['devienne', 'devient', 'deviendra', 'devenait'] },
    answer: { correct: 'devienne' },
    explanation: 'Souhaiter que — разные субъекты → субжонктив. devenir → неправильный: devienne.',
    explanationEn: 'Souhaiter que with different subjects → subjunctive. devenir is irregular: devienne.',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'translate',
    question: { text: 'Мы рады, что вы смогли прийти.', from: 'ru', to: 'fr' },
    answer: { text: 'Nous sommes contents que vous ayez pu venir.' },
    explanation: 'Être content que + субжонктив (разные субъекты). pouvoir субжонктив прош.: ayez pu.',
    explanationEn: 'Être content que + subjunctive (different subjects). pouvoir passé du subjonctif: ayez pu.',
  },
  {
    topicSlug: 'verbes-subjonctif-infinitif',
    type: 'translate',
    question: { text: 'Он хочет уехать в Париж. / Он хочет, чтобы мы уехали в Париж.', from: 'ru', to: 'fr' },
    answer: { text: 'Il veut partir à Paris. / Il veut que nous partions à Paris.' },
    explanation: 'Один субъект → инфинитив. Разные → que + субжонктив. partir → partions (nous).',
    explanationEn: 'Same subject → infinitive. Different → que + subjunctive. partir → partions (nous).',
  },

  // ═══════════════════════════════════════════════════════════
  // discours-indirect
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'discours-indirect',
    type: 'fill_blank',
    question: { text: '«Je suis fatigué.» → Il a dit qu\'il ___ fatigué.', blanks: 1 },
    answer: { values: ['était'] },
    explanation: 'Косвенная речь: глагол сообщения в прошедшем → présent → imparfait. être → était.',
    explanationEn: 'Indirect speech: reporting verb in past → présent becomes imparfait. être → était.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'fill_blank',
    question: { text: '«Je viendrai demain.» → Elle a promis qu\'elle ___ le lendemain.', blanks: 1 },
    answer: { values: ['viendrait'] },
    explanation: 'Futur simple → conditionnel présent. venir: viendrait. demain → le lendemain.',
    explanationEn: 'Future simple becomes conditional. venir → viendrait. demain → le lendemain.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'fill_blank',
    question: { text: '«Est-ce que tu travailles ?» → Il m\'a demandé ___ je travaillais.', blanks: 1 },
    answer: { values: ['si'] },
    explanation: 'Вопрос да/нет → si в косвенной речи. Il m\'a demandé si je travaillais.',
    explanationEn: 'Yes/no question → si in indirect speech. Il m\'a demandé si je travaillais.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'multiple_choice',
    question: { text: '«Qu\'est-ce que tu veux ?» → Elle a demandé ___ je voulais.', options: ['ce que', 'si', 'que', 'ce qui'] },
    answer: { correct: 'ce que' },
    explanation: '«Qu\'est-ce que» (COD) → ce que в косвенной речи. Elle a demandé ce que je voulais.',
    explanationEn: '"Qu\'est-ce que" (direct object) → ce que in indirect speech.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'multiple_choice',
    question: { text: '«Où habites-tu ?» → Il a demandé où ___ habitais.', options: ['je', 'tu', 'il', 'nous'] },
    answer: { correct: 'je' },
    explanation: 'В косвенной речи tu (вопрошаемый) → je (говорящий в пересказе). Нет инверсии.',
    explanationEn: 'In indirect speech, tu (the addressed) → je (the speaker in the retelling). No inversion.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'translate',
    question: { text: 'Он сказал мне: «Я уже ел». → Он сказал мне, что уже ел.', from: 'ru', to: 'fr' },
    answer: { text: 'Il m\'a dit qu\'il avait déjà mangé.' },
    explanation: 'Passé composé → plus-que-parfait в косвенной речи. manger → avait mangé.',
    explanationEn: 'Passé composé → plus-que-parfait in indirect speech. manger → avait mangé.',
  },
  {
    topicSlug: 'discours-indirect',
    type: 'translate',
    question: { text: 'Она спросила: «Ты идёшь на вечеринку?»', from: 'ru', to: 'fr' },
    answer: { text: 'Elle a demandé si j\'allais à la fête.' },
    explanation: 'Вопрос да/нет → si. aller в présent → imparfait. tu → je в косвенной речи.',
    explanationEn: 'Yes/no question → si. aller in présent → imparfait. tu → je in indirect speech.',
  },

  // ═══════════════════════════════════════════════════════════
  // interrogation-indirecte
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'interrogation-indirecte',
    type: 'fill_blank',
    question: { text: 'Je ne sais pas ___ elle habite.', blanks: 1 },
    answer: { values: ['où'] },
    explanation: 'Косвенный вопрос с «où». Нет инверсии: où elle habite (не où habite-elle).',
    explanationEn: 'Indirect question with "où". No inversion: où elle habite (not où habite-elle).',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'fill_blank',
    question: { text: 'Dis-moi ___ tu penses de ce film.', blanks: 1 },
    answer: { values: ['ce que'] },
    explanation: '«Qu\'est-ce que tu penses» → ce que. Dis-moi ce que tu penses.',
    explanationEn: '"Qu\'est-ce que tu penses" → ce que. Dis-moi ce que tu penses.',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'fill_blank',
    question: { text: 'Je me demande ___ il est encore au bureau.', blanks: 1 },
    answer: { values: ['si'] },
    explanation: 'Да/нет вопрос в косвенной речи → si. Je me demande si il est au bureau.',
    explanationEn: 'Yes/no question in indirect speech → si. Je me demande s\'il est encore au bureau.',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'multiple_choice',
    question: { text: 'Il veut savoir ___ se passe dans le couloir.', options: ['ce qui', 'ce que', 'si', 'que'] },
    answer: { correct: 'ce qui' },
    explanation: '«Qu\'est-ce qui» (субъект) → ce qui. Il veut savoir ce qui se passe.',
    explanationEn: '"Qu\'est-ce qui" (subject) → ce qui. Il veut savoir ce qui se passe.',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'multiple_choice',
    question: { text: 'Je voudrais savoir ___ vous avez pris cette décision.', options: ['pourquoi', 'si', 'ce que', 'ce qui'] },
    answer: { correct: 'pourquoi' },
    explanation: 'Почему? → pourquoi (сохраняется). Je voudrais savoir pourquoi vous avez pris...',
    explanationEn: 'Why? → pourquoi (kept as is). Je voudrais savoir pourquoi vous avez pris...',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'translate',
    question: { text: 'Я хочу знать, когда ты вернёшься.', from: 'ru', to: 'fr' },
    answer: { text: 'Je veux savoir quand tu reviendras.' },
    explanation: 'Косвенный вопрос с quand. Нет инверсии. futur simple: reviendras.',
    explanationEn: 'Indirect question with quand. No inversion. futur simple: reviendras.',
  },
  {
    topicSlug: 'interrogation-indirecte',
    type: 'translate',
    question: { text: 'Скажи мне, что ты думаешь об этом.', from: 'ru', to: 'fr' },
    answer: { text: 'Dis-moi ce que tu penses de ça.' },
    explanation: 'Qu\'est-ce que → ce que. Нет инверсии. Dis-moi ce que tu penses.',
    explanationEn: 'Qu\'est-ce que → ce que. No inversion. Dis-moi ce que tu penses.',
  },

  // ═══════════════════════════════════════════════════════════
  // expression-cause
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'expression-cause',
    type: 'fill_blank',
    question: { text: 'Il ne peut pas venir ___ il est malade.', blanks: 1 },
    answer: { values: ['parce que', 'car', 'puisque'] },
    explanation: 'parce que, car или puisque — все подходят для выражения причины в этом контексте.',
    explanationEn: 'parce que, car, or puisque all work for expressing cause in this context.',
  },
  {
    topicSlug: 'expression-cause',
    type: 'fill_blank',
    question: { text: '___ tu es déjà là, aide-moi à préparer le dîner.', blanks: 1 },
    answer: { values: ['Puisque', 'Comme'] },
    explanation: 'Puisque или Comme — известная/очевидная причина, логичный вывод. Puisque/Comme tu es là...',
    explanationEn: 'Puisque or Comme — known/obvious reason for a logical conclusion.',
  },
  {
    topicSlug: 'expression-cause',
    type: 'fill_blank',
    question: { text: 'J\'ai réussi ___ à ton aide.', blanks: 1 },
    answer: { values: ['grâce'] },
    explanation: 'Grâce à = благодаря (позитивная причина). J\'ai réussi grâce à ton aide.',
    explanationEn: 'Grâce à = thanks to (positive cause). J\'ai réussi grâce à ton aide.',
  },
  {
    topicSlug: 'expression-cause',
    type: 'multiple_choice',
    question: { text: 'Le match a été annulé ___ la tempête.', options: ['à cause de', 'grâce à', 'parce que', 'puisque'] },
    answer: { correct: 'à cause de' },
    explanation: 'À cause de + nom (причина, обычно негативная). à cause de la tempête.',
    explanationEn: 'À cause de + noun (cause, often negative). à cause de la tempête.',
  },
  {
    topicSlug: 'expression-cause',
    type: 'multiple_choice',
    question: { text: '___ il pleuvait, nous avons décidé de rester chez nous.', options: ['Comme', 'Puisque', 'Car', 'Grâce à'] },
    answer: { correct: 'Comme' },
    explanation: 'Comme в начале предложения — причина как контекст/фон. Comme il pleuvait, nous...',
    explanationEn: 'Comme at the start — cause as background/context. Comme il pleuvait, nous...',
  },
  {
    topicSlug: 'expression-cause',
    type: 'translate',
    question: { text: 'Я не пошёл на работу, потому что был болен.', from: 'ru', to: 'fr' },
    answer: { text: 'Je ne suis pas allé au travail parce que j\'étais malade.' },
    explanation: 'parce que — нейтральное объяснение причины. Стандартный ответ на «pourquoi?».',
    explanationEn: 'parce que — neutral reason, standard answer to "pourquoi?".',
  },
  {
    topicSlug: 'expression-cause',
    type: 'translate',
    question: { text: 'Благодаря хорошей погоде мы провели день на улице.', from: 'ru', to: 'fr' },
    answer: { text: 'Grâce au beau temps, nous avons passé la journée dehors.' },
    explanation: 'Grâce à + nom (позитивная причина). grâce au (= à + le) beau temps.',
    explanationEn: 'Grâce à + noun (positive cause). grâce au (= à + le) beau temps.',
  },

  // ═══════════════════════════════════════════════════════════
  // expression-but-consequence
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'expression-but-consequence',
    type: 'fill_blank',
    question: { text: 'Je travaille ___ gagner ma vie.', blanks: 1 },
    answer: { values: ['pour'] },
    explanation: 'Цель с одним субъектом → pour + инфинитив. Je travaille pour gagner...',
    explanationEn: 'Purpose with same subject → pour + infinitive. Je travaille pour gagner...',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'fill_blank',
    question: { text: 'Il parle lentement ___ que tout le monde comprenne.', blanks: 1 },
    answer: { values: ['pour'] },
    explanation: 'Цель с разными субъектами → pour que + субжонктив. pour que tout le monde comprenne.',
    explanationEn: 'Purpose with different subjects → pour que + subjunctive. pour que tout le monde comprenne.',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'fill_blank',
    question: { text: 'Il a trop mangé, ___ il s\'est senti mal.', blanks: 1 },
    answer: { values: ['donc', 'alors', "si bien que", "c'est pourquoi"] },
    explanation: 'Следствие: donc, alors, si bien que, c\'est pourquoi — все выражают вывод/результат.',
    explanationEn: 'Consequence: donc, alors, si bien que, c\'est pourquoi — all express result/consequence.',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'multiple_choice',
    question: { text: 'Elle est ___ belle ___ tout le monde la regarde.', options: ['tellement / que', 'si bien / que', 'tant / que', 'assez / que'] },
    answer: { correct: 'tellement / que' },
    explanation: 'Степень → следствие: tellement + прилагательное + que. tellement belle que...',
    explanationEn: 'Degree → consequence: tellement + adjective + que. tellement belle que...',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'multiple_choice',
    question: { text: 'Il était en retard, ___ il a raté la réunion.', options: ['c\'est pourquoi', 'bien que', 'même si', 'pour que'] },
    answer: { correct: 'c\'est pourquoi' },
    explanation: 'C\'est pourquoi выражает следствие/вывод. Подчёркивает логическую связь.',
    explanationEn: 'C\'est pourquoi expresses consequence/conclusion. Emphasizes the logical connection.',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'translate',
    question: { text: 'Она позвонила нам, чтобы мы не беспокоились.', from: 'ru', to: 'fr' },
    answer: { text: 'Elle nous a appelés pour que nous ne nous inquiétions pas.' },
    explanation: 'Цель с разными субъектами → pour que + субжонктив. s\'inquiéter → inquiétions.',
    explanationEn: 'Purpose with different subjects → pour que + subjunctive. s\'inquiéter → inquiétions.',
  },
  {
    topicSlug: 'expression-but-consequence',
    type: 'translate',
    question: { text: 'Он так быстро говорит, что я ничего не понимаю.', from: 'ru', to: 'fr' },
    answer: { text: 'Il parle tellement vite que je ne comprends rien.' },
    explanation: 'Степень → следствие: tellement + наречие + que. ne...rien = ничего.',
    explanationEn: 'Degree → consequence: tellement + adverb + que. ne...rien = nothing.',
  },

  // ═══════════════════════════════════════════════════════════
  // expression-concession
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'expression-concession',
    type: 'fill_blank',
    question: { text: '___ qu\'il soit fatigué, il continue à travailler.', blanks: 1 },
    answer: { values: ['Bien'] },
    explanation: 'Bien que + субжонктив = хотя. Bien qu\'il soit fatigué.',
    explanationEn: 'Bien que + subjunctive = although. Bien qu\'il soit fatigué.',
  },
  {
    topicSlug: 'expression-concession',
    type: 'fill_blank',
    question: { text: '___ si tu n\'es pas d\'accord, c\'est la règle.', blanks: 1 },
    answer: { values: ['Même'] },
    explanation: 'Même si + индикатив = даже если. Même si tu n\'es pas d\'accord...',
    explanationEn: 'Même si + indicative = even if. Même si tu n\'es pas d\'accord...',
  },
  {
    topicSlug: 'expression-concession',
    type: 'fill_blank',
    question: { text: 'Il a beau ___ (expliquer), personne ne comprend.', blanks: 1 },
    answer: { values: ['expliquer'] },
    explanation: 'Avoir beau + инфинитив = как бы ни... Инфинитив остаётся без изменений.',
    explanationEn: 'Avoir beau + infinitive = no matter how much... The infinitive stays unchanged.',
  },
  {
    topicSlug: 'expression-concession',
    type: 'multiple_choice',
    question: { text: 'Il est riche, ___ il est très généreux.', options: ['pourtant', 'bien que', 'même si', 'malgré'] },
    answer: { correct: 'pourtant' },
    explanation: 'Pourtant — союз координации между двумя предложениями. Не требует субжонктива.',
    explanationEn: 'Pourtant is a coordinating conjunction between two clauses. No subjunctive needed.',
  },
  {
    topicSlug: 'expression-concession',
    type: 'multiple_choice',
    question: { text: '___ sa fatigue, elle a fini le marathon.', options: ['Malgré', 'Bien que', 'Même si', 'Pourtant'] },
    answer: { correct: 'Malgré' },
    explanation: 'Malgré + имя существительное (без глагола). Malgré sa fatigue (не: bien que sa fatigue).',
    explanationEn: 'Malgré + noun (no verb). Malgré sa fatigue (not: bien que sa fatigue).',
  },
  {
    topicSlug: 'expression-concession',
    type: 'translate',
    question: { text: 'Хотя погода плохая, мы выходим на прогулку.', from: 'ru', to: 'fr' },
    answer: { text: 'Bien que le temps soit mauvais, nous sortons nous promener.' },
    explanation: 'Bien que + субжонктив. être → soit. Bien que le temps soit mauvais.',
    explanationEn: 'Bien que + subjunctive. être → soit. Bien que le temps soit mauvais.',
  },
  {
    topicSlug: 'expression-concession',
    type: 'translate',
    question: { text: 'Он много тренируется, и всё же не побеждает.', from: 'ru', to: 'fr' },
    answer: { text: 'Il s\'entraîne beaucoup, pourtant il ne gagne pas.' },
    explanation: 'Pourtant = и всё же, тем не менее. Две части предложения с противоречием.',
    explanationEn: 'Pourtant = yet, nevertheless. Two clauses in contrast.',
  },

  // ═══════════════════════════════════════════════════════════
  // ne-que-restriction
  // ═══════════════════════════════════════════════════════════
  {
    topicSlug: 'ne-que-restriction',
    type: 'fill_blank',
    question: { text: 'Je n\'ai ___ dix euros dans mon portefeuille.', blanks: 1 },
    answer: { values: ['que'] },
    explanation: 'Ne...que = seulement (только). ne + глагол + que + ограничиваемый элемент.',
    explanationEn: 'Ne...que = seulement (only). ne + verb + que + restricted element.',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'fill_blank',
    question: { text: 'Il ne mange ___ des légumes — jamais de viande.', blanks: 1 },
    answer: { values: ['que'] },
    explanation: 'Ne...que = seulement. После que артикль не меняется (des, не de).',
    explanationEn: 'Ne...que = only. After que, the article does not change (des, not de).',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'fill_blank',
    question: { text: 'Il ___ pas encore répondu à mon message.', blanks: 1 },
    answer: { values: ['n\'a'] },
    explanation: 'Ne...pas encore = ещё не. Il n\'a pas encore répondu.',
    explanationEn: 'Ne...pas encore = not yet. Il n\'a pas encore répondu.',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'multiple_choice',
    question: { text: 'Elle ___ travaille pas encore — elle étudie toujours.', options: ['ne', 'n\'', 'pas', 'ni'] },
    answer: { correct: 'ne' },
    explanation: 'Перед согласной: ne (не n\'). Elle ne travaille pas encore.',
    explanationEn: 'Before a consonant: ne (not n\'). Elle ne travaille pas encore.',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'multiple_choice',
    question: { text: 'Je n\'aime ___ le café et le thé — pas les jus.', options: ['que', 'pas', 'plus', 'jamais'] },
    answer: { correct: 'que' },
    explanation: 'Ne...que = только. Je n\'aime que le café et le thé.',
    explanationEn: 'Ne...que = only. Je n\'aime que le café et le thé.',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'translate',
    question: { text: 'Он по-прежнему не отвечает на мои звонки.', from: 'ru', to: 'fr' },
    answer: { text: 'Il ne répond toujours pas à mes appels.' },
    explanation: 'Ne...toujours pas = по-прежнему не, всё ещё не. toujours между ne и pas.',
    explanationEn: 'Ne...toujours pas = still not. toujours goes between ne and pas.',
  },
  {
    topicSlug: 'ne-que-restriction',
    type: 'translate',
    question: { text: 'Я прочитал только три страницы этой книги.', from: 'ru', to: 'fr' },
    answer: { text: 'Je n\'ai lu que trois pages de ce livre.' },
    explanation: 'Ne...que в passé composé: ne + aux + que + participe. Je n\'ai lu que trois pages.',
    explanationEn: 'Ne...que in passé composé: ne + aux + que + participle. Je n\'ai lu que trois pages.',
  },
];
