// Listening exercises A1 — short dialogs and monologues
// audioUrl will be generated by TTS on demand (empty initially)

export interface ListeningExerciseSeed {
  title: string;
  level: 'A1';
  transcript: string;
  durationSec: number; // approximate
  questions: Array<{
    id: string;
    text: string;
    options: string[];
    correct: string;
  }>;
}

export const listeningExercisesA1: ListeningExerciseSeed[] = [
  {
    title: 'Se présenter',
    level: 'A1',
    transcript: `Bonjour ! Je m'appelle Marie. J'ai vingt-cinq ans. Je suis étudiante en médecine. J'habite à Paris, dans le quatrième arrondissement. J'aime beaucoup la musique et le cinéma. Le week-end, je retrouve mes amis au café. Et toi, comment tu t'appelles ?`,
    durationSec: 18,
    questions: [
      {
        id: 'q1',
        text: 'Comment s\'appelle la personne ?',
        options: ['Sophie', 'Marie', 'Claire', 'Julie'],
        correct: 'Marie',
      },
      {
        id: 'q2',
        text: 'Quel âge a-t-elle ?',
        options: ['vingt ans', 'vingt-deux ans', 'vingt-cinq ans', 'trente ans'],
        correct: 'vingt-cinq ans',
      },
      {
        id: 'q3',
        text: 'Qu\'est-ce qu\'elle étudie ?',
        options: ['le droit', 'la médecine', 'les langues', 'l\'informatique'],
        correct: 'la médecine',
      },
      {
        id: 'q4',
        text: 'Où habite-t-elle ?',
        options: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'],
        correct: 'Paris',
      },
    ],
  },
  {
    title: 'Au café',
    level: 'A1',
    transcript: `Serveur : Bonjour, vous désirez ?
Client : Bonjour ! Je voudrais un café, s'il vous plaît.
Serveur : Un café crème ou un café noir ?
Client : Un café noir, merci. Et aussi un croissant.
Serveur : Très bien. C'est pour emporter ou sur place ?
Client : Sur place, s'il vous plaît.
Serveur : Ça fait trois euros cinquante.
Client : Voici. Merci !
Serveur : Bonne journée !`,
    durationSec: 22,
    questions: [
      {
        id: 'q1',
        text: 'Qu\'est-ce que le client commande ?',
        options: ['un thé et un pain', 'un café et un croissant', 'un jus et un gâteau', 'un café et un sandwich'],
        correct: 'un café et un croissant',
      },
      {
        id: 'q2',
        text: 'Quel type de café veut le client ?',
        options: ['un café crème', 'un café au lait', 'un café noir', 'un café glacé'],
        correct: 'un café noir',
      },
      {
        id: 'q3',
        text: 'Combien coûte la commande ?',
        options: ['deux euros', 'deux euros cinquante', 'trois euros', 'trois euros cinquante'],
        correct: 'trois euros cinquante',
      },
      {
        id: 'q4',
        text: 'Le client mange sur place ou à emporter ?',
        options: ['à emporter', 'sur place', 'en livraison', 'chez lui'],
        correct: 'sur place',
      },
    ],
  },
  {
    title: 'La famille',
    level: 'A1',
    transcript: `Je m'appelle Thomas. J'ai une grande famille. Mon père s'appelle Paul et ma mère s'appelle Isabelle. J'ai deux frères et une sœur. Mon frère aîné a trente ans. Il est marié et il a un enfant. Ma sœur a seize ans. Elle est encore au lycée. Nous habitons tous dans la même ville, à Lyon.`,
    durationSec: 20,
    questions: [
      {
        id: 'q1',
        text: 'Combien de frères a Thomas ?',
        options: ['un', 'deux', 'trois', 'aucun'],
        correct: 'deux',
      },
      {
        id: 'q2',
        text: 'Quel âge a la sœur de Thomas ?',
        options: ['quatorze ans', 'quinze ans', 'seize ans', 'dix-sept ans'],
        correct: 'seize ans',
      },
      {
        id: 'q3',
        text: 'Où habite la famille ?',
        options: ['Paris', 'Marseille', 'Lyon', 'Bordeaux'],
        correct: 'Lyon',
      },
      {
        id: 'q4',
        text: 'Le frère aîné est-il marié ?',
        options: ['oui', 'non', 'on ne sait pas', 'il est divorcé'],
        correct: 'oui',
      },
    ],
  },
  {
    title: 'La météo',
    level: 'A1',
    transcript: `Bonjour et bienvenue sur Radio France. Voici la météo pour aujourd'hui. Il fait beau à Paris, avec un soleil magnifique. La température est de vingt-deux degrés. Dans le nord du pays, il y a des nuages et il pleut un peu. Dans le sud, il fait très chaud : trente degrés à Marseille. Demain, le temps sera similaire. Bonne journée à tous !`,
    durationSec: 22,
    questions: [
      {
        id: 'q1',
        text: 'Quel temps fait-il à Paris ?',
        options: ['il pleut', 'il neige', 'il fait beau', 'il y a du vent'],
        correct: 'il fait beau',
      },
      {
        id: 'q2',
        text: 'Quelle est la température à Paris ?',
        options: ['dix-huit degrés', 'vingt degrés', 'vingt-deux degrés', 'vingt-cinq degrés'],
        correct: 'vingt-deux degrés',
      },
      {
        id: 'q3',
        text: 'Quel temps fait-il dans le nord ?',
        options: ['il fait chaud', 'il neige', 'il y a des nuages', 'il fait beau'],
        correct: 'il y a des nuages',
      },
      {
        id: 'q4',
        text: 'Quelle est la température à Marseille ?',
        options: ['vingt degrés', 'vingt-cinq degrés', 'trente degrés', 'trente-cinq degrés'],
        correct: 'trente degrés',
      },
    ],
  },
  {
    title: 'Les directions',
    level: 'A1',
    transcript: `Touriste : Excusez-moi, je cherche la gare, s'il vous plaît.
Passant : La gare ? Ce n'est pas loin. Vous allez tout droit, puis vous tournez à gauche au feu rouge. Ensuite, vous continuez tout droit pendant environ cinq minutes. La gare est sur votre droite, en face du parc.
Touriste : Merci beaucoup ! C'est loin à pied ?
Passant : Non, c'est à dix minutes à pied.
Touriste : Parfait, merci !`,
    durationSec: 20,
    questions: [
      {
        id: 'q1',
        text: 'Qu\'est-ce que le touriste cherche ?',
        options: ['l\'hôtel', 'la gare', 'le musée', 'la pharmacie'],
        correct: 'la gare',
      },
      {
        id: 'q2',
        text: 'Où faut-il tourner ?',
        options: ['à droite au stop', 'à gauche au feu rouge', 'à droite au feu', 'à gauche au carrefour'],
        correct: 'à gauche au feu rouge',
      },
      {
        id: 'q3',
        text: 'Où est la gare par rapport au parc ?',
        options: ['derrière le parc', 'à côté du parc', 'en face du parc', 'loin du parc'],
        correct: 'en face du parc',
      },
      {
        id: 'q4',
        text: 'Combien de temps faut-il marcher ?',
        options: ['cinq minutes', 'dix minutes', 'quinze minutes', 'vingt minutes'],
        correct: 'dix minutes',
      },
    ],
  },
];
