// Placement test questions: adaptive A1→B2
// Structure: each question has a level, type, and correct answer

export interface PlacementQuestion {
  id: string;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  type: 'vocabulary' | 'grammar' | 'comprehension';
  question: string;
  options: string[];
  correct: string;
  explanation?: string;
}

export const placementQuestions: PlacementQuestion[] = [
  // === A1 Vocabulary ===
  {
    id: 'a1-v1',
    level: 'A1',
    type: 'vocabulary',
    question: 'Comment dit-on "bonjour" en russe ?',
    options: ['Привет', 'До свидания', 'Спасибо', 'Пожалуйста'],
    correct: 'Привет',
  },
  {
    id: 'a1-v2',
    level: 'A1',
    type: 'vocabulary',
    question: 'Que signifie "le chat" ?',
    options: ['собака', 'кот', 'птица', 'рыба'],
    correct: 'кот',
  },
  {
    id: 'a1-v3',
    level: 'A1',
    type: 'vocabulary',
    question: 'Que signifie "manger" ?',
    options: ['спать', 'пить', 'есть', 'идти'],
    correct: 'есть',
  },
  {
    id: 'a1-v4',
    level: 'A1',
    type: 'vocabulary',
    question: 'Comment dit-on "la maison" ?',
    options: ['школа', 'дом', 'машина', 'улица'],
    correct: 'дом',
  },

  // === A1 Grammar ===
  {
    id: 'a1-g1',
    level: 'A1',
    type: 'grammar',
    question: 'Choisissez la bonne forme : "Je ___ français."',
    options: ['parle', 'parles', 'parlons', 'parlent'],
    correct: 'parle',
    explanation: 'Verbe parler: je parle',
  },
  {
    id: 'a1-g2',
    level: 'A1',
    type: 'grammar',
    question: '"___ chat est noir." Quel article ?',
    options: ['Un', 'Le', 'La', 'Les'],
    correct: 'Le',
    explanation: 'chat — masculin singulier → le',
  },
  {
    id: 'a1-g3',
    level: 'A1',
    type: 'grammar',
    question: 'Quelle est la forme correcte de "être" pour "ils" ?',
    options: ['est', 'sont', 'sommes', 'êtes'],
    correct: 'sont',
  },
  {
    id: 'a1-g4',
    level: 'A1',
    type: 'grammar',
    question: '"J\'___ un frère." Complétez avec avoir.',
    options: ['ai', 'as', 'a', 'avons'],
    correct: 'ai',
  },
  {
    id: 'a1-g5',
    level: 'A1',
    type: 'grammar',
    question: 'Comment dit-on "Je n\'ai pas de voiture" ? (отрицание)',
    options: [
      'Je n\'ai pas une voiture.',
      'Je n\'ai pas de voiture.',
      'Je ai pas voiture.',
      'Je pas ai voiture.',
    ],
    correct: 'Je n\'ai pas de voiture.',
    explanation: 'Après la négation: pas de (pas un/une)',
  },

  // === A2 Vocabulary ===
  {
    id: 'a2-v1',
    level: 'A2',
    type: 'vocabulary',
    question: 'Que signifie "se souvenir" ?',
    options: ['засыпать', 'вспоминать', 'беспокоиться', 'просыпаться'],
    correct: 'вспоминать',
  },
  {
    id: 'a2-v2',
    level: 'A2',
    type: 'vocabulary',
    question: 'Que signifie "le boulanger" ?',
    options: ['мясник', 'пекарь', 'сапожник', 'портной'],
    correct: 'пекарь',
  },
  {
    id: 'a2-v3',
    level: 'A2',
    type: 'vocabulary',
    question: 'Comment dit-on "скучать" (ennuyer) ?',
    options: ['s\'amuser', 's\'ennuyer', 'se reposer', 'se dépêcher'],
    correct: 's\'ennuyer',
  },

  // === A2 Grammar ===
  {
    id: 'a2-g1',
    level: 'A2',
    type: 'grammar',
    question: 'Passé composé de "manger" (je) :',
    options: ['je mangeais', 'j\'ai mangé', 'je mange', 'j\'avais mangé'],
    correct: 'j\'ai mangé',
    explanation: 'Passé composé: avoir + participe passé (mangé)',
  },
  {
    id: 'a2-g2',
    level: 'A2',
    type: 'grammar',
    question: '"Elle ___ (aller) au marché hier."',
    options: ['est allé', 'est allée', 'a allé', 'a allée'],
    correct: 'est allée',
    explanation: 'aller → être au passé composé; elle → participe s\'accorde: allée',
  },
  {
    id: 'a2-g3',
    level: 'A2',
    type: 'grammar',
    question: 'Futur proche : "Nous ___ partir demain."',
    options: ['allons', 'irons', 'sommes', 'avons'],
    correct: 'allons',
    explanation: 'Futur proche = aller (présent) + infinitif: nous allons partir',
  },
  {
    id: 'a2-g4',
    level: 'A2',
    type: 'grammar',
    question: '"___ livre est intéressant." (ce/cet/cette/ces)',
    options: ['Ce', 'Cet', 'Cette', 'Ces'],
    correct: 'Ce',
    explanation: 'livre — masculin, commence par consonne → ce',
  },
  {
    id: 'a2-g5',
    level: 'A2',
    type: 'grammar',
    question: '"Il ___ depuis deux heures." (pleuvoir)',
    options: ['pleut', 'pleure', 'a plu', 'pleuvait'],
    correct: 'pleut',
    explanation: 'pleuvoit → il pleut (présent)',
  },

  // === B1 Vocabulary ===
  {
    id: 'b1-v1',
    level: 'B1',
    type: 'vocabulary',
    question: 'Que signifie "pourtant" ?',
    options: ['поэтому', 'тем не менее', 'следовательно', 'как только'],
    correct: 'тем не менее',
  },
  {
    id: 'b1-v2',
    level: 'B1',
    type: 'vocabulary',
    question: 'Que signifie "se méfier de" ?',
    options: ['доверять', 'не доверять, остерегаться', 'заботиться', 'привыкать'],
    correct: 'не доверять, остерегаться',
  },
  {
    id: 'b1-v3',
    level: 'B1',
    type: 'vocabulary',
    question: '"Il a réussi à ___ son examen." Quel verbe ?',
    options: ['passer', 'réussir', 'rater', 'préparer'],
    correct: 'passer',
    explanation: 'réussir à + infinitif = suмеет сдать; passer un examen = сдавать экзамен',
  },

  // === B1 Grammar ===
  {
    id: 'b1-g1',
    level: 'B1',
    type: 'grammar',
    question: 'Subjonctif présent de "être" (que je) :',
    options: ['que je sois', 'que je suis', 'que je serai', 'que j\'étais'],
    correct: 'que je sois',
    explanation: 'Subjonctif: que je sois',
  },
  {
    id: 'b1-g2',
    level: 'B1',
    type: 'grammar',
    question: '"Il faut que tu ___ (venir) à l\'heure."',
    options: ['viens', 'viennes', 'venais', 'viendras'],
    correct: 'viennes',
    explanation: 'Il faut que + subjonctif: que tu viennes',
  },
  {
    id: 'b1-g3',
    level: 'B1',
    type: 'grammar',
    question: 'Imparfait de "faire" (nous) :',
    options: ['nous faisions', 'nous fîmes', 'nous avons fait', 'nous ferons'],
    correct: 'nous faisions',
    explanation: 'Imparfait: nous faisions',
  },
  {
    id: 'b1-g4',
    level: 'B1',
    type: 'grammar',
    question: '"Je lui ___ dit la vérité." (pronom)',
    options: ['lui ai', 'l\'ai', 'leur ai', 'y ai'],
    correct: 'lui ai',
    explanation: 'lui = pronom COI (à lui/elle)',
  },
  {
    id: 'b1-g5',
    level: 'B1',
    type: 'grammar',
    question: 'Accord du participe passé : "Les lettres que j\'___ écri___."',
    options: ['ai écrit', 'ai écrites', 'ai écrits', 'suis écrit'],
    correct: 'ai écrites',
    explanation: 'COD "les lettres" (féminin pluriel) précède le verbe → participe s\'accorde: écrites',
  },

  // === B2 Vocabulary ===
  {
    id: 'b2-v1',
    level: 'B2',
    type: 'vocabulary',
    question: 'Que signifie "à l\'insu de" ?',
    options: ['благодаря', 'несмотря на', 'без ведома', 'вместо'],
    correct: 'без ведома',
  },
  {
    id: 'b2-v2',
    level: 'B2',
    type: 'vocabulary',
    question: 'Quel mot est un synonyme de "véhément" ?',
    options: ['doux', 'passionné', 'calme', 'timide'],
    correct: 'passionné',
  },
  {
    id: 'b2-v3',
    level: 'B2',
    type: 'vocabulary',
    question: '"Cette loi ___ en vigueur le mois prochain." (entrer)',
    options: ['entre', 'entrera', 'est entrée', 'entrerait'],
    correct: 'entrera',
    explanation: 'Futur simple: entrera en vigueur',
  },

  // === B2 Grammar ===
  {
    id: 'b2-g1',
    level: 'B2',
    type: 'grammar',
    question: 'Conditionnel passé : "Si j\'avais su, je n\'___ pas venu."',
    options: ['aurais', 'serais', 'avais', 'suis'],
    correct: 'serais',
    explanation: 'Conditionnel passé avec être: je ne serais pas venu',
  },
  {
    id: 'b2-g2',
    level: 'B2',
    type: 'grammar',
    question: 'Voix passive : "Le rapport ___ rédigé par le directeur."',
    options: ['a été', 'est', 'était', 'aura été'],
    correct: 'a été',
    explanation: 'Passif passé composé: a été + participe passé',
  },
  {
    id: 'b2-g3',
    level: 'B2',
    type: 'grammar',
    question: '"Bien que ce soit difficile, il ___." (persévérer — subjonctif)',
    options: ['persévère', 'persévérera', 'persévèrerait', 'persévérât'],
    correct: 'persévère',
    explanation: 'Bien que + subjonctif présent: il persévère',
  },

  // === C1 Vocabulary ===
  {
    id: 'c1-v1',
    level: 'C1',
    type: 'vocabulary',
    question: 'Que signifie "néanmoins" ?',
    options: ['тем не менее', 'кроме того', 'вследствие этого', 'без сомнения'],
    correct: 'тем не менее',
  },
  {
    id: 'c1-v2',
    level: 'C1',
    type: 'vocabulary',
    question: 'Choisissez le synonyme de "scrupuleux" (внимательный, добросовестный) :',
    options: ['négligent', 'méticuleux', 'imprévoyant', 'oisif'],
    correct: 'méticuleux',
  },
  {
    id: 'c1-v3',
    level: 'C1',
    type: 'vocabulary',
    question: 'Que signifie "tirer la sonnette d\'alarme" ?',
    options: ['опаздывать', 'бить тревогу', 'звонить в дверь', 'будить кого-то'],
    correct: 'бить тревогу',
    explanation: 'Идиома: привлекать внимание к проблеме',
  },

  // === C1 Grammar ===
  {
    id: 'c1-g1',
    level: 'C1',
    type: 'grammar',
    question: 'Subjonctif passé : "Je regrette qu\'il ___ (partir) sans nous prévenir."',
    options: ['parte', 'soit parti', 'serait parti', 'est parti'],
    correct: 'soit parti',
    explanation: 'Регретер + антериорное действие → subjonctif passé: soit + participe (parti)',
  },
  {
    id: 'c1-g2',
    level: 'C1',
    type: 'grammar',
    question: 'Двойное местоимение: "Tu lui as donné le livre ? — Oui, je ___ ai donné."',
    options: ['lui le', 'le lui', 'lui en', 'la lui'],
    correct: 'le lui',
    explanation: 'Порядок: le/la/les перед lui/leur. Я ему его дал — je le lui ai donné',
  },
  {
    id: 'c1-g3',
    level: 'C1',
    type: 'grammar',
    question: 'Эмфаза: "C\'est de cette question ___ je veux parler."',
    options: ['que', 'qui', 'dont', 'où'],
    correct: 'dont',
    explanation: 'parler de qch → dont (с предлогом de после эмфатического c\'est)',
  },
  {
    id: 'c1-g4',
    level: 'C1',
    type: 'grammar',
    question: 'Сложная инверсия: "Peut-être ___ (avoir-il) raison."',
    options: ['avait il', 'a-t-il', 'qu\'il a', 'qu\'a-t-il'],
    correct: 'a-t-il',
    explanation: 'После peut-être в формальном регистре: инверсия с -t- между гласными',
  },

  // === C2 Vocabulary ===
  {
    id: 'c2-v1',
    level: 'C2',
    type: 'vocabulary',
    question: 'Que signifie "nonobstant" (registre soutenu) ?',
    options: ['благодаря', 'вопреки, несмотря на', 'до тех пор пока', 'между прочим'],
    correct: 'вопреки, несмотря на',
  },
  {
    id: 'c2-v2',
    level: 'C2',
    type: 'vocabulary',
    question: 'Choisissez le synonyme littéraire de "discord" (раздор) :',
    options: ['l\'harmonie', 'l\'inimitié', 'la concorde', 'l\'entente'],
    correct: 'l\'inimitié',
    explanation: 'inimitié — литературный синоним discord/враждебности',
  },
  {
    id: 'c2-v3',
    level: 'C2',
    type: 'vocabulary',
    question: 'Quelle figure de style: "un silence éloquent" ?',
    options: ['hyperbole', 'oxymore', 'métaphore', 'litote'],
    correct: 'oxymore',
    explanation: 'Сочетание противоположных понятий → оксюморон',
  },

  // === C2 Grammar ===
  {
    id: 'c2-g1',
    level: 'C2',
    type: 'grammar',
    question: 'Subjonctif imparfait : "Il fallait qu\'il ___ (savoir) la vérité." (registre littéraire)',
    options: ['savait', 'sache', 'sût', 'saurait'],
    correct: 'sût',
    explanation: 'В литературном регистре главное в passé → subj. imparfait: qu\'il sût',
  },
  {
    id: 'c2-g2',
    level: 'C2',
    type: 'grammar',
    question: 'Passé simple 3 л. мн.ч. de "venir" :',
    options: ['ils venaient', 'ils vinrent', 'ils sont venus', 'ils viendraient'],
    correct: 'ils vinrent',
    explanation: 'Passé simple — литературное время; venir → ils vinrent',
  },
  {
    id: 'c2-g3',
    level: 'C2',
    type: 'grammar',
    question: 'Архаическая форма: "___ il pleuvoir, nous sortirons quand même."',
    options: ['Bien que', 'Fût-il pleuvoir', 'Dût-il pleuvoir', 'Si']
    ,
    correct: 'Dût-il pleuvoir',
    explanation: 'Концессивная инверсия subj. imparfait/passé II формы: «Даже если будет лить» — Dût-il pleuvoir',
  },
  {
    id: 'c2-g4',
    level: 'C2',
    type: 'grammar',
    question: 'Ne explétif : "J\'ai peur qu\'il ___ tard."',
    options: ['est', 'soit', 'ne soit', 'sera'],
    correct: 'ne soit',
    explanation: 'После craindre/avoir peur que → ne explétif перед subjonctif (не несёт отрицание)',
  },
];
