export const wordsB2Extra4 = [
  // Finance et économie approfondie
  { french: 'l\'actionnaire', translation: 'акционер', translationEn: 'shareholder', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les actionnaires ont voté pour la fusion.', exampleRu: 'Акционеры проголосовали за слияние.', exampleEn: 'The shareholders voted for the merger.' },
  { french: 'le dividende', translation: 'дивиденд', translationEn: 'dividend', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La société verse un dividende annuel.', exampleRu: 'Компания выплачивает ежегодный дивиденд.', exampleEn: 'The company pays an annual dividend.' },
  { french: 'l\'obligation', translation: 'облигация; обязательство', translationEn: 'bond; obligation', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Il a investi dans des obligations d\'État.', exampleRu: 'Он вложил деньги в государственные облигации.', exampleEn: 'He invested in government bonds.' },
  { french: 'la bourse', translation: 'биржа; фондовый рынок', translationEn: 'stock exchange', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les cours de bourse ont chuté ce matin.', exampleRu: 'Котировки акций упали этим утром.', exampleEn: 'Stock prices fell this morning.' },
  { french: 'le portefeuille', translation: 'портфель (инвестиций)', translationEn: 'portfolio; wallet', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Il diversifie son portefeuille d\'investissements.', exampleRu: 'Он диверсифицирует свой инвестиционный портфель.', exampleEn: 'He diversifies his investment portfolio.' },
  { french: 'le taux d\'intérêt', translation: 'процентная ставка', translationEn: 'interest rate', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La banque centrale a relevé les taux d\'intérêt.', exampleRu: 'Центральный банк повысил процентные ставки.', exampleEn: 'The central bank raised interest rates.' },
  { french: 'l\'inflation', translation: 'инфляция', translationEn: 'inflation', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'inflation a atteint 5% cette année.', exampleRu: 'Инфляция достигла 5% в этом году.', exampleEn: 'Inflation reached 5% this year.' },
  { french: 'la récession', translation: 'рецессия', translationEn: 'recession', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Le pays est entré en récession au troisième trimestre.', exampleRu: 'Страна вошла в рецессию в третьем квартале.', exampleEn: 'The country entered recession in the third quarter.' },
  { french: 'le déficit', translation: 'дефицит', translationEn: 'deficit', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le déficit budgétaire a doublé en un an.', exampleRu: 'Бюджетный дефицит удвоился за год.', exampleEn: 'The budget deficit doubled in a year.' },
  { french: 'l\'excédent', translation: 'профицит; излишек', translationEn: 'surplus; excess', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La balance commerciale affiche un excédent.', exampleRu: 'Торговый баланс показывает профицит.', exampleEn: 'The trade balance shows a surplus.' },
  { french: 'la liquidité', translation: 'ликвидность', translationEn: 'liquidity', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La banque manque de liquidités.', exampleRu: 'Банку не хватает ликвидности.', exampleEn: 'The bank lacks liquidity.' },
  { french: 'la solvabilité', translation: 'платёжеспособность', translationEn: 'solvency', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La solvabilité de l\'entreprise est en question.', exampleRu: 'Платёжеспособность компании под вопросом.', exampleEn: 'The solvency of the company is in question.' },
  { french: 'la faillite', translation: 'банкротство', translationEn: 'bankruptcy', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'entreprise a déposé le bilan pour faillite.', exampleRu: 'Компания подала заявление о банкротстве.', exampleEn: 'The company filed for bankruptcy.' },
  { french: 'fusionner', translation: 'объединяться; сливаться', translationEn: 'to merge', category: 'finance', partOfSpeech: 'verb', exampleFr: 'Les deux banques ont décidé de fusionner.', exampleRu: 'Два банка решили объединиться.', exampleEn: 'The two banks decided to merge.' },
  { french: 'acquérir', translation: 'приобретать; поглощать', translationEn: 'to acquire', category: 'finance', partOfSpeech: 'verb', exampleFr: 'La multinationale a acquis un concurrent.', exampleRu: 'Транснациональная компания поглотила конкурента.', exampleEn: 'The multinational acquired a competitor.' },

  // Entrepreneuriat
  { french: 'la start-up', translation: 'стартап', translationEn: 'start-up', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Sa start-up a levé deux millions d\'euros.', exampleRu: 'Его стартап привлёк два миллиона евро.', exampleEn: 'His start-up raised two million euros.' },
  { french: 'le capital-risque', translation: 'венчурный капитал', translationEn: 'venture capital', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Elle a obtenu du financement en capital-risque.', exampleRu: 'Она получила финансирование от венчурного капитала.', exampleEn: 'She secured venture capital funding.' },
  { french: 'l\'incubateur', translation: 'инкубатор (бизнес)', translationEn: 'incubator', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'incubateur accompagne les jeunes entrepreneurs.', exampleRu: 'Инкубатор поддерживает молодых предпринимателей.', exampleEn: 'The incubator supports young entrepreneurs.' },
  { french: 'le pivot', translation: 'разворот; пивот', translationEn: 'pivot', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La start-up a effectué un pivot stratégique.', exampleRu: 'Стартап совершил стратегический разворот.', exampleEn: 'The start-up made a strategic pivot.' },
  { french: 'la levée de fonds', translation: 'привлечение инвестиций', translationEn: 'fundraising', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La levée de fonds s\'est conclue avec succès.', exampleRu: 'Раунд привлечения инвестиций завершился успешно.', exampleEn: 'The fundraising round concluded successfully.' },
  { french: 'la valorisation', translation: 'оценка (компании)', translationEn: 'valuation', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La valorisation de la licorne dépasse un milliard.', exampleRu: 'Оценка единорога превышает миллиард.', exampleEn: 'The unicorn\'s valuation exceeds a billion.' },
  { french: 'l\'écosystème', translation: 'экосистема', translationEn: 'ecosystem', category: 'entrepreneurship', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Paris a un écosystème start-up dynamique.', exampleRu: 'В Париже динамичная стартап-экосистема.', exampleEn: 'Paris has a dynamic start-up ecosystem.' },
  { french: 'scalable', translation: 'масштабируемый', translationEn: 'scalable', category: 'entrepreneurship', partOfSpeech: 'adjective', exampleFr: 'Leur modèle économique est facilement scalable.', exampleRu: 'Их бизнес-модель легко масштабируется.', exampleEn: 'Their business model is easily scalable.' },
  { french: 'disruptif', translation: 'разрушительный (об инновациях)', translationEn: 'disruptive', category: 'entrepreneurship', partOfSpeech: 'adjective', exampleFr: 'C\'est une technologie vraiment disruptive.', exampleRu: 'Это действительно прорывная технология.', exampleEn: 'It is a truly disruptive technology.' },

  // Commerce international
  { french: 'le protectionnisme', translation: 'протекционизм', translationEn: 'protectionism', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le protectionnisme nuit aux échanges mondiaux.', exampleRu: 'Протекционизм вредит мировой торговле.', exampleEn: 'Protectionism harms global trade.' },
  { french: 'le libre-échange', translation: 'свободная торговля', translationEn: 'free trade', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'accord de libre-échange a été signé.', exampleRu: 'Соглашение о свободной торговле было подписано.', exampleEn: 'The free trade agreement was signed.' },
  { french: 'la mondialisation', translation: 'глобализация', translationEn: 'globalization', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La mondialisation a transformé l\'économie.', exampleRu: 'Глобализация изменила экономику.', exampleEn: 'Globalization has transformed the economy.' },
  { french: 'la délocalisation', translation: 'аутсорсинг; перенос производства', translationEn: 'offshoring; outsourcing', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La délocalisation a détruit des emplois locaux.', exampleRu: 'Перенос производства уничтожил местные рабочие места.', exampleEn: 'Offshoring destroyed local jobs.' },
  { french: 'la relocalisation', translation: 'возврат производства', translationEn: 'reshoring; relocalization', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La relocalisation industrielle est une priorité.', exampleRu: 'Возврат производства является приоритетом.', exampleEn: 'Industrial reshoring is a priority.' },
  { french: 'le dumping', translation: 'демпинг', translationEn: 'dumping', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Ce pays pratique le dumping social.', exampleRu: 'Эта страна практикует социальный демпинг.', exampleEn: 'This country practices social dumping.' },

  // Macroéconomie
  { french: 'le PIB', translation: 'ВВП (валовой внутренний продукт)', translationEn: 'GDP', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le PIB a augmenté de 2% l\'an dernier.', exampleRu: 'ВВП вырос на 2% в прошлом году.', exampleEn: 'GDP grew by 2% last year.' },
  { french: 'la croissance économique', translation: 'экономический рост', translationEn: 'economic growth', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La croissance économique ralentit depuis un an.', exampleRu: 'Экономический рост замедляется уже год.', exampleEn: 'Economic growth has been slowing for a year.' },
  { french: 'le chômage structurel', translation: 'структурная безработица', translationEn: 'structural unemployment', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le chômage structurel persiste malgré la reprise.', exampleRu: 'Структурная безработица сохраняется, несмотря на восстановление.', exampleEn: 'Structural unemployment persists despite recovery.' },
  { french: 'la politique monétaire', translation: 'денежно-кредитная политика', translationEn: 'monetary policy', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La BCE a durci sa politique monétaire.', exampleRu: 'ЕЦБ ужесточил денежно-кредитную политику.', exampleEn: 'The ECB tightened its monetary policy.' },
  { french: 'la politique budgétaire', translation: 'бюджетная политика', translationEn: 'fiscal policy', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Une politique budgétaire expansionniste stimule l\'économie.', exampleRu: 'Экспансионистская бюджетная политика стимулирует экономику.', exampleEn: 'An expansionary fiscal policy stimulates the economy.' },
  { french: 'l\'austérité', translation: 'жёсткая экономия; аскетизм', translationEn: 'austerity', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les mesures d\'austérité ont provoqué des manifestations.', exampleRu: 'Меры жёсткой экономии вызвали протесты.', exampleEn: 'Austerity measures provoked protests.' },
  { french: 'la stagflation', translation: 'стагфляция', translationEn: 'stagflation', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La stagflation combine chômage élevé et inflation.', exampleRu: 'Стагфляция сочетает высокую безработицу и инфляцию.', exampleEn: 'Stagflation combines high unemployment and inflation.' },

  // Verbes économiques
  { french: 'fluctuer', translation: 'колебаться', translationEn: 'to fluctuate', category: 'economics', partOfSpeech: 'verb', exampleFr: 'Le prix du pétrole fluctue beaucoup.', exampleRu: 'Цена нефти сильно колеблется.', exampleEn: 'The price of oil fluctuates a lot.' },
  { french: 'spéculer', translation: 'спекулировать', translationEn: 'to speculate', category: 'finance', partOfSpeech: 'verb', exampleFr: 'Il spécule sur les marchés financiers.', exampleRu: 'Он спекулирует на финансовых рынках.', exampleEn: 'He speculates on financial markets.' },
  { french: 'subventionner', translation: 'субсидировать', translationEn: 'to subsidize', category: 'economics', partOfSpeech: 'verb', exampleFr: 'L\'État subventionne les énergies renouvelables.', exampleRu: 'Государство субсидирует возобновляемую энергию.', exampleEn: 'The state subsidizes renewable energies.' },
  { french: 'privatiser', translation: 'приватизировать', translationEn: 'to privatize', category: 'economics', partOfSpeech: 'verb', exampleFr: 'Le gouvernement a privatisé l\'entreprise publique.', exampleRu: 'Правительство приватизировало государственную компанию.', exampleEn: 'The government privatized the state company.' },
  { french: 'nationaliser', translation: 'национализировать', translationEn: 'to nationalize', category: 'economics', partOfSpeech: 'verb', exampleFr: 'On a nationalisé les banques en crise.', exampleRu: 'Банки в кризисе были национализированы.', exampleEn: 'Banks in crisis were nationalized.' },

  // Adjectifs économiques
  { french: 'rentable', translation: 'рентабельный; прибыльный', translationEn: 'profitable; cost-effective', category: 'finance', partOfSpeech: 'adjective', exampleFr: 'Ce projet n\'est pas encore rentable.', exampleRu: 'Этот проект пока не рентабелен.', exampleEn: 'This project is not yet profitable.' },
  { french: 'viable', translation: 'жизнеспособный', translationEn: 'viable', category: 'economics', partOfSpeech: 'adjective', exampleFr: 'Le modèle économique doit être viable à long terme.', exampleRu: 'Бизнес-модель должна быть жизнеспособной в долгосрочной перспективе.', exampleEn: 'The business model must be viable long-term.' },
  { french: 'concurrentiel', translation: 'конкурентный', translationEn: 'competitive', category: 'economics', partOfSpeech: 'adjective', exampleFr: 'Leurs prix sont très concurrentiels.', exampleRu: 'Их цены очень конкурентоспособны.', exampleEn: 'Their prices are very competitive.' },
  { french: 'lucratif', translation: 'выгодный; доходный', translationEn: 'lucrative', category: 'finance', partOfSpeech: 'adjective', exampleFr: 'C\'est un secteur très lucratif.', exampleRu: 'Это очень доходный сектор.', exampleEn: 'It is a very lucrative sector.' },

  // Travail et entreprise avancé
  { french: 'le télétravail', translation: 'удалённая работа', translationEn: 'remote work; teleworking', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le télétravail est devenu courant après la pandémie.', exampleRu: 'Удалённая работа стала обычной после пандемии.', exampleEn: 'Remote work became common after the pandemic.' },
  { french: 'l\'intérim', translation: 'временная работа', translationEn: 'temporary work', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Elle travaille en intérim dans plusieurs entreprises.', exampleRu: 'Она работает временно в нескольких компаниях.', exampleEn: 'She works temporarily at several companies.' },
  { french: 'la sous-traitance', translation: 'субподряд; аутсорсинг', translationEn: 'subcontracting; outsourcing', category: 'work', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Ils ont recours à la sous-traitance pour réduire les coûts.', exampleRu: 'Они прибегают к субподряду для снижения затрат.', exampleEn: 'They use subcontracting to reduce costs.' },
  { french: 'le bilan social', translation: 'социальный отчёт', translationEn: 'social report', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le bilan social reflète les conditions de travail.', exampleRu: 'Социальный отчёт отражает условия труда.', exampleEn: 'The social report reflects working conditions.' },
  { french: 'la convention collective', translation: 'коллективный договор', translationEn: 'collective agreement', category: 'work', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La convention collective protège les droits des salariés.', exampleRu: 'Коллективный договор защищает права работников.', exampleEn: 'The collective agreement protects employee rights.' },
  { french: 'la productivité', translation: 'производительность', translationEn: 'productivity', category: 'work', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La productivité des équipes a augmenté.', exampleRu: 'Производительность команд возросла.', exampleEn: 'Team productivity has increased.' },
  { french: 'la compétitivité', translation: 'конкурентоспособность', translationEn: 'competitiveness', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La compétitivité nationale dépend de l\'innovation.', exampleRu: 'Конкурентоспособность страны зависит от инноваций.', exampleEn: 'National competitiveness depends on innovation.' },
  { french: 'le compte rendu', translation: 'отчёт; доклад', translationEn: 'report; minutes', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Il a rédigé un compte rendu de la réunion.', exampleRu: 'Он составил протокол собрания.', exampleEn: 'He wrote the minutes of the meeting.' },
  { french: 'le cahier des charges', translation: 'техническое задание', translationEn: 'specifications; brief', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le cahier des charges précise les exigences du projet.', exampleRu: 'Техническое задание определяет требования к проекту.', exampleEn: 'The specifications define the project requirements.' },
  { french: 'l\'appel d\'offres', translation: 'тендер; конкурс предложений', translationEn: 'call for tenders; bid', category: 'work', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La mairie a lancé un appel d\'offres.', exampleRu: 'Мэрия объявила тендер.', exampleEn: 'The city hall launched a call for tenders.' },

  // Verbes professionnels avancés
  { french: 'déléguer', translation: 'делегировать', translationEn: 'to delegate', category: 'work', partOfSpeech: 'verb', exampleFr: 'Un bon manager sait déléguer les tâches.', exampleRu: 'Хороший менеджер умеет делегировать задачи.', exampleEn: 'A good manager knows how to delegate tasks.' },
  { french: 'négocier', translation: 'вести переговоры; торговаться', translationEn: 'to negotiate', category: 'work', partOfSpeech: 'verb', exampleFr: 'Ils ont négocié un meilleur contrat.', exampleRu: 'Они договорились о лучшем контракте.', exampleEn: 'They negotiated a better contract.' },
  { french: 'externaliser', translation: 'отдавать на аутсорсинг', translationEn: 'to outsource', category: 'work', partOfSpeech: 'verb', exampleFr: 'Ils ont externalisé leur service informatique.', exampleRu: 'Они отдали свой IT-отдел на аутсорсинг.', exampleEn: 'They outsourced their IT department.' },
  { french: 'restructurer', translation: 'реструктурировать', translationEn: 'to restructure', category: 'work', partOfSpeech: 'verb', exampleFr: 'L\'entreprise a dû se restructurer après la crise.', exampleRu: 'Компании пришлось реструктурироваться после кризиса.', exampleEn: 'The company had to restructure after the crisis.' },

  // Fiscalité
  { french: 'l\'imposition', translation: 'налогообложение', translationEn: 'taxation', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Le régime d\'imposition varie selon les revenus.', exampleRu: 'Режим налогообложения варьируется в зависимости от дохода.', exampleEn: 'The tax regime varies according to income.' },
  { french: 'l\'évasion fiscale', translation: 'уклонение от уплаты налогов', translationEn: 'tax evasion', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'évasion fiscale coûte des milliards à l\'État.', exampleRu: 'Уклонение от уплаты налогов обходится государству в миллиарды.', exampleEn: 'Tax evasion costs the state billions.' },
  { french: 'l\'optimisation fiscale', translation: 'налоговая оптимизация', translationEn: 'tax optimization', category: 'finance', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les multinationales pratiquent l\'optimisation fiscale.', exampleRu: 'Транснациональные компании занимаются налоговой оптимизацией.', exampleEn: 'Multinationals practice tax optimization.' },
  { french: 'le paradis fiscal', translation: 'налоговый рай', translationEn: 'tax haven', category: 'finance', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Certaines sociétés s\'installent dans des paradis fiscaux.', exampleRu: 'Некоторые компании регистрируются в налоговых убежищах.', exampleEn: 'Some companies set up in tax havens.' },

  // Consommation et marché
  { french: 'le pouvoir d\'achat', translation: 'покупательная способность', translationEn: 'purchasing power', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'inflation a réduit le pouvoir d\'achat des ménages.', exampleRu: 'Инфляция снизила покупательную способность домохозяйств.', exampleEn: 'Inflation has reduced household purchasing power.' },
  { french: 'la demande', translation: 'спрос', translationEn: 'demand', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La demande en logements est forte dans cette ville.', exampleRu: 'Спрос на жильё в этом городе высок.', exampleEn: 'Demand for housing is high in this city.' },
  { french: 'l\'offre', translation: 'предложение (рыночное)', translationEn: 'supply', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'offre est insuffisante face à la demande.', exampleRu: 'Предложение недостаточно по сравнению со спросом.', exampleEn: 'Supply is insufficient compared to demand.' },
  { french: 'la pénurie', translation: 'дефицит; нехватка', translationEn: 'shortage; scarcity', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Une pénurie de semi-conducteurs a ralenti l\'industrie.', exampleRu: 'Дефицит полупроводников замедлил промышленность.', exampleEn: 'A shortage of semiconductors slowed the industry.' },
  { french: 'la surabondance', translation: 'перепроизводство; изобилие', translationEn: 'overabundance; glut', category: 'economics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La surabondance de pétrole a fait chuter les prix.', exampleRu: 'Перепроизводство нефти обвалило цены.', exampleEn: 'The oil glut caused prices to crash.' },
  { french: 'le monopole', translation: 'монополия', translationEn: 'monopoly', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Ce géant du numérique est accusé de monopole.', exampleRu: 'Этот цифровой гигант обвиняется в монополии.', exampleEn: 'This digital giant is accused of monopoly.' },
  { french: 'l\'oligopole', translation: 'олигополия', translationEn: 'oligopoly', category: 'economics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le marché téléphonique est un oligopole.', exampleRu: 'Рынок мобильной связи — это олигополия.', exampleEn: 'The mobile phone market is an oligopoly.' },
];
