export const wordsB2Extra13 = [
  // ── Enseignement supérieur ──
  {
    french: 'la licence',
    translation: 'степень бакалавра (3 года)',
    translationEn: 'bachelor\'s degree (3 years in France)',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'Elle prépare une licence de droit à l\'Université Paris 1.',
    exampleRu: 'Она получает степень бакалавра по праву в Парижском университете 1.',
    exampleEn: 'She is doing a law degree at Paris 1 University.',
  },
  {
    french: 'le master',
    translation: 'магистратура, степень магистра',
    translationEn: 'master\'s degree',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4000,
    exampleFr: 'Il a intégré un master en gestion internationale.',
    exampleRu: 'Он поступил в магистратуру по международному менеджменту.',
    exampleEn: 'He joined a master\'s programme in international management.',
  },
  {
    french: 'le doctorat',
    translation: 'докторантура, степень доктора',
    translationEn: 'doctorate, PhD',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4500,
    exampleFr: 'Son doctorat porte sur les effets du changement climatique sur la biodiversité.',
    exampleRu: 'Его диссертация посвящена влиянию климатических изменений на биоразнообразие.',
    exampleEn: 'Her doctorate focuses on the effects of climate change on biodiversity.',
  },
  {
    french: 'la soutenance',
    translation: 'защита (диссертации)',
    translationEn: 'thesis defence',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'La soutenance de thèse aura lieu le quinze janvier devant un jury de cinq membres.',
    exampleRu: 'Защита диссертации состоится пятнадцатого января перед комиссией из пяти человек.',
    exampleEn: 'The thesis defence will take place on January 15th before a panel of five.',
  },
  {
    french: 'le directeur de thèse',
    translation: 'научный руководитель',
    translationEn: 'thesis supervisor, PhD supervisor',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Son directeur de thèse l\'a encouragée à publier ses premiers résultats.',
    exampleRu: 'Научный руководитель поощрил её опубликовать первые результаты.',
    exampleEn: 'Her thesis supervisor encouraged her to publish her first results.',
  },
  {
    french: 'l\'amphithéâtre',
    translation: 'аудитория-амфитеатр',
    translationEn: 'lecture hall, amphitheatre',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4700,
    exampleFr: 'Le cours magistral rassemble trois cents étudiants dans l\'amphithéâtre.',
    exampleRu: 'Лекция собирает триста студентов в аудитории-амфитеатре.',
    exampleEn: 'The lecture brings together three hundred students in the lecture hall.',
  },
  {
    french: 'le séminaire',
    translation: 'семинар',
    translationEn: 'seminar',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4200,
    exampleFr: 'Le séminaire de recherche réunit des spécialistes du monde entier.',
    exampleRu: 'Исследовательский семинар собирает специалистов со всего мира.',
    exampleEn: 'The research seminar brings together specialists from around the world.',
  },
  {
    french: 'le colloque',
    translation: 'научная конференция, коллоквиум',
    translationEn: 'conference, colloquium',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Elle a présenté ses travaux lors d\'un colloque international à Lyon.',
    exampleRu: 'Она представила свои работы на международной конференции в Лионе.',
    exampleEn: 'She presented her research at an international conference in Lyon.',
  },
  {
    french: 'les grandes écoles',
    translation: 'grandes écoles (элитные вузы Франции)',
    translationEn: 'grandes écoles (elite French higher education institutions)',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'Les grandes écoles forment une grande partie des élites françaises.',
    exampleRu: 'Grandes écoles готовят значительную часть французской элиты.',
    exampleEn: 'The grandes écoles train a large part of the French elite.',
  },
  {
    french: 'les classes préparatoires',
    translation: 'подготовительные классы (для конкурса в grandes écoles)',
    translationEn: 'preparatory classes (for entry to grandes écoles)',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'Les classes préparatoires exigent un travail intense pendant deux ans.',
    exampleRu: 'Подготовительные классы требуют напряжённой работы на протяжении двух лет.',
    exampleEn: 'Preparatory classes require intensive work for two years.',
  },
  {
    french: 'le concours',
    translation: 'конкурсный экзамен',
    translationEn: 'competitive examination',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2600,
    exampleFr: 'Elle a réussi le concours de l\'agrégation du premier coup.',
    exampleRu: 'Она сдала конкурсный экзамен на агрегацию с первого раза.',
    exampleEn: 'She passed the agrégation competitive exam on the first attempt.',
  },
  {
    french: 'la filière',
    translation: 'направление обучения, специальность',
    translationEn: 'stream, track, field of study',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3700,
    exampleFr: 'La filière scientifique mène à des débouchés très variés.',
    exampleRu: 'Научное направление открывает очень разнообразные карьерные перспективы.',
    exampleEn: 'The science stream leads to a wide variety of career opportunities.',
  },
  {
    french: 'l\'orientation',
    translation: 'профориентация; ориентация на специальность',
    translationEn: 'course guidance, career guidance',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3000,
    exampleFr: 'L\'orientation scolaire est souvent mal adaptée aux besoins du marché.',
    exampleRu: 'Профориентация в школе зачастую плохо соответствует потребностям рынка труда.',
    exampleEn: 'School guidance is often poorly matched to labour market needs.',
  },
  // ── Recherche académique ──
  {
    french: 'le paradigme',
    translation: 'парадигма',
    translationEn: 'paradigm',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Ce chercheur a proposé un changement de paradigme dans son domaine.',
    exampleRu: 'Этот исследователь предложил смену парадигмы в своей области.',
    exampleEn: 'This researcher proposed a paradigm shift in his field.',
  },
  {
    french: 'le corpus',
    translation: 'корпус (текстов, данных)',
    translationEn: 'corpus',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5300,
    exampleFr: 'Son corpus d\'analyse comprend deux cents articles scientifiques.',
    exampleRu: 'Её аналитический корпус включает двести научных статей.',
    exampleEn: 'Her corpus of analysis includes two hundred scientific articles.',
  },
  {
    french: 'la méthodologie',
    translation: 'методология',
    translationEn: 'methodology',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'La méthodologie de l\'étude doit être clairement exposée.',
    exampleRu: 'Методология исследования должна быть чётко изложена.',
    exampleEn: 'The study\'s methodology must be clearly set out.',
  },
  {
    french: 'la revue à comité de lecture',
    translation: 'рецензируемый журнал',
    translationEn: 'peer-reviewed journal',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'Publier dans une revue à comité de lecture est indispensable pour un chercheur.',
    exampleRu: 'Публикация в рецензируемом журнале обязательна для исследователя.',
    exampleEn: 'Publishing in a peer-reviewed journal is essential for a researcher.',
  },
  {
    french: 'le plagiat',
    translation: 'плагиат',
    translationEn: 'plagiarism',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'Le plagiat est sanctionné par l\'annulation de la note et de possibles poursuites.',
    exampleRu: 'Плагиат карается аннулированием оценки и возможным уголовным преследованием.',
    exampleEn: 'Plagiarism is punished by cancellation of the grade and possible prosecution.',
  },
  {
    french: 'l\'état de l\'art',
    translation: 'обзор литературы, состояние области',
    translationEn: 'literature review, state of the art',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'La première partie de la thèse dresse un état de l\'art exhaustif.',
    exampleRu: 'Первая часть диссертации представляет исчерпывающий обзор литературы.',
    exampleEn: 'The first part of the thesis provides an exhaustive literature review.',
  },
  {
    french: 'la problématique',
    translation: 'проблематика, исследовательский вопрос',
    translationEn: 'research question, problematic',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4300,
    exampleFr: 'La problématique de cette thèse porte sur l\'impact des réseaux sociaux.',
    exampleRu: 'Исследовательский вопрос данной диссертации касается влияния социальных сетей.',
    exampleEn: 'The research question of this thesis concerns the impact of social networks.',
  },
  {
    french: 'corroborer',
    translation: 'подтверждать, подкреплять (доказательствами)',
    translationEn: 'to corroborate',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 6200,
    exampleFr: 'Ces données corroborent l\'hypothèse formulée au départ.',
    exampleRu: 'Эти данные подтверждают первоначально сформулированную гипотезу.',
    exampleEn: 'These data corroborate the hypothesis formulated at the outset.',
  },
  {
    french: 'infirmer',
    translation: 'опровергать (гипотезу, теорию)',
    translationEn: 'to refute, to invalidate',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 6400,
    exampleFr: 'Les résultats de l\'expérience infirment la théorie initiale.',
    exampleRu: 'Результаты эксперимента опровергают первоначальную теорию.',
    exampleEn: 'The experimental results invalidate the initial theory.',
  },
  {
    french: 'étayer',
    translation: 'обосновывать, подкреплять (аргументами)',
    translationEn: 'to substantiate, to support (an argument)',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 6000,
    exampleFr: 'Il faut étayer chaque affirmation par des références précises.',
    exampleRu: 'Каждое утверждение необходимо подкреплять точными ссылками.',
    exampleEn: 'Every assertion must be substantiated with precise references.',
  },
  {
    french: 'inférer',
    translation: 'выводить умозаключение, делать вывод',
    translationEn: 'to infer',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 6500,
    exampleFr: 'On peut inférer de ces données que le phénomène est universel.',
    exampleRu: 'Из этих данных можно сделать вывод, что явление универсально.',
    exampleEn: 'One can infer from these data that the phenomenon is universal.',
  },
  {
    french: 'extrapoler',
    translation: 'экстраполировать',
    translationEn: 'to extrapolate',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 6300,
    exampleFr: 'Il est risqué d\'extrapoler ces résultats à l\'ensemble de la population.',
    exampleRu: 'Опасно экстраполировать эти результаты на всё население.',
    exampleEn: 'It is risky to extrapolate these results to the entire population.',
  },
  {
    french: 'réfuter',
    translation: 'опровергать (довод, теорию)',
    translationEn: 'to refute',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 5700,
    exampleFr: 'Popper affirmait qu\'une théorie scientifique doit être réfutable.',
    exampleRu: 'Поппер утверждал, что научная теория должна быть опровержимой.',
    exampleEn: 'Popper claimed that a scientific theory must be refutable.',
  },
  {
    french: 'valider',
    translation: 'подтверждать, валидировать (гипотезу)',
    translationEn: 'to validate',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 4100,
    exampleFr: 'L\'expérimentation permet de valider ou d\'invalider les hypothèses.',
    exampleRu: 'Эксперимент позволяет подтвердить или опровергнуть гипотезы.',
    exampleEn: 'Experimentation allows hypotheses to be validated or invalidated.',
  },
  {
    french: 'le postulat',
    translation: 'постулат, исходное допущение',
    translationEn: 'postulate, assumption',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6100,
    exampleFr: 'Ce postulat de départ est discutable et mérite d\'être remis en cause.',
    exampleRu: 'Это исходное допущение спорно и заслуживает пересмотра.',
    exampleEn: 'This initial postulate is debatable and deserves to be challenged.',
  },
  {
    french: 'l\'axiome',
    translation: 'аксиома',
    translationEn: 'axiom',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6700,
    exampleFr: 'En mathématiques, un axiome est admis sans démonstration.',
    exampleRu: 'В математике аксиома принимается без доказательства.',
    exampleEn: 'In mathematics, an axiom is accepted without proof.',
  },
  {
    french: 'la conjecture',
    translation: 'предположение, конъектура',
    translationEn: 'conjecture',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6800,
    exampleFr: 'La conjecture de Goldbach n\'a pas encore été prouvée.',
    exampleRu: 'Гипотеза Гольдбаха до сих пор не доказана.',
    exampleEn: 'Goldbach\'s conjecture has not yet been proved.',
  },
  // ── Pédagogie ──
  {
    french: 'la pédagogie',
    translation: 'педагогика; методика преподавания',
    translationEn: 'pedagogy, teaching method',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4500,
    exampleFr: 'Une pédagogie active engage davantage les élèves.',
    exampleRu: 'Активная педагогика в большей мере вовлекает учеников.',
    exampleEn: 'Active pedagogy engages students more.',
  },
  {
    french: 'la différenciation pédagogique',
    translation: 'дифференцированное обучение',
    translationEn: 'differentiated instruction',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 7000,
    exampleFr: 'La différenciation pédagogique adapte l\'enseignement à chaque élève.',
    exampleRu: 'Дифференцированное обучение адаптирует преподавание к каждому ученику.',
    exampleEn: 'Differentiated instruction adapts teaching to each student.',
  },
  {
    french: 'le tutorat',
    translation: 'наставничество, тьюторство',
    translationEn: 'tutoring, mentoring',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5900,
    exampleFr: 'Le tutorat entre étudiants améliore les résultats des plus fragiles.',
    exampleRu: 'Взаимное наставничество студентов улучшает результаты более слабых.',
    exampleEn: 'Peer tutoring improves the results of weaker students.',
  },
  {
    french: 'l\'évaluation formative',
    translation: 'формирующее оценивание',
    translationEn: 'formative assessment',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'L\'évaluation formative aide l\'élève à identifier ses lacunes.',
    exampleRu: 'Формирующее оценивание помогает ученику выявить свои пробелы.',
    exampleEn: 'Formative assessment helps the student identify their gaps.',
  },
  {
    french: 'le référentiel',
    translation: 'референциальная база, стандарт компетенций',
    translationEn: 'reference framework, competency standard',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le référentiel de compétences définit ce que l\'élève doit savoir faire.',
    exampleRu: 'Стандарт компетенций определяет, что ученик должен уметь делать.',
    exampleEn: 'The competency framework defines what the student should be able to do.',
  },
  {
    french: 'le maître de conférences',
    translation: 'доцент (французский университет)',
    translationEn: 'associate professor (French university)',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Elle est maître de conférences en linguistique à l\'Université de Bordeaux.',
    exampleRu: 'Она доцент по лингвистике в Бордоском университете.',
    exampleEn: 'She is an associate professor of linguistics at the University of Bordeaux.',
  },
  {
    french: 'l\'allocataire de recherche',
    translation: 'стипендиат, аспирант на финансовой поддержке',
    translationEn: 'research grant holder, funded doctoral student',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 7200,
    exampleFr: 'Les allocataires de recherche perçoivent un contrat doctoral financé.',
    exampleRu: 'Стипендиаты получают финансируемый докторский контракт.',
    exampleEn: 'Research grant holders receive a funded doctoral contract.',
  },
  {
    french: 'l\'appel à projets',
    translation: 'конкурс проектов (на финансирование)',
    translationEn: 'call for projects, grant application',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5400,
    exampleFr: 'Le laboratoire a répondu à un appel à projets de l\'ANR.',
    exampleRu: 'Лаборатория подала заявку на конкурс проектов ANR.',
    exampleEn: 'The laboratory responded to a call for projects from the ANR.',
  },
  {
    french: 'la bibliographie',
    translation: 'библиография',
    translationEn: 'bibliography',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5000,
    exampleFr: 'La bibliographie doit respecter les normes de citation en vigueur.',
    exampleRu: 'Библиография должна соответствовать действующим нормам цитирования.',
    exampleEn: 'The bibliography must comply with current citation standards.',
  },
  {
    french: 'l\'expérimentation',
    translation: 'экспериментирование',
    translationEn: 'experimentation',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'L\'expérimentation en sciences sociales soulève des questions éthiques.',
    exampleRu: 'Экспериментирование в социальных науках поднимает этические вопросы.',
    exampleEn: 'Experimentation in social sciences raises ethical questions.',
  },
  {
    french: 'la transversalité',
    translation: 'трансдисциплинарность, межпредметность',
    translationEn: 'cross-disciplinarity, transversality',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6600,
    exampleFr: 'La transversalité entre disciplines enrichit les résultats de la recherche.',
    exampleRu: 'Трансдисциплинарность обогащает результаты исследований.',
    exampleEn: 'Cross-disciplinarity enriches research outcomes.',
  },
  {
    french: 'la démarche inductive',
    translation: 'индуктивный подход',
    translationEn: 'inductive approach',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6900,
    exampleFr: 'La démarche inductive part des observations pour construire une théorie.',
    exampleRu: 'Индуктивный подход исходит из наблюдений для построения теории.',
    exampleEn: 'The inductive approach starts from observations to build a theory.',
  },
  {
    french: 'la démarche déductive',
    translation: 'дедуктивный подход',
    translationEn: 'deductive approach',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6900,
    exampleFr: 'La démarche déductive part d\'une théorie pour la tester sur des données.',
    exampleRu: 'Дедуктивный подход исходит из теории для проверки на данных.',
    exampleEn: 'The deductive approach starts from a theory to test it against data.',
  },
  {
    french: 'la note de bas de page',
    translation: 'сноска',
    translationEn: 'footnote',
    category: 'academic',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'Les notes de bas de page précisent les sources sans alourdir le texte.',
    exampleRu: 'Сноски уточняют источники, не перегружая основной текст.',
    exampleEn: 'Footnotes specify sources without overloading the main text.',
  },
  {
    french: 'synthétiser',
    translation: 'синтезировать, обобщать',
    translationEn: 'to synthesise, to summarise',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 5600,
    exampleFr: 'La conclusion doit synthétiser les principaux apports de la recherche.',
    exampleRu: 'Заключение должно обобщать основные вклады исследования.',
    exampleEn: 'The conclusion should synthesise the main contributions of the research.',
  },
  {
    french: 'démontrer',
    translation: 'доказывать, демонстрировать',
    translationEn: 'to demonstrate, to prove',
    category: 'academic',
    partOfSpeech: 'verb',
    frequencyRank: 2900,
    exampleFr: 'L\'auteur démontre que la corrélation n\'implique pas la causalité.',
    exampleRu: 'Автор доказывает, что корреляция не означает причинно-следственной связи.',
    exampleEn: 'The author demonstrates that correlation does not imply causation.',
  },
  {
    french: 'le financement de la recherche',
    translation: 'финансирование исследований',
    translationEn: 'research funding',
    category: 'education',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Le financement de la recherche publique est en baisse dans de nombreux pays.',
    exampleRu: 'Финансирование государственных исследований снижается во многих странах.',
    exampleEn: 'Public research funding is declining in many countries.',
  },
];
