import type { NewWord } from './index.js';

export const wordsB2Extra2: Omit<NewWord, 'id' | 'createdAt'>[] = [
  // ── Sciences et recherche ──
  { french: 'l\'expérience', translation: 'опыт, эксперимент', translationEn: 'experiment, experience', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1600, exampleFr: 'Les scientifiques ont mené une expérience concluante.', exampleRu: 'Учёные провели убедительный эксперимент.', exampleEn: 'The scientists conducted a conclusive experiment.' },
  { french: 'la recherche fondamentale', translation: 'фундаментальная наука', translationEn: 'fundamental research, basic research', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1601, exampleFr: 'La recherche fondamentale prépare les avancées de demain.', exampleRu: 'Фундаментальная наука готовит прогресс будущего.', exampleEn: 'Fundamental research prepares the advances of tomorrow.' },
  { french: 'le génome', translation: 'геном', translationEn: 'genome', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1602, exampleFr: 'Le séquençage du génome révolutionne la médecine.', exampleRu: 'Секвенирование генома революционизирует медицину.', exampleEn: 'Genome sequencing is revolutionizing medicine.' },
  { french: 'la nanotechnologie', translation: 'нанотехнология', translationEn: 'nanotechnology', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1603, exampleFr: 'Les nanotechnologies ouvrent de nouvelles perspectives.', exampleRu: 'Нанотехнологии открывают новые перспективы.', exampleEn: 'Nanotechnologies open up new perspectives.' },
  { french: 'la variable', translation: 'переменная, переменная величина', translationEn: 'variable', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1604, exampleFr: 'Cette étude comporte plusieurs variables.', exampleRu: 'Это исследование включает несколько переменных.', exampleEn: 'This study involves several variables.' },
  { french: 'le résultat', translation: 'результат, итог', translationEn: 'result, outcome', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1605, exampleFr: 'Les résultats de l\'étude sont prometteurs.', exampleRu: 'Результаты исследования многообещающие.', exampleEn: 'The study results are promising.' },
  { french: 'l\'échantillon', translation: 'выборка, образец, пример', translationEn: 'sample, specimen', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1606, exampleFr: 'L\'échantillon doit être représentatif.', exampleRu: 'Выборка должна быть репрезентативной.', exampleEn: 'The sample must be representative.' },
  { french: 'la théorie', translation: 'теория', translationEn: 'theory', level: 'B2', category: 'science', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1607, exampleFr: 'La théorie de l\'évolution est solidement établie.', exampleRu: 'Теория эволюции надёжно установлена.', exampleEn: 'The theory of evolution is solidly established.' },

  // ── Urbanisme et architecture ──
  { french: 'l\'urbanisme', translation: 'градостроительство, урбанизм', translationEn: 'urban planning, urbanism', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1610, exampleFr: 'L\'urbanisme de cette ville est remarquable.', exampleRu: 'Градостроительство этого города замечательно.', exampleEn: 'The urban planning of this city is remarkable.' },
  { french: 'la densité', translation: 'плотность', translationEn: 'density', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1611, exampleFr: 'La densité de population est très élevée.', exampleRu: 'Плотность населения очень высокая.', exampleEn: 'The population density is very high.' },
  { french: 'l\'étalement urbain', translation: 'разрастание городов, субурбанизация', translationEn: 'urban sprawl', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1612, exampleFr: 'L\'étalement urbain menace les terres agricoles.', exampleRu: 'Разрастание городов угрожает сельскохозяйственным землям.', exampleEn: 'Urban sprawl threatens agricultural land.' },
  { french: 'la rénovation', translation: 'реновация, ремонт, обновление', translationEn: 'renovation, restoration', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1613, exampleFr: 'La rénovation du quartier a pris dix ans.', exampleRu: 'Реновация района заняла десять лет.', exampleEn: 'The renovation of the neighborhood took ten years.' },
  { french: 'les transports en commun', translation: 'общественный транспорт', translationEn: 'public transport, public transit', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1614, exampleFr: 'Les transports en commun réduisent la pollution.', exampleRu: 'Общественный транспорт снижает загрязнение.', exampleEn: 'Public transport reduces pollution.' },
  { french: 'la banlieue', translation: 'пригород, пригородный район', translationEn: 'suburb, outskirts', level: 'B2', category: 'urban', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1615, exampleFr: 'Il habite en banlieue et travaille à Paris.', exampleRu: 'Он живёт в пригороде и работает в Париже.', exampleEn: 'He lives in the suburbs and works in Paris.' },

  // ── Travail et entreprise ──
  { french: 'le recrutement', translation: 'набор, вербовка', translationEn: 'recruitment, hiring', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1620, exampleFr: 'Le recrutement est difficile dans ce secteur.', exampleRu: 'Набор персонала в этой отрасли труден.', exampleEn: 'Recruitment is difficult in this sector.' },
  { french: 'la négociation', translation: 'переговоры', translationEn: 'negotiation', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1621, exampleFr: 'Les négociations salariales sont en cours.', exampleRu: 'Зарплатные переговоры идут.', exampleEn: 'Salary negotiations are underway.' },
  { french: 'la productivité', translation: 'производительность', translationEn: 'productivity', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1622, exampleFr: 'Comment améliorer la productivité des équipes ?', exampleRu: 'Как улучшить производительность команд?', exampleEn: 'How to improve team productivity?' },
  { french: 'le télétravail', translation: 'удалённая работа, телеработа', translationEn: 'remote work, teleworking', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1623, exampleFr: 'Le télétravail s\'est généralisé depuis la pandémie.', exampleRu: 'Удалённая работа стала распространённой со времён пандемии.', exampleEn: 'Remote work has become widespread since the pandemic.' },
  { french: 'la grève', translation: 'забастовка', translationEn: 'strike', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1624, exampleFr: 'Les employés sont en grève depuis une semaine.', exampleRu: 'Работники бастуют уже неделю.', exampleEn: 'The employees have been on strike for a week.' },
  { french: 'le licenciement', translation: 'увольнение', translationEn: 'dismissal, layoff', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1625, exampleFr: 'Il a reçu une lettre de licenciement.', exampleRu: 'Он получил уведомление об увольнении.', exampleEn: 'He received a dismissal letter.' },
  { french: 'le syndicat', translation: 'профсоюз, синдикат', translationEn: 'trade union, labor union', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1626, exampleFr: 'Le syndicat défend les droits des travailleurs.', exampleRu: 'Профсоюз защищает права работников.', exampleEn: 'The trade union defends workers\' rights.' },
  { french: 'la convention collective', translation: 'коллективный договор', translationEn: 'collective agreement', level: 'B2', category: 'work', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1627, exampleFr: 'La convention collective régit les conditions de travail.', exampleRu: 'Коллективный договор регулирует условия труда.', exampleEn: 'The collective agreement governs working conditions.' },

  // ── Histoire ──
  { french: 'le régime', translation: 'режим, строй', translationEn: 'regime, government system', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1630, exampleFr: 'Ce régime autoritaire a duré 40 ans.', exampleRu: 'Этот авторитарный режим просуществовал 40 лет.', exampleEn: 'This authoritarian regime lasted 40 years.' },
  { french: 'la révolution', translation: 'революция', translationEn: 'revolution', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1631, exampleFr: 'La Révolution française a changé l\'Europe.', exampleRu: 'Французская революция изменила Европу.', exampleEn: 'The French Revolution changed Europe.' },
  { french: 'l\'empire', translation: 'империя', translationEn: 'empire', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1632, exampleFr: 'L\'Empire romain a duré plusieurs siècles.', exampleRu: 'Римская империя просуществовала несколько веков.', exampleEn: 'The Roman Empire lasted several centuries.' },
  { french: 'la colonisation', translation: 'колонизация', translationEn: 'colonization', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1633, exampleFr: 'La colonisation a laissé des traces durables.', exampleRu: 'Колонизация оставила долговременные следы.', exampleEn: 'Colonization left lasting traces.' },
  { french: 'la décolonisation', translation: 'деколонизация', translationEn: 'decolonization', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1634, exampleFr: 'La décolonisation a eu lieu après la Seconde Guerre mondiale.', exampleRu: 'Деколонизация произошла после Второй мировой войны.', exampleEn: 'Decolonization took place after World War II.' },
  { french: 'l\'armistice', translation: 'перемирие', translationEn: 'armistice, ceasefire', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1635, exampleFr: 'L\'armistice du 11 novembre 1918 a mis fin à la guerre.', exampleRu: 'Перемирие 11 ноября 1918 года положило конец войне.', exampleEn: 'The armistice of November 11, 1918 ended the war.' },
  { french: 'la résistance', translation: 'сопротивление', translationEn: 'resistance', level: 'B2', category: 'history', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1636, exampleFr: 'La Résistance française a combattu l\'occupation.', exampleRu: 'Французское Сопротивление боролось с оккупацией.', exampleEn: 'The French Resistance fought against the occupation.' },

  // ── Expressions idiomatiques B2 ──
  { french: 'avoir beau', translation: 'сколько ни, хоть и, несмотря на', translationEn: 'no matter how much, to do something in vain', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1640, exampleFr: 'Il a beau essayer, ça ne fonctionne pas.', exampleRu: 'Сколько бы он ни пытался, ничего не получается.', exampleEn: 'No matter how hard he tries, it doesn\'t work.' },
  { french: 'tenir compte de', translation: 'принимать во внимание', translationEn: 'to take into account, to consider', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1641, exampleFr: 'Il faut tenir compte des avis de chacun.', exampleRu: 'Нужно принимать во внимание мнение каждого.', exampleEn: 'We must take everyone\'s opinions into account.' },
  { french: 'se rendre compte de', translation: 'осознавать, понимать', translationEn: 'to realize, to become aware of', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1642, exampleFr: 'Je me suis rendu compte de mon erreur trop tard.', exampleRu: 'Я осознал свою ошибку слишком поздно.', exampleEn: 'I realized my mistake too late.' },
  { french: 'prendre en charge', translation: 'брать на себя, нести ответственность', translationEn: 'to take charge of, to cover, to handle', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1643, exampleFr: 'L\'assurance prend en charge les frais médicaux.', exampleRu: 'Страховка покрывает медицинские расходы.', exampleEn: 'Insurance covers medical expenses.' },
  { french: 'mettre en œuvre', translation: 'осуществлять, реализовывать', translationEn: 'to implement, to carry out', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1644, exampleFr: 'Il est temps de mettre en œuvre ce plan.', exampleRu: 'Пришло время реализовать этот план.', exampleEn: 'It\'s time to implement this plan.' },
  { french: 'faire preuve de', translation: 'проявлять', translationEn: 'to show, to demonstrate, to display', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1645, exampleFr: 'Il faut faire preuve de patience.', exampleRu: 'Нужно проявлять терпение.', exampleEn: 'We must show patience.' },
  { french: 'remettre en question', translation: 'ставить под сомнение', translationEn: 'to question, to challenge, to reconsider', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1646, exampleFr: 'Ce résultat remet en question nos hypothèses.', exampleRu: 'Этот результат ставит под сомнение наши гипотезы.', exampleEn: 'This result calls our hypotheses into question.' },
  { french: 'faire face à', translation: 'сталкиваться с, противостоять', translationEn: 'to face, to deal with, to cope with', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1647, exampleFr: 'Il faut faire face aux défis du XXIe siècle.', exampleRu: 'Нужно противостоять вызовам XXI века.', exampleEn: 'We must face the challenges of the 21st century.' },
  { french: 'prendre conscience de', translation: 'осознавать, становиться сознательным', translationEn: 'to become aware of, to realize', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1648, exampleFr: 'Il faut prendre conscience de l\'urgence climatique.', exampleRu: 'Нужно осознать климатическую срочность.', exampleEn: 'We must become aware of the climate emergency.' },
  { french: 'à long terme', translation: 'долгосрочно, в долгосрочной перспективе', translationEn: 'in the long term, long-term', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1649, exampleFr: 'À long terme, cela sera bénéfique.', exampleRu: 'В долгосрочной перспективе это будет полезно.', exampleEn: 'In the long term, this will be beneficial.' },
  { french: 'à court terme', translation: 'краткосрочно, в краткосрочной перспективе', translationEn: 'in the short term, short-term', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1650, exampleFr: 'À court terme, les résultats sont décevants.', exampleRu: 'В краткосрочной перспективе результаты разочаровывают.', exampleEn: 'In the short term, the results are disappointing.' },
  { french: 'au fond', translation: 'в глубине, в сущности, на самом деле', translationEn: 'at the bottom, fundamentally, basically', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1651, exampleFr: 'Au fond, il a raison.', exampleRu: 'В сущности, он прав.', exampleEn: 'Basically, he is right.' },
  { french: 'en dépit de', translation: 'несмотря на', translationEn: 'in spite of, despite', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1652, exampleFr: 'En dépit des obstacles, il a réussi.', exampleRu: 'Несмотря на препятствия, ему удалось.', exampleEn: 'In spite of the obstacles, he succeeded.' },
  { french: 'à l\'égard de', translation: 'по отношению к, в отношении', translationEn: 'with regard to, towards', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1653, exampleFr: 'Son attitude à l\'égard des autres est bienveillante.', exampleRu: 'Его отношение к другим доброжелательное.', exampleEn: 'His attitude towards others is benevolent.' },
  { french: 'en matière de', translation: 'в области, в отношении', translationEn: 'in terms of, in the area of, as regards', level: 'B2', category: 'expressions', partOfSpeech: 'expression', gender: null, frequencyRank: 1654, exampleFr: 'Des progrès ont été faits en matière d\'éducation.', exampleRu: 'Прогресс был достигнут в области образования.', exampleEn: 'Progress has been made in terms of education.' },

  // ── Noms abstraits niveau soutenu ──
  { french: 'l\'adversité', translation: 'невзгоды, тяготы', translationEn: 'adversity, hardship', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1660, exampleFr: 'Il a surmonté bien des adversités.', exampleRu: 'Он преодолел немало невзгод.', exampleEn: 'He overcame many adversities.' },
  { french: 'la cohésion', translation: 'сплочённость, единство', translationEn: 'cohesion, unity', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1661, exampleFr: 'La cohésion sociale est menacée.', exampleRu: 'Социальная сплочённость находится под угрозой.', exampleEn: 'Social cohesion is under threat.' },
  { french: 'la complexité', translation: 'сложность, комплексность', translationEn: 'complexity', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1662, exampleFr: 'La complexité de la situation est évidente.', exampleRu: 'Сложность ситуации очевидна.', exampleEn: 'The complexity of the situation is obvious.' },
  { french: 'la crédibilité', translation: 'достоверность, авторитет', translationEn: 'credibility', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1663, exampleFr: 'Il a perdu sa crédibilité après ce scandale.', exampleRu: 'Он потерял авторитет после этого скандала.', exampleEn: 'He lost his credibility after this scandal.' },
  { french: 'la divergence', translation: 'расхождение, различие', translationEn: 'divergence, difference', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1664, exampleFr: 'Il y a des divergences d\'opinion sur ce point.', exampleRu: 'По этому вопросу есть расхождения мнений.', exampleEn: 'There are divergences of opinion on this point.' },
  { french: 'l\'efficacité', translation: 'эффективность, результативность', translationEn: 'efficiency, effectiveness', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1665, exampleFr: 'L\'efficacité de ce traitement est prouvée.', exampleRu: 'Эффективность этого лечения доказана.', exampleEn: 'The effectiveness of this treatment is proven.' },
  { french: 'la faisabilité', translation: 'осуществимость, реализуемость', translationEn: 'feasibility', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1666, exampleFr: 'Une étude de faisabilité est nécessaire.', exampleRu: 'Необходимо технико-экономическое обоснование.', exampleEn: 'A feasibility study is necessary.' },
  { french: 'la légitimité', translation: 'законность, легитимность', translationEn: 'legitimacy', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1667, exampleFr: 'La légitimité du gouvernement est contestée.', exampleRu: 'Легитимность правительства оспаривается.', exampleEn: 'The legitimacy of the government is contested.' },
  { french: 'la réciprocité', translation: 'взаимность', translationEn: 'reciprocity', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1668, exampleFr: 'La réciprocité est la base de tout échange.', exampleRu: 'Взаимность — основа любого обмена.', exampleEn: 'Reciprocity is the basis of any exchange.' },
  { french: 'la transparence', translation: 'прозрачность', translationEn: 'transparency', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1669, exampleFr: 'La transparence des institutions est essentielle.', exampleRu: 'Прозрачность институтов имеет важное значение.', exampleEn: 'The transparency of institutions is essential.' },
  { french: 'la viabilité', translation: 'жизнеспособность', translationEn: 'viability', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1670, exampleFr: 'La viabilité économique du projet est discutable.', exampleRu: 'Экономическая жизнеспособность проекта спорна.', exampleEn: 'The economic viability of the project is debatable.' },

  // ── Philosophie et éthique ──
  { french: 'l\'éthique', translation: 'этика', translationEn: 'ethics', level: 'B2', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1680, exampleFr: 'L\'éthique médicale est un domaine complexe.', exampleRu: 'Медицинская этика — сложная область.', exampleEn: 'Medical ethics is a complex field.' },
  { french: 'la morale', translation: 'нравственность, мораль', translationEn: 'morality, ethics, moral', level: 'B2', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1681, exampleFr: 'La morale évolue avec les sociétés.', exampleRu: 'Нравственность меняется вместе с обществами.', exampleEn: 'Morality evolves with societies.' },
  { french: 'le déterminisme', translation: 'детерминизм', translationEn: 'determinism', level: 'B2', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1682, exampleFr: 'Le débat entre déterminisme et libre arbitre est ancien.', exampleRu: 'Дебаты между детерминизмом и свободой воли стары.', exampleEn: 'The debate between determinism and free will is ancient.' },
  { french: 'le relativisme', translation: 'релятивизм', translationEn: 'relativism', level: 'B2', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1683, exampleFr: 'Le relativisme culturel reconnaît la diversité des valeurs.', exampleRu: 'Культурный релятивизм признаёт многообразие ценностей.', exampleEn: 'Cultural relativism acknowledges the diversity of values.' },
  { french: 'l\'utopie', translation: 'утопия', translationEn: 'utopia', level: 'B2', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1684, exampleFr: 'Une société parfaite reste une utopie.', exampleRu: 'Идеальное общество остаётся утопией.', exampleEn: 'A perfect society remains a utopia.' },
];
