// A2 extra vocabulary part 2 — new categories not in any existing A1/A2 file
export const wordsA2Extra2 = [
  // ===== SANTÉ =====
  { french: 'ordonnance', translation: 'рецепт (медицинский)', translationEn: 'prescription', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2700, exampleFr: "Le médecin m'a donné une ordonnance.", exampleRu: 'Врач выписал мне рецепт.', exampleEn: 'The doctor gave me a prescription.' },
  { french: 'allergie', translation: 'аллергия', translationEn: 'allergy', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2710, exampleFr: "J'ai une allergie au pollen.", exampleRu: 'У меня аллергия на пыльцу.', exampleEn: 'I have a pollen allergy.' },
  { french: 'médicament', translation: 'лекарство', translationEn: 'medicine, medication', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2720, exampleFr: "Prends ce médicament après le repas.", exampleRu: 'Принимай это лекарство после еды.', exampleEn: 'Take this medicine after meals.' },
  { french: 'blessure', translation: 'рана, травма', translationEn: 'injury, wound', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2730, exampleFr: "Sa blessure est grave.", exampleRu: 'Его рана серьёзная.', exampleEn: 'His injury is serious.' },
  { french: 'douleur', translation: 'боль', translationEn: 'pain', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2740, exampleFr: "J'ai une douleur au dos.", exampleRu: 'У меня боль в спине.', exampleEn: 'I have a pain in my back.' },
  { french: 'fièvre', translation: 'жар, лихорадка', translationEn: 'fever', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2750, exampleFr: "Il a de la fièvre.", exampleRu: 'У него жар.', exampleEn: 'He has a fever.' },
  { french: 'toux', translation: 'кашель', translationEn: 'cough', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2760, exampleFr: "J'ai une toux persistante.", exampleRu: 'У меня упорный кашель.', exampleEn: 'I have a persistent cough.' },
  { french: 'opération', translation: 'операция', translationEn: 'operation, surgery', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2770, exampleFr: "L'opération a réussi.", exampleRu: 'Операция прошла успешно.', exampleEn: 'The operation was successful.' },
  { french: 'chirurgien', translation: 'хирург', translationEn: 'surgeon', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2780, exampleFr: "Le chirurgien est expert.", exampleRu: 'Хирург опытный.', exampleEn: 'The surgeon is an expert.' },
  { french: 'infirmier', translation: 'медбрат / медсестра', translationEn: 'nurse', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2790, exampleFr: "L'infirmière m'a fait une piqûre.", exampleRu: 'Медсестра сделала мне укол.', exampleEn: 'The nurse gave me an injection.' },
  { french: 'urgences', translation: 'скорая помощь, приёмный покой', translationEn: 'emergency room', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2800, exampleFr: "Allons aux urgences.", exampleRu: 'Едем в скорую помощь.', exampleEn: "Let's go to the emergency room." },
  { french: 'rendez-vous médical', translation: 'приём у врача', translationEn: 'doctor\'s appointment', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2810, exampleFr: "J'ai un rendez-vous médical lundi.", exampleRu: 'У меня приём у врача в понедельник.', exampleEn: 'I have a doctor\'s appointment on Monday.' },
  { french: 'guérir', translation: 'выздоравливать, вылечивать', translationEn: 'to heal, to recover', category: 'health', partOfSpeech: 'verb', frequencyRank: 2820, exampleFr: "Il guérit rapidement.", exampleRu: 'Он быстро выздоравливает.', exampleEn: 'He recovers quickly.' },
  { french: 'soigner', translation: 'лечить, ухаживать', translationEn: 'to treat, to care for', category: 'health', partOfSpeech: 'verb', frequencyRank: 2830, exampleFr: "Le médecin la soigne bien.", exampleRu: 'Врач хорошо её лечит.', exampleEn: 'The doctor treats her well.' },

  // ===== MÉDIAS =====
  { french: 'journal', translation: 'газета, дневник', translationEn: 'newspaper, diary', category: 'media', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2840, exampleFr: "Je lis le journal chaque matin.", exampleRu: 'Я читаю газету каждое утро.', exampleEn: 'I read the newspaper every morning.' },
  { french: 'magazine', translation: 'журнал', translationEn: 'magazine', category: 'media', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2850, exampleFr: "Ce magazine est intéressant.", exampleRu: 'Этот журнал интересный.', exampleEn: 'This magazine is interesting.' },
  { french: 'émission', translation: 'передача, программа (ТВ)', translationEn: 'TV show, broadcast', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2860, exampleFr: "Mon émission préférée commence.", exampleRu: 'Начинается моя любимая передача.', exampleEn: 'My favourite show is starting.' },
  { french: 'publicité', translation: 'реклама', translationEn: 'advertisement', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2870, exampleFr: "Il y a trop de publicité.", exampleRu: 'Слишком много рекламы.', exampleEn: 'There is too much advertising.' },
  { french: 'chaîne', translation: 'канал (ТВ), цепочка', translationEn: 'channel, chain', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2880, exampleFr: "Change de chaîne.", exampleRu: 'Переключи канал.', exampleEn: 'Change the channel.' },
  { french: 'actualité', translation: 'новости, текущие события', translationEn: 'news, current events', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2890, exampleFr: "Je suis les actualités.", exampleRu: 'Я слежу за новостями.', exampleEn: 'I follow the news.' },
  { french: 'reportage', translation: 'репортаж', translationEn: 'report, documentary', category: 'media', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2900, exampleFr: "C'est un reportage sur la guerre.", exampleRu: 'Это репортаж о войне.', exampleEn: 'It is a report about the war.' },
  { french: 'journaliste', translation: 'журналист', translationEn: 'journalist', category: 'media', partOfSpeech: 'noun', frequencyRank: 2910, exampleFr: "Elle est journaliste.", exampleRu: 'Она журналист.', exampleEn: 'She is a journalist.' },
  { french: 'titre', translation: 'заголовок, название', translationEn: 'title, headline', category: 'media', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2920, exampleFr: "Le titre de l'article est accrocheur.", exampleRu: 'Заголовок статьи цепляющий.', exampleEn: 'The article headline is catchy.' },

  // ===== NATURE =====
  { french: 'lac', translation: 'озеро', translationEn: 'lake', category: 'nature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2930, exampleFr: "Nous nous baignons dans le lac.", exampleRu: 'Мы купаемся в озере.', exampleEn: 'We swim in the lake.' },
  { french: 'rivière', translation: 'река (небольшая)', translationEn: 'river', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2940, exampleFr: "La rivière est froide.", exampleRu: 'Река холодная.', exampleEn: 'The river is cold.' },
  { french: 'rocher', translation: 'скала, камень', translationEn: 'rock, boulder', category: 'nature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2950, exampleFr: "Il grimpe sur les rochers.", exampleRu: 'Он лезет на скалы.', exampleEn: 'He climbs on the rocks.' },
  { french: 'falaise', translation: 'утёс, скала (у моря)', translationEn: 'cliff', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2960, exampleFr: "Les falaises de Normandie sont magnifiques.", exampleRu: 'Скалы Нормандии великолепны.', exampleEn: 'The cliffs of Normandy are magnificent.' },
  { french: 'campagne', translation: 'деревня, countryside', translationEn: 'countryside', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2970, exampleFr: "J'aime vivre à la campagne.", exampleRu: 'Я люблю жить в деревне.', exampleEn: 'I love living in the countryside.' },
  { french: 'paysage', translation: 'пейзаж, ландшафт', translationEn: 'landscape, scenery', category: 'nature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2980, exampleFr: "Le paysage est superbe.", exampleRu: 'Пейзаж великолепный.', exampleEn: 'The scenery is superb.' },
  { french: 'prairie', translation: 'луг, прерия', translationEn: 'meadow, prairie', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2990, exampleFr: "Les vaches paissent dans la prairie.", exampleRu: 'Коровы пасутся на лугу.', exampleEn: 'The cows graze in the meadow.' },
  { french: 'horizon', translation: 'горизонт', translationEn: 'horizon', category: 'nature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3000, exampleFr: "Le soleil se couche à l'horizon.", exampleRu: 'Солнце садится за горизонт.', exampleEn: 'The sun sets on the horizon.' },
  { french: 'colline', translation: 'холм', translationEn: 'hill', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3010, exampleFr: "On monte sur la colline.", exampleRu: 'Мы поднимаемся на холм.', exampleEn: 'We go up the hill.' },
  { french: 'désert', translation: 'пустыня', translationEn: 'desert', category: 'nature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3020, exampleFr: "Le désert du Sahara est immense.", exampleRu: 'Пустыня Сахара огромная.', exampleEn: 'The Sahara desert is immense.' },
  { french: 'île', translation: 'остров', translationEn: 'island', category: 'nature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3030, exampleFr: "Nous visitons une île tropicale.", exampleRu: 'Мы посещаем тропический остров.', exampleEn: 'We visit a tropical island.' },

  // ===== COURSES / SHOPPING =====
  { french: 'soldes', translation: 'распродажа', translationEn: 'sales, clearance', category: 'shopping', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3040, exampleFr: "Les soldes commencent demain.", exampleRu: 'Распродажа начинается завтра.', exampleEn: 'The sales start tomorrow.' },
  { french: 'réduction', translation: 'скидка', translationEn: 'discount, reduction', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3050, exampleFr: "Il y a une réduction de 30%.", exampleRu: 'Скидка 30%.', exampleEn: 'There is a 30% discount.' },
  { french: 'taille', translation: 'размер (одежды)', translationEn: 'size (clothing)', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3060, exampleFr: "Quelle est votre taille ?", exampleRu: 'Какой у вас размер?', exampleEn: 'What is your size?' },
  { french: 'pointure', translation: 'размер (обуви)', translationEn: 'shoe size', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3070, exampleFr: "Je chausse du 42.", exampleRu: 'У меня 42-й размер.', exampleEn: 'I take a size 42.' },
  { french: 'cabine', translation: 'примерочная, кабина', translationEn: 'fitting room, cabin', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3080, exampleFr: "La cabine d'essayage est libre.", exampleRu: 'Примерочная свободна.', exampleEn: 'The fitting room is free.' },
  { french: 'caisse', translation: 'касса', translationEn: 'checkout, cash register', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3090, exampleFr: "Payez à la caisse.", exampleRu: 'Платите на кассе.', exampleEn: 'Pay at the checkout.' },
  { french: 'reçu', translation: 'чек, квитанция', translationEn: 'receipt', category: 'shopping', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3100, exampleFr: "Gardez votre reçu.", exampleRu: 'Сохраните чек.', exampleEn: 'Keep your receipt.' },
  { french: 'vitrine', translation: 'витрина', translationEn: 'shop window, display', category: 'shopping', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3110, exampleFr: "Je regarde la vitrine.", exampleRu: 'Я смотрю на витрину.', exampleEn: 'I look at the shop window.' },
  { french: 'rembourser', translation: 'возвращать деньги, возмещать', translationEn: 'to refund, to reimburse', category: 'shopping', partOfSpeech: 'verb', frequencyRank: 3120, exampleFr: "On m'a remboursé.", exampleRu: 'Мне вернули деньги.', exampleEn: 'I was refunded.' },
  { french: 'échanger', translation: 'обменивать', translationEn: 'to exchange', category: 'shopping', partOfSpeech: 'verb', frequencyRank: 3130, exampleFr: "Je veux échanger ce pantalon.", exampleRu: 'Я хочу обменять эти брюки.', exampleEn: 'I want to exchange these trousers.' },

  // ===== ARGENT / BANQUE =====
  { french: 'monnaie', translation: 'мелочь, валюта', translationEn: 'change, currency', category: 'money', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3140, exampleFr: "Avez-vous de la monnaie ?", exampleRu: 'У вас есть мелочь?', exampleEn: 'Do you have change?' },
  { french: 'compte bancaire', translation: 'банковский счёт', translationEn: 'bank account', category: 'money', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3150, exampleFr: "J'ouvre un compte bancaire.", exampleRu: 'Я открываю банковский счёт.', exampleEn: 'I am opening a bank account.' },
  { french: 'virement', translation: 'банковский перевод', translationEn: 'bank transfer', category: 'money', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3160, exampleFr: "J'ai fait un virement.", exampleRu: 'Я сделал перевод.', exampleEn: 'I made a bank transfer.' },
  { french: 'distributeur', translation: 'банкомат', translationEn: 'ATM, cash machine', category: 'money', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3170, exampleFr: "Le distributeur est en panne.", exampleRu: 'Банкомат не работает.', exampleEn: 'The ATM is out of order.' },
  { french: 'économiser', translation: 'экономить, копить', translationEn: 'to save (money)', category: 'money', partOfSpeech: 'verb', frequencyRank: 3180, exampleFr: "Je veux économiser pour les vacances.", exampleRu: 'Я хочу накопить на каникулы.', exampleEn: 'I want to save for the holidays.' },
  { french: 'dépenser', translation: 'тратить (деньги)', translationEn: 'to spend (money)', category: 'money', partOfSpeech: 'verb', frequencyRank: 3190, exampleFr: "Il dépense trop.", exampleRu: 'Он слишком много тратит.', exampleEn: 'He spends too much.' },
  { french: 'prêt', translation: 'кредит, заём', translationEn: 'loan', category: 'money', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3200, exampleFr: "Je rembourse mon prêt.", exampleRu: 'Я выплачиваю кредит.', exampleEn: 'I am repaying my loan.' },
  { french: 'budget', translation: 'бюджет', translationEn: 'budget', category: 'money', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3210, exampleFr: "Respecte ton budget.", exampleRu: 'Придерживайся бюджета.', exampleEn: 'Stick to your budget.' },

  // ===== CORPS HUMAIN =====
  { french: 'épaule', translation: 'плечо', translationEn: 'shoulder', category: 'body', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3220, exampleFr: "J'ai mal à l'épaule.", exampleRu: 'У меня болит плечо.', exampleEn: 'My shoulder hurts.' },
  { french: 'genou', translation: 'колено', translationEn: 'knee', category: 'body', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3230, exampleFr: "Il s'est blessé au genou.", exampleRu: 'Он травмировал колено.', exampleEn: 'He injured his knee.' },
  { french: 'coude', translation: 'локоть', translationEn: 'elbow', category: 'body', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3240, exampleFr: "Ne mets pas les coudes sur la table.", exampleRu: 'Не клади локти на стол.', exampleEn: 'Don\'t put your elbows on the table.' },
  { french: 'cheville', translation: 'лодыжка', translationEn: 'ankle', category: 'body', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3250, exampleFr: "Elle s'est tordu la cheville.", exampleRu: 'Она подвернула лодыжку.', exampleEn: 'She twisted her ankle.' },
  { french: 'joue', translation: 'щека', translationEn: 'cheek', category: 'body', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3260, exampleFr: "Il a les joues roses.", exampleRu: 'У него розовые щёки.', exampleEn: 'He has rosy cheeks.' },
  { french: 'sourcil', translation: 'бровь', translationEn: 'eyebrow', category: 'body', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3270, exampleFr: "Elle a les sourcils épais.", exampleRu: 'У неё густые брови.', exampleEn: 'She has thick eyebrows.' },
  { french: 'poignet', translation: 'запястье', translationEn: 'wrist', category: 'body', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3280, exampleFr: "Je porte un bracelet au poignet.", exampleRu: 'Я ношу браслет на запястье.', exampleEn: 'I wear a bracelet on my wrist.' },
  { french: 'nuque', translation: 'затылок, шея сзади', translationEn: 'nape of the neck', category: 'body', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3290, exampleFr: "J'ai mal à la nuque.", exampleRu: 'У меня болит затылок.', exampleEn: 'I have a pain in my neck.' },

  // ===== LOGEMENT (compléments) =====
  { french: 'balcon', translation: 'балкон', translationEn: 'balcony', category: 'home', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3300, exampleFr: "Je bois mon café sur le balcon.", exampleRu: 'Я пью кофе на балконе.', exampleEn: 'I drink my coffee on the balcony.' },
  { french: 'ascenseur', translation: 'лифт', translationEn: 'elevator, lift', category: 'home', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3310, exampleFr: "L'ascenseur est en panne.", exampleRu: 'Лифт не работает.', exampleEn: 'The elevator is out of order.' },
  { french: 'escalier', translation: 'лестница', translationEn: 'staircase, stairs', category: 'home', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3320, exampleFr: "Il monte les escaliers.", exampleRu: 'Он поднимается по лестнице.', exampleEn: 'He goes up the stairs.' },
  { french: 'boîte aux lettres', translation: 'почтовый ящик', translationEn: 'mailbox', category: 'home', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3330, exampleFr: "Il y a du courrier dans la boîte aux lettres.", exampleRu: 'В почтовом ящике есть письма.', exampleEn: 'There is mail in the mailbox.' },
  { french: 'sonnette', translation: 'дверной звонок', translationEn: 'doorbell', category: 'home', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3340, exampleFr: "On a sonné à la porte.", exampleRu: 'Кто-то позвонил в дверь.', exampleEn: 'Someone rang the doorbell.' },

  // ===== ÉMOTIONS =====
  { french: 'anxieux', translation: 'тревожный, беспокойный', translationEn: 'anxious', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3350, exampleFr: "Je suis anxieux avant l'examen.", exampleRu: 'Я тревожен перед экзаменом.', exampleEn: 'I am anxious before the exam.' },
  { french: 'enthousiaste', translation: 'энтузиастичный, воодушевлённый', translationEn: 'enthusiastic', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3360, exampleFr: "Elle est très enthousiaste.", exampleRu: 'Она очень воодушевлена.', exampleEn: 'She is very enthusiastic.' },
  { french: 'nostalgique', translation: 'ностальгирующий', translationEn: 'nostalgic', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3370, exampleFr: "Cette musique me rend nostalgique.", exampleRu: 'Эта музыка вызывает у меня ностальгию.', exampleEn: 'This music makes me nostalgic.' },
  { french: 'déçu', translation: 'разочарованный', translationEn: 'disappointed', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3380, exampleFr: "Je suis très déçu.", exampleRu: 'Я очень разочарован.', exampleEn: 'I am very disappointed.' },
  { french: 'soulagé', translation: 'облегчённый (чувствующий облегчение)', translationEn: 'relieved', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3390, exampleFr: "Je suis soulagé que tout soit fini.", exampleRu: 'Я рад, что всё закончилось.', exampleEn: 'I am relieved that it is all over.' },
  { french: 'jaloux', translation: 'ревнивый, завистливый', translationEn: 'jealous', category: 'emotions', partOfSpeech: 'adjective', frequencyRank: 3400, exampleFr: "Il est jaloux de son succès.", exampleRu: 'Он завидует его успеху.', exampleEn: 'He is jealous of his success.' },
  { french: 'émotion', translation: 'эмоция, волнение', translationEn: 'emotion', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3410, exampleFr: "Il cache ses émotions.", exampleRu: 'Он скрывает свои эмоции.', exampleEn: 'He hides his emotions.' },
  { french: 'joie', translation: 'радость', translationEn: 'joy', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3420, exampleFr: "Quelle joie de te voir !", exampleRu: 'Как радостно тебя видеть!', exampleEn: 'What a joy to see you!' },
  { french: 'tristesse', translation: 'грусть, печаль', translationEn: 'sadness', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3430, exampleFr: "Sa tristesse me touche.", exampleRu: 'Его грусть меня трогает.', exampleEn: 'His sadness touches me.' },
  { french: 'peur', translation: 'страх', translationEn: 'fear', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3440, exampleFr: "J'ai peur du noir.", exampleRu: 'Я боюсь темноты.', exampleEn: 'I am afraid of the dark.' },
  { french: 'surprise', translation: 'удивление, сюрприз', translationEn: 'surprise', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3450, exampleFr: "Quelle bonne surprise !", exampleRu: 'Какой приятный сюрприз!', exampleEn: 'What a nice surprise!' },
  { french: 'honte', translation: 'стыд', translationEn: 'shame', category: 'emotions', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3460, exampleFr: "J'ai honte de moi.", exampleRu: 'Мне стыдно за себя.', exampleEn: 'I am ashamed of myself.' },

  // ===== TEMPS / EXPRESSIONS =====
  { french: 'siècle', translation: 'век, столетие', translationEn: 'century', category: 'time', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3470, exampleFr: "Au vingt et unième siècle.", exampleRu: 'В двадцать первом веке.', exampleEn: 'In the twenty-first century.' },
  { french: 'époque', translation: 'эпоха, время', translationEn: 'era, epoch', category: 'time', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3480, exampleFr: "À cette époque, tout était différent.", exampleRu: 'В ту эпоху всё было иначе.', exampleEn: 'At that time, everything was different.' },
  { french: 'délai', translation: 'срок, задержка', translationEn: 'deadline, delay', category: 'time', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3490, exampleFr: "Respectez le délai.", exampleRu: 'Соблюдайте срок.', exampleEn: 'Respect the deadline.' },
  { french: 'durée', translation: 'длительность, продолжительность', translationEn: 'duration', category: 'time', partOfSpeech: 'noun', gender: 'f', frequencyRank: 3500, exampleFr: "La durée du film est deux heures.", exampleRu: 'Продолжительность фильма два часа.', exampleEn: 'The duration of the film is two hours.' },
  { french: 'agenda', translation: 'ежедневник, повестка дня', translationEn: 'diary, agenda', category: 'time', partOfSpeech: 'noun', gender: 'm', frequencyRank: 3510, exampleFr: "Je note ça dans mon agenda.", exampleRu: 'Я записываю это в ежедневник.', exampleEn: 'I note that in my diary.' },
];
