import { NewWord } from '../schema.js'

export const wordsB1Extra7: Omit<NewWord, 'id' | 'createdAt' | 'isActive' | 'audioUrl' | 'imageUrl' | 'imageGenerating'>[] = [
  // arts_literature
  { french: 'le roman', translation: 'роман (книга)', translationEn: 'novel', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 320, exampleFr: 'Elle a écrit un roman policier.', exampleRu: 'Она написала детективный роман.', exampleEn: 'She wrote a detective novel.' },
  { french: 'le personnage', translation: 'персонаж, герой', translationEn: 'character', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 330, exampleFr: 'Le personnage principal est très attachant.', exampleRu: 'Главный персонаж очень привлекательный.', exampleEn: 'The main character is very endearing.' },
  { french: 'l\'intrigue', translation: 'сюжет, интрига', translationEn: 'plot, intrigue', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 400, exampleFr: 'L\'intrigue du film est passionnante.', exampleRu: 'Сюжет фильма захватывающий.', exampleEn: 'The plot of the film is gripping.' },
  { french: 'le scénario', translation: 'сценарий', translationEn: 'script, screenplay', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 390, exampleFr: 'Le scénario a été écrit par le réalisateur.', exampleRu: 'Сценарий написан режиссёром.', exampleEn: 'The screenplay was written by the director.' },
  { french: 'le réalisateur', translation: 'режиссёр', translationEn: 'director', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 380, exampleFr: 'C\'est un grand réalisateur de cinéma.', exampleRu: 'Это великий кинорежиссёр.', exampleEn: 'He is a great film director.' },
  { french: 'le tournage', translation: 'съёмка фильма', translationEn: 'filming, shooting', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 430, exampleFr: 'Le tournage du film a duré six mois.', exampleRu: 'Съёмки фильма длились шесть месяцев.', exampleEn: 'The filming of the movie lasted six months.' },
  { french: 'l\'exposition', translation: 'выставка, экспозиция', translationEn: 'exhibition', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 370, exampleFr: 'J\'ai visité une exposition de photographie.', exampleRu: 'Я посетил фотовыставку.', exampleEn: 'I visited a photography exhibition.' },
  { french: 'la galerie', translation: 'галерея', translationEn: 'gallery', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 390, exampleFr: 'Cette galerie expose des artistes contemporains.', exampleRu: 'В этой галерее выставляются современные художники.', exampleEn: 'This gallery exhibits contemporary artists.' },
  { french: 'le chef-d\'œuvre', translation: 'шедевр', translationEn: 'masterpiece', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 440, exampleFr: 'La Joconde est un chef-d\'œuvre absolu.', exampleRu: 'Мона Лиза — абсолютный шедевр.', exampleEn: 'The Mona Lisa is an absolute masterpiece.' },
  { french: 'l\'auteur', translation: 'автор', translationEn: 'author', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 310, exampleFr: 'Qui est l\'auteur de ce livre?', exampleRu: 'Кто автор этой книги?', exampleEn: 'Who is the author of this book?' },
  { french: 'le compositeur', translation: 'композитор', translationEn: 'composer', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 450, exampleFr: 'Mozart est un compositeur de génie.', exampleRu: 'Моцарт — гениальный композитор.', exampleEn: 'Mozart is a genius composer.' },
  { french: 'la nouvelle', translation: 'рассказ, новелла', translationEn: 'short story', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 370, exampleFr: 'Elle a publié un recueil de nouvelles.', exampleRu: 'Она опубликовала сборник рассказов.', exampleEn: 'She published a collection of short stories.' },
  { french: 'la biographie', translation: 'биография', translationEn: 'biography', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 420, exampleFr: 'Il lit une biographie de Napoléon.', exampleRu: 'Он читает биографию Наполеона.', exampleEn: 'He is reading a biography of Napoleon.' },
  { french: 'le style', translation: 'стиль', translationEn: 'style', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 310, exampleFr: 'Il a un style d\'écriture très original.', exampleRu: 'У него очень оригинальный стиль письма.', exampleEn: 'He has a very original writing style.' },
  { french: 'la créativité', translation: 'творчество, креативность', translationEn: 'creativity', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 450, exampleFr: 'La créativité est essentielle dans l\'art.', exampleRu: 'Творчество необходимо в искусстве.', exampleEn: 'Creativity is essential in art.' },
  { french: 'l\'inspiration', translation: 'вдохновение', translationEn: 'inspiration', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 430, exampleFr: 'Il trouve son inspiration dans la nature.', exampleRu: 'Он черпает вдохновение в природе.', exampleEn: 'He finds his inspiration in nature.' },
  { french: 'le patrimoine', translation: 'наследие, достояние', translationEn: 'heritage, patrimony', category: 'arts_literature', partOfSpeech: 'noun', gender: 'm', frequencyRank: 400, exampleFr: 'Ce monument fait partie du patrimoine national.', exampleRu: 'Этот памятник является частью национального достояния.', exampleEn: 'This monument is part of the national heritage.' },
  { french: 'la collection', translation: 'коллекция', translationEn: 'collection', category: 'arts_literature', partOfSpeech: 'noun', gender: 'f', frequencyRank: 360, exampleFr: 'Le musée possède une riche collection de tableaux.', exampleRu: 'В музее хранится богатая коллекция картин.', exampleEn: 'The museum has a rich collection of paintings.' },
  { french: 'interpréter', translation: 'интерпретировать, исполнять', translationEn: 'to interpret, to perform', category: 'arts_literature', partOfSpeech: 'verb', gender: null, frequencyRank: 400, exampleFr: 'Elle interprète le rôle principal dans cette pièce.', exampleRu: 'Она исполняет главную роль в этой пьесе.', exampleEn: 'She plays the lead role in this play.' },
  { french: 'critiquer', translation: 'критиковать, рецензировать', translationEn: 'to criticise, to review', category: 'arts_literature', partOfSpeech: 'verb', gender: null, frequencyRank: 390, exampleFr: 'Les critiques ont bien apprécié ce film.', exampleRu: 'Критики высоко оценили этот фильм.', exampleEn: 'Critics appreciated this film very much.' },

  // culture_b1
  { french: 'la tendance', translation: 'тенденция, тренд', translationEn: 'trend, tendency', category: 'culture_b1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 360, exampleFr: 'La tendance est au minimalisme.', exampleRu: 'Тенденция направлена к минимализму.', exampleEn: 'The trend is towards minimalism.' },
  { french: 'le mouvement', translation: 'движение, течение', translationEn: 'movement', category: 'culture_b1', partOfSpeech: 'noun', gender: 'm', frequencyRank: 300, exampleFr: 'L\'impressionnisme est un mouvement artistique.', exampleRu: 'Импрессионизм — художественное течение.', exampleEn: 'Impressionism is an artistic movement.' },
  { french: 'le festival', translation: 'фестиваль', translationEn: 'festival', category: 'culture_b1', partOfSpeech: 'noun', gender: 'm', frequencyRank: 370, exampleFr: 'Le festival de Cannes est très célèbre.', exampleRu: 'Каннский фестиваль очень известен.', exampleEn: 'The Cannes festival is very famous.' },
  { french: 'la cérémonie', translation: 'церемония', translationEn: 'ceremony', category: 'culture_b1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 380, exampleFr: 'La cérémonie de remise des prix a eu lieu hier.', exampleRu: 'Церемония вручения наград состоялась вчера.', exampleEn: 'The awards ceremony took place yesterday.' },
  { french: 'l\'œuvre', translation: 'произведение, труд', translationEn: 'work, artwork', category: 'culture_b1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 320, exampleFr: 'Cette œuvre d\'art est très appréciée.', exampleRu: 'Это произведение искусства очень ценится.', exampleEn: 'This artwork is highly appreciated.' },
  { french: 'la critique', translation: 'критика, рецензия', translationEn: 'review, criticism', category: 'culture_b1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 340, exampleFr: 'Le film a reçu des critiques très positives.', exampleRu: 'Фильм получил очень положительные отзывы.', exampleEn: 'The film received very positive reviews.' },
  { french: 'le symbole', translation: 'символ', translationEn: 'symbol', category: 'culture_b1', partOfSpeech: 'noun', gender: 'm', frequencyRank: 340, exampleFr: 'La Tour Eiffel est le symbole de Paris.', exampleRu: 'Эйфелева башня — символ Парижа.', exampleEn: 'The Eiffel Tower is the symbol of Paris.' },
  { french: 'la coutume', translation: 'обычай, обыкновение', translationEn: 'custom, tradition', category: 'culture_b1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 430, exampleFr: 'Chaque pays a ses propres coutumes.', exampleRu: 'У каждой страны есть свои обычаи.', exampleEn: 'Each country has its own customs.' },
  { french: 'l\'artiste', translation: 'художник, артист', translationEn: 'artist', category: 'culture_b1', partOfSpeech: 'noun', gender: 'm', frequencyRank: 330, exampleFr: 'Cet artiste expose ses œuvres à Paris.', exampleRu: 'Этот художник выставляет свои работы в Париже.', exampleEn: 'This artist exhibits his works in Paris.' },
  { french: 'symboliser', translation: 'символизировать', translationEn: 'to symbolise', category: 'culture_b1', partOfSpeech: 'verb', gender: null, frequencyRank: 480, exampleFr: 'La colombe symbolise la paix.', exampleRu: 'Голубь символизирует мир.', exampleEn: 'The dove symbolises peace.' },
  { french: 'valoriser', translation: 'ценить, повышать ценность', translationEn: 'to value, to enhance', category: 'culture_b1', partOfSpeech: 'verb', gender: null, frequencyRank: 490, exampleFr: 'Il faut valoriser le patrimoine culturel.', exampleRu: 'Нужно ценить культурное наследие.', exampleEn: 'Cultural heritage must be valued.' },
  { french: 'illustrer', translation: 'иллюстрировать', translationEn: 'to illustrate', category: 'culture_b1', partOfSpeech: 'verb', gender: null, frequencyRank: 430, exampleFr: 'Ce tableau illustre parfaitement l\'époque.', exampleRu: 'Эта картина прекрасно иллюстрирует эпоху.', exampleEn: 'This painting perfectly illustrates the era.' },
]
