export const wordsA1Extra4 = [
  // === WEATHER A1 ===
  { french: 'sec', translation: 'сухой', translationEn: 'dry', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1100, exampleFr: 'Le temps est sec aujourd\'hui.', exampleRu: 'Сегодня сухая погода.', exampleEn: 'The weather is dry today.' },
  { french: 'couvert', translation: 'пасмурный', translationEn: 'overcast', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1110, exampleFr: 'Le ciel est couvert ce matin.', exampleRu: 'Небо пасмурное этим утром.', exampleEn: 'The sky is overcast this morning.' },
  { french: 'brumeux', translation: 'туманный', translationEn: 'misty, foggy', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1120, exampleFr: 'Il fait brumeux en novembre.', exampleRu: 'В ноябре туманно.', exampleEn: 'It is misty in November.' },
  { french: 'ciel', translation: 'небо', translationEn: 'sky', category: 'weather_a1', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1130, exampleFr: 'Le ciel est bleu aujourd\'hui.', exampleRu: 'Сегодня голубое небо.', exampleEn: 'The sky is blue today.' },
  { french: 'chaleur', translation: 'жара, тепло', translationEn: 'heat, warmth', category: 'weather_a1', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1140, exampleFr: 'La chaleur est forte en été.', exampleRu: 'Летом стоит сильная жара.', exampleEn: 'The heat is intense in summer.' },
  { french: 'neigeux', translation: 'снежный', translationEn: 'snowy', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1150, exampleFr: 'La montagne est neigeuse en hiver.', exampleRu: 'Зимой горы снежные.', exampleEn: 'The mountain is snowy in winter.' },
  { french: 'venteux', translation: 'ветреный', translationEn: 'windy', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1160, exampleFr: 'C\'est une journée venteuse.', exampleRu: 'Сегодня ветреный день.', exampleEn: 'It is a windy day.' },
  { french: 'orageux', translation: 'грозовой, бурный', translationEn: 'stormy, thundery', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1170, exampleFr: 'Le temps est orageux ce soir.', exampleRu: 'Сегодня вечером грозовая погода.', exampleEn: 'The weather is stormy tonight.' },
  { french: 'pluvieux', translation: 'дождливый', translationEn: 'rainy', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1180, exampleFr: 'Novembre est très pluvieux.', exampleRu: 'Ноябрь очень дождливый.', exampleEn: 'November is very rainy.' },
  { french: 'frais', translation: 'прохладный, свежий', translationEn: 'cool, fresh', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1190, exampleFr: 'Il fait frais le matin.', exampleRu: 'По утрам прохладно.', exampleEn: 'It is cool in the morning.' },
  { french: 'humide', translation: 'влажный', translationEn: 'humid, damp', category: 'weather_a1', partOfSpeech: 'adjective', frequencyRank: 1200, exampleFr: 'Le temps est chaud et humide.', exampleRu: 'Погода жаркая и влажная.', exampleEn: 'The weather is hot and humid.' },

  // === EXTRA COLORS ===
  { french: 'bordeaux', translation: 'бордовый', translationEn: 'burgundy, dark red', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1210, exampleFr: 'Elle porte une robe bordeaux.', exampleRu: 'Она носит бордовое платье.', exampleEn: 'She is wearing a burgundy dress.' },
  { french: 'beige', translation: 'бежевый', translationEn: 'beige', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1220, exampleFr: 'Les murs sont de couleur beige.', exampleRu: 'Стены бежевого цвета.', exampleEn: 'The walls are beige.' },
  { french: 'doré', translation: 'золотистый, золотой', translationEn: 'golden, gold-colored', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1230, exampleFr: 'Ses cheveux sont dorés.', exampleRu: 'Её волосы золотистые.', exampleEn: 'Her hair is golden.' },
  { french: 'argenté', translation: 'серебристый', translationEn: 'silver, silvery', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1240, exampleFr: 'La voiture est de couleur argentée.', exampleRu: 'Машина серебристого цвета.', exampleEn: 'The car is silver-colored.' },
  { french: 'clair', translation: 'светлый', translationEn: 'light (in color)', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1250, exampleFr: 'Il préfère les couleurs claires.', exampleRu: 'Он предпочитает светлые цвета.', exampleEn: 'He prefers light colors.' },
  { french: 'foncé', translation: 'тёмный', translationEn: 'dark (in color)', category: 'colors_extra', partOfSpeech: 'adjective', frequencyRank: 1260, exampleFr: 'Elle aime le bleu foncé.', exampleRu: 'Она любит тёмно-синий.', exampleEn: 'She likes dark blue.' },

  // === CLASSROOM ===
  { french: 'tableau', translation: 'доска (учебная)', translationEn: 'blackboard, whiteboard', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1270, exampleFr: 'Le professeur écrit au tableau.', exampleRu: 'Учитель пишет на доске.', exampleEn: 'The teacher writes on the board.' },
  { french: 'cahier', translation: 'тетрадь', translationEn: 'notebook, exercise book', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1280, exampleFr: 'J\'écris les mots dans mon cahier.', exampleRu: 'Я записываю слова в тетрадь.', exampleEn: 'I write words in my notebook.' },
  { french: 'règle', translation: 'линейка, правило', translationEn: 'ruler, rule', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1290, exampleFr: 'Je trace une ligne avec la règle.', exampleRu: 'Я провожу линию линейкой.', exampleEn: 'I draw a line with the ruler.' },
  { french: 'gomme', translation: 'ластик', translationEn: 'eraser, rubber', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1300, exampleFr: 'J\'efface mon erreur avec la gomme.', exampleRu: 'Я стираю ошибку ластиком.', exampleEn: 'I erase my mistake with the rubber.' },
  { french: 'cartable', translation: 'школьный ранец, портфель', translationEn: 'school bag, satchel', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1310, exampleFr: 'Mon cartable est très lourd.', exampleRu: 'Мой школьный ранец очень тяжёлый.', exampleEn: 'My school bag is very heavy.' },
  { french: 'trousse', translation: 'пенал', translationEn: 'pencil case', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1320, exampleFr: 'Ma trousse contient des stylos et des crayons.', exampleRu: 'В моём пенале есть ручки и карандаши.', exampleEn: 'My pencil case contains pens and pencils.' },
  { french: 'crayon', translation: 'карандаш', translationEn: 'pencil', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1330, exampleFr: 'Je dessine avec un crayon de couleur.', exampleRu: 'Я рисую цветным карандашом.', exampleEn: 'I draw with a colored pencil.' },
  { french: 'colle', translation: 'клей', translationEn: 'glue', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1340, exampleFr: 'Je colle les images avec de la colle.', exampleRu: 'Я приклеиваю картинки клеем.', exampleEn: 'I stick the pictures with glue.' },
  { french: 'ciseaux', translation: 'ножницы', translationEn: 'scissors', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1350, exampleFr: 'Je coupe le papier avec les ciseaux.', exampleRu: 'Я режу бумагу ножницами.', exampleEn: 'I cut the paper with scissors.' },
  { french: 'feuille', translation: 'лист (бумаги)', translationEn: 'sheet of paper, leaf', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1360, exampleFr: 'Prenez une feuille blanche, s\'il vous plaît.', exampleRu: 'Возьмите, пожалуйста, чистый листок.', exampleEn: 'Please take a blank sheet of paper.' },
  { french: 'pupitre', translation: 'парта, пюпитр', translationEn: 'school desk', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1370, exampleFr: 'Asseyez-vous à votre pupitre.', exampleRu: 'Садитесь за парту.', exampleEn: 'Sit at your desk.' },
  { french: 'ardoise', translation: 'грифельная доска', translationEn: 'slate board, chalkboard', category: 'classroom', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1380, exampleFr: 'L\'enfant écrit sur l\'ardoise.', exampleRu: 'Ребёнок пишет на грифельной доске.', exampleEn: 'The child writes on the slate.' },
  { french: 'marqueur', translation: 'маркер', translationEn: 'marker, felt-tip pen', category: 'classroom', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1390, exampleFr: 'Le professeur utilise un marqueur rouge.', exampleRu: 'Учитель использует красный маркер.', exampleEn: 'The teacher uses a red marker.' },

  // === QUESTION WORDS EXTRA ===
  { french: 'quel', translation: 'какой, который', translationEn: 'which, what (adjective)', category: 'question_words_extra', partOfSpeech: 'adjective', frequencyRank: 1400, exampleFr: 'Quel âge avez-vous ?', exampleRu: 'Сколько вам лет?', exampleEn: 'How old are you?' },
  { french: 'lequel', translation: 'который из, какой из', translationEn: 'which one', category: 'question_words_extra', partOfSpeech: 'pronoun', frequencyRank: 1410, exampleFr: 'Lequel préférez-vous ?', exampleRu: 'Который из них вы предпочитаете?', exampleEn: 'Which one do you prefer?' },
  { french: 'est-ce que', translation: 'вопросительная частица', translationEn: 'question marker (do/does/is)', category: 'question_words_extra', partOfSpeech: 'particle', frequencyRank: 1420, exampleFr: 'Est-ce que tu parles français ?', exampleRu: 'Ты говоришь по-французски?', exampleEn: 'Do you speak French?' },
  { french: 'qu\'est-ce que', translation: 'что (такое)', translationEn: 'what (is it that)', category: 'question_words_extra', partOfSpeech: 'pronoun', frequencyRank: 1430, exampleFr: 'Qu\'est-ce que c\'est ?', exampleRu: 'Что это такое?', exampleEn: 'What is this?' },
  { french: 'depuis quand', translation: 'с каких пор, с какого времени', translationEn: 'since when, how long', category: 'question_words_extra', partOfSpeech: 'adverb', frequencyRank: 1440, exampleFr: 'Depuis quand apprenez-vous le français ?', exampleRu: 'С каких пор вы учите французский?', exampleEn: 'Since when have you been learning French?' },

  // === GREETINGS EXTRA ===
  { french: 'enchanté', translation: 'рад познакомиться', translationEn: 'pleased to meet you', category: 'greetings_extra', partOfSpeech: 'adjective', frequencyRank: 1450, exampleFr: 'Enchanté de faire votre connaissance !', exampleRu: 'Очень рад с вами познакомиться!', exampleEn: 'Pleased to meet you!' },
  { french: 'bienvenue', translation: 'добро пожаловать', translationEn: 'welcome', category: 'greetings_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1460, exampleFr: 'Bienvenue en France !', exampleRu: 'Добро пожаловать во Францию!', exampleEn: 'Welcome to France!' },
  { french: 'félicitations', translation: 'поздравления', translationEn: 'congratulations', category: 'greetings_extra', partOfSpeech: 'noun', frequencyRank: 1470, exampleFr: 'Félicitations pour ton succès !', exampleRu: 'Поздравляю с успехом!', exampleEn: 'Congratulations on your success!' },
];
