export const wordsB2Extra8 = [
  // Technologie numérique avancée
  { french: 'l\'algorithme', translation: 'алгоритм', translationEn: 'algorithm', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'algorithme de recommandation analyse vos préférences.', exampleRu: 'Алгоритм рекомендаций анализирует ваши предпочтения.', exampleEn: 'The recommendation algorithm analyzes your preferences.' },
  { french: 'l\'intelligence artificielle', translation: 'искусственный интеллект', translationEn: 'artificial intelligence', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'intelligence artificielle transforme de nombreux secteurs.', exampleRu: 'Искусственный интеллект трансформирует многие отрасли.', exampleEn: 'Artificial intelligence is transforming many sectors.' },
  { french: 'l\'apprentissage automatique', translation: 'машинное обучение', translationEn: 'machine learning', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'apprentissage automatique améliore les prédictions.', exampleRu: 'Машинное обучение улучшает прогнозы.', exampleEn: 'Machine learning improves predictions.' },
  { french: 'le réseau neuronal', translation: 'нейронная сеть', translationEn: 'neural network', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les réseaux neuronaux imitent le cerveau humain.', exampleRu: 'Нейронные сети имитируют человеческий мозг.', exampleEn: 'Neural networks imitate the human brain.' },
  { french: 'le traitement des données', translation: 'обработка данных', translationEn: 'data processing', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le traitement des données massives pose des défis éthiques.', exampleRu: 'Обработка больших данных ставит этические вызовы.', exampleEn: 'Processing massive data poses ethical challenges.' },
  { french: 'le mégadonnées', translation: 'большие данные', translationEn: 'big data', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les mégadonnées permettent des analyses prédictives.', exampleRu: 'Большие данные позволяют делать предиктивные анализы.', exampleEn: 'Big data enables predictive analysis.' },
  { french: 'le cloud computing', translation: 'облачные вычисления', translationEn: 'cloud computing', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le cloud computing réduit les coûts d\'infrastructure.', exampleRu: 'Облачные вычисления снижают затраты на инфраструктуру.', exampleEn: 'Cloud computing reduces infrastructure costs.' },
  { french: 'la cybersécurité', translation: 'кибербезопасность', translationEn: 'cybersecurity', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La cybersécurité est devenue une priorité nationale.', exampleRu: 'Кибербезопасность стала национальным приоритетом.', exampleEn: 'Cybersecurity has become a national priority.' },
  { french: 'le piratage informatique', translation: 'компьютерный взлом; хакерство', translationEn: 'hacking', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le piratage informatique coûte des milliards aux entreprises.', exampleRu: 'Компьютерный взлом обходится компаниям в миллиарды.', exampleEn: 'Hacking costs companies billions.' },
  { french: 'la blockchain', translation: 'блокчейн', translationEn: 'blockchain', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La blockchain assure la traçabilité des transactions.', exampleRu: 'Блокчейн обеспечивает прослеживаемость транзакций.', exampleEn: 'Blockchain ensures transaction traceability.' },
  { french: 'la cryptomonnaie', translation: 'криптовалюта', translationEn: 'cryptocurrency', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Le Bitcoin est la cryptomonnaie la plus connue.', exampleRu: 'Биткоин — самая известная криптовалюта.', exampleEn: 'Bitcoin is the best-known cryptocurrency.' },
  { french: 'l\'internet des objets', translation: 'интернет вещей', translationEn: 'Internet of Things (IoT)', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'internet des objets connecte des milliards d\'appareils.', exampleRu: 'Интернет вещей соединяет миллиарды устройств.', exampleEn: 'The Internet of Things connects billions of devices.' },
  { french: 'la réalité virtuelle', translation: 'виртуальная реальность', translationEn: 'virtual reality', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La réalité virtuelle révolutionne les jeux vidéo.', exampleRu: 'Виртуальная реальность революционизирует видеоигры.', exampleEn: 'Virtual reality is revolutionizing video games.' },
  { french: 'la réalité augmentée', translation: 'дополненная реальность', translationEn: 'augmented reality', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La réalité augmentée superpose le numérique au réel.', exampleRu: 'Дополненная реальность накладывает цифровое на реальное.', exampleEn: 'Augmented reality overlays digital onto reality.' },
  { french: 'l\'automatisation', translation: 'автоматизация', translationEn: 'automation', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'automatisation menace certains emplois répétitifs.', exampleRu: 'Автоматизация угрожает некоторым однообразным профессиям.', exampleEn: 'Automation threatens some repetitive jobs.' },
  { french: 'la robotique', translation: 'робототехника', translationEn: 'robotics', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La robotique chirurgicale améliore la précision.', exampleRu: 'Хирургическая робототехника повышает точность.', exampleEn: 'Surgical robotics improves precision.' },

  // Données et vie privée
  { french: 'les données personnelles', translation: 'персональные данные', translationEn: 'personal data', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Le RGPD protège les données personnelles des citoyens.', exampleRu: 'GDPR защищает персональные данные граждан.', exampleEn: 'GDPR protects citizens\' personal data.' },
  { french: 'la vie privée numérique', translation: 'цифровая конфиденциальность', translationEn: 'digital privacy', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La vie privée numérique est de plus en plus menacée.', exampleRu: 'Цифровая конфиденциальность всё больше находится под угрозой.', exampleEn: 'Digital privacy is increasingly threatened.' },
  { french: 'la surveillance numérique', translation: 'цифровая слежка', translationEn: 'digital surveillance', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La surveillance numérique pose des questions éthiques.', exampleRu: 'Цифровая слежка ставит этические вопросы.', exampleEn: 'Digital surveillance raises ethical questions.' },
  { french: 'l\'empreinte numérique', translation: 'цифровой след', translationEn: 'digital footprint', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Chaque clic laisse une empreinte numérique.', exampleRu: 'Каждый клик оставляет цифровой след.', exampleEn: 'Every click leaves a digital footprint.' },
  { french: 'la désinformation', translation: 'дезинформация', translationEn: 'disinformation', category: 'media', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La désinformation se propage rapidement sur les réseaux sociaux.', exampleRu: 'Дезинформация быстро распространяется в социальных сетях.', exampleEn: 'Disinformation spreads rapidly on social media.' },
  { french: 'la bulle de filtre', translation: 'информационный пузырь', translationEn: 'filter bubble', category: 'media', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les algorithmes créent des bulles de filtre idéologique.', exampleRu: 'Алгоритмы создают идеологические информационные пузыри.', exampleEn: 'Algorithms create ideological filter bubbles.' },
  { french: 'les fake news', translation: 'фейк-ньюс; ложные новости', translationEn: 'fake news', category: 'media', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les fake news influencent les opinions politiques.', exampleRu: 'Фейк-ньюс влияют на политические мнения.', exampleEn: 'Fake news influences political opinions.' },

  // Transition numérique et industrie
  { french: 'la transformation numérique', translation: 'цифровая трансформация', translationEn: 'digital transformation', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La transformation numérique touche tous les secteurs.', exampleRu: 'Цифровая трансформация затрагивает все отрасли.', exampleEn: 'Digital transformation touches all sectors.' },
  { french: 'l\'industrie 4.0', translation: 'индустрия 4.0', translationEn: 'Industry 4.0', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'industrie 4.0 intègre robots, IA et IoT.', exampleRu: 'Индустрия 4.0 интегрирует роботов, ИИ и IoT.', exampleEn: 'Industry 4.0 integrates robots, AI and IoT.' },
  { french: 'la numérisation', translation: 'оцифровка; цифровизация', translationEn: 'digitization', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La numérisation des archives historiques est en cours.', exampleRu: 'Оцифровка исторических архивов продолжается.', exampleEn: 'The digitization of historical archives is underway.' },
  { french: 'l\'interface', translation: 'интерфейс', translationEn: 'interface', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'interface utilisateur doit être intuitive.', exampleRu: 'Пользовательский интерфейс должен быть интуитивным.', exampleEn: 'The user interface must be intuitive.' },
  { french: 'le logiciel', translation: 'программное обеспечение', translationEn: 'software', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Ce logiciel open source est gratuit.', exampleRu: 'Это программное обеспечение с открытым исходным кодом бесплатное.', exampleEn: 'This open source software is free.' },
  { french: 'le matériel informatique', translation: 'компьютерное оборудование', translationEn: 'computer hardware', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le matériel informatique est devenu plus abordable.', exampleRu: 'Компьютерное оборудование стало более доступным.', exampleEn: 'Computer hardware has become more affordable.' },
  { french: 'le protocole', translation: 'протокол', translationEn: 'protocol', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le protocole HTTPS sécurise les échanges web.', exampleRu: 'Протокол HTTPS защищает веб-обмены.', exampleEn: 'The HTTPS protocol secures web exchanges.' },

  // Énergie et innovation
  { french: 'les énergies renouvelables', translation: 'возобновляемые источники энергии', translationEn: 'renewable energies', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les énergies renouvelables remplacent peu à peu le charbon.', exampleRu: 'Возобновляемые источники энергии постепенно вытесняют уголь.', exampleEn: 'Renewable energies are gradually replacing coal.' },
  { french: 'l\'hydrogène vert', translation: 'зелёный водород', translationEn: 'green hydrogen', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'hydrogène vert est un carburant du futur.', exampleRu: 'Зелёный водород — топливо будущего.', exampleEn: 'Green hydrogen is a fuel of the future.' },
  { french: 'la transition énergétique', translation: 'энергетический переход', translationEn: 'energy transition', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La transition énergétique requiert des investissements massifs.', exampleRu: 'Энергетический переход требует массивных инвестиций.', exampleEn: 'The energy transition requires massive investments.' },
  { french: 'le stockage d\'énergie', translation: 'накопление энергии', translationEn: 'energy storage', category: 'technology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le stockage d\'énergie reste un défi technique.', exampleRu: 'Накопление энергии остаётся техническим вызовом.', exampleEn: 'Energy storage remains a technical challenge.' },
  { french: 'la voiture électrique', translation: 'электромобиль', translationEn: 'electric car', category: 'technology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La voiture électrique représente l\'avenir de la mobilité.', exampleRu: 'Электромобиль представляет будущее мобильности.', exampleEn: 'The electric car represents the future of mobility.' },

  // Verbes technologiques
  { french: 'numériser', translation: 'оцифровывать', translationEn: 'to digitize', category: 'technology', partOfSpeech: 'verb', exampleFr: 'Il faut numériser tous les documents papier.', exampleRu: 'Необходимо оцифровать все бумажные документы.', exampleEn: 'All paper documents need to be digitized.' },
  { french: 'crypter', translation: 'шифровать', translationEn: 'to encrypt', category: 'technology', partOfSpeech: 'verb', exampleFr: 'Les messages sont cryptés pour protéger la vie privée.', exampleRu: 'Сообщения шифруются для защиты конфиденциальности.', exampleEn: 'Messages are encrypted to protect privacy.' },
  { french: 'pirater', translation: 'взламывать; хакерствовать', translationEn: 'to hack', category: 'technology', partOfSpeech: 'verb', exampleFr: 'Des hackers ont piraté le système informatique.', exampleRu: 'Хакеры взломали компьютерную систему.', exampleEn: 'Hackers hacked into the computer system.' },
  { french: 'programmer', translation: 'программировать', translationEn: 'to program; to code', category: 'technology', partOfSpeech: 'verb', exampleFr: 'Il a appris à programmer en Python.', exampleRu: 'Он научился программировать на Python.', exampleEn: 'He learned to program in Python.' },
  { french: 'automatiser', translation: 'автоматизировать', translationEn: 'to automate', category: 'technology', partOfSpeech: 'verb', exampleFr: 'L\'usine a automatisé sa chaîne de production.', exampleRu: 'Завод автоматизировал свою производственную линию.', exampleEn: 'The factory automated its production line.' },

  // Adjectifs technologiques
  { french: 'innovant', translation: 'инновационный', translationEn: 'innovative', category: 'technology', partOfSpeech: 'adjective', exampleFr: 'C\'est une solution vraiment innovante.', exampleRu: 'Это действительно инновационное решение.', exampleEn: 'It is a truly innovative solution.' },
  { french: 'connecté', translation: 'подключённый; умный (о технике)', translationEn: 'connected; smart', category: 'technology', partOfSpeech: 'adjective', exampleFr: 'Les objets connectés envahissent nos maisons.', exampleRu: 'Умные устройства заполняют наши дома.', exampleEn: 'Connected objects are invading our homes.' },
  { french: 'obsolète', translation: 'устаревший', translationEn: 'obsolete', category: 'technology', partOfSpeech: 'adjective', exampleFr: 'Ce logiciel est devenu obsolète en quelques années.', exampleRu: 'Это программное обеспечение устарело за несколько лет.', exampleEn: 'This software became obsolete in a few years.' },
  { french: 'numérique', translation: 'цифровой', translationEn: 'digital', category: 'technology', partOfSpeech: 'adjective', exampleFr: 'La transformation numérique est inévitable.', exampleRu: 'Цифровая трансформация неизбежна.', exampleEn: 'The digital transformation is inevitable.' },
  { french: 'interactif', translation: 'интерактивный', translationEn: 'interactive', category: 'technology', partOfSpeech: 'adjective', exampleFr: 'Le musée propose des expositions interactives.', exampleRu: 'Музей предлагает интерактивные экспозиции.', exampleEn: 'The museum offers interactive exhibitions.' },
];
