export const wordsB2Extra15 = [
  // ── Biologie cellulaire ──
  {
    french: 'la mitose',
    translation: 'митоз',
    translationEn: 'mitosis',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 7000,
    exampleFr: 'La mitose permet à une cellule de se diviser en deux cellules identiques.',
    exampleRu: 'Митоз позволяет клетке разделиться на две идентичные клетки.',
    exampleEn: 'Mitosis allows a cell to divide into two identical cells.',
  },
  {
    french: 'la mutation génétique',
    translation: 'генетическая мутация',
    translationEn: 'genetic mutation',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'Certaines mutations génétiques sont à l\'origine de maladies héréditaires.',
    exampleRu: 'Некоторые генетические мутации являются причиной наследственных заболеваний.',
    exampleEn: 'Some genetic mutations cause hereditary diseases.',
  },
  {
    french: 'le clonage',
    translation: 'клонирование',
    translationEn: 'cloning',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le clonage thérapeutique soulève des questions éthiques complexes.',
    exampleRu: 'Терапевтическое клонирование поднимает сложные этические вопросы.',
    exampleEn: 'Therapeutic cloning raises complex ethical questions.',
  },
  {
    french: 'l\'organisme génétiquement modifié',
    translation: 'генетически модифицированный организм (ГМО)',
    translationEn: 'genetically modified organism (GMO)',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'La culture des OGM est très encadrée en Europe.',
    exampleRu: 'Выращивание ГМО жёстко регулируется в Европе.',
    exampleEn: 'The cultivation of GMOs is heavily regulated in Europe.',
  },
  {
    french: 'la chaîne alimentaire',
    translation: 'пищевая цепь',
    translationEn: 'food chain',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'La disparition d\'un maillon de la chaîne alimentaire peut tout déstabiliser.',
    exampleRu: 'Исчезновение звена пищевой цепи может дестабилизировать всю систему.',
    exampleEn: 'The disappearance of a link in the food chain can destabilise everything.',
  },
  {
    french: 'la pollinisation',
    translation: 'опыление',
    translationEn: 'pollination',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La pollinisation par les abeilles est essentielle à la production agricole.',
    exampleRu: 'Опыление пчёлами необходимо для сельскохозяйственного производства.',
    exampleEn: 'Pollination by bees is essential for agricultural production.',
  },
  {
    french: 'l\'espèce envahissante',
    translation: 'инвазивный вид',
    translationEn: 'invasive species',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6400,
    exampleFr: 'Les espèces envahissantes menacent la biodiversité locale.',
    exampleRu: 'Инвазивные виды угрожают местному биоразнообразию.',
    exampleEn: 'Invasive species threaten local biodiversity.',
  },
  {
    french: 'la sélection naturelle',
    translation: 'естественный отбор',
    translationEn: 'natural selection',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'Darwin a décrit la sélection naturelle comme moteur de l\'évolution.',
    exampleRu: 'Дарвин описал естественный отбор как движущую силу эволюции.',
    exampleEn: 'Darwin described natural selection as the engine of evolution.',
  },
  {
    french: 'l\'évolution',
    translation: 'эволюция',
    translationEn: 'evolution',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2600,
    exampleFr: 'La théorie de l\'évolution reste la base de la biologie moderne.',
    exampleRu: 'Теория эволюции остаётся основой современной биологии.',
    exampleEn: 'The theory of evolution remains the foundation of modern biology.',
  },
  {
    french: 'la photosynthèse',
    translation: 'фотосинтез',
    translationEn: 'photosynthesis',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'La photosynthèse convertit la lumière solaire en énergie chimique.',
    exampleRu: 'Фотосинтез преобразует солнечный свет в химическую энергию.',
    exampleEn: 'Photosynthesis converts sunlight into chemical energy.',
  },
  // ── Chimie ──
  {
    french: 'la réaction chimique',
    translation: 'химическая реакция',
    translationEn: 'chemical reaction',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'Une réaction chimique produit de nouvelles substances.',
    exampleRu: 'Химическая реакция образует новые вещества.',
    exampleEn: 'A chemical reaction produces new substances.',
  },
  {
    french: 'le catalyseur',
    translation: 'катализатор',
    translationEn: 'catalyst',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Le catalyseur accélère la réaction sans être consommé.',
    exampleRu: 'Катализатор ускоряет реакцию, не расходуясь при этом.',
    exampleEn: 'The catalyst speeds up the reaction without being consumed.',
  },
  {
    french: 'l\'oxydation',
    translation: 'окисление',
    translationEn: 'oxidation',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5900,
    exampleFr: 'La rouille est le résultat de l\'oxydation du fer au contact de l\'eau.',
    exampleRu: 'Ржавчина — результат окисления железа при контакте с водой.',
    exampleEn: 'Rust is the result of the oxidation of iron in contact with water.',
  },
  {
    french: 'l\'isotope',
    translation: 'изотоп',
    translationEn: 'isotope',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le carbone 14 est un isotope radioactif utilisé pour la datation.',
    exampleRu: 'Углерод-14 — радиоактивный изотоп, используемый для датировки.',
    exampleEn: 'Carbon-14 is a radioactive isotope used for dating.',
  },
  {
    french: 'la radioactivité',
    translation: 'радиоактивность',
    translationEn: 'radioactivity',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5300,
    exampleFr: 'Marie Curie a découvert la radioactivité à la fin du XIXe siècle.',
    exampleRu: 'Мария Кюри открыла радиоактивность в конце XIX века.',
    exampleEn: 'Marie Curie discovered radioactivity at the end of the 19th century.',
  },
  {
    french: 'la fission nucléaire',
    translation: 'ядерное деление',
    translationEn: 'nuclear fission',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La fission nucléaire libère une énergie considérable.',
    exampleRu: 'Ядерное деление высвобождает огромную энергию.',
    exampleEn: 'Nuclear fission releases considerable energy.',
  },
  {
    french: 'la fusion nucléaire',
    translation: 'ядерный синтез',
    translationEn: 'nuclear fusion',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5700,
    exampleFr: 'La fusion nucléaire pourrait fournir une énergie presque illimitée.',
    exampleRu: 'Ядерный синтез мог бы обеспечить практически неограниченную энергию.',
    exampleEn: 'Nuclear fusion could provide almost unlimited energy.',
  },
  {
    french: 'la molécule',
    translation: 'молекула',
    translationEn: 'molecule',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'L\'eau est composée de molécules H₂O.',
    exampleRu: 'Вода состоит из молекул H₂O.',
    exampleEn: 'Water is composed of H₂O molecules.',
  },
  {
    french: 'la liaison chimique',
    translation: 'химическая связь',
    translationEn: 'chemical bond',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'Les liaisons chimiques maintiennent les atomes ensemble dans une molécule.',
    exampleRu: 'Химические связи удерживают атомы вместе в молекуле.',
    exampleEn: 'Chemical bonds hold atoms together in a molecule.',
  },
  // ── Physique ──
  {
    french: 'la gravitation',
    translation: 'гравитация, тяготение',
    translationEn: 'gravitation',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'Newton a formulé la loi de la gravitation universelle.',
    exampleRu: 'Ньютон сформулировал закон всемирного тяготения.',
    exampleEn: 'Newton formulated the law of universal gravitation.',
  },
  {
    french: 'la mécanique quantique',
    translation: 'квантовая механика',
    translationEn: 'quantum mechanics',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5900,
    exampleFr: 'La mécanique quantique décrit le comportement des particules subatomiques.',
    exampleRu: 'Квантовая механика описывает поведение субатомных частиц.',
    exampleEn: 'Quantum mechanics describes the behaviour of subatomic particles.',
  },
  {
    french: 'la relativité',
    translation: 'теория относительности',
    translationEn: 'theory of relativity',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5100,
    exampleFr: 'La théorie de la relativité générale d\'Einstein a révolutionné la physique.',
    exampleRu: 'Общая теория относительности Эйнштейна произвела революцию в физике.',
    exampleEn: 'Einstein\'s general theory of relativity revolutionised physics.',
  },
  {
    french: 'la thermodynamique',
    translation: 'термодинамика',
    translationEn: 'thermodynamics',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6300,
    exampleFr: 'Le second principe de la thermodynamique énonce l\'irréversibilité des processus.',
    exampleRu: 'Второй закон термодинамики формулирует необратимость процессов.',
    exampleEn: 'The second law of thermodynamics states the irreversibility of processes.',
  },
  // ── Astronomie ──
  {
    french: 'l\'orbite',
    translation: 'орбита',
    translationEn: 'orbit',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4900,
    exampleFr: 'La Lune gravite sur une orbite elliptique autour de la Terre.',
    exampleRu: 'Луна обращается по эллиптической орбите вокруг Земли.',
    exampleEn: 'The Moon orbits the Earth on an elliptical orbit.',
  },
  {
    french: 'le trou noir',
    translation: 'чёрная дыра',
    translationEn: 'black hole',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'La première image d\'un trou noir a été capturée en 2019.',
    exampleRu: 'Первое изображение чёрной дыры было получено в 2019 году.',
    exampleEn: 'The first image of a black hole was captured in 2019.',
  },
  {
    french: 'la matière noire',
    translation: 'тёмная материя',
    translationEn: 'dark matter',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La matière noire représente environ vingt-cinq pour cent de l\'univers.',
    exampleRu: 'Тёмная материя составляет около двадцати пяти процентов вселенной.',
    exampleEn: 'Dark matter represents about twenty-five percent of the universe.',
  },
  {
    french: 'l\'exoplanète',
    translation: 'экзопланета',
    translationEn: 'exoplanet',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6800,
    exampleFr: 'Des milliers d\'exoplanètes ont été découvertes depuis les années 1990.',
    exampleRu: 'С 1990-х годов обнаружены тысячи экзопланет.',
    exampleEn: 'Thousands of exoplanets have been discovered since the 1990s.',
  },
  {
    french: 'la supernova',
    translation: 'сверхновая (звезда)',
    translationEn: 'supernova',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'Une supernova libère en quelques secondes plus d\'énergie qu\'une étoile en milliards d\'années.',
    exampleRu: 'Сверхновая за несколько секунд высвобождает больше энергии, чем звезда за миллиарды лет.',
    exampleEn: 'A supernova releases in seconds more energy than a star in billions of years.',
  },
  {
    french: 'la cosmologie',
    translation: 'космология',
    translationEn: 'cosmology',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La cosmologie étudie l\'origine et l\'évolution de l\'univers.',
    exampleRu: 'Космология изучает происхождение и эволюцию вселенной.',
    exampleEn: 'Cosmology studies the origin and evolution of the universe.',
  },
  {
    french: 'le Big Bang',
    translation: 'Большой взрыв',
    translationEn: 'Big Bang',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Le Big Bang a eu lieu il y a environ treize virgule huit milliards d\'années.',
    exampleRu: 'Большой взрыв произошёл около тринадцати целых восьми миллиардов лет назад.',
    exampleEn: 'The Big Bang occurred approximately 13.8 billion years ago.',
  },
  // ── Mathématiques ──
  {
    french: 'le théorème',
    translation: 'теорема',
    translationEn: 'theorem',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le théorème de Pythagore est l\'un des plus connus en mathématiques.',
    exampleRu: 'Теорема Пифагора — одна из самых известных в математике.',
    exampleEn: 'Pythagoras\'s theorem is one of the best-known in mathematics.',
  },
  {
    french: 'la probabilité',
    translation: 'вероятность',
    translationEn: 'probability',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4500,
    exampleFr: 'La probabilité d\'un événement est comprise entre 0 et 1.',
    exampleRu: 'Вероятность события находится между 0 и 1.',
    exampleEn: 'The probability of an event lies between 0 and 1.',
  },
  {
    french: 'la statistique',
    translation: 'статистика',
    translationEn: 'statistics',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'La statistique permet d\'analyser des données et d\'en tirer des conclusions.',
    exampleRu: 'Статистика позволяет анализировать данные и делать выводы.',
    exampleEn: 'Statistics allows data to be analysed and conclusions to be drawn.',
  },
  {
    french: 'le modèle mathématique',
    translation: 'математическая модель',
    translationEn: 'mathematical model',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5400,
    exampleFr: 'Le modèle mathématique prédit l\'évolution de l\'épidémie.',
    exampleRu: 'Математическая модель предсказывает развитие эпидемии.',
    exampleEn: 'The mathematical model predicts the progression of the epidemic.',
  },
  {
    french: 'l\'équation',
    translation: 'уравнение',
    translationEn: 'equation',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4300,
    exampleFr: 'L\'équation différentielle modélise des phénomènes en perpétuelle évolution.',
    exampleRu: 'Дифференциальное уравнение моделирует непрерывно изменяющиеся явления.',
    exampleEn: 'The differential equation models phenomena in perpetual change.',
  },
  {
    french: 'le neurone',
    translation: 'нейрон',
    translationEn: 'neuron',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Le cerveau humain contient environ quatre-vingt-six milliards de neurones.',
    exampleRu: 'Мозг человека содержит около восьмидесяти шести миллиардов нейронов.',
    exampleEn: 'The human brain contains approximately eighty-six billion neurons.',
  },
  {
    french: 'la synapse',
    translation: 'синапс',
    translationEn: 'synapse',
    category: 'science',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6700,
    exampleFr: 'Les synapses transmettent l\'influx nerveux d\'un neurone à l\'autre.',
    exampleRu: 'Синапсы передают нервный импульс от одного нейрона к другому.',
    exampleEn: 'Synapses transmit nerve impulses from one neuron to another.',
  },
];
