import type { NewWord } from './index.js';

export const wordsB2Extra3: Omit<NewWord, 'id' | 'createdAt'>[] = [
  // ── Verbes B2 niveau soutenu ──
  { french: 'aborder', translation: 'затрагивать, подходить, причаливать', translationEn: 'to approach, to broach, to address', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1700, exampleFr: 'Nous allons aborder un sujet délicat.', exampleRu: 'Мы собираемся затронуть деликатную тему.', exampleEn: 'We are going to address a sensitive topic.' },
  { french: 'accroître', translation: 'увеличивать, наращивать', translationEn: 'to increase, to augment, to grow', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1701, exampleFr: 'L\'objectif est d\'accroître la productivité.', exampleRu: 'Цель — увеличить производительность.', exampleEn: 'The goal is to increase productivity.' },
  { french: 'affirmer', translation: 'утверждать, заявлять', translationEn: 'to affirm, to assert, to claim', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1702, exampleFr: 'Il affirme avoir vu l\'accusé.', exampleRu: 'Он утверждает, что видел обвиняемого.', exampleEn: 'He claims to have seen the accused.' },
  { french: 'aggraver', translation: 'усугублять, ухудшать', translationEn: 'to worsen, to aggravate', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1703, exampleFr: 'Cette décision ne fera qu\'aggraver la situation.', exampleRu: 'Это решение только ухудшит ситуацию.', exampleEn: 'This decision will only worsen the situation.' },
  { french: 'anticiper', translation: 'предвидеть, предупреждать', translationEn: 'to anticipate, to foresee', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1704, exampleFr: 'Il faut anticiper les risques.', exampleRu: 'Нужно предвидеть риски.', exampleEn: 'We must anticipate risks.' },
  { french: 'approfondir', translation: 'углублять, расширять', translationEn: 'to deepen, to go deeper into', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1705, exampleFr: 'Il faut approfondir cette analyse.', exampleRu: 'Нужно углубить этот анализ.', exampleEn: 'We need to deepen this analysis.' },
  { french: 'aspirer', translation: 'стремиться, желать; вдыхать', translationEn: 'to aspire to, to desire; to inhale', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1706, exampleFr: 'Elle aspire à une vie plus simple.', exampleRu: 'Она стремится к более простой жизни.', exampleEn: 'She aspires to a simpler life.' },
  { french: 'atteindre', translation: 'достигать, добираться', translationEn: 'to reach, to achieve, to attain', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1707, exampleFr: 'Il a atteint ses objectifs.', exampleRu: 'Он достиг своих целей.', exampleEn: 'He achieved his goals.' },
  { french: 'cautionner', translation: 'одобрять, поддерживать, ручаться', translationEn: 'to sanction, to support, to guarantee', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1708, exampleFr: 'Je ne peux pas cautionner ce comportement.', exampleRu: 'Я не могу одобрить такое поведение.', exampleEn: 'I cannot sanction this behavior.' },
  { french: 'commander', translation: 'командовать, заказывать, требовать', translationEn: 'to command, to order', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1709, exampleFr: 'La situation commande une réaction rapide.', exampleRu: 'Ситуация требует быстрой реакции.', exampleEn: 'The situation demands a quick reaction.' },
  { french: 'concéder', translation: 'уступать, признавать', translationEn: 'to concede, to grant, to admit', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1710, exampleFr: 'Je concède que j\'avais tort sur ce point.', exampleRu: 'Признаю, что был неправ по этому вопросу.', exampleEn: 'I concede that I was wrong on this point.' },
  { french: 'consolider', translation: 'укреплять, консолидировать', translationEn: 'to consolidate, to strengthen', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1711, exampleFr: 'Il faut consolider les acquis sociaux.', exampleRu: 'Нужно укрепить социальные завоевания.', exampleEn: 'We must consolidate social gains.' },
  { french: 'converger', translation: 'сходиться, сближаться', translationEn: 'to converge', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1712, exampleFr: 'Nos opinions convergent sur ce sujet.', exampleRu: 'Наши мнения сходятся по этому вопросу.', exampleEn: 'Our opinions converge on this topic.' },
  { french: 'culminer', translation: 'достигать пика, кульминировать', translationEn: 'to culminate, to peak', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1713, exampleFr: 'La crise a culminé en 2008.', exampleRu: 'Кризис достиг пика в 2008 году.', exampleEn: 'The crisis culminated in 2008.' },
  { french: 'déléguer', translation: 'делегировать, поручать', translationEn: 'to delegate', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1714, exampleFr: 'Un bon manager sait déléguer.', exampleRu: 'Хороший менеджер умеет делегировать.', exampleEn: 'A good manager knows how to delegate.' },

  // ── Noms B2 domaine éducation / savoir ──
  { french: 'le cursus', translation: 'учебная программа, курс обучения', translationEn: 'curriculum, course of study', level: 'B2', category: 'education', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1720, exampleFr: 'Il a suivi un cursus scientifique.', exampleRu: 'Он прошёл научную программу обучения.', exampleEn: 'He followed a scientific curriculum.' },
  { french: 'la formation professionnelle', translation: 'профессиональная подготовка', translationEn: 'vocational training, professional development', level: 'B2', category: 'education', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1721, exampleFr: 'La formation professionnelle est financée par l\'État.', exampleRu: 'Профессиональная подготовка финансируется государством.', exampleEn: 'Vocational training is funded by the state.' },
  { french: 'le savoir-faire', translation: 'умение, навыки, ноу-хау', translationEn: 'know-how, expertise, skill', level: 'B2', category: 'education', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1722, exampleFr: 'Ce métier demande un vrai savoir-faire.', exampleRu: 'Это ремесло требует настоящего мастерства.', exampleEn: 'This craft requires real know-how.' },
  { french: 'la compétence', translation: 'компетенция, навык', translationEn: 'competence, skill', level: 'B2', category: 'education', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1723, exampleFr: 'Ce poste exige des compétences linguistiques.', exampleRu: 'Эта должность требует языковых компетенций.', exampleEn: 'This position requires linguistic competences.' },
  { french: 'le diplôme', translation: 'диплом', translationEn: 'diploma, degree', level: 'B2', category: 'education', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1724, exampleFr: 'Elle a obtenu son diplôme avec mention.', exampleRu: 'Она получила диплом с отличием.', exampleEn: 'She obtained her diploma with honors.' },

  // ── Santé mentale et société ──
  { french: 'l\'anxiété', translation: 'тревога, беспокойство', translationEn: 'anxiety', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1730, exampleFr: 'L\'anxiété sociale touche de nombreux jeunes.', exampleRu: 'Социальная тревога затрагивает многих молодых людей.', exampleEn: 'Social anxiety affects many young people.' },
  { french: 'le burn-out', translation: 'профессиональное выгорание', translationEn: 'burnout', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1731, exampleFr: 'Le burn-out est reconnu comme maladie professionnelle.', exampleRu: 'Профессиональное выгорание признано профессиональным заболеванием.', exampleEn: 'Burnout is recognized as an occupational disease.' },
  { french: 'la dépression', translation: 'депрессия', translationEn: 'depression', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1732, exampleFr: 'La dépression est une maladie à prendre au sérieux.', exampleRu: 'Депрессия — это болезнь, которую нужно воспринимать серьёзно.', exampleEn: 'Depression is a disease to be taken seriously.' },
  { french: 'la résilience', translation: 'устойчивость, жизнестойкость', translationEn: 'resilience', level: 'B2', category: 'psychology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1733, exampleFr: 'La résilience est une capacité à rebondir.', exampleRu: 'Жизнестойкость — это способность восстанавливаться.', exampleEn: 'Resilience is the ability to bounce back.' },
  { french: 'l\'empathie', translation: 'эмпатия', translationEn: 'empathy', level: 'B2', category: 'psychology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1734, exampleFr: 'Faire preuve d\'empathie envers les autres est essentiel.', exampleRu: 'Проявлять эмпатию к другим необходимо.', exampleEn: 'Showing empathy towards others is essential.' },
  { french: 'l\'addiction', translation: 'зависимость', translationEn: 'addiction', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1735, exampleFr: 'L\'addiction aux écrans est un problème grandissant.', exampleRu: 'Зависимость от экранов — растущая проблема.', exampleEn: 'Screen addiction is a growing problem.' },

  // ── Adjectifs B2 (suite) ──
  { french: 'éphémère', translation: 'недолговечный, скоротечный', translationEn: 'ephemeral, transient, fleeting', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1740, exampleFr: 'La gloire est éphémère.', exampleRu: 'Слава скоротечна.', exampleEn: 'Glory is fleeting.' },
  { french: 'équivoque', translation: 'двусмысленный, неоднозначный', translationEn: 'equivocal, ambiguous', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1741, exampleFr: 'Sa réponse était équivoque.', exampleRu: 'Его ответ был двусмысленным.', exampleEn: 'His answer was equivocal.' },
  { french: 'exhaustif', translation: 'исчерпывающий, всесторонний', translationEn: 'exhaustive, comprehensive', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1742, exampleFr: 'Cette liste n\'est pas exhaustive.', exampleRu: 'Этот список не является исчерпывающим.', exampleEn: 'This list is not exhaustive.' },
  { french: 'impartial', translation: 'беспристрастный', translationEn: 'impartial, unbiased', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1743, exampleFr: 'Un juge doit être impartial.', exampleRu: 'Судья должен быть беспристрастным.', exampleEn: 'A judge must be impartial.' },
  { french: 'intrinsèque', translation: 'внутренний, неотъемлемый', translationEn: 'intrinsic', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1744, exampleFr: 'La valeur intrinsèque de l\'art ne peut être mesurée.', exampleRu: 'Внутреннюю ценность искусства нельзя измерить.', exampleEn: 'The intrinsic value of art cannot be measured.' },
  { french: 'irréversible', translation: 'необратимый', translationEn: 'irreversible', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1745, exampleFr: 'Certains dégâts environnementaux sont irréversibles.', exampleRu: 'Некоторый экологический ущерб необратим.', exampleEn: 'Some environmental damage is irreversible.' },
  { french: 'marginal', translation: 'маргинальный, незначительный, окраинный', translationEn: 'marginal, fringe', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1746, exampleFr: 'Ce phénomène reste marginal.', exampleRu: 'Это явление остаётся маргинальным.', exampleEn: 'This phenomenon remains marginal.' },
  { french: 'paradoxal', translation: 'парадоксальный', translationEn: 'paradoxical', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1747, exampleFr: 'La situation est paradoxale.', exampleRu: 'Ситуация парадоксальная.', exampleEn: 'The situation is paradoxical.' },
  { french: 'pragmatique', translation: 'прагматичный, практичный', translationEn: 'pragmatic, practical', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1748, exampleFr: 'Il faut adopter une approche pragmatique.', exampleRu: 'Нужно принять прагматичный подход.', exampleEn: 'We must adopt a pragmatic approach.' },
  { french: 'récurrent', translation: 'повторяющийся, регулярный', translationEn: 'recurring, recurrent', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1749, exampleFr: 'C\'est un problème récurrent dans ce secteur.', exampleRu: 'Это повторяющаяся проблема в этой отрасли.', exampleEn: 'It\'s a recurring problem in this sector.' },
  { french: 'significatif', translation: 'значительный, значимый', translationEn: 'significant, meaningful', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1750, exampleFr: 'Les résultats sont significatifs.', exampleRu: 'Результаты значительные.', exampleEn: 'The results are significant.' },
  { french: 'successif', translation: 'последовательный, следующий друг за другом', translationEn: 'successive, consecutive', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1751, exampleFr: 'Trois défaites successives ont découragé l\'équipe.', exampleRu: 'Три последовательных поражения обескуражили команду.', exampleEn: 'Three successive defeats discouraged the team.' },
  { french: 'unilatéral', translation: 'односторонний', translationEn: 'unilateral', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1752, exampleFr: 'Une décision unilatérale est rarement efficace.', exampleRu: 'Одностороннее решение редко бывает эффективным.', exampleEn: 'A unilateral decision is rarely effective.' },

  // ── Langue et communication ──
  { french: 'l\'argumentation', translation: 'аргументация', translationEn: 'argumentation, reasoning', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1760, exampleFr: 'Son argumentation est solide.', exampleRu: 'Его аргументация убедительная.', exampleEn: 'His argumentation is solid.' },
  { french: 'le discours', translation: 'речь, выступление, дискурс', translationEn: 'speech, discourse', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1761, exampleFr: 'Le président a prononcé un discours important.', exampleRu: 'Президент произнёс важную речь.', exampleEn: 'The president delivered an important speech.' },
  { french: 'la rhétorique', translation: 'риторика', translationEn: 'rhetoric', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1762, exampleFr: 'Sa rhétorique est percutante.', exampleRu: 'Его риторика убедительна.', exampleEn: 'His rhetoric is impactful.' },
  { french: 'le registre', translation: 'регистр, стиль', translationEn: 'register, style, level of language', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1763, exampleFr: 'Il faut adapter son registre à la situation.', exampleRu: 'Нужно адаптировать стиль к ситуации.', exampleEn: 'We must adapt our register to the situation.' },
  { french: 'la périphrase', translation: 'перифраз, описательный оборот', translationEn: 'periphrasis, circumlocution', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1764, exampleFr: 'Éviter les périphrases pour aller à l\'essentiel.', exampleRu: 'Избегать описательных оборотов, чтобы сразу перейти к сути.', exampleEn: 'Avoid circumlocutions to get to the point.' },
  { french: 'l\'euphémisme', translation: 'эвфемизм', translationEn: 'euphemism', level: 'B2', category: 'language', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1765, exampleFr: '"Partir pour un long voyage" est un euphémisme pour mourir.', exampleRu: '"Уйти в долгое путешествие" — эвфемизм смерти.', exampleEn: '"Going on a long journey" is a euphemism for dying.' },

  // ── Géographie humaine ──
  { french: 'le territoire', translation: 'территория', translationEn: 'territory', level: 'B2', category: 'geography', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1770, exampleFr: 'Ce territoire est disputé depuis des siècles.', exampleRu: 'Эта территория оспаривается уже несколько веков.', exampleEn: 'This territory has been disputed for centuries.' },
  { french: 'le bassin', translation: 'бассейн, котловина', translationEn: 'basin, pool', level: 'B2', category: 'geography', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1771, exampleFr: 'Le bassin méditerranéen est menacé par le réchauffement.', exampleRu: 'Средиземноморский бассейн находится под угрозой потепления.', exampleEn: 'The Mediterranean basin is threatened by warming.' },
  { french: 'la métropole', translation: 'крупный город, метрополия', translationEn: 'metropolis, major city', level: 'B2', category: 'geography', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1772, exampleFr: 'Paris est la principale métropole française.', exampleRu: 'Париж — главная французская метрополия.', exampleEn: 'Paris is the main French metropolis.' },
  { french: 'le littoral', translation: 'побережье, береговая линия', translationEn: 'coastline, coastal area', level: 'B2', category: 'geography', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1773, exampleFr: 'Le littoral atlantique est magnifique.', exampleRu: 'Атлантическое побережье великолепно.', exampleEn: 'The Atlantic coastline is magnificent.' },
  { french: 'la démographie', translation: 'демография', translationEn: 'demography, demographics', level: 'B2', category: 'geography', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1774, exampleFr: 'La démographie mondiale est en évolution rapide.', exampleRu: 'Мировая демография стремительно меняется.', exampleEn: 'World demographics are changing rapidly.' },
];
