export const wordsB2Extra10 = [
  // ── Cinéma ──
  {
    french: 'le réalisateur',
    translation: 'режиссёр (кино)',
    translationEn: 'film director',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3200,
    exampleFr: 'Le réalisateur a tourné son film en six semaines.',
    exampleRu: 'Режиссёр снял фильм за шесть недель.',
    exampleEn: 'The director shot his film in six weeks.',
  },
  {
    french: 'le scénario',
    translation: 'сценарий',
    translationEn: 'screenplay, script',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3400,
    exampleFr: 'Le scénario original a été adapté d\'un roman.',
    exampleRu: 'Оригинальный сценарий был адаптирован из романа.',
    exampleEn: 'The original screenplay was adapted from a novel.',
  },
  {
    french: 'le tournage',
    translation: 'съёмки, кинопроизводство',
    translationEn: 'filming, shoot',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3600,
    exampleFr: 'Le tournage a eu lieu en Bretagne pendant l\'été.',
    exampleRu: 'Съёмки прошли в Бретани летом.',
    exampleEn: 'The shoot took place in Brittany during the summer.',
  },
  {
    french: 'le montage',
    translation: 'монтаж (видео/кино)',
    translationEn: 'editing, montage',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3100,
    exampleFr: 'Le montage final dure deux heures et demie.',
    exampleRu: 'Финальный монтаж длится два с половиной часа.',
    exampleEn: 'The final cut lasts two and a half hours.',
  },
  {
    french: 'la bande originale',
    translation: 'оригинальный саундтрек',
    translationEn: 'original soundtrack',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'La bande originale a remporté un César.',
    exampleRu: 'Оригинальный саундтрек получил премию Сезар.',
    exampleEn: 'The original soundtrack won a César award.',
  },
  {
    french: 'interpréter',
    translation: 'исполнять (роль/произведение)',
    translationEn: 'to perform, to play, to interpret',
    category: 'arts',
    partOfSpeech: 'verb',
    frequencyRank: 2800,
    exampleFr: 'Elle interprète le rôle principal avec beaucoup de finesse.',
    exampleRu: 'Она исполняет главную роль с большим мастерством.',
    exampleEn: 'She plays the lead role with great finesse.',
  },
  {
    french: 'la représentation',
    translation: 'спектакль, представление',
    translationEn: 'performance, show',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2200,
    exampleFr: 'La représentation a reçu une standing ovation.',
    exampleRu: 'Спектакль был встречен стоячими овациями.',
    exampleEn: 'The performance received a standing ovation.',
  },
  {
    french: 'la répétition',
    translation: 'репетиция',
    translationEn: 'rehearsal',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2900,
    exampleFr: 'Les répétitions ont duré trois mois avant la première.',
    exampleRu: 'Репетиции длились три месяца до премьеры.',
    exampleEn: 'Rehearsals lasted three months before the premiere.',
  },
  {
    french: 'la première',
    translation: 'премьера',
    translationEn: 'premiere, opening night',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 1800,
    exampleFr: 'La première du film a eu lieu au festival de Cannes.',
    exampleRu: 'Премьера фильма прошла на Каннском фестивале.',
    exampleEn: 'The film premiere took place at the Cannes festival.',
  },
  {
    french: 'le festival',
    translation: 'фестиваль',
    translationEn: 'festival',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2100,
    exampleFr: 'Le festival d\'Avignon est dédié au théâtre contemporain.',
    exampleRu: 'Авиньонский фестиваль посвящён современному театру.',
    exampleEn: 'The Avignon festival is dedicated to contemporary theatre.',
  },
  // ── Musique ──
  {
    french: 'la symphonie',
    translation: 'симфония',
    translationEn: 'symphony',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4500,
    exampleFr: 'La Neuvième symphonie de Beethoven est une œuvre universelle.',
    exampleRu: 'Девятая симфония Бетховена — универсальное произведение.',
    exampleEn: 'Beethoven\'s Ninth Symphony is a universal masterpiece.',
  },
  {
    french: 'l\'harmonie',
    translation: 'гармония',
    translationEn: 'harmony',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2700,
    exampleFr: 'L\'harmonie des voix crée une atmosphère envoûtante.',
    exampleRu: 'Гармония голосов создаёт завораживающую атмосферу.',
    exampleEn: 'The harmony of voices creates a captivating atmosphere.',
  },
  {
    french: 'la partition',
    translation: 'нотная партитура',
    translationEn: 'musical score',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4100,
    exampleFr: 'Le chef d\'orchestre étudie la partition avant le concert.',
    exampleRu: 'Дирижёр изучает партитуру перед концертом.',
    exampleEn: 'The conductor studies the score before the concert.',
  },
  {
    french: 'le chef d\'orchestre',
    translation: 'дирижёр',
    translationEn: 'conductor',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4300,
    exampleFr: 'Le chef d\'orchestre dirige l\'ensemble avec précision.',
    exampleRu: 'Дирижёр управляет ансамблем с точностью.',
    exampleEn: 'The conductor leads the ensemble with precision.',
  },
  {
    french: 'le soliste',
    translation: 'солист',
    translationEn: 'soloist',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4600,
    exampleFr: 'Le soliste a joué le concerto avec une technique irréprochable.',
    exampleRu: 'Солист исполнил концерт с безупречной техникой.',
    exampleEn: 'The soloist performed the concerto with flawless technique.',
  },
  {
    french: 'l\'improvisation',
    translation: 'импровизация',
    translationEn: 'improvisation',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'Le jazz est fondé sur l\'improvisation collective.',
    exampleRu: 'Джаз основан на коллективной импровизации.',
    exampleEn: 'Jazz is built on collective improvisation.',
  },
  {
    french: 'composer',
    translation: 'сочинять (музыку)',
    translationEn: 'to compose',
    category: 'arts',
    partOfSpeech: 'verb',
    frequencyRank: 3300,
    exampleFr: 'Il a composé cette sonate en seulement deux semaines.',
    exampleRu: 'Он сочинил эту сонату всего за две недели.',
    exampleEn: 'He composed this sonata in just two weeks.',
  },
  {
    french: 'le timbre',
    translation: 'тембр (голоса/инструмента)',
    translationEn: 'timbre, tone colour',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3700,
    exampleFr: 'Le timbre de sa voix est immédiatement reconnaissable.',
    exampleRu: 'Тембр её голоса узнаваем с первых секунд.',
    exampleEn: 'The timbre of her voice is immediately recognisable.',
  },
  // ── Arts visuels ──
  {
    french: 'l\'aquarelle',
    translation: 'акварель',
    translationEn: 'watercolour',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'Ses aquarelles capturent la lumière du matin avec subtilité.',
    exampleRu: 'Его акварели тонко передают утренний свет.',
    exampleEn: 'His watercolours capture the morning light with subtlety.',
  },
  {
    french: 'la gravure',
    translation: 'гравюра',
    translationEn: 'engraving, print',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5000,
    exampleFr: 'Les gravures de Dürer sont d\'une précision remarquable.',
    exampleRu: 'Гравюры Дюрера отличаются исключительной точностью.',
    exampleEn: 'Dürer\'s engravings are of remarkable precision.',
  },
  {
    french: 'l\'installation artistique',
    translation: 'художественная инсталляция',
    translationEn: 'art installation',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'L\'installation artistique occupe tout l\'espace du musée.',
    exampleRu: 'Художественная инсталляция занимает всё пространство музея.',
    exampleEn: 'The art installation occupies the entire museum space.',
  },
  {
    french: 'le vernissage',
    translation: 'вернисаж, открытие выставки',
    translationEn: 'private view, opening',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Le vernissage de l\'exposition a attiré de nombreux collectionneurs.',
    exampleRu: 'На вернисаже выставки собрались многие коллекционеры.',
    exampleEn: 'The opening of the exhibition attracted many collectors.',
  },
  {
    french: 'le commissaire d\'exposition',
    translation: 'куратор выставки',
    translationEn: 'exhibition curator',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Le commissaire d\'exposition a sélectionné cent œuvres du monde entier.',
    exampleRu: 'Куратор выставки отобрал сто работ со всего мира.',
    exampleEn: 'The exhibition curator selected a hundred works from around the world.',
  },
  {
    french: 'peindre',
    translation: 'рисовать, писать (картину)',
    translationEn: 'to paint',
    category: 'arts',
    partOfSpeech: 'verb',
    frequencyRank: 3500,
    exampleFr: 'Elle peint des portraits à l\'huile depuis vingt ans.',
    exampleRu: 'Она пишет портреты маслом вот уже двадцать лет.',
    exampleEn: 'She has been painting oil portraits for twenty years.',
  },
  {
    french: 'sculpter',
    translation: 'ваять, лепить',
    translationEn: 'to sculpt, to carve',
    category: 'arts',
    partOfSpeech: 'verb',
    frequencyRank: 5100,
    exampleFr: 'Rodin sculptait le marbre avec une force extraordinaire.',
    exampleRu: 'Роден ваял мрамор с необычайной силой.',
    exampleEn: 'Rodin sculpted marble with extraordinary force.',
  },
  // ── Architecture ──
  {
    french: 'la façade',
    translation: 'фасад',
    translationEn: 'facade',
    category: 'architecture',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3400,
    exampleFr: 'La façade de la cathédrale a été restaurée l\'année dernière.',
    exampleRu: 'Фасад собора был отреставрирован в прошлом году.',
    exampleEn: 'The cathedral\'s facade was restored last year.',
  },
  {
    french: 'la voûte',
    translation: 'свод, арка',
    translationEn: 'vault, arch',
    category: 'architecture',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'Les voûtes gothiques créent une impression d\'élévation.',
    exampleRu: 'Готические своды создают ощущение высоты.',
    exampleEn: 'Gothic vaults create an impression of height.',
  },
  {
    french: 'la fresque',
    translation: 'фреска',
    translationEn: 'fresco',
    category: 'architecture',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5300,
    exampleFr: 'Les fresques de Michel-Ange ornent le plafond de la chapelle Sixtine.',
    exampleRu: 'Фрески Микеланджело украшают потолок Сикстинской капеллы.',
    exampleEn: 'Michelangelo\'s frescoes adorn the ceiling of the Sistine Chapel.',
  },
  {
    french: 'le vitrail',
    translation: 'витраж',
    translationEn: 'stained glass window',
    category: 'architecture',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5600,
    exampleFr: 'Les vitraux de la cathédrale de Chartres sont parmi les plus beaux du monde.',
    exampleRu: 'Витражи Шартрского собора — одни из красивейших в мире.',
    exampleEn: 'The stained glass windows of Chartres Cathedral are among the most beautiful in the world.',
  },
  {
    french: 'classé monument historique',
    translation: 'внесённый в список исторических памятников',
    translationEn: 'listed historical monument',
    category: 'architecture',
    partOfSpeech: 'expression',
    frequencyRank: 5800,
    exampleFr: 'Cet immeuble est classé monument historique depuis 1965.',
    exampleRu: 'Это здание внесено в список исторических памятников с 1965 года.',
    exampleEn: 'This building has been a listed historical monument since 1965.',
  },
  // ── Littérature ──
  {
    french: 'le narrateur',
    translation: 'рассказчик, нарратор',
    translationEn: 'narrator',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4000,
    exampleFr: 'Le narrateur omniscient connaît les pensées de tous les personnages.',
    exampleRu: 'Всеведущий рассказчик знает мысли всех персонажей.',
    exampleEn: 'The omniscient narrator knows the thoughts of all characters.',
  },
  {
    french: 'le dénouement',
    translation: 'развязка',
    translationEn: 'denouement, resolution',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Le dénouement inattendu surprend le lecteur jusqu\'à la dernière page.',
    exampleRu: 'Неожиданная развязка удивляет читателя до последней страницы.',
    exampleEn: 'The unexpected denouement surprises the reader until the last page.',
  },
  {
    french: 'l\'allégorie',
    translation: 'аллегория',
    translationEn: 'allegory',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'La Ferme des animaux est une allégorie du totalitarisme.',
    exampleRu: '«Скотный двор» — аллегория тоталитаризма.',
    exampleEn: 'Animal Farm is an allegory of totalitarianism.',
  },
  {
    french: 'l\'ironie',
    translation: 'ирония',
    translationEn: 'irony',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2600,
    exampleFr: 'L\'ironie voltairienne est redoutable dans Candide.',
    exampleRu: 'Вольтеровская ирония в «Кандиде» беспощадна.',
    exampleEn: 'Voltairian irony in Candide is devastating.',
  },
  {
    french: 'la satire',
    translation: 'сатира',
    translationEn: 'satire',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'La satire sociale est au cœur de l\'œuvre de Molière.',
    exampleRu: 'Социальная сатира — в центре творчества Мольера.',
    exampleEn: 'Social satire is at the heart of Molière\'s work.',
  },
  {
    french: 'le naturalisme',
    translation: 'натурализм',
    translationEn: 'naturalism',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5600,
    exampleFr: 'Zola est le chef de file du naturalisme français.',
    exampleRu: 'Золя — лидер французского натурализма.',
    exampleEn: 'Zola is the leading figure of French naturalism.',
  },
  {
    french: 'le surréalisme',
    translation: 'сюрреализм',
    translationEn: 'surrealism',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5400,
    exampleFr: 'Breton a fondé le mouvement surréaliste dans les années 1920.',
    exampleRu: 'Бретон основал сюрреалистическое движение в 1920-х годах.',
    exampleEn: 'Breton founded the surrealist movement in the 1920s.',
  },
  {
    french: 'le personnage',
    translation: 'персонаж, герой',
    translationEn: 'character',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 1600,
    exampleFr: 'Le personnage principal évolue considérablement au fil du roman.',
    exampleRu: 'Главный персонаж значительно меняется на протяжении романа.',
    exampleEn: 'The main character evolves considerably throughout the novel.',
  },
  {
    french: 'le protagoniste',
    translation: 'главный герой, протагонист',
    translationEn: 'protagonist',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4000,
    exampleFr: 'Le protagoniste est confronté à un dilemme moral insoluble.',
    exampleRu: 'Протагонист сталкивается с неразрешимой моральной дилеммой.',
    exampleEn: 'The protagonist faces an unsolvable moral dilemma.',
  },
  {
    french: 'l\'autobiographie',
    translation: 'автобиография',
    translationEn: 'autobiography',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'Son autobiographie retrace cinquante ans de carrière artistique.',
    exampleRu: 'Его автобиография охватывает пятьдесят лет творческой карьеры.',
    exampleEn: 'His autobiography traces fifty years of artistic career.',
  },
  {
    french: 'le témoignage',
    translation: 'свидетельство, мемуары',
    translationEn: 'testimony, account',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2900,
    exampleFr: 'Son témoignage sur la guerre a marqué plusieurs générations.',
    exampleRu: 'Его свидетельство о войне произвело впечатление на несколько поколений.',
    exampleEn: 'His account of the war has marked several generations.',
  },
  {
    french: 'la dramaturgie',
    translation: 'драматургия',
    translationEn: 'dramaturgy, playwriting',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'Sa dramaturgie mêle le tragique et le comique avec maestria.',
    exampleRu: 'Его драматургия мастерски сочетает трагическое и комическое.',
    exampleEn: 'His dramaturgy masterfully blends the tragic and the comic.',
  },
  {
    french: 'la scénographie',
    translation: 'сценография',
    translationEn: 'set design, scenography',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'La scénographie minimaliste renforce l\'impact émotionnel de la pièce.',
    exampleRu: 'Минималистичная сценография усиливает эмоциональный эффект спектакля.',
    exampleEn: 'The minimalist set design enhances the emotional impact of the play.',
  },
  {
    french: 'les coulisses',
    translation: 'кулисы, закулисье',
    translationEn: 'backstage, wings',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'Les coulisses de la politique sont souvent plus intéressantes que la scène.',
    exampleRu: 'Политические кулисы часто интереснее сцены.',
    exampleEn: 'The backstage of politics is often more interesting than the stage.',
  },
  {
    french: 'la critique',
    translation: 'критика; рецензия',
    translationEn: 'review, criticism',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 1500,
    exampleFr: 'Les critiques ont été unanimement enthousiastes après la première.',
    exampleRu: 'После премьеры критики единодушно выразили восторг.',
    exampleEn: 'The reviews were unanimously enthusiastic after the premiere.',
  },
  {
    french: 'l\'avant-garde',
    translation: 'авангард',
    translationEn: 'avant-garde',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4500,
    exampleFr: 'Ce compositeur appartient à l\'avant-garde de la musique contemporaine.',
    exampleRu: 'Этот композитор принадлежит к авангарду современной музыки.',
    exampleEn: 'This composer belongs to the avant-garde of contemporary music.',
  },
  {
    french: 'l\'intertextualité',
    translation: 'интертекстуальность',
    translationEn: 'intertextuality',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 7000,
    exampleFr: 'L\'intertextualité est un procédé central dans la littérature postmoderne.',
    exampleRu: 'Интертекстуальность — центральный приём постмодернистской литературы.',
    exampleEn: 'Intertextuality is a central device in postmodern literature.',
  },
  {
    french: 'le metteur en scène',
    translation: 'режиссёр (театральный)',
    translationEn: 'theatre director',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4700,
    exampleFr: 'Le metteur en scène a réinterprété Hamlet de façon contemporaine.',
    exampleRu: 'Театральный режиссёр переосмыслил Гамлета в современном ключе.',
    exampleEn: 'The theatre director reinterpreted Hamlet in a contemporary way.',
  },
  {
    french: 'le roman graphique',
    translation: 'графический роман',
    translationEn: 'graphic novel',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le roman graphique s\'est imposé comme un genre littéraire à part entière.',
    exampleRu: 'Графический роман утвердился как самостоятельный литературный жанр.',
    exampleEn: 'The graphic novel has established itself as a literary genre in its own right.',
  },
  {
    french: 'la mise en abyme',
    translation: 'mise en abyme (приём «текст в тексте»)',
    translationEn: 'mise en abyme (story within a story)',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 7500,
    exampleFr: 'La mise en abyme crée une réflexion sur l\'acte même de créer.',
    exampleRu: 'Mise en abyme создаёт рефлексию над самим актом творения.',
    exampleEn: 'Mise en abyme creates a reflection on the very act of creation.',
  },
  {
    french: 'l\'enjambement',
    translation: 'анжамбеман (перенос строки)',
    translationEn: 'enjambment',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 8000,
    exampleFr: 'Victor Hugo utilisait l\'enjambement pour briser le rythme classique.',
    exampleRu: 'Виктор Гюго использовал анжамбеман для нарушения классического ритма.',
    exampleEn: 'Victor Hugo used enjambment to break the classical rhythm.',
  },
  {
    french: 'le sonnet',
    translation: 'сонет',
    translationEn: 'sonnet',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Les sonnets de Du Bellay expriment la nostalgie de la patrie.',
    exampleRu: 'Сонеты Дю Белле выражают тоску по родине.',
    exampleEn: 'Du Bellay\'s sonnets express nostalgia for the homeland.',
  },
  {
    french: 'la fable',
    translation: 'басня',
    translationEn: 'fable',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4900,
    exampleFr: 'Les fables de La Fontaine transmettent des leçons morales universelles.',
    exampleRu: 'Басни Лафонтена несут универсальные нравственные уроки.',
    exampleEn: 'La Fontaine\'s fables convey universal moral lessons.',
  },
  {
    french: 'la nouvelle',
    translation: 'новелла, рассказ',
    translationEn: 'short story, novella',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2000,
    exampleFr: 'Maupassant excelle dans l\'art de la nouvelle.',
    exampleRu: 'Мопассан мастерски владеет жанром новеллы.',
    exampleEn: 'Maupassant excels in the art of the short story.',
  },
  {
    french: 'le roman policier',
    translation: 'детектив, полицейский роман',
    translationEn: 'detective novel, crime fiction',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4400,
    exampleFr: 'Le roman policier est l\'un des genres les plus lus en France.',
    exampleRu: 'Детектив — один из самых читаемых жанров во Франции.',
    exampleEn: 'Crime fiction is one of the most read genres in France.',
  },
  {
    french: 'la dystopie',
    translation: 'антиутопия',
    translationEn: 'dystopia',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5900,
    exampleFr: '1984 d\'Orwell est une dystopie politique magistrale.',
    exampleRu: '«1984» Оруэлла — мастерская политическая антиутопия.',
    exampleEn: 'Orwell\'s 1984 is a masterful political dystopia.',
  },
  {
    french: 'l\'utopie',
    translation: 'утопия',
    translationEn: 'utopia',
    category: 'literature',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4300,
    exampleFr: 'More a imaginé une société idéale dans son œuvre Utopie.',
    exampleRu: 'Мор представил идеальное общество в своей «Утопии».',
    exampleEn: 'More imagined an ideal society in his work Utopia.',
  },
  {
    french: 'le casting',
    translation: 'кастинг',
    translationEn: 'casting',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4100,
    exampleFr: 'Le casting de ce film a duré six mois.',
    exampleRu: 'Кастинг этого фильма занял шесть месяцев.',
    exampleEn: 'The casting for this film took six months.',
  },
  {
    french: 'le documentaire',
    translation: 'документальный фильм',
    translationEn: 'documentary',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3600,
    exampleFr: 'Ce documentaire sur le réchauffement climatique a remporté de nombreux prix.',
    exampleRu: 'Этот документальный фильм о глобальном потеплении получил множество наград.',
    exampleEn: 'This documentary on climate change won numerous awards.',
  },
  {
    french: 'le court-métrage',
    translation: 'короткометражный фильм',
    translationEn: 'short film',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'Son premier court-métrage a été sélectionné à Cannes.',
    exampleRu: 'Её первый короткометражный фильм был отобран для Канн.',
    exampleEn: 'Her first short film was selected for Cannes.',
  },
  {
    french: 'le symbolisme',
    translation: 'символизм',
    translationEn: 'symbolism',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Baudelaire est l\'un des précurseurs du symbolisme.',
    exampleRu: 'Бодлер — один из предшественников символизма.',
    exampleEn: 'Baudelaire is one of the forerunners of symbolism.',
  },
  {
    french: 'le réalisme',
    translation: 'реализм',
    translationEn: 'realism',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4000,
    exampleFr: 'Le réalisme de Flaubert décrit la société provinciale sans illusions.',
    exampleRu: 'Реализм Флобера описывает провинциальное общество без прикрас.',
    exampleEn: 'Flaubert\'s realism depicts provincial society without illusions.',
  },
  {
    french: 'le slam',
    translation: 'слэм (поэтическое выступление)',
    translationEn: 'slam (spoken word poetry)',
    category: 'arts',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6800,
    exampleFr: 'Grand Corps Malade a popularisé le slam en France.',
    exampleRu: 'Grand Corps Malade популяризовал слэм во Франции.',
    exampleEn: 'Grand Corps Malade popularised slam poetry in France.',
  },
];
