// Words discovered missing during the post-content audit
// (see check-reading-words.ts). Every entry here failed the full lookup
// chain (per-text wordMap → FUNCTION_WORDS dict → DB exact/ilike → verb stem
// → noun stem) on the prod DB, so users were seeing "перевода нет" tooltips.
//
// Entries are grouped by purpose:
//   1. High-frequency demonstratives, quantifiers, stressed pronouns
//   2. Common nouns/verbs/adjectives missed by lemmatization
//   3. Numbers (cardinal compounds + ordinals)
//   4. Verb-pronoun inversion forms (a-t-elle, est-ce, faut-il, ...)
//   5. Proper nouns: people / brands / places (still get translations
//      so the tooltip is informative)
//   6. Specialized / formal / technical terms
//
// Translations follow the existing words-reading.ts style: brief, with
// a parenthetical hint when the form needs clarification.

export const wordsReadingExtra = [
  // ── 1. High-freq demonstratives, quantifiers, stressed pronouns ──
  { french: 'tous',        translation: 'все (м.р. мн.ч.)',                  partOfSpeech: 'pronoun',     level: 'A1' as const, gender: null },
  { french: 'toute',       translation: 'вся, целая (tout, ж.р.)',           partOfSpeech: 'adj',         level: 'A1' as const, gender: 'f' },
  { french: 'toutes',      translation: 'все (ж.р. мн.ч., tout)',            partOfSpeech: 'adj',         level: 'A1' as const, gender: 'f' },
  { french: 'moi',         translation: 'я, мне (ударная форма)',            partOfSpeech: 'pronoun',     level: 'A1' as const, gender: null },
  { french: 'eux',         translation: 'они (после предлога, м.р.)',        partOfSpeech: 'pronoun',     level: 'A2' as const, gender: null },
  { french: 'celle',       translation: 'та, эта (ж.р., указ. мест.)',       partOfSpeech: 'pronoun',     level: 'B1' as const, gender: 'f' },
  { french: 'celui',       translation: 'тот, этот (м.р., указ. мест.)',     partOfSpeech: 'pronoun',     level: 'B1' as const, gender: 'm' },
  { french: 'ceux',        translation: 'те, эти (м.р. мн.ч., указ. мест.)', partOfSpeech: 'pronoun',     level: 'B1' as const, gender: null },
  { french: 'soi',         translation: 'себя (возвратное)',                 partOfSpeech: 'pronoun',     level: 'B1' as const, gender: null },
  { french: 'eux-mêmes',   translation: 'они сами (м.р. мн.ч.)',             partOfSpeech: 'pronoun',     level: 'B2' as const, gender: null },
  { french: 'lui-même',    translation: 'он сам',                            partOfSpeech: 'pronoun',     level: 'B1' as const, gender: 'm' },

  // ── 2. Common nouns / verbs / adjectives missed by lemmatization ──
  { french: 'partie',      translation: 'часть (faire partie de — быть частью)', partOfSpeech: 'noun',    level: 'A2' as const, gender: 'f' },
  { french: 'madame',      translation: 'мадам, госпожа',                    partOfSpeech: 'noun',         level: 'A1' as const, gender: 'f' },
  { french: 'monsieur',    translation: 'мсье, господин',                    partOfSpeech: 'noun',         level: 'A1' as const, gender: 'm' },
  { french: 'effet',       translation: 'эффект, следствие (en effet — действительно)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'film',        translation: 'фильм',                             partOfSpeech: 'noun',         level: 'A1' as const, gender: 'm' },
  { french: 'mode',        translation: 'способ, режим (m); мода (f)',       partOfSpeech: 'noun',         level: 'A2' as const, gender: null },
  { french: 'voiture',     translation: 'машина, автомобиль',                partOfSpeech: 'noun',         level: 'A1' as const, gender: 'f' },
  { french: 'classe',      translation: 'класс; аудитория',                  partOfSpeech: 'noun',         level: 'A1' as const, gender: 'f' },
  { french: 'élève',       translation: 'ученик, ученица',                   partOfSpeech: 'noun',         level: 'A1' as const, gender: null },
  { french: 'élevé',       translation: 'высокий; воспитанный (élever — поднимать)', partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'gros',        translation: 'толстый; крупный',                  partOfSpeech: 'adj',         level: 'A2' as const, gender: null },
  { french: 'forte',       translation: 'сильная (fort, ж.р.)',              partOfSpeech: 'adj',         level: 'B1' as const, gender: 'f' },
  { french: 'mondial',     translation: 'мировой, всемирный',                partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'sûr',         translation: 'уверенный; надёжный (bien sûr — конечно)', partOfSpeech: 'adj',  level: 'A2' as const, gender: 'm' },
  { french: 'différent',   translation: 'другой, различный',                 partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'complet',     translation: 'полный, законченный',               partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'content',     translation: 'довольный',                         partOfSpeech: 'adj',         level: 'A1' as const, gender: 'm' },
  { french: 'coûteux',     translation: 'дорогой, затратный',                partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'croissant',   translation: 'растущий; круассан',                partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'européen',    translation: 'европейский',                       partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'excellent',   translation: 'отличный',                          partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'majeur',      translation: 'основной; совершеннолетний',        partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'massif',      translation: 'массивный',                         partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'noir',        translation: 'чёрный',                            partOfSpeech: 'adj',         level: 'A1' as const, gender: 'm' },
  { french: 'ouvert',      translation: 'открытый',                          partOfSpeech: 'adj',         level: 'A1' as const, gender: 'm' },
  { french: 'personnel',   translation: 'личный (m); персонал (m)',          partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'politique',   translation: 'политический; политика',            partOfSpeech: 'adj',         level: 'B1' as const, gender: null },
  { french: 'présent',     translation: 'присутствующий; настоящее (время)', partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'principal',   translation: 'главный',                           partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'profond',     translation: 'глубокий',                          partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'public',      translation: 'публичный; общественный',           partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'réel',        translation: 'настоящий, реальный',               partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'républicain', translation: 'республиканский',                   partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'scolaire',    translation: 'школьный',                          partOfSpeech: 'adj',         level: 'A2' as const, gender: null },
  { french: 'spectaculaire', translation: 'зрелищный, эффектный',            partOfSpeech: 'adj',         level: 'B2' as const, gender: null },
  { french: 'strict',      translation: 'строгий',                           partOfSpeech: 'adj',         level: 'B1' as const, gender: 'm' },
  { french: 'supérieur',   translation: 'высший; превосходящий',             partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'total',       translation: 'полный, общий',                     partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },
  { french: 'touristique', translation: 'туристический',                     partOfSpeech: 'adj',         level: 'A2' as const, gender: null },
  { french: 'vrai',        translation: 'настоящий, правдивый',              partOfSpeech: 'adj',         level: 'A2' as const, gender: 'm' },

  // ── Nouns ──
  { french: 'accident',    translation: 'авария, несчастный случай',         partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'adolescent',  translation: 'подросток',                         partOfSpeech: 'noun',         level: 'B1' as const, gender: null },
  { french: 'agriculture', translation: 'сельское хозяйство',                partOfSpeech: 'noun',         level: 'B2' as const, gender: 'f' },
  { french: 'aventure',    translation: 'приключение',                       partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'boutique',    translation: 'магазин, бутик',                    partOfSpeech: 'noun',         level: 'A2' as const, gender: 'f' },
  { french: 'cancer',      translation: 'рак (болезнь); Рак (знак)',         partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'consulat',    translation: 'консульство',                       partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'contexte',    translation: 'контекст',                          partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'désir',       translation: 'желание',                           partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'développeur', translation: 'разработчик (программист)',         partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'difficulté',  translation: 'трудность',                         partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'état',        translation: 'состояние; государство',            partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'étranger',    translation: 'иностранец; заграница (à l\'étranger — за границей)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'finance',     translation: 'финансы',                           partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'fonction',    translation: 'функция; должность',                partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'gain',        translation: 'выигрыш, прибыль',                  partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'gaz',         translation: 'газ',                               partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'geste',       translation: 'жест, поступок',                    partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'groupe',      translation: 'группа',                            partOfSpeech: 'noun',         level: 'A2' as const, gender: 'm' },
  { french: 'humain',      translation: 'человек; человеческий',             partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'individu',    translation: 'индивид, личность',                 partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'industrie',   translation: 'промышленность',                    partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'majorité',    translation: 'большинство',                       partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'médecine',    translation: 'медицина',                          partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'messagerie',  translation: 'мессенджер; почта (служба сообщений)', partOfSpeech: 'noun',      level: 'B2' as const, gender: 'f' },
  { french: 'moyen',       translation: 'средство, способ; средний',         partOfSpeech: 'noun',         level: 'A2' as const, gender: 'm' },
  { french: 'principe',    translation: 'принцип',                           partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'priorité',    translation: 'приоритет',                         partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'regard',      translation: 'взгляд',                            partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'remise',      translation: 'передача; скидка',                  partOfSpeech: 'noun',         level: 'B2' as const, gender: 'f' },
  { french: 'république',  translation: 'республика',                        partOfSpeech: 'noun',         level: 'B2' as const, gender: 'f' },
  { french: 'respect',     translation: 'уважение',                          partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'ressource',   translation: 'ресурс',                            partOfSpeech: 'noun',         level: 'B1' as const, gender: 'f' },
  { french: 'revanche',    translation: 'реванш; en revanche — зато, напротив', partOfSpeech: 'noun',     level: 'B2' as const, gender: 'f' },
  { french: 'science-fiction', translation: 'научная фантастика',            partOfSpeech: 'noun',         level: 'B2' as const, gender: 'f' },
  { french: 'serre',       translation: 'теплица (effet de serre — парниковый эффект)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'spécialité',  translation: 'специальность; фирменное блюдо',    partOfSpeech: 'noun',         level: 'A2' as const, gender: 'f' },
  { french: 'stand',       translation: 'стенд, прилавок',                   partOfSpeech: 'noun',         level: 'A2' as const, gender: 'm' },
  { french: 'succès',      translation: 'успех',                             partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'sud',         translation: 'юг',                                partOfSpeech: 'noun',         level: 'A2' as const, gender: 'm' },
  { french: 'texte',       translation: 'текст',                             partOfSpeech: 'noun',         level: 'A2' as const, gender: 'm' },
  { french: 'utilisateur', translation: 'пользователь',                      partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },
  { french: 'visiteur',    translation: 'посетитель',                        partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'voyageur',    translation: 'путешественник',                    partOfSpeech: 'noun',         level: 'B1' as const, gender: 'm' },
  { french: 'volume',      translation: 'объём; том',                        partOfSpeech: 'noun',         level: 'B2' as const, gender: 'm' },

  // ── Verbs (infinitives so lemmatization catches inflections) ──
  { french: 'accompagner', translation: 'сопровождать',                      partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'accuser',     translation: 'обвинять',                          partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'afficher',    translation: 'показывать, отображать',            partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'appliquer',   translation: 'применять',                         partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'attendre',    translation: 'ждать',                             partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'célébrer',    translation: 'отмечать, праздновать',             partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'constituer',  translation: 'составлять, представлять собой',    partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'contenter',   translation: 'удовлетворять (se contenter — довольствоваться)', partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'devenir',     translation: 'становиться',                       partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'exercer',     translation: 'осуществлять (право, профессию)',   partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'frapper',     translation: 'бить, ударять; поражать',           partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'guider',      translation: 'направлять, вести',                 partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'installer',   translation: 'устанавливать; s\'installer — обустраиваться', partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'interroger',  translation: 'опрашивать; задаваться вопросом',   partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'mettre',      translation: 'класть, помещать (mis — кладёт, причастие)', partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'naître',      translation: 'рождаться (né — родился)',          partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'poser',       translation: 'ставить, класть; задавать (вопрос)', partOfSpeech: 'verb',        level: 'A2' as const, gender: null },
  { french: 'présenter',   translation: 'представлять',                      partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'promettre',   translation: 'обещать',                           partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'réduire',     translation: 'уменьшать, сокращать',              partOfSpeech: 'verb',         level: 'B1' as const, gender: null },
  { french: 'reproduire',  translation: 'воспроизводить',                    partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'résoudre',    translation: 'решать (résolu — решённый)',        partOfSpeech: 'verb',         level: 'B2' as const, gender: null },
  { french: 'rester',      translation: 'оставаться',                        partOfSpeech: 'verb',         level: 'A1' as const, gender: null },
  { french: 'revenir',     translation: 'возвращаться',                      partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'révéler',     translation: 'раскрывать; se révéler — оказываться', partOfSpeech: 'verb',     level: 'B2' as const, gender: null },
  { french: 'révolter',    translation: 'возмущать (se révolter — восставать)', partOfSpeech: 'verb',     level: 'B2' as const, gender: null },
  { french: 'servir',      translation: 'служить; обслуживать (sert — служит)', partOfSpeech: 'verb',     level: 'A2' as const, gender: null },
  { french: 'terminer',    translation: 'заканчивать',                       partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'voler',       translation: 'летать; красть',                    partOfSpeech: 'verb',         level: 'A2' as const, gender: null },
  { french: 'valoir',      translation: 'стоить (vaut — стоит; il vaut mieux — лучше)', partOfSpeech: 'verb', level: 'B1' as const, gender: null },

  // ── Adverbs ──
  { french: 'dès',          translation: 'с (момента), начиная с (dès que — как только)', partOfSpeech: 'preposition', level: 'B1' as const, gender: null },
  { french: 'au-delà',      translation: 'за пределами (au-delà de — за пределами)',      partOfSpeech: 'preposition', level: 'B2' as const, gender: null },
  { french: 'autour',       translation: 'вокруг (autour de — вокруг)',       partOfSpeech: 'preposition', level: 'B1' as const, gender: null },
  { french: 'travers',      translation: 'сквозь, через (à travers — через)', partOfSpeech: 'preposition', level: 'B2' as const, gender: null },
  { french: 'tandis',       translation: 'в то время как (tandis que)',      partOfSpeech: 'conjunction', level: 'B2' as const, gender: null },
  { french: 'là-bas',       translation: 'там (вдалеке)',                    partOfSpeech: 'adverb',     level: 'A1' as const, gender: null },
  { french: 'là-haut',      translation: 'наверху',                          partOfSpeech: 'adverb',     level: 'A2' as const, gender: null },
  { french: 'clairement',   translation: 'ясно, чётко',                      partOfSpeech: 'adverb',     level: 'B1' as const, gender: null },
  { french: 'historiquement', translation: 'исторически',                    partOfSpeech: 'adverb',     level: 'B2' as const, gender: null },
  { french: 'majoritairement', translation: 'в большинстве, преимущественно', partOfSpeech: 'adverb',    level: 'B2' as const, gender: null },
  { french: 'politiquement', translation: 'политически',                     partOfSpeech: 'adverb',     level: 'B1' as const, gender: null },
  { french: 'réellement',    translation: 'на самом деле',                   partOfSpeech: 'adverb',     level: 'B1' as const, gender: null },
  { french: 'premièrement',  translation: 'во-первых',                       partOfSpeech: 'adverb',     level: 'B1' as const, gender: null },
  { french: 'deuxièmement',  translation: 'во-вторых',                       partOfSpeech: 'adverb',     level: 'B1' as const, gender: null },
  { french: 'magique',       translation: 'волшебный',                       partOfSpeech: 'adj',        level: 'A1' as const, gender: null },

  // ── Other adjectives / nouns missed ──
  { french: 'bel',          translation: 'красивый (форма beau перед гласной)', partOfSpeech: 'adj',     level: 'A2' as const, gender: 'm' },
  { french: 'faciale',      translation: 'лицевая (facial, ж.р.)',           partOfSpeech: 'adj',         level: 'B2' as const, gender: 'f' },
  { french: 'environnementale', translation: 'экологическая (environnemental, ж.р.)', partOfSpeech: 'adj', level: 'B2' as const, gender: 'f' },
  { french: 'inaccessible',  translation: 'недоступный',                     partOfSpeech: 'adj',         level: 'B2' as const, gender: null },
  { french: 'musulman',      translation: 'мусульманский',                   partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'voilé',         translation: 'в вуали; завуалированный',        partOfSpeech: 'adj',         level: 'B2' as const, gender: 'm' },
  { french: 'gris',          translation: 'серый (zones grises — серые зоны)', partOfSpeech: 'adj',      level: 'A1' as const, gender: 'm' },
  { french: 'catholique',    translation: 'католический',                    partOfSpeech: 'adj',         level: 'B2' as const, gender: null },

  // ── 3. Numbers (cardinals + compounds) ──
  { french: 'treize',           translation: 'тринадцать (13)',              partOfSpeech: 'number',      level: 'A1' as const, gender: null },
  { french: 'seize',            translation: 'шестнадцать (16)',             partOfSpeech: 'number',      level: 'A1' as const, gender: null },
  { french: 'dix-sept',         translation: 'семнадцать (17)',              partOfSpeech: 'number',      level: 'A1' as const, gender: null },
  { french: 'vingt-deux',       translation: 'двадцать два (22)',            partOfSpeech: 'number',      level: 'A1' as const, gender: null },
  { french: 'cinquante-deux',   translation: 'пятьдесят два (52)',           partOfSpeech: 'number',      level: 'A1' as const, gender: null },
  { french: 'quatre-vingt-dix', translation: 'девяносто (90)',               partOfSpeech: 'number',      level: 'A2' as const, gender: null },
  { french: 'xviiᵉ',            translation: 'XVII (17-й) — порядковый век', partOfSpeech: 'number',      level: 'B2' as const, gender: null },
  { french: 'xixe',             translation: 'XIX (19-й век, ускоренная запись)', partOfSpeech: 'number', level: 'B2' as const, gender: null },
  { french: 'xixᵉ',             translation: 'XIX (19-й век, порядковое прилаг.)', partOfSpeech: 'number', level: 'B2' as const, gender: null },
  { french: 'xxᵉ',              translation: 'XX (20-й век, порядковое прилаг.)', partOfSpeech: 'number', level: 'B2' as const, gender: null },

  // ── 4. Verb-pronoun inversion forms (literal interrogative chunks) ──
  { french: 'est-ce',          translation: 'это есть; est-ce que — разве, ли (вопрос)',           partOfSpeech: 'expression', level: 'A2' as const, gender: null },
  { french: 'est-il',          translation: 'есть ли (он); — ли (être, инверсия)',                  partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'est-elle',        translation: 'есть ли (она); — ли (être, инверсия)',                 partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'a-t-elle',        translation: 'имеет ли она (avoir, инверсия)',                       partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'faut-il',         translation: 'нужно ли (falloir, инверсия)',                         partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'peut-elle',       translation: 'может ли она (pouvoir, инверсия)',                     partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'sommes-nous',     translation: 'где мы; есть ли мы (être, инверсия)',                  partOfSpeech: 'expression', level: 'B1' as const, gender: null },
  { french: 'soutiennent-ils', translation: 'утверждают ли они (soutenir, инверсия)',               partOfSpeech: 'expression', level: 'B2' as const, gender: null },
  { french: 'implique-t-elle', translation: 'подразумевает ли она (impliquer, инверсия)',           partOfSpeech: 'expression', level: 'B2' as const, gender: null },
  { french: 't\'écris',        translation: 'тебе пишу (te + écris от écrire)',                     partOfSpeech: 'verb',       level: 'A2' as const, gender: null },

  // ── 5. Proper nouns (names / brands / places) ──
  // Names of people
  { french: 'agnès',      translation: 'Аньес (имя)',          partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'alain',      translation: 'Ален (имя)',           partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'anna',       translation: 'Анна (имя)',           partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'auguste',    translation: 'Огюст (имя)',          partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'banksy',     translation: 'Бэнкси (художник стрит-арта)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'bernard',    translation: 'Бернар (имя)',         partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'camille',    translation: 'Камилла (имя)',        partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'ducasse',    translation: 'Дюкас (фамилия — шеф-повар)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'dupont',     translation: 'Дюпон (фамилия)',      partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'dupuis',     translation: 'Дюпюи (фамилия)',      partOfSpeech: 'noun', level: 'A2' as const, gender: null },
  { french: 'edwige',     translation: 'Эдвига (имя)',         partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'emma',       translation: 'Эмма (имя)',           partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'françois',   translation: 'Франсуа (имя)',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'godard',     translation: 'Годар (фамилия — кинорежиссёр)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'greta',      translation: 'Грета (имя — Тунберг)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'henri',      translation: 'Анри (имя)',           partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'hugo',       translation: 'Юго (фамилия Виктора Гюго)', partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'jack',       translation: 'Жак (имя — англ. вариант)', partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'jean-luc',   translation: 'Жан-Люк (имя)',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'julien',     translation: 'Жюльен (имя)',         partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'khaznadar',  translation: 'Хазнадар (фамилия — лингвист)', partOfSpeech: 'noun', level: 'B2' as const, gender: null },
  { french: 'lambert',    translation: 'Ламбер (фамилия)',     partOfSpeech: 'noun', level: 'A2' as const, gender: null },
  { french: 'lang',       translation: 'Ланг (фамилия — Жак Ланг)', partOfSpeech: 'noun', level: 'A2' as const, gender: null },
  { french: 'léa',        translation: 'Леа (имя)',            partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'lucas',      translation: 'Лукас (имя)',          partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'lucie',      translation: 'Люси (имя)',           partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'olivier',    translation: 'Оливье (имя; маслина)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'roellinger', translation: 'Рёллингер (фамилия — шеф-повар)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'sophie',     translation: 'Софи (имя)',           partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'thunberg',   translation: 'Тунберг (фамилия — Грета Тунберг)', partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'tom',        translation: 'Том (имя)',            partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'truffaut',   translation: 'Трюффо (фамилия — кинорежиссёр)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'varda',      translation: 'Варда (фамилия — кинорежиссёр)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'victor',     translation: 'Виктор (имя)',         partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'invader',    translation: 'Invader (стрит-арт художник)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },

  // Brands and companies
  { french: 'airbnb',     translation: 'Airbnb (сервис аренды жилья)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'blablacar',  translation: 'BlaBlaCar (сервис попутчиков)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'google',     translation: 'Google (компания)',    partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'instagram',  translation: 'Instagram (соцсеть)',  partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'netflix',    translation: 'Netflix (стриминг)',   partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'siri',       translation: 'Siri (голосовой ассистент Apple)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'snapchat',   translation: 'Snapchat (соцсеть)',   partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'tiktok',     translation: 'TikTok (соцсеть)',     partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'uber',       translation: 'Uber (сервис такси)',  partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'vinted',     translation: 'Vinted (маркетплейс одежды)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'volkswagen', translation: 'Volkswagen (автокомпания)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },

  // Places
  { french: 'annecy',     translation: 'Анси (город во Франции)', partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'australie',  translation: 'Австралия',            partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'barcelone',  translation: 'Барселона',            partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'canada',     translation: 'Канада',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'dubrovnik',  translation: 'Дубровник (город в Хорватии)', partOfSpeech: 'noun', level: 'B2' as const, gender: null },
  { french: 'europe',     translation: 'Европа',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'nantes',     translation: 'Нант (город во Франции)', partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'rennes',     translation: 'Ренн (город во Франции)', partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'royaume-uni', translation: 'Великобритания',      partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'venise',     translation: 'Венеция',              partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'tertre',     translation: 'Тертр (площадь в Париже)', partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },

  // Special / technical / English borrowings
  { french: 'act',        translation: 'акт (AI Act — закон ЕС об ИИ)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'b1',         translation: 'B1 (уровень CEFR — средний)', partOfSpeech: 'noun', level: 'A2' as const, gender: null },
  { french: 'ia',         translation: 'ИИ (intelligence artificielle)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'new',        translation: 'New (англ. — Нью-, New York)', partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'tech',       translation: 'tech (технологическая отрасль, англ.)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'shame',      translation: 'flygskam — стыд за полёт (швед.→англ., экотермин)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'flight',     translation: 'flight shame — стыд за полёт (англ., экотермин)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'rainforest', translation: 'Rainforest Alliance (организация экосертификации)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'alliance',   translation: 'альянс, союз',         partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'label',      translation: 'лейбл, знак качества', partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'éco-tourisme', translation: 'экотуризм',          partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'venise-isation', translation: '«венизация» (превращение в туристическую витрину как Венеция)', partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'cinématographique', translation: 'кинематографический', partOfSpeech: 'adj', level: 'B1' as const, gender: null },
  { french: 'bourguignon', translation: 'бургундский (bœuf bourguignon — говядина по-бургундски)', partOfSpeech: 'adj', level: 'A2' as const, gender: 'm' },
  { french: 'étudiant·e·s', translation: 'студенты (инклюзивная запись étudiants/étudiantes)', partOfSpeech: 'noun', level: 'B2' as const, gender: null },

  // ── Inflected forms that the auto-lemmatizer fails to resolve.
  // Adding them directly so the popup is always informative.
  { french: 'publiques',   translation: 'публичные (publique, ж.р. мн.ч.)',     partOfSpeech: 'adj',  level: 'A2' as const, gender: 'f' },
  { french: 'âgés',        translation: 'пожилые (âgé, м.р. мн.ч.)',            partOfSpeech: 'adj',  level: 'B1' as const, gender: 'm' },
  { french: 'américains',  translation: 'американцы; американские (м.р. мн.ч.)', partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'artificielle', translation: 'искусственная (artificiel, ж.р.)',    partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'assistant',   translation: 'ассистент, помощник',                  partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'assistants',  translation: 'ассистенты (assistant, мн.ч.)',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'attendent',   translation: 'ждут (attendre, 3 л. мн.ч.)',          partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'célèbrent',   translation: 'празднуют (célébrer, 3 л. мн.ч.)',     partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'chère',       translation: 'дорогая (cher, ж.р.); Дорогая (обращение)', partOfSpeech: 'adj', level: 'A1' as const, gender: 'f' },
  { french: 'compte',      translation: 'счёт; rendre compte de — отчитываться о', partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'croissante',  translation: 'растущая (croissant, ж.р.)',           partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'devenues',    translation: 'стали (devenir, прич. ж.р. мн.ч.)',    partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'devient',     translation: 'становится (devenir, 3 л. ед.)',       partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'différentes', translation: 'разные (différent, ж.р. мн.ч.)',       partOfSpeech: 'adj',  level: 'A2' as const, gender: 'f' },
  { french: 'étrangères',  translation: 'иностранные (étranger, ж.р. мн.ч.)',   partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'grises',      translation: 'серые (gris, ж.р. мн.ч.)',             partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'longs',       translation: 'длинные (long, м.р. мн.ч.)',           partOfSpeech: 'adj',  level: 'A2' as const, gender: 'm' },
  { french: 'majeure',     translation: 'главная (majeur, ж.р.)',               partOfSpeech: 'adj',  level: 'B2' as const, gender: 'f' },
  { french: 'meilleures',  translation: 'лучшие (meilleur, ж.р. мн.ч.)',        partOfSpeech: 'adj',  level: 'A2' as const, gender: 'f' },
  { french: 'mis',         translation: 'положенный (mettre, прич.)',           partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'musulmanes',  translation: 'мусульманские (musulman, ж.р. мн.ч.)', partOfSpeech: 'adj',  level: 'B2' as const, gender: 'f' },
  { french: 'né',          translation: 'рождённый (naître, прич.)',            partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'noire',       translation: 'чёрная (noir, ж.р.)',                  partOfSpeech: 'adj',  level: 'A1' as const, gender: 'f' },
  { french: 'ouverte',     translation: 'открытая (ouvert, ж.р.)',              partOfSpeech: 'adj',  level: 'A1' as const, gender: 'f' },
  { french: 'pourraient',  translation: 'могли бы (pouvoir, conditionnel 3 л. мн.ч.)', partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'profonde',    translation: 'глубокая (profond, ж.р.)',             partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'promet',      translation: 'обещает (promettre, 3 л. ед.)',        partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'réduisent',   translation: 'сокращают (réduire, 3 л. мн.ч.)',      partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'résolues',    translation: 'решённые (résoudre, прич. ж.р. мн.ч.)', partOfSpeech: 'verb', level: 'B2' as const, gender: null },
  { french: 'resteront',   translation: 'останутся (rester, futur 3 л. мн.ч.)', partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'reviennent',  translation: 'возвращаются (revenir, 3 л. мн.ч.)',   partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'sert',        translation: 'служит, подаётся (servir, 3 л. ед.)',  partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'seules',      translation: 'только; одни (seul, ж.р. мн.ч.)',      partOfSpeech: 'adj',  level: 'A2' as const, gender: 'f' },
  { french: 'seuls',       translation: 'только; одни (seul, м.р. мн.ч.)',      partOfSpeech: 'adj',  level: 'A2' as const, gender: 'm' },
  { french: 'stricte',     translation: 'строгая (strict, ж.р.)',               partOfSpeech: 'adj',  level: 'B1' as const, gender: 'f' },
  { french: 'supérieure',  translation: 'высшая (supérieur, ж.р.)',             partOfSpeech: 'adj',  level: 'B2' as const, gender: 'f' },
  { french: 'union',       translation: 'союз (Union européenne — Евросоюз)',   partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'vocaux',      translation: 'голосовые (vocal, м.р. мн.ч.)',        partOfSpeech: 'adj',  level: 'B2' as const, gender: 'm' },
  { french: 'voilées',     translation: 'в вуали; завуалированные (voilé, ж.р. мн.ч.)', partOfSpeech: 'adj', level: 'B2' as const, gender: 'f' },
  { french: 'vraie',       translation: 'настоящая (vrai, ж.р.)',               partOfSpeech: 'adj',  level: 'A2' as const, gender: 'f' },
  { french: 'week-ends',   translation: 'выходные (week-end, мн.ч.)',           partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
];
