export const wordsB2Extra14 = [
  // ── Logement ──
  {
    french: 'le propriétaire bailleur',
    translation: 'арендодатель',
    translationEn: 'landlord',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Le propriétaire bailleur est tenu de remettre un logement décent.',
    exampleRu: 'Арендодатель обязан предоставить достойное жильё.',
    exampleEn: 'The landlord is required to provide decent housing.',
  },
  {
    french: 'le locataire',
    translation: 'арендатор, жилец',
    translationEn: 'tenant',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4500,
    exampleFr: 'Le locataire a le droit de rester dans les lieux à l\'expiration du bail.',
    exampleRu: 'Арендатор имеет право оставаться в жилье по истечении договора.',
    exampleEn: 'The tenant has the right to remain in the premises when the lease expires.',
  },
  {
    french: 'la sous-location',
    translation: 'субаренда',
    translationEn: 'subletting',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La sous-location est interdite sans l\'accord écrit du propriétaire.',
    exampleRu: 'Субаренда запрещена без письменного согласия арендодателя.',
    exampleEn: 'Subletting is prohibited without the landlord\'s written consent.',
  },
  {
    french: 'la colocation',
    translation: 'совместная аренда',
    translationEn: 'house-sharing, flat-sharing',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'La colocation est très répandue parmi les étudiants parisiens.',
    exampleRu: 'Совместная аренда очень распространена среди парижских студентов.',
    exampleEn: 'Flat-sharing is very common among Parisian students.',
  },
  {
    french: 'le sans-abri',
    translation: 'бездомный',
    translationEn: 'homeless person',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4800,
    exampleFr: 'Le nombre de sans-abri augmente chaque année dans les grandes villes.',
    exampleRu: 'Число бездомных растёт в крупных городах из года в год.',
    exampleEn: 'The number of homeless people increases every year in major cities.',
  },
  {
    french: 'le SDF (sans domicile fixe)',
    translation: 'лицо без определённого места жительства',
    translationEn: 'homeless person (no fixed abode)',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Les associations distribuent des repas chauds aux SDF en hiver.',
    exampleRu: 'Ассоциации раздают горячую еду бездомным зимой.',
    exampleEn: 'Associations distribute hot meals to homeless people in winter.',
  },
  {
    french: 'l\'expulsion',
    translation: 'выселение; депортация',
    translationEn: 'eviction; deportation',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'La trêve hivernale interdit les expulsions de novembre à mars.',
    exampleRu: 'Зимний мораторий запрещает выселения с ноября по март.',
    exampleEn: 'The winter moratorium bans evictions from November to March.',
  },
  {
    french: 'le loyer encadré',
    translation: 'регулируемая арендная плата',
    translationEn: 'rent-controlled price',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'À Paris, le loyer encadré limite les abus des propriétaires.',
    exampleRu: 'В Париже регулируемая арендная плата ограничивает злоупотребления арендодателей.',
    exampleEn: 'In Paris, rent control limits landlord abuses.',
  },
  {
    french: 'le HLM (habitation à loyer modéré)',
    translation: 'социальное жильё',
    translationEn: 'social housing',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5300,
    exampleFr: 'Des millions de Français vivent dans des HLM.',
    exampleRu: 'Миллионы французов живут в социальном жилье.',
    exampleEn: 'Millions of French people live in social housing.',
  },
  {
    french: 'la liste d\'attente',
    translation: 'лист ожидания',
    translationEn: 'waiting list',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'Il attend un logement social depuis cinq ans sur liste d\'attente.',
    exampleRu: 'Он ждёт социального жилья уже пять лет в листе ожидания.',
    exampleEn: 'He has been waiting for social housing for five years on the waiting list.',
  },
  // ── Protection sociale ──
  {
    french: 'le RSA (revenu de solidarité active)',
    translation: 'минимальный доход (базовый доход Франции)',
    translationEn: 'minimum income benefit (France)',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'Le RSA est versé aux personnes sans emploi dont les ressources sont très faibles.',
    exampleRu: 'RSA выплачивается безработным с очень низким уровнем доходов.',
    exampleEn: 'The RSA is paid to unemployed people with very low resources.',
  },
  {
    french: 'le travailleur social',
    translation: 'социальный работник',
    translationEn: 'social worker',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4900,
    exampleFr: 'Le travailleur social accompagne les familles en difficulté.',
    exampleRu: 'Социальный работник сопровождает семьи в трудной ситуации.',
    exampleEn: 'The social worker supports families in difficulty.',
  },
  {
    french: 'la réinsertion',
    translation: 'реинтеграция, ресоциализация',
    translationEn: 'social rehabilitation, reintegration',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'Les programmes de réinsertion réduisent le taux de récidive.',
    exampleRu: 'Программы ресоциализации снижают уровень рецидивизма.',
    exampleEn: 'Rehabilitation programmes reduce recidivism rates.',
  },
  {
    french: 'la précarité',
    translation: 'нестабильность, бедность',
    translationEn: 'precariousness, poverty',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4100,
    exampleFr: 'La précarité énergétique touche des millions de foyers.',
    exampleRu: 'Энергетическая бедность затрагивает миллионы домохозяйств.',
    exampleEn: 'Energy poverty affects millions of households.',
  },
  // ── Immigration ──
  {
    french: 'le demandeur d\'asile',
    translation: 'соискатель убежища',
    translationEn: 'asylum seeker',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Les demandeurs d\'asile attendent parfois deux ans une réponse.',
    exampleRu: 'Соискатели убежища порой ждут ответа два года.',
    exampleEn: 'Asylum seekers sometimes wait two years for a decision.',
  },
  {
    french: 'le titre de séjour',
    translation: 'вид на жительство',
    translationEn: 'residence permit',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Son titre de séjour doit être renouvelé tous les ans.',
    exampleRu: 'Его вид на жительство должен обновляться каждый год.',
    exampleEn: 'His residence permit must be renewed every year.',
  },
  {
    french: 'la naturalisation',
    translation: 'натурализация',
    translationEn: 'naturalisation',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'La naturalisation requiert cinq ans de résidence en France.',
    exampleRu: 'Натурализация требует пяти лет проживания во Франции.',
    exampleEn: 'Naturalisation requires five years of residence in France.',
  },
  {
    french: 'le sans-papiers',
    translation: 'нелегальный мигрант',
    translationEn: 'undocumented migrant',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5400,
    exampleFr: 'Plusieurs associations défendent les droits des sans-papiers.',
    exampleRu: 'Несколько ассоциаций защищают права нелегальных мигрантов.',
    exampleEn: 'Several associations defend the rights of undocumented migrants.',
  },
  {
    french: 'la reconduite à la frontière',
    translation: 'депортация, высылка на границу',
    translationEn: 'deportation, removal to the border',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La reconduite à la frontière peut être contestée devant le juge.',
    exampleRu: 'Депортация может быть обжалована перед судьёй.',
    exampleEn: 'Deportation can be challenged before a judge.',
  },
  // ── Discriminations ──
  {
    french: 'le racisme systémique',
    translation: 'системный расизм',
    translationEn: 'systemic racism',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6200,
    exampleFr: 'Le racisme systémique se manifeste dans les inégalités d\'accès à l\'emploi.',
    exampleRu: 'Системный расизм проявляется в неравенстве доступа к занятости.',
    exampleEn: 'Systemic racism manifests in unequal access to employment.',
  },
  {
    french: 'le sexisme ordinaire',
    translation: 'бытовой сексизм',
    translationEn: 'everyday sexism',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le sexisme ordinaire passe souvent inaperçu car banalisé.',
    exampleRu: 'Бытовой сексизм часто остаётся незамеченным, поскольку нормализован.',
    exampleEn: 'Everyday sexism often goes unnoticed because it is normalised.',
  },
  {
    french: 'le harcèlement moral',
    translation: 'моральный харасмент, психологическое преследование',
    translationEn: 'moral harassment, psychological harassment',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5300,
    exampleFr: 'Le harcèlement moral au travail est reconnu comme délit.',
    exampleRu: 'Психологическое преследование на работе признаётся правонарушением.',
    exampleEn: 'Moral harassment at work is recognised as a criminal offence.',
  },
  {
    french: 'le harcèlement sexuel',
    translation: 'сексуальный харасмент',
    translationEn: 'sexual harassment',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'Le mouvement #MeToo a libéré la parole sur le harcèlement sexuel.',
    exampleRu: 'Движение #MeToo дало голос жертвам сексуального харасмента.',
    exampleEn: 'The #MeToo movement freed voices about sexual harassment.',
  },
  // ── Genre et égalité ──
  {
    french: 'la parité',
    translation: 'гендерное равенство в представительстве',
    translationEn: 'gender parity',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4700,
    exampleFr: 'La loi sur la parité impose une alternance homme-femme sur les listes électorales.',
    exampleRu: 'Закон о паритете требует чередования мужчин и женщин в избирательных списках.',
    exampleEn: 'The parity law requires alternating male and female candidates on electoral lists.',
  },
  {
    french: 'le plafond de verre',
    translation: 'стеклянный потолок',
    translationEn: 'glass ceiling',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le plafond de verre empêche encore de nombreuses femmes d\'accéder aux postes dirigeants.',
    exampleRu: 'Стеклянный потолок по-прежнему мешает многим женщинам занимать руководящие должности.',
    exampleEn: 'The glass ceiling still prevents many women from reaching leadership positions.',
  },
  {
    french: 'le congé parental',
    translation: 'родительский отпуск',
    translationEn: 'parental leave',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Le congé parental peut être pris par le père comme par la mère.',
    exampleRu: 'Родительский отпуск может взять как отец, так и мать.',
    exampleEn: 'Parental leave can be taken by either the father or the mother.',
  },
  {
    french: 'la charge mentale',
    translation: 'ментальная нагрузка',
    translationEn: 'mental load, cognitive load',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6300,
    exampleFr: 'La charge mentale pèse encore principalement sur les femmes dans le foyer.',
    exampleRu: 'Ментальная нагрузка по-прежнему лежит преимущественно на женщинах в семье.',
    exampleEn: 'The mental load still falls primarily on women in the home.',
  },
  {
    french: 'l\'intersectionnalité',
    translation: 'интерсекциональность',
    translationEn: 'intersectionality',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6800,
    exampleFr: 'L\'intersectionnalité analyse les discriminations croisées de genre et d\'origine.',
    exampleRu: 'Интерсекциональность анализирует перекрёстную дискриминацию по признаку пола и происхождения.',
    exampleEn: 'Intersectionality analyses the overlapping discriminations of gender and origin.',
  },
  {
    french: 'le patriarcat',
    translation: 'патриархат',
    translationEn: 'patriarchy',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5900,
    exampleFr: 'Le féminisme remet en cause les structures du patriarcat.',
    exampleRu: 'Феминизм ставит под сомнение структуры патриархата.',
    exampleEn: 'Feminism challenges the structures of patriarchy.',
  },
  {
    french: 'la discrimination positive',
    translation: 'позитивная дискриминация',
    translationEn: 'positive discrimination, affirmative action',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5700,
    exampleFr: 'La discrimination positive fait l\'objet de vifs débats en France.',
    exampleRu: 'Позитивная дискриминация вызывает острые споры во Франции.',
    exampleEn: 'Positive discrimination is the subject of heated debates in France.',
  },
  // ── Tissu associatif ──
  {
    french: 'le bénévole',
    translation: 'волонтёр',
    translationEn: 'volunteer',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4400,
    exampleFr: 'L\'association compte cinq cents bénévoles actifs.',
    exampleRu: 'В ассоциации пятьсот активных волонтёров.',
    exampleEn: 'The association has five hundred active volunteers.',
  },
  {
    french: 'le mécénat',
    translation: 'меценатство',
    translationEn: 'patronage, sponsorship (non-profit)',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5600,
    exampleFr: 'Le mécénat d\'entreprise est encouragé par des avantages fiscaux.',
    exampleRu: 'Корпоративное меценатство поощряется налоговыми льготами.',
    exampleEn: 'Corporate patronage is encouraged through tax advantages.',
  },
  {
    french: 'la collecte de fonds',
    translation: 'сбор средств, фандрайзинг',
    translationEn: 'fundraising',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'La collecte de fonds en ligne a transformé le secteur associatif.',
    exampleRu: 'Онлайн-фандрайзинг изменил некоммерческий сектор.',
    exampleEn: 'Online fundraising has transformed the non-profit sector.',
  },
  {
    french: 'la campagne de sensibilisation',
    translation: 'информационная кампания, кампания по просвещению',
    translationEn: 'awareness campaign',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'Une campagne de sensibilisation au harcèlement scolaire a été lancée.',
    exampleRu: 'Была запущена информационная кампания о школьном харасменте.',
    exampleEn: 'An awareness campaign on school bullying was launched.',
  },
  {
    french: 'la mobilisation',
    translation: 'мобилизация, подъём',
    translationEn: 'mobilisation',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'La mobilisation citoyenne a abouti à l\'annulation du projet.',
    exampleRu: 'Гражданская мобилизация привела к отмене проекта.',
    exampleEn: 'Citizens\' mobilisation led to the cancellation of the project.',
  },
  {
    french: 'le tissu associatif',
    translation: 'сеть гражданских организаций',
    translationEn: 'network of civil society organisations',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le tissu associatif local joue un rôle essentiel dans la cohésion sociale.',
    exampleRu: 'Местная сеть гражданских организаций играет ключевую роль в социальной сплочённости.',
    exampleEn: 'The local network of civil society organisations plays an essential role in social cohesion.',
  },
  {
    french: 'l\'homophobie',
    translation: 'гомофобия',
    translationEn: 'homophobia',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'L\'homophobie est un délit puni par la loi française.',
    exampleRu: 'Гомофобия является правонарушением, наказуемым по французскому закону.',
    exampleEn: 'Homophobia is an offence punishable under French law.',
  },
  {
    french: 'l\'égalité des chances',
    translation: 'равенство возможностей',
    translationEn: 'equal opportunities',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'L\'école républicaine repose sur le principe d\'égalité des chances.',
    exampleRu: 'Республиканская школа основана на принципе равенства возможностей.',
    exampleEn: 'The republican school is based on the principle of equal opportunities.',
  },
  {
    french: 'le mouvement social',
    translation: 'социальное движение',
    translationEn: 'social movement',
    category: 'social_issues',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4200,
    exampleFr: 'Les mouvements sociaux ont obtenu de grandes avancées au XXe siècle.',
    exampleRu: 'Социальные движения добились больших успехов в XX веке.',
    exampleEn: 'Social movements achieved great progress in the 20th century.',
  },
  {
    french: 'la précarité du logement',
    translation: 'жилищная нестабильность',
    translationEn: 'housing insecurity',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La précarité du logement augmente avec la hausse des loyers.',
    exampleRu: 'Жилищная нестабильность растёт вместе с повышением арендных ставок.',
    exampleEn: 'Housing insecurity increases as rents rise.',
  },
];
