export const wordsB2Extra16 = [
  // ── Gastronomie ──
  {
    french: 'la gastronomie',
    translation: 'гастрономия',
    translationEn: 'gastronomy',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'La gastronomie française est inscrite au patrimoine immatériel de l\'UNESCO.',
    exampleRu: 'Французская гастрономия включена в нематериальное наследие ЮНЕСКО.',
    exampleEn: 'French gastronomy is listed as UNESCO\'s intangible heritage.',
  },
  {
    french: 'le terroir',
    translation: 'терруар (географическое происхождение продукта)',
    translationEn: 'terroir',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Ce vin exprime parfaitement le terroir de la Bourgogne.',
    exampleRu: 'Это вино прекрасно отражает терруар Бургундии.',
    exampleEn: 'This wine perfectly expresses the terroir of Burgundy.',
  },
  {
    french: 'l\'appellation d\'origine contrôlée',
    translation: 'контролируемое наименование происхождения (АОС)',
    translationEn: 'controlled designation of origin (AOC)',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'Le Comté et le Roquefort sont des fromages à appellation d\'origine contrôlée.',
    exampleRu: 'Конте и Рокфор — сыры с контролируемым наименованием происхождения.',
    exampleEn: 'Comté and Roquefort are cheeses with a controlled designation of origin.',
  },
  {
    french: 'le millésime',
    translation: 'год урожая (вино)',
    translationEn: 'vintage (wine year)',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le millésime 2010 est considéré comme exceptionnel en Bordeaux.',
    exampleRu: 'Урожай 2010 года считается исключительным в Бордо.',
    exampleEn: 'The 2010 vintage is considered exceptional in Bordeaux.',
  },
  {
    french: 'la dégustation',
    translation: 'дегустация',
    translationEn: 'tasting',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5100,
    exampleFr: 'La dégustation professionnelle évalue la robe, le nez et le palais du vin.',
    exampleRu: 'Профессиональная дегустация оценивает цвет, аромат и вкус вина.',
    exampleEn: 'Professional tasting evaluates the colour, nose and palate of the wine.',
  },
  {
    french: 'l\'accord mets-vins',
    translation: 'сочетание блюд и вин',
    translationEn: 'food and wine pairing',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Un bon accord mets-vins sublime les deux éléments.',
    exampleRu: 'Хорошее сочетание блюд и вин возвышает оба элемента.',
    exampleEn: 'A good food and wine pairing elevates both elements.',
  },
  {
    french: 'braiser',
    translation: 'тушить (мясо) на медленном огне',
    translationEn: 'to braise',
    category: 'gastronomy',
    partOfSpeech: 'verb',
    frequencyRank: 7200,
    exampleFr: 'On braise le bœuf bourguignon plusieurs heures pour l\'attendrir.',
    exampleRu: 'Говядину по-бургундски тушат несколько часов для мягкости.',
    exampleEn: 'Beef bourguignon is braised for several hours to tenderise it.',
  },
  {
    french: 'mijoter',
    translation: 'томить, готовить на медленном огне',
    translationEn: 'to simmer, to slow cook',
    category: 'gastronomy',
    partOfSpeech: 'verb',
    frequencyRank: 6000,
    exampleFr: 'La blanquette de veau doit mijoter une heure et demie.',
    exampleRu: 'Бланкет из телятины должен томиться полтора часа.',
    exampleEn: 'Blanquette de veau must simmer for an hour and a half.',
  },
  {
    french: 'farcir',
    translation: 'фаршировать',
    translationEn: 'to stuff, to fill',
    category: 'gastronomy',
    partOfSpeech: 'verb',
    frequencyRank: 7000,
    exampleFr: 'Elle a farci les tomates avec du riz et de la chair à saucisse.',
    exampleRu: 'Она нафаршировала помидоры рисом и колбасным фаршем.',
    exampleEn: 'She stuffed the tomatoes with rice and sausage meat.',
  },
  {
    french: 'gratiner',
    translation: 'запекать под золотистой корочкой',
    translationEn: 'to gratin, to brown',
    category: 'gastronomy',
    partOfSpeech: 'verb',
    frequencyRank: 7500,
    exampleFr: 'Faire gratiner les lasagnes dix minutes à 200 degrés.',
    exampleRu: 'Запечь лазанью под корочкой десять минут при 200 градусах.',
    exampleEn: 'Gratin the lasagne for ten minutes at 200 degrees.',
  },
  {
    french: 'caraméliser',
    translation: 'карамелизировать',
    translationEn: 'to caramelise',
    category: 'gastronomy',
    partOfSpeech: 'verb',
    frequencyRank: 7000,
    exampleFr: 'Caraméliser les oignons à feu doux jusqu\'à ce qu\'ils soient dorés.',
    exampleRu: 'Карамелизировать лук на медленном огне до золотистого цвета.',
    exampleEn: 'Caramelise the onions over a low heat until golden.',
  },
  {
    french: 'le sommelier',
    translation: 'сомелье',
    translationEn: 'sommelier',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5900,
    exampleFr: 'Le sommelier a recommandé un Chablis pour accompagner les huîtres.',
    exampleRu: 'Сомелье порекомендовал Шабли к устрицам.',
    exampleEn: 'The sommelier recommended a Chablis to accompany the oysters.',
  },
  {
    french: 'le maître d\'hôtel',
    translation: 'метрдотель',
    translationEn: 'maître d\'hôtel, head waiter',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Le maître d\'hôtel gère la salle et accueille les clients.',
    exampleRu: 'Метрдотель управляет залом и принимает гостей.',
    exampleEn: 'The maître d\'hôtel manages the dining room and welcomes guests.',
  },
  {
    french: 'le menu dégustation',
    translation: 'дегустационное меню',
    translationEn: 'tasting menu',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le menu dégustation comprend sept plats et des accords mets-vins.',
    exampleRu: 'Дегустационное меню включает семь блюд и сочетание вин.',
    exampleEn: 'The tasting menu includes seven courses and wine pairings.',
  },
  {
    french: 'la mise en bouche',
    translation: 'закуска перед едой (аперитивная)',
    translationEn: 'amuse-bouche',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 7000,
    exampleFr: 'La mise en bouche préparait les papilles pour les plats suivants.',
    exampleRu: 'Закуска подготовила вкусовые рецепторы к последующим блюдам.',
    exampleEn: 'The amuse-bouche prepared the palate for the following courses.',
  },
  {
    french: 'le chef étoilé',
    translation: 'шеф-повар со звездой Мишлен',
    translationEn: 'Michelin-starred chef',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Le chef étoilé a ouvert une nouvelle adresse dans le seizième arrondissement.',
    exampleRu: 'Шеф-повар со звездой Мишлен открыл новый ресторан в шестнадцатом округе.',
    exampleEn: 'The Michelin-starred chef opened a new restaurant in the 16th arrondissement.',
  },
  {
    french: 'la saveur',
    translation: 'вкус, вкусовые качества',
    translationEn: 'flavour, taste',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'Les épices rehaussent les saveurs du plat.',
    exampleRu: 'Специи подчёркивают вкус блюда.',
    exampleEn: 'Spices enhance the flavours of the dish.',
  },
  {
    french: 'les aromates',
    translation: 'ароматические травы и специи',
    translationEn: 'aromatic herbs and spices',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6200,
    exampleFr: 'Le thym, le laurier et le persil sont des aromates classiques.',
    exampleRu: 'Тимьян, лавровый лист и петрушка — классические ароматические травы.',
    exampleEn: 'Thyme, bay leaf and parsley are classic aromatic herbs.',
  },
  // ── Vie quotidienne / Bien-être ──
  {
    french: 'la sédentarité',
    translation: 'малоподвижный образ жизни',
    translationEn: 'sedentary lifestyle',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La sédentarité augmente le risque de maladies cardiovasculaires.',
    exampleRu: 'Малоподвижный образ жизни повышает риск сердечно-сосудистых заболеваний.',
    exampleEn: 'A sedentary lifestyle increases the risk of cardiovascular disease.',
  },
  {
    french: 'l\'activité physique',
    translation: 'физическая активность',
    translationEn: 'physical activity',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4400,
    exampleFr: 'Trente minutes d\'activité physique par jour réduisent le stress.',
    exampleRu: 'Тридцать минут физической активности в день снижают стресс.',
    exampleEn: 'Thirty minutes of physical activity a day reduces stress.',
  },
  {
    french: 'l\'ergonomie',
    translation: 'эргономика',
    translationEn: 'ergonomics',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'L\'ergonomie du poste de travail prévient les troubles musculo-squelettiques.',
    exampleRu: 'Эргономика рабочего места предотвращает мышечно-скелетные расстройства.',
    exampleEn: 'Workplace ergonomics prevents musculoskeletal disorders.',
  },
  {
    french: 'la pleine conscience',
    translation: 'осознанность, майндфулнесс',
    translationEn: 'mindfulness',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La pleine conscience réduit l\'anxiété selon de nombreuses études.',
    exampleRu: 'Осознанность снижает тревогу согласно многим исследованиям.',
    exampleEn: 'Mindfulness reduces anxiety according to many studies.',
  },
  {
    french: 'le jeûne intermittent',
    translation: 'интервальное голодание',
    translationEn: 'intermittent fasting',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le jeûne intermittent est populaire mais doit être pratiqué avec précaution.',
    exampleRu: 'Интервальное голодание популярно, но требует осторожного подхода.',
    exampleEn: 'Intermittent fasting is popular but must be practised with caution.',
  },
  {
    french: 'le cholestérol',
    translation: 'холестерин',
    translationEn: 'cholesterol',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Un excès de cholestérol favorise les maladies cardiaques.',
    exampleRu: 'Избыток холестерина способствует сердечным заболеваниям.',
    exampleEn: 'Excess cholesterol promotes heart disease.',
  },
  {
    french: 'la tension artérielle',
    translation: 'артериальное давление',
    translationEn: 'blood pressure',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'Une tension artérielle élevée augmente le risque d\'AVC.',
    exampleRu: 'Высокое артериальное давление увеличивает риск инсульта.',
    exampleEn: 'High blood pressure increases the risk of stroke.',
  },
  {
    french: 'l\'hygiène de vie',
    translation: 'образ жизни (здоровый)',
    translationEn: 'healthy lifestyle',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'Une bonne hygiène de vie inclut le sommeil, l\'alimentation et l\'exercice.',
    exampleRu: 'Хороший образ жизни включает сон, питание и физические упражнения.',
    exampleEn: 'A good lifestyle includes sleep, diet and exercise.',
  },
  {
    french: 'les fibres alimentaires',
    translation: 'пищевые волокна',
    translationEn: 'dietary fibre',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'Les fibres alimentaires favorisent le transit intestinal.',
    exampleRu: 'Пищевые волокна способствуют кишечному транзиту.',
    exampleEn: 'Dietary fibre promotes intestinal transit.',
  },
  {
    french: 'le stress chronique',
    translation: 'хронический стресс',
    translationEn: 'chronic stress',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le stress chronique affaiblit le système immunitaire.',
    exampleRu: 'Хронический стресс ослабляет иммунную систему.',
    exampleEn: 'Chronic stress weakens the immune system.',
  },
  {
    french: 'le sommeil réparateur',
    translation: 'восстанавливающий сон',
    translationEn: 'restorative sleep',
    category: 'health',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Un sommeil réparateur est indispensable à la récupération physique et mentale.',
    exampleRu: 'Восстанавливающий сон необходим для физического и ментального восстановления.',
    exampleEn: 'Restorative sleep is essential for physical and mental recovery.',
  },
  // ── Logement et vie domestique ──
  {
    french: 'la copropriété',
    translation: 'совладение; многоквартирный дом',
    translationEn: 'co-ownership; condominium',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'La copropriété implique des charges partagées entre tous les propriétaires.',
    exampleRu: 'Совладение предполагает общие расходы для всех собственников.',
    exampleEn: 'Co-ownership involves shared charges among all owners.',
  },
  {
    french: 'le syndic de copropriété',
    translation: 'управляющая компания (многоквартирного дома)',
    translationEn: 'property management company',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le syndic de copropriété gère l\'entretien des parties communes.',
    exampleRu: 'Управляющая компания занимается содержанием общих частей.',
    exampleEn: 'The property management company maintains the common areas.',
  },
  {
    french: 'les charges locatives',
    translation: 'коммунальные платежи (аренда)',
    translationEn: 'service charges, rental charges',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5700,
    exampleFr: 'Le loyer est de huit cents euros hors charges locatives.',
    exampleRu: 'Аренда составляет восемьсот евро без коммунальных платежей.',
    exampleEn: 'The rent is eight hundred euros excluding service charges.',
  },
  {
    french: 'l\'assurance habitation',
    translation: 'страховка жилья',
    translationEn: 'home insurance',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'L\'assurance habitation est obligatoire pour tout locataire.',
    exampleRu: 'Страховка жилья обязательна для каждого арендатора.',
    exampleEn: 'Home insurance is compulsory for every tenant.',
  },
  {
    french: 'la rénovation énergétique',
    translation: 'энергетическая реновация',
    translationEn: 'energy renovation',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La rénovation énergétique des logements réduit les factures et les émissions.',
    exampleRu: 'Энергетическая реновация жилья снижает счета и выбросы.',
    exampleEn: 'Energy renovation of housing reduces bills and emissions.',
  },
  {
    french: 'le diagnostic de performance énergétique',
    translation: 'диагностика энергоэффективности жилья (ДПЭ)',
    translationEn: 'energy performance certificate (DPE)',
    category: 'housing',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6800,
    exampleFr: 'Le diagnostic de performance énergétique est obligatoire pour vendre ou louer.',
    exampleRu: 'Диагностика энергоэффективности обязательна при продаже или аренде.',
    exampleEn: 'The energy performance certificate is compulsory for selling or renting.',
  },
  {
    french: 'la pâtisserie artisanale',
    translation: 'ремесленная кондитерская',
    translationEn: 'artisan pastry shop',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La pâtisserie artisanale valorise les recettes traditionnelles.',
    exampleRu: 'Ремесленная кондитерская ценит традиционные рецепты.',
    exampleEn: 'The artisan pastry shop values traditional recipes.',
  },
  {
    french: 'la charcuterie',
    translation: 'мясная гастрономия; колбасная лавка',
    translationEn: 'charcuterie, deli meats',
    category: 'gastronomy',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'La charcuterie française compte des dizaines de spécialités régionales.',
    exampleRu: 'Французская мясная гастрономия насчитывает десятки региональных специалитетов.',
    exampleEn: 'French charcuterie includes dozens of regional specialities.',
  },
];
