export const wordsB2Extra7 = [
  // Politique nationale avancée
  { french: 'le suffrage universel', translation: 'всеобщее избирательное право', translationEn: 'universal suffrage', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le suffrage universel garantit le droit de vote à tous.', exampleRu: 'Всеобщее избирательное право гарантирует право голоса для всех.', exampleEn: 'Universal suffrage guarantees the right to vote for all.' },
  { french: 'la séparation des pouvoirs', translation: 'разделение властей', translationEn: 'separation of powers', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La séparation des pouvoirs est un principe démocratique.', exampleRu: 'Разделение властей — демократический принцип.', exampleEn: 'The separation of powers is a democratic principle.' },
  { french: 'l\'État de droit', translation: 'правовое государство', translationEn: 'rule of law', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'État de droit garantit l\'égalité devant la loi.', exampleRu: 'Правовое государство гарантирует равенство перед законом.', exampleEn: 'The rule of law guarantees equality before the law.' },
  { french: 'la démocratie participative', translation: 'партиципаторная демократия', translationEn: 'participatory democracy', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les citoyens réclament plus de démocratie participative.', exampleRu: 'Граждане требуют большей партиципаторной демократии.', exampleEn: 'Citizens demand more participatory democracy.' },
  { french: 'le plébiscite', translation: 'плебисцит; референдум', translationEn: 'plebiscite; referendum', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le plébiscite a approuvé la réforme constitutionnelle.', exampleRu: 'Плебисцит одобрил конституционную реформу.', exampleEn: 'The plebiscite approved the constitutional reform.' },
  { french: 'l\'oligarchie', translation: 'олигархия', translationEn: 'oligarchy', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Certains accusent le pouvoir d\'être une oligarchie.', exampleRu: 'Некоторые обвиняют власть в том, что она является олигархией.', exampleEn: 'Some accuse the government of being an oligarchy.' },
  { french: 'la technocratie', translation: 'технократия', translationEn: 'technocracy', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La technocratie est critiquée pour son manque de légitimité.', exampleRu: 'Технократия критикуется за недостаток легитимности.', exampleEn: 'Technocracy is criticized for its lack of legitimacy.' },
  { french: 'le mandat', translation: 'мандат; срок (политический)', translationEn: 'mandate; term', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Il a exercé son mandat pendant cinq ans.', exampleRu: 'Он исполнял свой мандат пять лет.', exampleEn: 'He served his mandate for five years.' },
  { french: 'la légitimité', translation: 'легитимность', translationEn: 'legitimacy', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La légitimité du gouvernement est contestée.', exampleRu: 'Легитимность правительства оспаривается.', exampleEn: 'The legitimacy of the government is contested.' },
  { french: 'l\'alternance', translation: 'смена власти', translationEn: 'change in power; alternation', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'alternance démocratique est un signe de bonne santé politique.', exampleRu: 'Демократическая смена власти — признак политического здоровья.', exampleEn: 'Democratic alternation in power is a sign of political health.' },

  // Diplomatie internationale
  { french: 'la souveraineté nationale', translation: 'национальный суверенитет', translationEn: 'national sovereignty', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La souveraineté nationale est un principe du droit international.', exampleRu: 'Национальный суверенитет — принцип международного права.', exampleEn: 'National sovereignty is a principle of international law.' },
  { french: 'l\'ingérence', translation: 'вмешательство (во внутренние дела)', translationEn: 'interference; intervention', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'ONU a condamné l\'ingérence militaire.', exampleRu: 'ООН осудила военное вмешательство.', exampleEn: 'The UN condemned the military interference.' },
  { french: 'la coopération internationale', translation: 'международное сотрудничество', translationEn: 'international cooperation', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La coopération internationale est indispensable face aux crises.', exampleRu: 'Международное сотрудничество необходимо в условиях кризисов.', exampleEn: 'International cooperation is indispensable in crises.' },
  { french: 'le multilatéralisme', translation: 'многостороннее сотрудничество', translationEn: 'multilateralism', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le multilatéralisme est menacé par les nationalismes.', exampleRu: 'Многостороннее сотрудничество под угрозой из-за национализма.', exampleEn: 'Multilateralism is threatened by nationalisms.' },
  { french: 'le bilatéralisme', translation: 'двустороннее сотрудничество', translationEn: 'bilateralism', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les deux pays privilégient le bilatéralisme.', exampleRu: 'Обе страны отдают предпочтение двустороннему сотрудничеству.', exampleEn: 'The two countries prefer bilateralism.' },
  { french: 'l\'ambassade', translation: 'посольство', translationEn: 'embassy', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'ambassade française est fermée ce jour férié.', exampleRu: 'Французское посольство закрыто в праздничный день.', exampleEn: 'The French embassy is closed on this holiday.' },
  { french: 'l\'ambassadeur', translation: 'посол', translationEn: 'ambassador', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'ambassadeur a été convoqué par le ministre.', exampleRu: 'Посол был вызван министром.', exampleEn: 'The ambassador was summoned by the minister.' },
  { french: 'le sommet', translation: 'саммит; встреча на высшем уровне', translationEn: 'summit', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le sommet du G20 se tient cette semaine.', exampleRu: 'Саммит G20 проходит на этой неделе.', exampleEn: 'The G20 summit is taking place this week.' },
  { french: 'le traité', translation: 'договор; соглашение', translationEn: 'treaty', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le traité de paix a été signé après de longs mois.', exampleRu: 'Мирный договор был подписан после долгих месяцев.', exampleEn: 'The peace treaty was signed after long months.' },
  { french: 'les sanctions', translation: 'санкции', translationEn: 'sanctions', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Des sanctions économiques ont été imposées au régime.', exampleRu: 'На режим были наложены экономические санкции.', exampleEn: 'Economic sanctions were imposed on the regime.' },
  { french: 'le veto', translation: 'вето', translationEn: 'veto', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'La Russie a opposé son veto à la résolution.', exampleRu: 'Россия наложила вето на резолюцию.', exampleEn: 'Russia vetoed the resolution.' },
  { french: 'la résolution', translation: 'резолюция', translationEn: 'resolution', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'ONU a adopté une résolution d\'urgence.', exampleRu: 'ООН приняла чрезвычайную резолюцию.', exampleEn: 'The UN adopted an emergency resolution.' },

  // Conflits et sécurité
  { french: 'la guerre asymétrique', translation: 'асимметричная война', translationEn: 'asymmetric warfare', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La guerre asymétrique caractérise les conflits modernes.', exampleRu: 'Асимметричная война характеризует современные конфликты.', exampleEn: 'Asymmetric warfare characterizes modern conflicts.' },
  { french: 'la guérilla', translation: 'партизанская война', translationEn: 'guerrilla warfare', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les rebelles mènent une guérilla dans la jungle.', exampleRu: 'Повстанцы ведут партизанскую войну в джунглях.', exampleEn: 'The rebels wage guerrilla warfare in the jungle.' },
  { french: 'le cessez-le-feu', translation: 'прекращение огня', translationEn: 'ceasefire', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Un cessez-le-feu a été négocié après des semaines de combats.', exampleRu: 'Перемирие было достигнуто после недель боёв.', exampleEn: 'A ceasefire was negotiated after weeks of fighting.' },
  { french: 'l\'armistice', translation: 'перемирие; перемирное соглашение', translationEn: 'armistice', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'armistice de 1918 a mis fin à la Première Guerre mondiale.', exampleRu: 'Перемирие 1918 года положило конец Первой мировой войне.', exampleEn: 'The 1918 armistice ended World War I.' },
  { french: 'le génocide', translation: 'геноцид', translationEn: 'genocide', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le génocide arménien est reconnu par plusieurs pays.', exampleRu: 'Армянский геноцид признан рядом стран.', exampleEn: 'The Armenian genocide is recognized by several countries.' },
  { french: 'les réfugiés', translation: 'беженцы', translationEn: 'refugees', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Des millions de réfugiés ont fui leur pays.', exampleRu: 'Миллионы беженцев покинули свои страны.', exampleEn: 'Millions of refugees fled their countries.' },
  { french: 'l\'asile politique', translation: 'политическое убежище', translationEn: 'political asylum', category: 'politics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Il a demandé l\'asile politique en France.', exampleRu: 'Он попросил политического убежища во Франции.', exampleEn: 'He applied for political asylum in France.' },

  // Relations et institutions internationales
  { french: 'le droit international', translation: 'международное право', translationEn: 'international law', category: 'law', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le droit international régit les relations entre États.', exampleRu: 'Международное право регулирует отношения между государствами.', exampleEn: 'International law governs relations between states.' },
  { french: 'la juridiction internationale', translation: 'международная юрисдикция', translationEn: 'international jurisdiction', category: 'law', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La Cour pénale internationale a une juridiction mondiale.', exampleRu: 'Международный уголовный суд имеет мировую юрисдикцию.', exampleEn: 'The International Criminal Court has global jurisdiction.' },
  { french: 'l\'ONG', translation: 'НКО; неправительственная организация', translationEn: 'NGO', category: 'politics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'ONG a dénoncé les violations des droits de l\'homme.', exampleRu: 'НКО осудила нарушения прав человека.', exampleEn: 'The NGO denounced human rights violations.' },
  { french: 'le droit humanitaire', translation: 'гуманитарное право', translationEn: 'humanitarian law', category: 'law', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le droit humanitaire protège les civils en temps de guerre.', exampleRu: 'Гуманитарное право защищает мирных жителей в военное время.', exampleEn: 'Humanitarian law protects civilians in wartime.' },

  // Verbes politiques
  { french: 'ratifier', translation: 'ратифицировать', translationEn: 'to ratify', category: 'politics', partOfSpeech: 'verb', exampleFr: 'L\'Assemblée a ratifié le traité international.', exampleRu: 'Ассамблея ратифицировала международный договор.', exampleEn: 'The Assembly ratified the international treaty.' },
  { french: 'abroger', translation: 'отменять (закон)', translationEn: 'to repeal', category: 'law', partOfSpeech: 'verb', exampleFr: 'Ce gouvernement a abrogé la loi controversée.', exampleRu: 'Это правительство отменило спорный закон.', exampleEn: 'This government repealed the controversial law.' },
  { french: 'promulguer', translation: 'обнародовать; ввести в действие (закон)', translationEn: 'to promulgate', category: 'law', partOfSpeech: 'verb', exampleFr: 'Le président a promulgué la loi sur le climat.', exampleRu: 'Президент обнародовал закон об изменении климата.', exampleEn: 'The president promulgated the climate law.' },
  { french: 'déposer', translation: 'вносить (поправку, законопроект)', translationEn: 'to table; to file', category: 'politics', partOfSpeech: 'verb', exampleFr: 'L\'opposition a déposé une motion de censure.', exampleRu: 'Оппозиция внесла вотум недоверия.', exampleEn: 'The opposition tabled a motion of no confidence.' },
  { french: 'dissoudre', translation: 'распускать (парламент)', translationEn: 'to dissolve', category: 'politics', partOfSpeech: 'verb', exampleFr: 'Le président a dissous l\'Assemblée nationale.', exampleRu: 'Президент распустил Национальную ассамблею.', exampleEn: 'The president dissolved the National Assembly.' },
  { french: 'coopérer', translation: 'сотрудничать', translationEn: 'to cooperate', category: 'politics', partOfSpeech: 'verb', exampleFr: 'Les pays membres doivent coopérer plus étroitement.', exampleRu: 'Государства-члены должны сотрудничать теснее.', exampleEn: 'Member states must cooperate more closely.' },
  { french: 'arbitrer', translation: 'разрешать спор; арбитрировать', translationEn: 'to arbitrate; to mediate', category: 'politics', partOfSpeech: 'verb', exampleFr: 'L\'ONU tente d\'arbitrer le conflit.', exampleRu: 'ООН пытается урегулировать конфликт.', exampleEn: 'The UN tries to arbitrate the conflict.' },

  // Adjectifs politiques
  { french: 'souverain', translation: 'суверенный', translationEn: 'sovereign', category: 'politics', partOfSpeech: 'adjective', exampleFr: 'Chaque État souverain définit sa propre politique.', exampleRu: 'Каждое суверенное государство определяет собственную политику.', exampleEn: 'Each sovereign state defines its own policy.' },
  { french: 'parlementaire', translation: 'парламентский', translationEn: 'parliamentary', category: 'politics', partOfSpeech: 'adjective', exampleFr: 'Le régime parlementaire donne plus de pouvoir au parlement.', exampleRu: 'Парламентский режим даёт больше власти парламенту.', exampleEn: 'The parliamentary regime gives more power to parliament.' },
  { french: 'présidentiel', translation: 'президентский', translationEn: 'presidential', category: 'politics', partOfSpeech: 'adjective', exampleFr: 'La France a un régime semi-présidentiel.', exampleRu: 'Франция имеет полупрезидентский режим.', exampleEn: 'France has a semi-presidential system.' },
  { french: 'laïc', translation: 'светский; мирской', translationEn: 'secular; lay', category: 'politics', partOfSpeech: 'adjective', exampleFr: 'L\'école publique est laïque en France.', exampleRu: 'Государственная школа во Франции светская.', exampleEn: 'Public school in France is secular.' },
];
