export const wordsB2Extra18 = [
  // ── Psychanalyse ──
  {
    french: 'le refoulement',
    translation: 'вытеснение (психоанализ)',
    translationEn: 'repression (psychoanalysis)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Le refoulement enfouit les souvenirs douloureux dans l\'inconscient.',
    exampleRu: 'Вытеснение погружает болезненные воспоминания в подсознание.',
    exampleEn: 'Repression buries painful memories in the unconscious.',
  },
  {
    french: 'la projection',
    translation: 'проекция (психол.)',
    translationEn: 'projection (psychological)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'La projection consiste à attribuer à l\'autre ses propres sentiments.',
    exampleRu: 'Проекция состоит в приписывании другому собственных чувств.',
    exampleEn: 'Projection consists in attributing one\'s own feelings to others.',
  },
  {
    french: 'le transfert',
    translation: 'перенос (психоанализ)',
    translationEn: 'transference (psychoanalysis)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Le transfert est un phénomène central dans la relation thérapeutique.',
    exampleRu: 'Перенос — центральное явление в терапевтических отношениях.',
    exampleEn: 'Transference is a central phenomenon in the therapeutic relationship.',
  },
  {
    french: 'la sublimation',
    translation: 'сублимация',
    translationEn: 'sublimation',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La sublimation transforme les pulsions en activités socialement valorisées.',
    exampleRu: 'Сублимация преобразует влечения в социально ценные виды деятельности.',
    exampleEn: 'Sublimation transforms drives into socially valued activities.',
  },
  {
    french: 'le narcissisme',
    translation: 'нарциссизм',
    translationEn: 'narcissism',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Le narcissisme pathologique empêche toute relation authentique.',
    exampleRu: 'Патологический нарциссизм исключает подлинные отношения.',
    exampleEn: 'Pathological narcissism prevents any authentic relationship.',
  },
  // ── Biais cognitifs ──
  {
    french: 'le biais de confirmation',
    translation: 'предвзятость подтверждения, confirmation bias',
    translationEn: 'confirmation bias',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6500,
    exampleFr: 'Le biais de confirmation nous pousse à ne retenir que ce qui confirme nos croyances.',
    exampleRu: 'Предвзятость подтверждения заставляет нас замечать лишь то, что подтверждает наши убеждения.',
    exampleEn: 'Confirmation bias leads us to retain only what confirms our beliefs.',
  },
  {
    french: 'l\'effet de halo',
    translation: 'эффект ореола',
    translationEn: 'halo effect',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6800,
    exampleFr: 'L\'effet de halo amène à juger quelqu\'un positivement sur la seule base de son apparence.',
    exampleRu: 'Эффект ореола заставляет положительно оценивать человека только по его внешности.',
    exampleEn: 'The halo effect leads to judging someone positively based solely on their appearance.',
  },
  {
    french: 'l\'ancrage cognitif',
    translation: 'когнитивная привязка',
    translationEn: 'anchoring bias',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 7000,
    exampleFr: 'L\'ancrage cognitif influence les négociations commerciales dès le premier chiffre cité.',
    exampleRu: 'Когнитивная привязка влияет на коммерческие переговоры с первой названной цифры.',
    exampleEn: 'Anchoring bias influences commercial negotiations from the first figure mentioned.',
  },
  {
    french: 'la dissonance cognitive',
    translation: 'когнитивный диссонанс',
    translationEn: 'cognitive dissonance',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6400,
    exampleFr: 'La dissonance cognitive crée un malaise quand actes et valeurs se contredisent.',
    exampleRu: 'Когнитивный диссонанс вызывает дискомфорт, когда поступки и ценности противоречат друг другу.',
    exampleEn: 'Cognitive dissonance creates discomfort when actions and values contradict each other.',
  },
  // ── Relations interpersonnelles ──
  {
    french: 'l\'ambivalence',
    translation: 'амбивалентность',
    translationEn: 'ambivalence',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'Il éprouve une ambivalence profonde envers sa famille.',
    exampleRu: 'Он испытывает глубокую амбивалентность по отношению к семье.',
    exampleEn: 'He feels a profound ambivalence towards his family.',
  },
  {
    french: 'la dépendance affective',
    translation: 'эмоциональная зависимость',
    translationEn: 'emotional dependency',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6300,
    exampleFr: 'La dépendance affective entraîne souvent des relations déséquilibrées.',
    exampleRu: 'Эмоциональная зависимость нередко приводит к несбалансированным отношениям.',
    exampleEn: 'Emotional dependency often leads to unbalanced relationships.',
  },
  {
    french: 'l\'emprise',
    translation: 'эмоциональный контроль, эмпрайз',
    translationEn: 'emotional hold, coercive control',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'La victime peine à se libérer de l\'emprise de son partenaire.',
    exampleRu: 'Жертве сложно освободиться от эмоционального контроля партнёра.',
    exampleEn: 'The victim struggles to free herself from her partner\'s coercive control.',
  },
  {
    french: 'le gaslighting',
    translation: 'газлайтинг',
    translationEn: 'gaslighting',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 7000,
    exampleFr: 'Le gaslighting consiste à faire douter la victime de sa propre perception.',
    exampleRu: 'Газлайтинг состоит в том, чтобы заставить жертву сомневаться в своём восприятии.',
    exampleEn: 'Gaslighting consists in making the victim doubt their own perception.',
  },
  {
    french: 'le conformisme',
    translation: 'конформизм',
    translationEn: 'conformism',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5300,
    exampleFr: 'Le conformisme social pousse à s\'aligner sur les comportements du groupe.',
    exampleRu: 'Социальный конформизм побуждает следовать поведению группы.',
    exampleEn: 'Social conformism pushes us to align with group behaviour.',
  },
  {
    french: 'le bouc émissaire',
    translation: 'козёл отпущения',
    translationEn: 'scapegoat',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'Il a été désigné comme bouc émissaire par tout le groupe.',
    exampleRu: 'Он был назначен козлом отпущения всей группой.',
    exampleEn: 'He was designated as the scapegoat by the whole group.',
  },
  {
    french: 'la dynamique de groupe',
    translation: 'групповая динамика',
    translationEn: 'group dynamics',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La dynamique de groupe influence fortement les prises de décision collectives.',
    exampleRu: 'Групповая динамика сильно влияет на коллективное принятие решений.',
    exampleEn: 'Group dynamics strongly influence collective decision-making.',
  },
  // ── États émotionnels ──
  {
    french: 'la culpabilité',
    translation: 'чувство вины',
    translationEn: 'guilt',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'La culpabilité excessive peut paralyser la capacité d\'action.',
    exampleRu: 'Чрезмерное чувство вины способно парализовать способность к действию.',
    exampleEn: 'Excessive guilt can paralyse the capacity to act.',
  },
  {
    french: 'la honte',
    translation: 'стыд',
    translationEn: 'shame',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3200,
    exampleFr: 'La honte est une émotion sociale liée au regard d\'autrui.',
    exampleRu: 'Стыд — это социальная эмоция, связанная с взглядом других.',
    exampleEn: 'Shame is a social emotion linked to how others see us.',
  },
  {
    french: 'la rancœur',
    translation: 'злопамятность, затаённая обида',
    translationEn: 'rancour, resentment',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5500,
    exampleFr: 'La rancœur non exprimée empoisonne les relations sur le long terme.',
    exampleRu: 'Невысказанная злопамятность отравляет отношения в долгосрочной перспективе.',
    exampleEn: 'Unexpressed rancour poisons relationships over the long term.',
  },
  {
    french: 'la rumination',
    translation: 'руминация (навязчивые мысли)',
    translationEn: 'rumination (obsessive thinking)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'La rumination mentale est un facteur de risque pour la dépression.',
    exampleRu: 'Ментальная руминация является фактором риска депрессии.',
    exampleEn: 'Mental rumination is a risk factor for depression.',
  },
  {
    french: 'la catharsis',
    translation: 'катарсис',
    translationEn: 'catharsis',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6000,
    exampleFr: 'La catharsis permet de libérer des émotions refoulées.',
    exampleRu: 'Катарсис позволяет высвободить подавленные эмоции.',
    exampleEn: 'Catharsis allows repressed emotions to be released.',
  },
  {
    french: 'l\'introspection',
    translation: 'интроспекция, самонаблюдение',
    translationEn: 'introspection',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5700,
    exampleFr: 'L\'introspection aide à mieux comprendre ses propres motivations.',
    exampleRu: 'Интроспекция помогает лучше понять собственные мотивы.',
    exampleEn: 'Introspection helps to better understand one\'s own motivations.',
  },
  {
    french: 'l\'auto-sabotage',
    translation: 'самосаботаж',
    translationEn: 'self-sabotage',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 7000,
    exampleFr: 'L\'auto-sabotage empêche de réaliser son plein potentiel.',
    exampleRu: 'Самосаботаж мешает реализовать свой полный потенциал.',
    exampleEn: 'Self-sabotage prevents one from realising one\'s full potential.',
  },
  {
    french: 'la régulation émotionnelle',
    translation: 'эмоциональная регуляция',
    translationEn: 'emotional regulation',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6800,
    exampleFr: 'La régulation émotionnelle s\'apprend dès l\'enfance.',
    exampleRu: 'Эмоциональная регуляция усваивается с раннего детства.',
    exampleEn: 'Emotional regulation is learnt from early childhood.',
  },
  {
    french: 'l\'intelligence émotionnelle',
    translation: 'эмоциональный интеллект',
    translationEn: 'emotional intelligence',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'L\'intelligence émotionnelle est aussi importante que le QI dans le monde professionnel.',
    exampleRu: 'Эмоциональный интеллект так же важен, как IQ в профессиональной среде.',
    exampleEn: 'Emotional intelligence is as important as IQ in the professional world.',
  },
  {
    french: 'la communication non-violente',
    translation: 'ненасильственное общение',
    translationEn: 'nonviolent communication (NVC)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'La communication non-violente transforme les conflits en dialogue.',
    exampleRu: 'Ненасильственное общение превращает конфликты в диалог.',
    exampleEn: 'Nonviolent communication transforms conflicts into dialogue.',
  },
  // ── Thérapies ──
  {
    french: 'la thérapie cognitivo-comportementale',
    translation: 'когнитивно-поведенческая терапия (КПТ)',
    translationEn: 'cognitive-behavioural therapy (CBT)',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'La thérapie cognitivo-comportementale est efficace contre les phobies.',
    exampleRu: 'Когнитивно-поведенческая терапия эффективна против фобий.',
    exampleEn: 'Cognitive-behavioural therapy is effective against phobias.',
  },
  {
    french: 'la psychothérapie',
    translation: 'психотерапия',
    translationEn: 'psychotherapy',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'La psychothérapie peut durer plusieurs années selon les besoins.',
    exampleRu: 'Психотерапия может длиться несколько лет в зависимости от потребностей.',
    exampleEn: 'Psychotherapy can last several years depending on needs.',
  },
  {
    french: 'le perfectionnisme',
    translation: 'перфекционизм',
    translationEn: 'perfectionism',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5900,
    exampleFr: 'Le perfectionnisme excessif est source de stress et de procrastination.',
    exampleRu: 'Чрезмерный перфекционизм является источником стресса и прокрастинации.',
    exampleEn: 'Excessive perfectionism is a source of stress and procrastination.',
  },
  {
    french: 'la procrastination',
    translation: 'прокрастинация',
    translationEn: 'procrastination',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'La procrastination est souvent liée à la peur de l\'échec.',
    exampleRu: 'Прокрастинация часто связана со страхом неудачи.',
    exampleEn: 'Procrastination is often linked to a fear of failure.',
  },
  {
    french: 'l\'assertivité',
    translation: 'ассертивность, уверенность в себе',
    translationEn: 'assertiveness',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6700,
    exampleFr: 'L\'assertivité permet d\'exprimer ses besoins sans agressivité ni soumission.',
    exampleRu: 'Ассертивность позволяет выражать свои потребности без агрессии и без подчинения.',
    exampleEn: 'Assertiveness allows one to express one\'s needs without aggression or submission.',
  },
  {
    french: 'la co-dépendance',
    translation: 'созависимость',
    translationEn: 'co-dependency',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6800,
    exampleFr: 'La co-dépendance se caractérise par un besoin excessif de l\'autre.',
    exampleRu: 'Созависимость характеризуется чрезмерной потребностью в другом человеке.',
    exampleEn: 'Co-dependency is characterised by an excessive need for the other.',
  },
  {
    french: 'le deuil',
    translation: 'горе, скорбь; траур',
    translationEn: 'grief, mourning',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3500,
    exampleFr: 'Le deuil est un processus naturel qui prend du temps.',
    exampleRu: 'Горевание — это естественный процесс, который требует времени.',
    exampleEn: 'Grief is a natural process that takes time.',
  },
  {
    french: 'la vulnérabilité',
    translation: 'уязвимость',
    translationEn: 'vulnerability',
    category: 'psychology',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4300,
    exampleFr: 'Reconnaître sa vulnérabilité est le premier pas vers la guérison.',
    exampleRu: 'Признание своей уязвимости — первый шаг к исцелению.',
    exampleEn: 'Recognising one\'s vulnerability is the first step towards healing.',
  },
];
