export const wordsA1Extra5 = [
  // === PLACES IN THE CITY ===
  { french: 'banque', translation: 'банк', translationEn: 'bank', category: 'places_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1480, exampleFr: 'Je vais à la banque retirer de l\'argent.', exampleRu: 'Я иду в банк снять деньги.', exampleEn: 'I am going to the bank to withdraw money.' },
  { french: 'supermarché', translation: 'супермаркет', translationEn: 'supermarket', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1490, exampleFr: 'Je fais mes courses au supermarché.', exampleRu: 'Я делаю покупки в супермаркете.', exampleEn: 'I do my shopping at the supermarket.' },
  { french: 'hôpital', translation: 'больница', translationEn: 'hospital', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1500, exampleFr: 'Il est à l\'hôpital depuis deux jours.', exampleRu: 'Он в больнице уже два дня.', exampleEn: 'He has been in the hospital for two days.' },
  { french: 'musée', translation: 'музей', translationEn: 'museum', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1510, exampleFr: 'Nous visitons le musée du Louvre.', exampleRu: 'Мы посещаем музей Лувр.', exampleEn: 'We visit the Louvre museum.' },
  { french: 'église', translation: 'церковь', translationEn: 'church', category: 'places_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1520, exampleFr: 'L\'église est au centre du village.', exampleRu: 'Церковь находится в центре деревни.', exampleEn: 'The church is in the center of the village.' },
  { french: 'parc', translation: 'парк', translationEn: 'park', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1530, exampleFr: 'Les enfants jouent dans le parc.', exampleRu: 'Дети играют в парке.', exampleEn: 'The children play in the park.' },
  { french: 'piscine', translation: 'бассейн', translationEn: 'swimming pool', category: 'places_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1540, exampleFr: 'Je vais à la piscine le jeudi.', exampleRu: 'По четвергам я хожу в бассейн.', exampleEn: 'I go to the swimming pool on Thursdays.' },
  { french: 'gare', translation: 'вокзал, станция', translationEn: 'train station', category: 'places_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1550, exampleFr: 'Le train part de la gare à midi.', exampleRu: 'Поезд отправляется с вокзала в полдень.', exampleEn: 'The train leaves the station at noon.' },
  { french: 'cinéma', translation: 'кинотеатр, кино', translationEn: 'cinema, movie theater', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1560, exampleFr: 'On va au cinéma ce soir ?', exampleRu: 'Мы идём в кино сегодня вечером?', exampleEn: 'Are we going to the cinema tonight?' },
  { french: 'médecin', translation: 'врач, доктор', translationEn: 'doctor, physician', category: 'places_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1570, exampleFr: 'Je dois voir un médecin aujourd\'hui.', exampleRu: 'Мне нужно сегодня попасть к врачу.', exampleEn: 'I need to see a doctor today.' },

  // === CLOTHES EXTRA ===
  { french: 'jean', translation: 'джинсы', translationEn: 'jeans', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1580, exampleFr: 'Il porte un jean bleu et un t-shirt.', exampleRu: 'Он носит синие джинсы и футболку.', exampleEn: 'He is wearing blue jeans and a t-shirt.' },
  { french: 'short', translation: 'шорты', translationEn: 'shorts', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1590, exampleFr: 'En été, je mets un short.', exampleRu: 'Летом я надеваю шорты.', exampleEn: 'In summer, I wear shorts.' },
  { french: 'costume', translation: 'костюм (деловой)', translationEn: 'suit', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1600, exampleFr: 'Il porte un costume noir pour le travail.', exampleRu: 'На работу он надевает чёрный костюм.', exampleEn: 'He wears a black suit for work.' },
  { french: 'cravate', translation: 'галстук', translationEn: 'tie, necktie', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1610, exampleFr: 'Il porte une cravate rouge.', exampleRu: 'Он носит красный галстук.', exampleEn: 'He is wearing a red tie.' },
  { french: 'sandales', translation: 'сандалии', translationEn: 'sandals', category: 'clothes_extra', partOfSpeech: 'noun', frequencyRank: 1620, exampleFr: 'Elle met ses sandales pour la plage.', exampleRu: 'Она надевает сандалии для пляжа.', exampleEn: 'She puts on her sandals for the beach.' },
  { french: 'bottes', translation: 'сапоги, ботинки', translationEn: 'boots', category: 'clothes_extra', partOfSpeech: 'noun', frequencyRank: 1630, exampleFr: 'Elle porte des bottes en cuir.', exampleRu: 'Она носит кожаные сапоги.', exampleEn: 'She is wearing leather boots.' },
  { french: 'maillot', translation: 'купальник, майка, форма', translationEn: 'swimsuit, jersey', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1640, exampleFr: 'N\'oublie pas ton maillot de bain.', exampleRu: 'Не забудь купальник.', exampleEn: 'Don\'t forget your swimsuit.' },
  { french: 'gilet', translation: 'жилет, кардиган', translationEn: 'waistcoat, cardigan, vest', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1650, exampleFr: 'Il fait frais, prends un gilet.', exampleRu: 'Прохладно, возьми жилет.', exampleEn: 'It is cool, take a cardigan.' },
  { french: 'pyjama', translation: 'пижама', translationEn: 'pyjamas, pajamas', category: 'clothes_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1660, exampleFr: 'Je mets mon pyjama pour dormir.', exampleRu: 'Я надеваю пижаму, чтобы спать.', exampleEn: 'I put on my pyjamas to sleep.' },

  // === DAILY PHRASES ===
  { french: 'bonne nuit', translation: 'спокойной ночи', translationEn: 'good night', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1670, exampleFr: 'Bonne nuit, dors bien !', exampleRu: 'Спокойной ночи, спи хорошо!', exampleEn: 'Good night, sleep well!' },
  { french: 'bonne soirée', translation: 'хорошего вечера', translationEn: 'have a good evening', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1680, exampleFr: 'À demain, bonne soirée !', exampleRu: 'До завтра, хорошего вечера!', exampleEn: 'See you tomorrow, have a good evening!' },
  { french: 'à demain', translation: 'до завтра', translationEn: 'see you tomorrow', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1690, exampleFr: 'À demain à neuf heures !', exampleRu: 'До завтра в девять часов!', exampleEn: 'See you tomorrow at nine!' },
  { french: 'pas mal', translation: 'неплохо', translationEn: 'not bad', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1700, exampleFr: '— Comment ça va ? — Pas mal, merci.', exampleRu: '— Как дела? — Неплохо, спасибо.', exampleEn: '— How are you? — Not bad, thanks.' },
  { french: 'comme ci comme ça', translation: 'так себе, сносно', translationEn: 'so-so', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1710, exampleFr: '— Tu aimes ce film ? — Comme ci comme ça.', exampleRu: '— Тебе нравится этот фильм? — Так себе.', exampleEn: '— Do you like this film? — So-so.' },
  { french: 'avec plaisir', translation: 'с удовольствием', translationEn: 'with pleasure, gladly', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1720, exampleFr: '— Tu peux m\'aider ? — Avec plaisir !', exampleRu: '— Можешь мне помочь? — С удовольствием!', exampleEn: '— Can you help me? — With pleasure!' },
  { french: 'de rien', translation: 'пожалуйста (в ответ на спасибо)', translationEn: 'you\'re welcome, don\'t mention it', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1730, exampleFr: '— Merci beaucoup ! — De rien !', exampleRu: '— Большое спасибо! — Пожалуйста!', exampleEn: '— Thank you so much! — You\'re welcome!' },
  { french: 'il n\'y a pas de quoi', translation: 'не за что', translationEn: 'don\'t mention it, no problem', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1740, exampleFr: '— Merci ! — Il n\'y a pas de quoi !', exampleRu: '— Спасибо! — Не за что!', exampleEn: '— Thanks! — Don\'t mention it!' },
  { french: 'je voudrais', translation: 'я хотел(а) бы', translationEn: 'I would like', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1750, exampleFr: 'Je voudrais un café, s\'il vous plaît.', exampleRu: 'Я хотел бы кофе, пожалуйста.', exampleEn: 'I would like a coffee, please.' },
  { french: 'c\'est combien', translation: 'сколько это стоит', translationEn: 'how much is it', category: 'daily_phrases', partOfSpeech: 'phrase', frequencyRank: 1760, exampleFr: 'C\'est combien ce livre ?', exampleRu: 'Сколько стоит эта книга?', exampleEn: 'How much is this book?' },

  // === FOOD EXTRA ===
  { french: 'confiture', translation: 'варенье, джем', translationEn: 'jam, preserve', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1770, exampleFr: 'Je mange du pain avec de la confiture.', exampleRu: 'Я ем хлеб с вареньем.', exampleEn: 'I eat bread with jam.' },
  { french: 'croissant', translation: 'круассан', translationEn: 'croissant', category: 'food_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1780, exampleFr: 'Le matin, je mange un croissant.', exampleRu: 'По утрам я ем круассан.', exampleEn: 'In the morning, I eat a croissant.' },
  { french: 'baguette', translation: 'багет', translationEn: 'baguette', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1790, exampleFr: 'Les Français achètent une baguette chaque jour.', exampleRu: 'Французы покупают багет каждый день.', exampleEn: 'The French buy a baguette every day.' },
  { french: 'pizza', translation: 'пицца', translationEn: 'pizza', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1800, exampleFr: 'On commande une pizza pour ce soir ?', exampleRu: 'Закажем пиццу на сегодняшний вечер?', exampleEn: 'Shall we order a pizza for tonight?' },
  { french: 'pâtes', translation: 'паста, макароны', translationEn: 'pasta', category: 'food_extra', partOfSpeech: 'noun', frequencyRank: 1810, exampleFr: 'Les pâtes sont faciles à préparer.', exampleRu: 'Макароны легко приготовить.', exampleEn: 'Pasta is easy to prepare.' },
  { french: 'riz', translation: 'рис', translationEn: 'rice', category: 'food_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1820, exampleFr: 'Le riz est un aliment de base en Asie.', exampleRu: 'Рис — основной продукт питания в Азии.', exampleEn: 'Rice is a staple food in Asia.' },
  { french: 'moutarde', translation: 'горчица', translationEn: 'mustard', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1830, exampleFr: 'La moutarde de Dijon est célèbre.', exampleRu: 'Дижонская горчица знаменита.', exampleEn: 'Dijon mustard is famous.' },
  { french: 'crêpe', translation: 'блин, крепп', translationEn: 'crepe', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1840, exampleFr: 'On fait des crêpes à la Chandeleur.', exampleRu: 'На Сретение делают блины.', exampleEn: 'We make crepes on Candlemas.' },
  { french: 'galette', translation: 'галет, лепёшка', translationEn: 'galette, flat cake', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1850, exampleFr: 'La galette bretonne est à base de sarrasin.', exampleRu: 'Бретонский галет сделан из гречневой муки.', exampleEn: 'The Breton galette is made from buckwheat.' },
  { french: 'quiche', translation: 'киш (пирог с начинкой)', translationEn: 'quiche', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1860, exampleFr: 'La quiche lorraine est un plat traditionnel.', exampleRu: 'Киш лорен — традиционное блюдо.', exampleEn: 'Quiche lorraine is a traditional dish.' },
  { french: 'brioche', translation: 'бриошь', translationEn: 'brioche', category: 'food_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1870, exampleFr: 'La brioche est un pain brioché sucré.', exampleRu: 'Бриошь — сдобная булочка.', exampleEn: 'Brioche is a sweet enriched bread.' },

  // === DIRECTIONS EXTRA ===
  { french: 'tourner', translation: 'поворачивать', translationEn: 'to turn', category: 'directions_extra', partOfSpeech: 'verb', frequencyRank: 1880, exampleFr: 'Tournez à droite au carrefour.', exampleRu: 'Поверните направо на перекрёстке.', exampleEn: 'Turn right at the crossroads.' },
  { french: 'feu rouge', translation: 'светофор', translationEn: 'traffic light', category: 'directions_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1890, exampleFr: 'Attendez au feu rouge.', exampleRu: 'Подождите у светофора.', exampleEn: 'Wait at the traffic light.' },
  { french: 'panneau', translation: 'знак, указатель, вывеска', translationEn: 'sign, road sign', category: 'directions_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1900, exampleFr: 'Suivez les panneaux pour le centre-ville.', exampleRu: 'Следуйте указателям в центр города.', exampleEn: 'Follow the signs to the city centre.' },
  { french: 'rue', translation: 'улица', translationEn: 'street', category: 'directions_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1910, exampleFr: 'La boulangerie est dans cette rue.', exampleRu: 'Булочная находится на этой улице.', exampleEn: 'The bakery is on this street.' },
  { french: 'avenue', translation: 'авеню, проспект', translationEn: 'avenue', category: 'directions_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1920, exampleFr: 'Les Champs-Élysées est une avenue célèbre.', exampleRu: 'Елисейские Поля — знаменитый проспект.', exampleEn: 'The Champs-Élysées is a famous avenue.' },
  { french: 'boulevard', translation: 'бульвар', translationEn: 'boulevard', category: 'directions_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1930, exampleFr: 'Le café est sur le boulevard principal.', exampleRu: 'Кафе находится на главном бульваре.', exampleEn: 'The café is on the main boulevard.' },
  { french: 'chemin', translation: 'дорожка, путь, дорога', translationEn: 'path, way, road', category: 'directions_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1940, exampleFr: 'Quel chemin prendre pour la gare ?', exampleRu: 'Какой путь выбрать до вокзала?', exampleEn: 'Which way should I take to the station?' },
  { french: 'distance', translation: 'расстояние', translationEn: 'distance', category: 'directions_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1950, exampleFr: 'La distance entre Paris et Lyon est de 470 km.', exampleRu: 'Расстояние от Парижа до Лиона — 470 км.', exampleEn: 'The distance from Paris to Lyon is 470 km.' },

  // === BASIC SPORTS ===
  { french: 'football', translation: 'футбол', translationEn: 'football, soccer', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1960, exampleFr: 'Il joue au football chaque week-end.', exampleRu: 'Он играет в футбол каждые выходные.', exampleEn: 'He plays football every weekend.' },
  { french: 'tennis', translation: 'теннис', translationEn: 'tennis', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1970, exampleFr: 'Elle joue au tennis depuis l\'enfance.', exampleRu: 'Она играет в теннис с детства.', exampleEn: 'She has been playing tennis since childhood.' },
  { french: 'basket', translation: 'баскетбол', translationEn: 'basketball', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1980, exampleFr: 'Ils jouent au basket dans le gymnase.', exampleRu: 'Они играют в баскетбол в спортзале.', exampleEn: 'They play basketball in the gym.' },
  { french: 'natation', translation: 'плавание', translationEn: 'swimming', category: 'sports_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1990, exampleFr: 'La natation est bonne pour la santé.', exampleRu: 'Плавание полезно для здоровья.', exampleEn: 'Swimming is good for your health.' },
  { french: 'vélo', translation: 'велосипед, езда на велосипеде', translationEn: 'bicycle, cycling', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2000, exampleFr: 'Je vais au travail à vélo.', exampleRu: 'Я езжу на работу на велосипеде.', exampleEn: 'I cycle to work.' },
  { french: 'yoga', translation: 'йога', translationEn: 'yoga', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2010, exampleFr: 'Elle fait du yoga tous les matins.', exampleRu: 'Она занимается йогой каждое утро.', exampleEn: 'She does yoga every morning.' },
  { french: 'danse', translation: 'танец, танцы', translationEn: 'dance, dancing', category: 'sports_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2020, exampleFr: 'Elle prend des cours de danse.', exampleRu: 'Она берёт уроки танцев.', exampleEn: 'She takes dance classes.' },
  { french: 'golf', translation: 'гольф', translationEn: 'golf', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2030, exampleFr: 'Mon père joue au golf le samedi.', exampleRu: 'Мой отец играет в гольф по субботам.', exampleEn: 'My father plays golf on Saturdays.' },
  { french: 'rugby', translation: 'регби', translationEn: 'rugby', category: 'sports_basic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2040, exampleFr: 'Le rugby est populaire dans le sud de la France.', exampleRu: 'Регби популярно на юге Франции.', exampleEn: 'Rugby is popular in the south of France.' },
  { french: 'escalade', translation: 'скалолазание, подъём', translationEn: 'climbing, rock climbing', category: 'sports_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2050, exampleFr: 'Il fait de l\'escalade en montagne.', exampleRu: 'Он занимается скалолазанием в горах.', exampleEn: 'He goes rock climbing in the mountains.' },
  { french: 'randonnée', translation: 'поход, пешая прогулка', translationEn: 'hiking, trek', category: 'sports_basic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2060, exampleFr: 'On part en randonnée ce dimanche.', exampleRu: 'В это воскресенье мы идём в поход.', exampleEn: 'We are going hiking this Sunday.' },

  // === HEALTH BASIC ===
  { french: 'blessé', translation: 'раненый, пострадавший', translationEn: 'injured, wounded', category: 'health_basic', partOfSpeech: 'adjective', frequencyRank: 2070, exampleFr: 'Il est blessé au genou.', exampleRu: 'У него травма колена.', exampleEn: 'He has an injured knee.' },
  { french: 'éternuer', translation: 'чихать', translationEn: 'to sneeze', category: 'health_basic', partOfSpeech: 'verb', frequencyRank: 2080, exampleFr: 'Il éternue à cause de son allergie.', exampleRu: 'Он чихает из-за аллергии.', exampleEn: 'He sneezes because of his allergy.' },

  // === ADJECTIVES EXTRA ===
  { french: 'épais', translation: 'толстый, густой', translationEn: 'thick', category: 'adjectives_extra', partOfSpeech: 'adjective', frequencyRank: 2090, exampleFr: 'La soupe est épaisse et chaude.', exampleRu: 'Суп густой и горячий.', exampleEn: 'The soup is thick and hot.' },
  { french: 'fin', translation: 'тонкий, изысканный', translationEn: 'thin, fine, delicate', category: 'adjectives_extra', partOfSpeech: 'adjective', frequencyRank: 2100, exampleFr: 'La tranche est très fine.', exampleRu: 'Ломтик очень тонкий.', exampleEn: 'The slice is very thin.' },
  { french: 'dur', translation: 'твёрдый, жёсткий, трудный', translationEn: 'hard, tough, difficult', category: 'adjectives_extra', partOfSpeech: 'adjective', frequencyRank: 2110, exampleFr: 'Ce travail est dur mais intéressant.', exampleRu: 'Эта работа трудная, но интересная.', exampleEn: 'This work is hard but interesting.' },

  // === REFLEXIVE VERBS EXTRA ===
  { french: 'se taire', translation: 'замолчать, молчать', translationEn: 'to be quiet, to shut up', category: 'reflexive_verbs_extra', partOfSpeech: 'verb', frequencyRank: 2120, exampleFr: 'Taisez-vous, s\'il vous plaît !', exampleRu: 'Замолчите, пожалуйста!', exampleEn: 'Please be quiet!' },
];
