export const wordsB2Extra9 = [
  // Environnement et climat avancés
  { french: 'le changement climatique', translation: 'изменение климата', translationEn: 'climate change', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le changement climatique affecte tous les continents.', exampleRu: 'Изменение климата затрагивает все континенты.', exampleEn: 'Climate change affects all continents.' },
  { french: 'le réchauffement climatique', translation: 'глобальное потепление', translationEn: 'global warming', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le réchauffement climatique menace les espèces polaires.', exampleRu: 'Глобальное потепление угрожает полярным видам.', exampleEn: 'Global warming threatens polar species.' },
  { french: 'l\'empreinte carbone', translation: 'углеродный след', translationEn: 'carbon footprint', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Chacun peut réduire son empreinte carbone.', exampleRu: 'Каждый может снизить свой углеродный след.', exampleEn: 'Everyone can reduce their carbon footprint.' },
  { french: 'les gaz à effet de serre', translation: 'парниковые газы', translationEn: 'greenhouse gases', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les gaz à effet de serre réchauffent la planète.', exampleRu: 'Парниковые газы нагревают планету.', exampleEn: 'Greenhouse gases are warming the planet.' },
  { french: 'la neutralité carbone', translation: 'углеродная нейтральность', translationEn: 'carbon neutrality', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'UE vise la neutralité carbone d\'ici 2050.', exampleRu: 'ЕС стремится к углеродной нейтральности к 2050 году.', exampleEn: 'The EU aims for carbon neutrality by 2050.' },
  { french: 'la déforestation', translation: 'обезлесение; вырубка лесов', translationEn: 'deforestation', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La déforestation de l\'Amazonie s\'accélère.', exampleRu: 'Обезлесение Амазонии ускоряется.', exampleEn: 'Deforestation of the Amazon is accelerating.' },
  { french: 'la biodiversité', translation: 'биоразнообразие', translationEn: 'biodiversity', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La biodiversité est menacée par l\'activité humaine.', exampleRu: 'Биоразнообразие находится под угрозой из-за деятельности человека.', exampleEn: 'Biodiversity is threatened by human activity.' },
  { french: 'l\'extinction', translation: 'вымирание', translationEn: 'extinction', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Nous vivons la sixième extinction de masse.', exampleRu: 'Мы переживаем шестое массовое вымирание.', exampleEn: 'We are experiencing the sixth mass extinction.' },
  { french: 'la pollution des sols', translation: 'загрязнение почвы', translationEn: 'soil pollution', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La pollution des sols touche les cultures agricoles.', exampleRu: 'Загрязнение почвы затрагивает сельскохозяйственные культуры.', exampleEn: 'Soil pollution affects agricultural crops.' },
  { french: 'la pollution atmosphérique', translation: 'загрязнение воздуха', translationEn: 'air pollution', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La pollution atmosphérique tue chaque année des millions de personnes.', exampleRu: 'Загрязнение воздуха ежегодно убивает миллионы людей.', exampleEn: 'Air pollution kills millions of people every year.' },
  { french: 'la sécheresse', translation: 'засуха', translationEn: 'drought', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La sécheresse prolongée a ravagé les récoltes.', exampleRu: 'Затяжная засуха опустошила урожай.', exampleEn: 'The prolonged drought devastated the harvests.' },
  { french: 'l\'inondation', translation: 'наводнение; затопление', translationEn: 'flood', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Des inondations catastrophiques ont touché le pays.', exampleRu: 'Катастрофические наводнения затронули страну.', exampleEn: 'Catastrophic floods hit the country.' },
  { french: 'la canicule', translation: 'жара; зной; волна тепла', translationEn: 'heat wave', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La canicule de cet été a battu des records.', exampleRu: 'Летняя жара этого года побила рекорды.', exampleEn: 'This summer\'s heat wave broke records.' },
  { french: 'l\'érosion', translation: 'эрозия', translationEn: 'erosion', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'érosion côtière menace les habitations.', exampleRu: 'Береговая эрозия угрожает жилью.', exampleEn: 'Coastal erosion threatens homes.' },

  // Écologie et durabilité
  { french: 'le développement durable', translation: 'устойчивое развитие', translationEn: 'sustainable development', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le développement durable concilie économie et écologie.', exampleRu: 'Устойчивое развитие сочетает экономику и экологию.', exampleEn: 'Sustainable development reconciles economy and ecology.' },
  { french: 'l\'économie circulaire', translation: 'циклическая экономика', translationEn: 'circular economy', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'économie circulaire réduit les déchets.', exampleRu: 'Циклическая экономика сокращает отходы.', exampleEn: 'The circular economy reduces waste.' },
  { french: 'la sobriété énergétique', translation: 'энергетическая трезвость; бережливость', translationEn: 'energy sobriety', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La sobriété énergétique consiste à consommer moins.', exampleRu: 'Энергетическая трезвость означает потреблять меньше.', exampleEn: 'Energy sobriety consists of consuming less.' },
  { french: 'le recyclage', translation: 'переработка; рециклинг', translationEn: 'recycling', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le recyclage des plastiques reste insuffisant.', exampleRu: 'Переработка пластика остаётся недостаточной.', exampleEn: 'Plastic recycling remains insufficient.' },
  { french: 'le compostage', translation: 'компостирование', translationEn: 'composting', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le compostage des déchets organiques enrichit le sol.', exampleRu: 'Компостирование органических отходов обогащает почву.', exampleEn: 'Composting organic waste enriches the soil.' },
  { french: 'la reforestation', translation: 'лесовосстановление', translationEn: 'reforestation', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La reforestation aide à absorber le CO2.', exampleRu: 'Лесовосстановление помогает поглощать CO2.', exampleEn: 'Reforestation helps absorb CO2.' },
  { french: 'la compensation carbone', translation: 'углеродная компенсация', translationEn: 'carbon offsetting', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La compensation carbone est une mesure transitoire.', exampleRu: 'Углеродная компенсация — переходная мера.', exampleEn: 'Carbon offsetting is a transitional measure.' },
  { french: 'le marché du carbone', translation: 'углеродный рынок', translationEn: 'carbon market', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le marché du carbone fixe un prix aux émissions.', exampleRu: 'Углеродный рынок устанавливает цену на выбросы.', exampleEn: 'The carbon market puts a price on emissions.' },

  // Agriculture et alimentation durable
  { french: 'l\'agriculture biologique', translation: 'органическое земледелие', translationEn: 'organic farming', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'agriculture biologique exclut les pesticides de synthèse.', exampleRu: 'Органическое земледелие исключает синтетические пестициды.', exampleEn: 'Organic farming excludes synthetic pesticides.' },
  { french: 'l\'agroécologie', translation: 'агроэкология', translationEn: 'agroecology', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'agroécologie préserve les sols et les écosystèmes.', exampleRu: 'Агроэкология сохраняет почвы и экосистемы.', exampleEn: 'Agroecology preserves soils and ecosystems.' },
  { french: 'les circuits courts', translation: 'короткие цепочки поставок', translationEn: 'short supply chains', category: 'environment', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les circuits courts réduisent l\'empreinte carbone alimentaire.', exampleRu: 'Короткие цепочки поставок сокращают углеродный след питания.', exampleEn: 'Short supply chains reduce the food carbon footprint.' },
  { french: 'la permaculture', translation: 'пермакультура', translationEn: 'permaculture', category: 'environment', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La permaculture s\'inspire des écosystèmes naturels.', exampleRu: 'Пермакультура черпает вдохновение из природных экосистем.', exampleEn: 'Permaculture draws inspiration from natural ecosystems.' },

  // Verbes environnementaux
  { french: 'polluer', translation: 'загрязнять', translationEn: 'to pollute', category: 'environment', partOfSpeech: 'verb', exampleFr: 'Les usines polluent la rivière depuis des décennies.', exampleRu: 'Заводы загрязняют реку уже десятилетия.', exampleEn: 'The factories have been polluting the river for decades.' },
  { french: 'dégrader', translation: 'разрушать; деградировать', translationEn: 'to degrade', category: 'environment', partOfSpeech: 'verb', exampleFr: 'L\'activité humaine dégrade les écosystèmes côtiers.', exampleRu: 'Деятельность человека деградирует прибрежные экосистемы.', exampleEn: 'Human activity degrades coastal ecosystems.' },
  { french: 'préserver', translation: 'сохранять; беречь', translationEn: 'to preserve', category: 'environment', partOfSpeech: 'verb', exampleFr: 'Il faut préserver les forêts tropicales.', exampleRu: 'Необходимо сохранять тропические леса.', exampleEn: 'Tropical forests must be preserved.' },
  { french: 'reboisser', translation: 'проводить лесовосстановление', translationEn: 'to reforest', category: 'environment', partOfSpeech: 'verb', exampleFr: 'Le gouvernement s\'engage à reboiser des milliers d\'hectares.', exampleRu: 'Правительство обязуется провести лесовосстановление на тысячах гектаров.', exampleEn: 'The government commits to reforesting thousands of hectares.' },
  { french: 'décarboner', translation: 'декарбонизировать', translationEn: 'to decarbonize', category: 'environment', partOfSpeech: 'verb', exampleFr: 'L\'objectif est de décarboner l\'économie d\'ici 2050.', exampleRu: 'Цель — декарбонизировать экономику к 2050 году.', exampleEn: 'The goal is to decarbonize the economy by 2050.' },
  { french: 'recycler', translation: 'перерабатывать', translationEn: 'to recycle', category: 'environment', partOfSpeech: 'verb', exampleFr: 'Il est important de recycler le verre et le papier.', exampleRu: 'Важно перерабатывать стекло и бумагу.', exampleEn: 'It is important to recycle glass and paper.' },

  // Adjectifs environnementaux
  { french: 'durable', translation: 'устойчивый; экологичный', translationEn: 'sustainable', category: 'environment', partOfSpeech: 'adjective', exampleFr: 'Nous cherchons un mode de vie plus durable.', exampleRu: 'Мы ищем более устойчивый образ жизни.', exampleEn: 'We are looking for a more sustainable lifestyle.' },
  { french: 'écologique', translation: 'экологический', translationEn: 'ecological', category: 'environment', partOfSpeech: 'adjective', exampleFr: 'Les transports écologiques se développent.', exampleRu: 'Экологический транспорт развивается.', exampleEn: 'Ecological transport is developing.' },
  { french: 'renouvelable', translation: 'возобновляемый', translationEn: 'renewable', category: 'environment', partOfSpeech: 'adjective', exampleFr: 'L\'énergie renouvelable est une solution d\'avenir.', exampleRu: 'Возобновляемая энергия — решение будущего.', exampleEn: 'Renewable energy is a future solution.' },
  { french: 'irréversible', translation: 'необратимый', translationEn: 'irreversible', category: 'environment', partOfSpeech: 'adjective', exampleFr: 'Certains dommages climatiques sont irréversibles.', exampleRu: 'Некоторые климатические повреждения необратимы.', exampleEn: 'Some climate damage is irreversible.' },
  { french: 'vulnérable', translation: 'уязвимый', translationEn: 'vulnerable', category: 'environment', partOfSpeech: 'adjective', exampleFr: 'Les zones côtières sont vulnérables à la montée des eaux.', exampleRu: 'Прибрежные зоны уязвимы к повышению уровня воды.', exampleEn: 'Coastal areas are vulnerable to rising sea levels.' },

  // Géographie humaine avancée
  { french: 'la métropolisation', translation: 'метрополизация', translationEn: 'metropolization', category: 'geography', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La métropolisation concentre richesse et population.', exampleRu: 'Метрополизация концентрирует богатство и население.', exampleEn: 'Metropolization concentrates wealth and population.' },
  { french: 'la périurbanisation', translation: 'субурбанизация', translationEn: 'suburbanization', category: 'geography', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La périurbanisation accentue l\'étalement urbain.', exampleRu: 'Субурбанизация усиливает городское расползание.', exampleEn: 'Suburbanization intensifies urban sprawl.' },
  { french: 'la densification urbaine', translation: 'уплотнение городской застройки', translationEn: 'urban densification', category: 'geography', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La densification urbaine réduit les déplacements en voiture.', exampleRu: 'Уплотнение городской застройки сокращает поездки на машине.', exampleEn: 'Urban densification reduces car travel.' },
  { french: 'l\'étalement urbain', translation: 'городское расползание', translationEn: 'urban sprawl', category: 'geography', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'étalement urbain consomme des terres agricoles.', exampleRu: 'Городское расползание поглощает сельскохозяйственные угодья.', exampleEn: 'Urban sprawl consumes agricultural land.' },
  { french: 'la gentrification', translation: 'джентрификация', translationEn: 'gentrification', category: 'geography', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La gentrification transforme les quartiers populaires.', exampleRu: 'Джентрификация трансформирует рабочие кварталы.', exampleEn: 'Gentrification transforms working-class neighborhoods.' },
  { french: 'le quartier défavorisé', translation: 'неблагополучный район', translationEn: 'disadvantaged neighborhood', category: 'geography', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les quartiers défavorisés manquent de services.', exampleRu: 'Неблагополучным районам не хватает услуг.', exampleEn: 'Disadvantaged neighborhoods lack services.' },
];
