export const wordsB2Extra5 = [
  // Médecine avancée
  { french: 'le diagnostic', translation: 'диагноз', translationEn: 'diagnosis', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le diagnostic a été posé après plusieurs examens.', exampleRu: 'Диагноз был поставлен после нескольких обследований.', exampleEn: 'The diagnosis was made after several examinations.' },
  { french: 'le pronostic', translation: 'прогноз (медицинский)', translationEn: 'prognosis', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le pronostic vital est engagé.', exampleRu: 'Прогноз для жизни неблагоприятен.', exampleEn: 'The vital prognosis is at stake.' },
  { french: 'la thérapie', translation: 'терапия; лечение', translationEn: 'therapy', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Il suit une thérapie cognitive comportementale.', exampleRu: 'Он проходит когнитивно-поведенческую терапию.', exampleEn: 'He follows cognitive behavioral therapy.' },
  { french: 'l\'immunité', translation: 'иммунитет', translationEn: 'immunity', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La vaccination renforce l\'immunité collective.', exampleRu: 'Вакцинация укрепляет коллективный иммунитет.', exampleEn: 'Vaccination strengthens collective immunity.' },
  { french: 'chronique', translation: 'хронический', translationEn: 'chronic', category: 'health', partOfSpeech: 'adjective', exampleFr: 'Il souffre d\'une maladie chronique.', exampleRu: 'Он страдает хроническим заболеванием.', exampleEn: 'He suffers from a chronic illness.' },
  { french: 'aigu', translation: 'острый (о болезни)', translationEn: 'acute', category: 'health', partOfSpeech: 'adjective', exampleFr: 'Elle a une douleur aiguë dans le dos.', exampleRu: 'У неё острая боль в спине.', exampleEn: 'She has acute back pain.' },
  { french: 'bénin', translation: 'доброкачественный; незначительный', translationEn: 'benign; mild', category: 'health', partOfSpeech: 'adjective', exampleFr: 'La tumeur est bénigne, sans danger.', exampleRu: 'Опухоль доброкачественная, не опасная.', exampleEn: 'The tumor is benign, not dangerous.' },
  { french: 'malin', translation: 'злокачественный', translationEn: 'malignant', category: 'health', partOfSpeech: 'adjective', exampleFr: 'Les cellules malignes se propagent rapidement.', exampleRu: 'Злокачественные клетки быстро распространяются.', exampleEn: 'Malignant cells spread quickly.' },
  { french: 'la pathologie', translation: 'патология', translationEn: 'pathology', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Cette pathologie est encore mal connue.', exampleRu: 'Эта патология ещё недостаточно изучена.', exampleEn: 'This pathology is still poorly understood.' },
  { french: 'la prévention', translation: 'профилактика; предотвращение', translationEn: 'prevention', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La prévention reste la meilleure médecine.', exampleRu: 'Профилактика остаётся лучшей медициной.', exampleEn: 'Prevention remains the best medicine.' },
  { french: 'le dépistage', translation: 'скрининг; ранняя диагностика', translationEn: 'screening; early detection', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le dépistage précoce du cancer sauve des vies.', exampleRu: 'Ранняя диагностика рака спасает жизни.', exampleEn: 'Early cancer screening saves lives.' },
  { french: 'le vaccin', translation: 'вакцина', translationEn: 'vaccine', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le vaccin a été développé en temps record.', exampleRu: 'Вакцина была разработана в рекордно короткие сроки.', exampleEn: 'The vaccine was developed in record time.' },
  { french: 'l\'épidémie', translation: 'эпидемия', translationEn: 'epidemic', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'épidémie de grippe a touché des milliers de personnes.', exampleRu: 'Эпидемия гриппа затронула тысячи людей.', exampleEn: 'The flu epidemic affected thousands of people.' },
  { french: 'la pandémie', translation: 'пандемия', translationEn: 'pandemic', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La pandémie a bouleversé nos habitudes.', exampleRu: 'Пандемия перевернула наши привычки.', exampleEn: 'The pandemic disrupted our habits.' },
  { french: 'la contagion', translation: 'заражение; распространение', translationEn: 'contagion; spread', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les mesures visent à limiter la contagion.', exampleRu: 'Меры направлены на ограничение распространения.', exampleEn: 'The measures aim to limit contagion.' },
  { french: 'l\'antibiothérapie', translation: 'антибиотикотерапия', translationEn: 'antibiotic treatment', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'antibiothérapie prolongée peut causer des résistances.', exampleRu: 'Длительная антибиотикотерапия может вызвать резистентность.', exampleEn: 'Prolonged antibiotic treatment can cause resistance.' },
  { french: 'la résistance aux antibiotiques', translation: 'устойчивость к антибиотикам', translationEn: 'antibiotic resistance', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La résistance aux antibiotiques est une menace mondiale.', exampleRu: 'Устойчивость к антибиотикам — мировая угроза.', exampleEn: 'Antibiotic resistance is a global threat.' },
  { french: 'la chirurgie', translation: 'хирургия; операция', translationEn: 'surgery', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La chirurgie mini-invasive réduit les risques.', exampleRu: 'Малоинвазивная хирургия снижает риски.', exampleEn: 'Minimally invasive surgery reduces risks.' },
  { french: 'la convalescence', translation: 'выздоровление; реабилитация', translationEn: 'convalescence; recovery', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Il est en convalescence après son opération.', exampleRu: 'Он восстанавливается после операции.', exampleEn: 'He is convalescing after his operation.' },
  { french: 'l\'anesthésie', translation: 'анестезия', translationEn: 'anesthesia', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'anesthésie générale est nécessaire pour cette opération.', exampleRu: 'Для этой операции необходим общий наркоз.', exampleEn: 'General anesthesia is required for this operation.' },

  // Corps humain avancé
  { french: 'le système immunitaire', translation: 'иммунная система', translationEn: 'immune system', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Un mode de vie sain renforce le système immunitaire.', exampleRu: 'Здоровый образ жизни укрепляет иммунную систему.', exampleEn: 'A healthy lifestyle strengthens the immune system.' },
  { french: 'le système nerveux', translation: 'нервная система', translationEn: 'nervous system', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le stress affecte le système nerveux central.', exampleRu: 'Стресс воздействует на центральную нервную систему.', exampleEn: 'Stress affects the central nervous system.' },
  { french: 'le métabolisme', translation: 'метаболизм; обмен веществ', translationEn: 'metabolism', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Son métabolisme est particulièrement rapide.', exampleRu: 'Его метаболизм особенно быстрый.', exampleEn: 'His metabolism is particularly fast.' },
  { french: 'les cellules souches', translation: 'стволовые клетки', translationEn: 'stem cells', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La recherche sur les cellules souches est prometteuse.', exampleRu: 'Исследования стволовых клеток перспективны.', exampleEn: 'Stem cell research is promising.' },
  { french: 'l\'ADN', translation: 'ДНК', translationEn: 'DNA', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'analyse ADN a confirmé l\'identité du suspect.', exampleRu: 'Анализ ДНК подтвердил личность подозреваемого.', exampleEn: 'DNA analysis confirmed the suspect\'s identity.' },
  { french: 'génétique', translation: 'генетический', translationEn: 'genetic', category: 'health', partOfSpeech: 'adjective', exampleFr: 'Cette maladie a une composante génétique.', exampleRu: 'Это заболевание имеет генетическую составляющую.', exampleEn: 'This disease has a genetic component.' },

  // Psychologie avancée
  { french: 'le traumatisme', translation: 'травма (психологическая)', translationEn: 'trauma', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le traumatisme de l\'enfance peut affecter toute la vie.', exampleRu: 'Детская травма может влиять на всю жизнь.', exampleEn: 'Childhood trauma can affect one\'s entire life.' },
  { french: 'le mécanisme de défense', translation: 'защитный механизм', translationEn: 'defense mechanism', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le déni est un mécanisme de défense courant.', exampleRu: 'Отрицание — распространённый защитный механизм.', exampleEn: 'Denial is a common defense mechanism.' },
  { french: 'le complexe', translation: 'комплекс (психологический)', translationEn: 'complex', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Il souffre d\'un complexe d\'infériorité.', exampleRu: 'Он страдает комплексом неполноценности.', exampleEn: 'He suffers from an inferiority complex.' },
  { french: 'la névrose', translation: 'невроз', translationEn: 'neurosis', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La névrose obsessionnelle perturbe sa vie quotidienne.', exampleRu: 'Обсессивный невроз нарушает его повседневную жизнь.', exampleEn: 'Obsessive neurosis disrupts his daily life.' },
  { french: 'la psychose', translation: 'психоз', translationEn: 'psychosis', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La psychose implique une rupture avec la réalité.', exampleRu: 'Психоз предполагает разрыв с реальностью.', exampleEn: 'Psychosis involves a break with reality.' },
  { french: 'l\'inconscient', translation: 'бессознательное', translationEn: 'the unconscious', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'inconscient joue un rôle central en psychanalyse.', exampleRu: 'Бессознательное играет центральную роль в психоанализе.', exampleEn: 'The unconscious plays a central role in psychoanalysis.' },
  { french: 'la pulsion', translation: 'влечение; побуждение', translationEn: 'drive; impulse', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les pulsions agressives peuvent être sublimées.', exampleRu: 'Агрессивные влечения можно сублимировать.', exampleEn: 'Aggressive drives can be sublimated.' },
  { french: 'l\'estime de soi', translation: 'самооценка', translationEn: 'self-esteem', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Une bonne estime de soi est essentielle au bien-être.', exampleRu: 'Здоровая самооценка необходима для благополучия.', exampleEn: 'Good self-esteem is essential for well-being.' },
  { french: 'le biais cognitif', translation: 'когнитивное искажение', translationEn: 'cognitive bias', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le biais de confirmation est très répandu.', exampleRu: 'Предвзятость подтверждения очень распространена.', exampleEn: 'Confirmation bias is very widespread.' },
  { french: 'l\'empathie', translation: 'эмпатия', translationEn: 'empathy', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'empathie est la capacité de se mettre à la place de l\'autre.', exampleRu: 'Эмпатия — это способность поставить себя на место другого.', exampleEn: 'Empathy is the ability to put oneself in another\'s place.' },
  { french: 'la résilience', translation: 'жизнестойкость; устойчивость', translationEn: 'resilience', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La résilience permet de surmonter les épreuves.', exampleRu: 'Жизнестойкость позволяет преодолевать испытания.', exampleEn: 'Resilience allows one to overcome hardships.' },
  { french: 'le bien-être', translation: 'благополучие; хорошее самочувствие', translationEn: 'well-being', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'entreprise investit dans le bien-être de ses employés.', exampleRu: 'Компания инвестирует в благополучие сотрудников.', exampleEn: 'The company invests in employee well-being.' },
  { french: 'l\'épanouissement', translation: 'самореализация; расцвет', translationEn: 'fulfillment; flourishing', category: 'psychology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'épanouissement personnel est une quête moderne.', exampleRu: 'Личностная самореализация — современный поиск.', exampleEn: 'Personal fulfillment is a modern quest.' },
  { french: 'la souffrance', translation: 'страдание', translationEn: 'suffering', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La souffrance psychique mérite une prise en charge.', exampleRu: 'Психическое страдание требует лечения.', exampleEn: 'Psychological suffering deserves treatment.' },
  { french: 'l\'aliénation', translation: 'отчуждение', translationEn: 'alienation', category: 'psychology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'aliénation au travail est un phénomène étudié.', exampleRu: 'Отчуждение на работе — изучаемый феномен.', exampleEn: 'Work alienation is a studied phenomenon.' },

  // Santé mentale avancée
  { french: 'la dépression', translation: 'депрессия', translationEn: 'depression', category: 'mental_health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La dépression touche des millions de personnes.', exampleRu: 'Депрессия затрагивает миллионы людей.', exampleEn: 'Depression affects millions of people.' },
  { french: 'l\'anxiété', translation: 'тревога; тревожность', translationEn: 'anxiety', category: 'mental_health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'anxiété sociale est fréquente chez les jeunes.', exampleRu: 'Социальная тревожность часто встречается у молодых людей.', exampleEn: 'Social anxiety is common among young people.' },
  { french: 'le burn-out', translation: 'выгорание', translationEn: 'burn-out', category: 'mental_health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le burn-out professionnel est reconnu comme maladie.', exampleRu: 'Профессиональное выгорание признано болезнью.', exampleEn: 'Professional burn-out is recognized as an illness.' },
  { french: 'la phobie', translation: 'фобия', translationEn: 'phobia', category: 'mental_health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Elle a développé une phobie des espaces clos.', exampleRu: 'У неё развилась фобия замкнутых пространств.', exampleEn: 'She developed a phobia of enclosed spaces.' },
  { french: 'le trouble', translation: 'расстройство (психическое)', translationEn: 'disorder', category: 'mental_health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les troubles alimentaires sont complexes à traiter.', exampleRu: 'Расстройства пищевого поведения сложно лечить.', exampleEn: 'Eating disorders are complex to treat.' },
  { french: 'la dépendance', translation: 'зависимость', translationEn: 'addiction; dependence', category: 'mental_health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La dépendance aux écrans inquiète les spécialistes.', exampleRu: 'Зависимость от экранов беспокоит специалистов.', exampleEn: 'Screen addiction worries specialists.' },
  { french: 'l\'addiction', translation: 'аддикция; зависимость', translationEn: 'addiction', category: 'mental_health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'addiction au jeu peut ruiner des vies.', exampleRu: 'Игровая аддикция может разрушить жизни.', exampleEn: 'Gambling addiction can ruin lives.' },

  // Verbes médicaux
  { french: 'diagnostiquer', translation: 'диагностировать', translationEn: 'to diagnose', category: 'health', partOfSpeech: 'verb', exampleFr: 'Le médecin a diagnostiqué une pneumonie.', exampleRu: 'Врач диагностировал пневмонию.', exampleEn: 'The doctor diagnosed pneumonia.' },
  { french: 'prescrire', translation: 'назначать (лечение); предписывать', translationEn: 'to prescribe', category: 'health', partOfSpeech: 'verb', exampleFr: 'Le médecin lui a prescrit des antibiotiques.', exampleRu: 'Врач назначил ему антибиотики.', exampleEn: 'The doctor prescribed him antibiotics.' },
  { french: 'opérer', translation: 'оперировать', translationEn: 'to operate', category: 'health', partOfSpeech: 'verb', exampleFr: 'Les chirurgiens ont opéré pendant cinq heures.', exampleRu: 'Хирурги оперировали пять часов.', exampleEn: 'The surgeons operated for five hours.' },
  { french: 'soigner', translation: 'лечить; ухаживать', translationEn: 'to treat; to care for', category: 'health', partOfSpeech: 'verb', exampleFr: 'Cette infirmière soigne les patients avec dévouement.', exampleRu: 'Эта медсестра самоотверженно ухаживает за пациентами.', exampleEn: 'This nurse cares for patients with dedication.' },
  { french: 'guérir', translation: 'выздоравливать; излечивать', translationEn: 'to heal; to recover', category: 'health', partOfSpeech: 'verb', exampleFr: 'Elle a guéri complètement de son cancer.', exampleRu: 'Она полностью вылечилась от рака.', exampleEn: 'She fully recovered from her cancer.' },
  { french: 'prévenir', translation: 'предотвращать; предупреждать', translationEn: 'to prevent; to warn', category: 'health', partOfSpeech: 'verb', exampleFr: 'Il vaut mieux prévenir que guérir.', exampleRu: 'Лучше предупредить, чем лечить.', exampleEn: 'Prevention is better than cure.' },

  // Système de santé
  { french: 'la médecine généraliste', translation: 'общая медицина', translationEn: 'general medicine', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Il est médecin généraliste depuis vingt ans.', exampleRu: 'Он работает врачом общей практики двадцать лет.', exampleEn: 'He has been a general practitioner for twenty years.' },
  { french: 'le spécialiste', translation: 'врач-специалист', translationEn: 'specialist', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Elle a été orientée vers un spécialiste cardiologue.', exampleRu: 'Её направили к врачу-кардиологу.', exampleEn: 'She was referred to a cardiologist specialist.' },
  { french: 'la mutuelle', translation: 'медицинская страховка', translationEn: 'supplementary health insurance', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La mutuelle rembourse une partie des soins dentaires.', exampleRu: 'Страховка возмещает часть стоматологических расходов.', exampleEn: 'The supplementary insurance reimburses part of dental costs.' },
  { french: 'la prise en charge', translation: 'покрытие расходов; медпомощь', translationEn: 'coverage; care management', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La prise en charge par la Sécu est partielle.', exampleRu: 'Покрытие расходов системой соцстраха частичное.', exampleEn: 'Social security coverage is partial.' },
  { french: 'l\'urgentiste', translation: 'врач скорой помощи', translationEn: 'emergency physician', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les urgentistes sont débordés ce soir.', exampleRu: 'Врачи скорой помощи сегодня вечером завалены работой.', exampleEn: 'Emergency physicians are overwhelmed tonight.' },
  { french: 'le désert médical', translation: 'нехватка врачей (в регионе)', translationEn: 'medical desert; underserved area', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Les zones rurales souffrent de déserts médicaux.', exampleRu: 'Сельские районы страдают от нехватки врачей.', exampleEn: 'Rural areas suffer from a lack of medical services.' },

  // Alimentation et santé
  { french: 'la malnutrition', translation: 'недоедание; неправильное питание', translationEn: 'malnutrition', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La malnutrition infantile reste un défi mondial.', exampleRu: 'Детское недоедание остаётся мировой проблемой.', exampleEn: 'Child malnutrition remains a global challenge.' },
  { french: 'l\'obésité', translation: 'ожирение', translationEn: 'obesity', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'obésité est liée à de nombreuses maladies chroniques.', exampleRu: 'Ожирение связано со многими хроническими заболеваниями.', exampleEn: 'Obesity is linked to many chronic diseases.' },
  { french: 'le microbiote', translation: 'микробиом; микробиота', translationEn: 'microbiome', category: 'health', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le microbiote intestinal influence la santé générale.', exampleRu: 'Кишечный микробиом влияет на общее здоровье.', exampleEn: 'The gut microbiome influences general health.' },
  { french: 'l\'alimentation équilibrée', translation: 'сбалансированное питание', translationEn: 'balanced diet', category: 'health', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Une alimentation équilibrée est la clé de la santé.', exampleRu: 'Сбалансированное питание — ключ к здоровью.', exampleEn: 'A balanced diet is the key to good health.' },
];
