export const wordsB2Extra17 = [
  // ── Verbes de haut registre ──
  {
    french: 'prévaloir',
    translation: 'преобладать, брать верх',
    translationEn: 'to prevail',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5000,
    exampleFr: 'L\'intérêt général doit prévaloir sur les intérêts particuliers.',
    exampleRu: 'Общий интерес должен брать верх над частными интересами.',
    exampleEn: 'The general interest must prevail over private interests.',
  },
  {
    french: 'tempérer',
    translation: 'умерять, смягчать',
    translationEn: 'to temper, to moderate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5800,
    exampleFr: 'Il faut tempérer cet enthousiasme par une analyse plus rigoureuse.',
    exampleRu: 'Следует умерить этот энтузиазм более строгим анализом.',
    exampleEn: 'This enthusiasm must be tempered by more rigorous analysis.',
  },
  {
    french: 'objecter',
    translation: 'возражать',
    translationEn: 'to object, to raise an objection',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5200,
    exampleFr: 'On peut objecter que les données sont insuffisantes pour conclure.',
    exampleRu: 'Можно возразить, что данных недостаточно для вывода.',
    exampleEn: 'One might object that the data are insufficient to draw conclusions.',
  },
  {
    french: 'rétorquer',
    translation: 'парировать, ответить возражением',
    translationEn: 'to retort, to riposte',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5600,
    exampleFr: 'Elle a rétorqué que ses chiffres n\'étaient pas exacts.',
    exampleRu: 'Она парировала, что его цифры неточны.',
    exampleEn: 'She retorted that his figures were not accurate.',
  },
  {
    french: 'trancher',
    translation: 'решать окончательно; резко контрастировать',
    translationEn: 'to settle, to cut through; to stand out',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4500,
    exampleFr: 'Le tribunal doit trancher cette question dans les prochaines semaines.',
    exampleRu: 'Суд должен решить этот вопрос в ближайшие недели.',
    exampleEn: 'The court must settle this issue in the coming weeks.',
  },
  {
    french: 'statuer',
    translation: 'выносить решение (юр., офиц.)',
    translationEn: 'to rule, to adjudicate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5400,
    exampleFr: 'Le Conseil d\'État a statué en faveur du requérant.',
    exampleRu: 'Государственный совет вынес решение в пользу заявителя.',
    exampleEn: 'The Council of State ruled in favour of the applicant.',
  },
  {
    french: 'délibérer',
    translation: 'обсуждать; совещаться (о вынесении решения)',
    translationEn: 'to deliberate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5100,
    exampleFr: 'Le jury a délibéré pendant quatre heures avant de rendre son verdict.',
    exampleRu: 'Жюри совещалось четыре часа перед вынесением вердикта.',
    exampleEn: 'The jury deliberated for four hours before returning its verdict.',
  },
  {
    french: 'discerner',
    translation: 'различать, распознавать',
    translationEn: 'to discern, to distinguish',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5300,
    exampleFr: 'Il est parfois difficile de discerner le vrai du faux.',
    exampleRu: 'Порой трудно отличить правду от лжи.',
    exampleEn: 'It is sometimes difficult to discern the true from the false.',
  },
  {
    french: 'appréhender',
    translation: 'опасаться; постигать, схватывать умом',
    translationEn: 'to dread; to grasp, to apprehend',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4800,
    exampleFr: 'Il est difficile d\'appréhender la complexité de ce phénomène.',
    exampleRu: 'Трудно постичь всю сложность этого явления.',
    exampleEn: 'It is difficult to grasp the complexity of this phenomenon.',
  },
  {
    french: 'décrypter',
    translation: 'расшифровывать; разбираться в чём-л.',
    translationEn: 'to decrypt; to unravel, to decode',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5700,
    exampleFr: 'Ce journaliste sait décrypter les enjeux géopolitiques complexes.',
    exampleRu: 'Этот журналист умеет разбираться в сложных геополитических вопросах.',
    exampleEn: 'This journalist knows how to decode complex geopolitical issues.',
  },
  {
    french: 'élucider',
    translation: 'прояснять, раскрывать (тайну)',
    translationEn: 'to elucidate, to solve',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6000,
    exampleFr: 'L\'enquête n\'a pas réussi à élucider les circonstances de sa mort.',
    exampleRu: 'Расследование не смогло раскрыть обстоятельства его гибели.',
    exampleEn: 'The investigation failed to elucidate the circumstances of his death.',
  },
  {
    french: 's\'avérer',
    translation: 'оказываться (правдой)',
    translationEn: 'to turn out, to prove to be',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4200,
    exampleFr: 'La solution proposée s\'est avérée inefficace en pratique.',
    exampleRu: 'Предложенное решение на практике оказалось неэффективным.',
    exampleEn: 'The proposed solution turned out to be ineffective in practice.',
  },
  {
    french: 'stipuler',
    translation: 'оговаривать, предписывать (в договоре)',
    translationEn: 'to stipulate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5900,
    exampleFr: 'Le contrat stipule que le travail doit être livré avant le quinze.',
    exampleRu: 'Договор предписывает сдать работу до пятнадцатого числа.',
    exampleEn: 'The contract stipulates that the work must be delivered before the 15th.',
  },
  {
    french: 'contrecarrer',
    translation: 'противодействовать, срывать (планы)',
    translationEn: 'to thwart, to counteract',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6200,
    exampleFr: 'L\'opposition a tenté de contrecarrer les réformes du gouvernement.',
    exampleRu: 'Оппозиция пыталась сорвать реформы правительства.',
    exampleEn: 'The opposition tried to thwart the government\'s reforms.',
  },
  {
    french: 'induire en erreur',
    translation: 'вводить в заблуждение',
    translationEn: 'to mislead, to deceive',
    category: 'verbs',
    partOfSpeech: 'expression',
    frequencyRank: 5500,
    exampleFr: 'Ces statistiques risquent d\'induire le lecteur en erreur.',
    exampleRu: 'Эта статистика рискует ввести читателя в заблуждение.',
    exampleEn: 'These statistics risk misleading the reader.',
  },
  {
    french: 's\'affranchir de',
    translation: 'освобождаться от, избавляться от',
    translationEn: 'to free oneself from, to break away from',
    category: 'verbs',
    partOfSpeech: 'expression',
    frequencyRank: 5400,
    exampleFr: 'L\'artiste cherche à s\'affranchir des contraintes du marché.',
    exampleRu: 'Художник стремится освободиться от рыночных ограничений.',
    exampleEn: 'The artist seeks to free himself from market constraints.',
  },
  {
    french: 's\'abstenir',
    translation: 'воздерживаться (от голосования, действий)',
    translationEn: 'to abstain, to refrain',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4600,
    exampleFr: 'Vingt parlementaires se sont abstenus lors du vote.',
    exampleRu: 'Двадцать парламентариев воздержались при голосовании.',
    exampleEn: 'Twenty parliamentarians abstained during the vote.',
  },
  {
    french: 'susciter',
    translation: 'вызывать, порождать (интерес, вопросы)',
    translationEn: 'to arouse, to give rise to',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4000,
    exampleFr: 'Cette déclaration a suscité un vif débat dans l\'opinion publique.',
    exampleRu: 'Это заявление вызвало оживлённые дискуссии в обществе.',
    exampleEn: 'This statement gave rise to a lively debate in public opinion.',
  },
  {
    french: 'engendrer',
    translation: 'порождать, вызывать (последствия)',
    translationEn: 'to engender, to generate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 4700,
    exampleFr: 'La crise a engendré des inégalités sans précédent.',
    exampleRu: 'Кризис породил беспрецедентное неравенство.',
    exampleEn: 'The crisis engendered unprecedented inequalities.',
  },
  {
    french: 'impulser',
    translation: 'придавать импульс, стимулировать',
    translationEn: 'to drive, to give impetus to',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6100,
    exampleFr: 'Ce plan vise à impulser une nouvelle dynamique économique.',
    exampleRu: 'Этот план направлен на придание нового экономического импульса.',
    exampleEn: 'This plan aims to drive a new economic dynamic.',
  },
  {
    french: 'infléchir',
    translation: 'изменять направление; влиять на курс',
    translationEn: 'to bend, to deflect; to influence',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6500,
    exampleFr: 'La pression populaire a infléchi la politique du gouvernement.',
    exampleRu: 'Народное давление изменило политику правительства.',
    exampleEn: 'Popular pressure deflected the government\'s policy.',
  },
  {
    french: 'présupposer',
    translation: 'предполагать заранее',
    translationEn: 'to presuppose',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6300,
    exampleFr: 'Cette démarche présuppose une bonne maîtrise des outils statistiques.',
    exampleRu: 'Этот подход предполагает хорошее владение статистическими инструментами.',
    exampleEn: 'This approach presupposes a good command of statistical tools.',
  },
  {
    french: 'sous-entendre',
    translation: 'подразумевать, намекать',
    translationEn: 'to imply, to insinuate',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 5200,
    exampleFr: 'Sa réponse laisse sous-entendre qu\'il n\'est pas d\'accord.',
    exampleRu: 'Его ответ подразумевает несогласие.',
    exampleEn: 'His answer implies that he disagrees.',
  },
  {
    french: 'entériner',
    translation: 'утверждать официально; закреплять',
    translationEn: 'to endorse officially, to ratify',
    category: 'verbs',
    partOfSpeech: 'verb',
    frequencyRank: 6400,
    exampleFr: 'Le Parlement doit entériner cette décision pour qu\'elle soit applicable.',
    exampleRu: 'Парламент должен официально утвердить это решение, чтобы оно стало применимым.',
    exampleEn: 'Parliament must endorse this decision for it to be applicable.',
  },
  {
    french: 'se soustraire à',
    translation: 'уклоняться от, избегать',
    translationEn: 'to evade, to escape from',
    category: 'verbs',
    partOfSpeech: 'expression',
    frequencyRank: 5800,
    exampleFr: 'Certaines multinationales parviennent à se soustraire à l\'impôt.',
    exampleRu: 'Некоторые транснациональные корпорации умудряются уклоняться от уплаты налогов.',
    exampleEn: 'Some multinationals manage to evade taxation.',
  },
  // ── Expressions formelles ──
  {
    french: 'force est de constater que',
    translation: 'приходится констатировать, что',
    translationEn: 'one cannot but note that',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 6500,
    exampleFr: 'Force est de constater que les résultats sont décevants.',
    exampleRu: 'Приходится констатировать, что результаты разочаровывают.',
    exampleEn: 'One cannot but note that the results are disappointing.',
  },
  {
    french: 'il convient de',
    translation: 'следует, уместно',
    translationEn: 'it is appropriate to, one should',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 5800,
    exampleFr: 'Il convient de nuancer ce jugement trop hâtif.',
    exampleRu: 'Следует смягчить это поспешное суждение.',
    exampleEn: 'It is appropriate to nuance this hasty judgement.',
  },
  {
    french: 'quoi qu\'il en soit',
    translation: 'как бы то ни было',
    translationEn: 'be that as it may, regardless',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 4500,
    exampleFr: 'Quoi qu\'il en soit, une décision doit être prise rapidement.',
    exampleRu: 'Как бы то ни было, решение должно быть принято быстро.',
    exampleEn: 'Be that as it may, a decision must be made quickly.',
  },
  {
    french: 'en tout état de cause',
    translation: 'в любом случае',
    translationEn: 'in any case, at all events',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 5600,
    exampleFr: 'En tout état de cause, cette option n\'est plus envisageable.',
    exampleRu: 'В любом случае эта опция более не рассматривается.',
    exampleEn: 'In any case, this option is no longer viable.',
  },
  {
    french: 'toutes choses égales par ailleurs',
    translation: 'при прочих равных',
    translationEn: 'all things being equal, ceteris paribus',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 6800,
    exampleFr: 'Toutes choses égales par ailleurs, ce modèle donne de bons résultats.',
    exampleRu: 'При прочих равных эта модель даёт хорошие результаты.',
    exampleEn: 'All things being equal, this model produces good results.',
  },
  {
    french: 'dans cette optique',
    translation: 'в этом ракурсе, с этой точки зрения',
    translationEn: 'in this perspective, with this in mind',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 5400,
    exampleFr: 'Dans cette optique, il est crucial de repenser notre stratégie.',
    exampleRu: 'В этом ракурсе крайне важно переосмыслить нашу стратегию.',
    exampleEn: 'With this in mind, it is crucial to rethink our strategy.',
  },
  {
    french: 'à cet égard',
    translation: 'в этом отношении',
    translationEn: 'in this regard, in this respect',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 4800,
    exampleFr: 'À cet égard, les mesures prises restent insuffisantes.',
    exampleRu: 'В этом отношении принятые меры остаются недостаточными.',
    exampleEn: 'In this respect, the measures taken remain insufficient.',
  },
  {
    french: 'au demeurant',
    translation: 'впрочем, к тому же',
    translationEn: 'moreover, for that matter',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 6000,
    exampleFr: 'Au demeurant, cette question dépasse le cadre du présent débat.',
    exampleRu: 'Впрочем, этот вопрос выходит за рамки настоящей дискуссии.',
    exampleEn: 'Moreover, this question goes beyond the scope of the present debate.',
  },
  {
    french: 'de prime abord',
    translation: 'на первый взгляд, поначалу',
    translationEn: 'at first glance, at first sight',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 5700,
    exampleFr: 'De prime abord, la solution semble simple, mais elle cache des difficultés.',
    exampleRu: 'На первый взгляд решение кажется простым, но за ним скрываются трудности.',
    exampleEn: 'At first glance, the solution seems simple, but it hides difficulties.',
  },
  {
    french: 'en l\'occurrence',
    translation: 'в данном случае, здесь',
    translationEn: 'in this case, here',
    category: 'expressions',
    partOfSpeech: 'expression',
    frequencyRank: 4600,
    exampleFr: 'En l\'occurrence, c\'est la loi française qui s\'applique.',
    exampleRu: 'В данном случае применяется французское право.',
    exampleEn: 'In this case, French law applies.',
  },
  {
    french: 'nonobstant',
    translation: 'невзирая на; тем не менее',
    translationEn: 'notwithstanding, nevertheless',
    category: 'expressions',
    partOfSpeech: 'adverb',
    frequencyRank: 7000,
    exampleFr: 'Nonobstant ces difficultés, le projet a été mené à bien.',
    exampleRu: 'Невзирая на эти трудности, проект был успешно завершён.',
    exampleEn: 'Notwithstanding these difficulties, the project was carried through.',
  },
  // ── Adjectifs académiques ──
  {
    french: 'subsidiaire',
    translation: 'вспомогательный, дополнительный',
    translationEn: 'subsidiary, supplementary',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 6200,
    exampleFr: 'La question subsidiaire mérite aussi d\'être examinée.',
    exampleRu: 'Вспомогательный вопрос тоже заслуживает рассмотрения.',
    exampleEn: 'The subsidiary question also deserves examination.',
  },
  {
    french: 'concomitant',
    translation: 'сопутствующий, одновременный',
    translationEn: 'concomitant, concurrent',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 6800,
    exampleFr: 'Ces deux phénomènes sont concomitants et probablement liés.',
    exampleRu: 'Эти два явления сопутствуют друг другу и, вероятно, связаны.',
    exampleEn: 'These two phenomena are concomitant and probably related.',
  },
  {
    french: 'inhérent',
    translation: 'присущий, неотъемлемый',
    translationEn: 'inherent',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 5400,
    exampleFr: 'Le risque est inhérent à toute activité entrepreneuriale.',
    exampleRu: 'Риск неотъемлем от любой предпринимательской деятельности.',
    exampleEn: 'Risk is inherent in all entrepreneurial activity.',
  },
  {
    french: 'normatif',
    translation: 'нормативный',
    translationEn: 'normative',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 6500,
    exampleFr: 'Le discours politique est souvent normatif plutôt que descriptif.',
    exampleRu: 'Политический дискурс часто носит нормативный, а не описательный характер.',
    exampleEn: 'Political discourse is often normative rather than descriptive.',
  },
  {
    french: 'préliminaire',
    translation: 'предварительный',
    translationEn: 'preliminary',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 5000,
    exampleFr: 'Les résultats préliminaires sont encourageants mais doivent être confirmés.',
    exampleRu: 'Предварительные результаты обнадёживают, но требуют подтверждения.',
    exampleEn: 'The preliminary results are encouraging but must be confirmed.',
  },
  {
    french: 'empirique',
    translation: 'эмпирический',
    translationEn: 'empirical',
    category: 'adjectives',
    partOfSpeech: 'adjective',
    frequencyRank: 5800,
    exampleFr: 'Les sciences sociales reposent sur des méthodes empiriques.',
    exampleRu: 'Социальные науки опираются на эмпирические методы.',
    exampleEn: 'Social sciences rely on empirical methods.',
  },
];
