export const wordsB2Extra11 = [
  // ── Procédure pénale ──
  {
    french: 'la plainte',
    translation: 'жалоба, заявление (в полицию)',
    translationEn: 'complaint, police report',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2800,
    exampleFr: 'Elle a déposé une plainte pour harcèlement moral.',
    exampleRu: 'Она подала жалобу по поводу морального харасмента.',
    exampleEn: 'She filed a complaint for moral harassment.',
  },
  {
    french: 'déposer une plainte',
    translation: 'подать заявление в полицию',
    translationEn: 'to file a complaint',
    category: 'law',
    partOfSpeech: 'expression',
    frequencyRank: 3200,
    exampleFr: 'La victime a déposé une plainte dès le lendemain.',
    exampleRu: 'Потерпевший подал заявление уже на следующий день.',
    exampleEn: 'The victim filed a complaint the very next day.',
  },
  {
    french: 'la mise en examen',
    translation: 'предъявление обвинения (фр. право)',
    translationEn: 'formal investigation charge',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'Sa mise en examen pour fraude a provoqué une crise politique.',
    exampleRu: 'Его обвинение в мошенничестве спровоцировало политический кризис.',
    exampleEn: 'His formal charge for fraud triggered a political crisis.',
  },
  {
    french: 'la garde à vue',
    translation: 'задержание, содержание под стражей (до 48 ч.)',
    translationEn: 'police custody',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4500,
    exampleFr: 'Le suspect a été placé en garde à vue pendant vingt-quatre heures.',
    exampleRu: 'Подозреваемый был задержан на двадцать четыре часа.',
    exampleEn: 'The suspect was held in police custody for twenty-four hours.',
  },
  {
    french: 'la détention provisoire',
    translation: 'предварительное заключение',
    translationEn: 'pre-trial detention, remand',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5000,
    exampleFr: 'La détention provisoire ne doit pas dépasser une durée raisonnable.',
    exampleRu: 'Предварительное заключение не должно превышать разумного срока.',
    exampleEn: 'Pre-trial detention must not exceed a reasonable duration.',
  },
  {
    french: 'le mis en examen',
    translation: 'лицо под следствием, обвиняемый',
    translationEn: 'person under formal investigation',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4800,
    exampleFr: 'Le mis en examen a le droit d\'être assisté d\'un avocat.',
    exampleRu: 'Обвиняемый имеет право на помощь адвоката.',
    exampleEn: 'The person under investigation has the right to legal counsel.',
  },
  {
    french: 'le juge d\'instruction',
    translation: 'следственный судья',
    translationEn: 'investigating judge',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4700,
    exampleFr: 'Le juge d\'instruction a ouvert une information judiciaire.',
    exampleRu: 'Следственный судья открыл судебное расследование.',
    exampleEn: 'The investigating judge opened a judicial inquiry.',
  },
  {
    french: 'le procureur',
    translation: 'прокурор',
    translationEn: 'prosecutor, public prosecutor',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3800,
    exampleFr: 'Le procureur a requis cinq ans de prison ferme.',
    exampleRu: 'Прокурор потребовал пяти лет реального заключения.',
    exampleEn: 'The prosecutor requested five years of actual imprisonment.',
  },
  {
    french: 'le greffier',
    translation: 'секретарь суда',
    translationEn: 'court clerk',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'Le greffier consigne les débats dans le procès-verbal.',
    exampleRu: 'Секретарь суда записывает ход заседания в протокол.',
    exampleEn: 'The court clerk records the proceedings in the minutes.',
  },
  {
    french: 'la cour d\'appel',
    translation: 'апелляционный суд',
    translationEn: 'court of appeal',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4400,
    exampleFr: 'L\'affaire a été portée devant la cour d\'appel.',
    exampleRu: 'Дело было передано в апелляционный суд.',
    exampleEn: 'The case was brought before the court of appeal.',
  },
  {
    french: 'la Cour de cassation',
    translation: 'Кассационный суд (высший суд)',
    translationEn: 'Court of Cassation (highest court)',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'La Cour de cassation a cassé l\'arrêt pour vice de procédure.',
    exampleRu: 'Кассационный суд отменил решение по процессуальному нарушению.',
    exampleEn: 'The Court of Cassation quashed the ruling on procedural grounds.',
  },
  // ── Peines et droits ──
  {
    french: 'la condamnation',
    translation: 'обвинительный приговор, осуждение',
    translationEn: 'conviction, sentence',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3500,
    exampleFr: 'Sa condamnation a été confirmée en appel.',
    exampleRu: 'Его приговор был подтверждён в апелляции.',
    exampleEn: 'His conviction was upheld on appeal.',
  },
  {
    french: 'le sursis',
    translation: 'условный срок',
    translationEn: 'suspended sentence',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Il a été condamné à deux ans de prison avec sursis.',
    exampleRu: 'Он был приговорён к двум годам условно.',
    exampleEn: 'He was sentenced to two years with a suspended sentence.',
  },
  {
    french: 'la liberté conditionnelle',
    translation: 'условно-досрочное освобождение',
    translationEn: 'parole, conditional release',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5300,
    exampleFr: 'Il a été libéré sous liberté conditionnelle après trois ans.',
    exampleRu: 'Он был освобождён условно-досрочно через три года.',
    exampleEn: 'He was released on parole after three years.',
  },
  {
    french: 'la récidive',
    translation: 'рецидив (повторное преступление)',
    translationEn: 'recidivism, reoffending',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5100,
    exampleFr: 'La récidive entraîne une aggravation des peines.',
    exampleRu: 'Рецидив влечёт ужесточение наказания.',
    exampleEn: 'Reoffending leads to harsher sentences.',
  },
  {
    french: 'la présomption d\'innocence',
    translation: 'презумпция невиновности',
    translationEn: 'presumption of innocence',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'La présomption d\'innocence est un principe fondamental du droit.',
    exampleRu: 'Презумпция невиновности — основополагающий принцип права.',
    exampleEn: 'The presumption of innocence is a fundamental principle of law.',
  },
  {
    french: 'la prescription',
    translation: 'исковая давность, срок давности',
    translationEn: 'statute of limitations, prescription',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'Les crimes contre l\'humanité sont imprescriptibles.',
    exampleRu: 'Преступления против человечности не имеют срока давности.',
    exampleEn: 'Crimes against humanity are not subject to any statute of limitations.',
  },
  {
    french: 'imprescriptible',
    translation: 'не имеющий срока давности',
    translationEn: 'imprescriptible, not subject to statute of limitations',
    category: 'law',
    partOfSpeech: 'adjective',
    frequencyRank: 6500,
    exampleFr: 'Le génocide est un crime imprescriptible.',
    exampleRu: 'Геноцид является преступлением, не имеющим срока давности.',
    exampleEn: 'Genocide is an imprescriptible crime.',
  },
  // ── Procédure civile ──
  {
    french: 'le litige',
    translation: 'спор, тяжба',
    translationEn: 'dispute, litigation',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4000,
    exampleFr: 'Ce litige commercial a duré trois ans avant d\'être réglé.',
    exampleRu: 'Этот коммерческий спор длился три года, прежде чем был урегулирован.',
    exampleEn: 'This commercial dispute lasted three years before being resolved.',
  },
  {
    french: 'l\'arbitrage',
    translation: 'арбитраж',
    translationEn: 'arbitration',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4200,
    exampleFr: 'Le contrat prévoit un arbitrage international en cas de conflit.',
    exampleRu: 'Договор предусматривает международный арбитраж в случае конфликта.',
    exampleEn: 'The contract provides for international arbitration in case of conflict.',
  },
  {
    french: 'la médiation',
    translation: 'медиация, посредничество',
    translationEn: 'mediation',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3900,
    exampleFr: 'La médiation a permis d\'éviter un procès long et coûteux.',
    exampleRu: 'Медиация позволила избежать длительного и дорогостоящего судебного процесса.',
    exampleEn: 'Mediation made it possible to avoid a long and costly trial.',
  },
  {
    french: 'le notaire',
    translation: 'нотариус',
    translationEn: 'notary',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4100,
    exampleFr: 'La vente de la maison a été signée chez le notaire.',
    exampleRu: 'Продажа дома была подписана у нотариуса.',
    exampleEn: 'The sale of the house was signed at the notary\'s office.',
  },
  {
    french: 'la clause',
    translation: 'пункт, статья (договора)',
    translationEn: 'clause',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3700,
    exampleFr: 'La clause de non-concurrence est valable pendant deux ans.',
    exampleRu: 'Пункт о неконкуренции действует в течение двух лет.',
    exampleEn: 'The non-compete clause is valid for two years.',
  },
  {
    french: 'la résiliation',
    translation: 'расторжение (договора)',
    translationEn: 'termination, cancellation',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4900,
    exampleFr: 'La résiliation du contrat doit être notifiée trois mois à l\'avance.',
    exampleRu: 'Расторжение договора должно быть уведомлено за три месяца.',
    exampleEn: 'Termination of the contract must be notified three months in advance.',
  },
  // ── Verbes juridiques ──
  {
    french: 'plaider',
    translation: 'защищать (в суде); признавать вину',
    translationEn: 'to plead, to argue in court',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 4300,
    exampleFr: 'L\'avocat a plaidé la légitime défense.',
    exampleRu: 'Адвокат привёл доводы в пользу самообороны.',
    exampleEn: 'The lawyer pleaded self-defence.',
  },
  {
    french: 'poursuivre en justice',
    translation: 'преследовать в судебном порядке',
    translationEn: 'to sue, to prosecute',
    category: 'law',
    partOfSpeech: 'expression',
    frequencyRank: 3600,
    exampleFr: 'L\'entreprise a décidé de poursuivre ses anciens associés en justice.',
    exampleRu: 'Компания решила подать в суд на своих бывших партнёров.',
    exampleEn: 'The company decided to sue its former partners.',
  },
  {
    french: 'acquitter',
    translation: 'оправдывать (в суде)',
    translationEn: 'to acquit',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 5000,
    exampleFr: 'Le jury l\'a acquitté faute de preuves suffisantes.',
    exampleRu: 'Жюри оправдало его из-за недостаточности доказательств.',
    exampleEn: 'The jury acquitted him for lack of sufficient evidence.',
  },
  {
    french: 'condamner',
    translation: 'осуждать, выносить приговор',
    translationEn: 'to convict, to sentence',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 2500,
    exampleFr: 'Il a été condamné à dix ans de réclusion criminelle.',
    exampleRu: 'Он был приговорён к десяти годам уголовного заключения.',
    exampleEn: 'He was sentenced to ten years of criminal imprisonment.',
  },
  {
    french: 'inculper',
    translation: 'предъявлять обвинение',
    translationEn: 'to indict, to charge',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 5400,
    exampleFr: 'Le suspect a été inculpé de meurtre avec préméditation.',
    exampleRu: 'Подозреваемый был обвинён в убийстве с предумыслом.',
    exampleEn: 'The suspect was charged with premeditated murder.',
  },
  {
    french: 'se pourvoir en cassation',
    translation: 'обращаться с кассационной жалобой',
    translationEn: 'to appeal to the Court of Cassation',
    category: 'law',
    partOfSpeech: 'expression',
    frequencyRank: 6000,
    exampleFr: 'Après l\'échec en appel, ils ont décidé de se pourvoir en cassation.',
    exampleRu: 'После отказа в апелляции они решили обратиться в Кассационный суд.',
    exampleEn: 'After failing on appeal, they decided to appeal to the Court of Cassation.',
  },
  // ── Droit général ──
  {
    french: 'le droit civil',
    translation: 'гражданское право',
    translationEn: 'civil law',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4500,
    exampleFr: 'Le droit civil régit les relations entre particuliers.',
    exampleRu: 'Гражданское право регулирует отношения между частными лицами.',
    exampleEn: 'Civil law governs relations between private individuals.',
  },
  {
    french: 'le droit pénal',
    translation: 'уголовное право',
    translationEn: 'criminal law',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4700,
    exampleFr: 'Le droit pénal définit les infractions et les peines correspondantes.',
    exampleRu: 'Уголовное право определяет правонарушения и соответствующие наказания.',
    exampleEn: 'Criminal law defines offences and corresponding penalties.',
  },
  {
    french: 'le droit du travail',
    translation: 'трудовое право',
    translationEn: 'labour law',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4300,
    exampleFr: 'Le Code du travail protège les salariés contre les licenciements abusifs.',
    exampleRu: 'Трудовой кодекс защищает работников от незаконных увольнений.',
    exampleEn: 'The Labour Code protects employees against unfair dismissal.',
  },
  {
    french: 'le décret',
    translation: 'указ, декрет',
    translationEn: 'decree',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3200,
    exampleFr: 'Un décret d\'application a été publié au Journal officiel.',
    exampleRu: 'Указ о применении был опубликован в официальном вестнике.',
    exampleEn: 'An implementing decree was published in the Official Journal.',
  },
  {
    french: 'l\'ordonnance',
    translation: 'ордонанс, постановление',
    translationEn: 'order, ordinance',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3600,
    exampleFr: 'Le gouvernement a adopté cette réforme par ordonnance.',
    exampleRu: 'Правительство провело эту реформу через ордонанс.',
    exampleEn: 'The government adopted this reform by ordinance.',
  },
  {
    french: 'la constitutionnalité',
    translation: 'конституционность',
    translationEn: 'constitutionality',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'La constitutionnalité de cette loi a été contestée.',
    exampleRu: 'Конституционность этого закона была оспорена.',
    exampleEn: 'The constitutionality of this law was challenged.',
  },
  {
    french: 'le Conseil constitutionnel',
    translation: 'Конституционный совет (Франция)',
    translationEn: 'Constitutional Council',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Le Conseil constitutionnel a censuré plusieurs articles de la loi.',
    exampleRu: 'Конституционный совет отменил несколько статей закона.',
    exampleEn: 'The Constitutional Council struck down several articles of the law.',
  },
  {
    french: 'la jurisprudence',
    translation: 'судебная практика, прецедент',
    translationEn: 'case law, jurisprudence',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5000,
    exampleFr: 'Cette décision fait jurisprudence pour les affaires similaires.',
    exampleRu: 'Это решение создаёт прецедент для аналогичных дел.',
    exampleEn: 'This ruling sets a precedent for similar cases.',
  },
  {
    french: 'le casier judiciaire',
    translation: 'судимость; судебное досье',
    translationEn: 'criminal record',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Il a un casier judiciaire vierge.',
    exampleRu: 'У него нет судимостей.',
    exampleEn: 'He has a clean criminal record.',
  },
  {
    french: 'le travail d\'intérêt général',
    translation: 'общественные работы (вид наказания)',
    translationEn: 'community service',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Le tribunal l\'a condamné à cent heures de travail d\'intérêt général.',
    exampleRu: 'Суд приговорил его к ста часам общественных работ.',
    exampleEn: 'The court sentenced him to one hundred hours of community service.',
  },
  {
    french: 'le non-lieu',
    translation: 'прекращение дела (за недостатком улик)',
    translationEn: 'dismissal (no case to answer)',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5800,
    exampleFr: 'L\'affaire a abouti à un non-lieu faute de preuves.',
    exampleRu: 'Дело было прекращено из-за отсутствия доказательств.',
    exampleEn: 'The case was dismissed due to lack of evidence.',
  },
  {
    french: 'la comparution',
    translation: 'явка в суд',
    translationEn: 'appearance in court',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6100,
    exampleFr: 'La comparution immédiate est réservée aux cas flagrants.',
    exampleRu: 'Немедленный вызов в суд применяется в очевидных случаях.',
    exampleEn: 'Immediate court appearance is reserved for clear-cut cases.',
  },
  {
    french: 'l\'huissier de justice',
    translation: 'судебный пристав; судебный исполнитель',
    translationEn: 'bailiff, process server',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'L\'huissier a signifié la décision de justice à l\'intéressé.',
    exampleRu: 'Судебный пристав вручил решение суда заинтересованному лицу.',
    exampleEn: 'The bailiff served the court ruling to the person concerned.',
  },
  {
    french: 'la saisie',
    translation: 'арест имущества; изъятие',
    translationEn: 'seizure, attachment',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4800,
    exampleFr: 'Une saisie sur salaire a été ordonnée pour rembourser la dette.',
    exampleRu: 'Для погашения долга было вынесено решение об аресте зарплаты.',
    exampleEn: 'A wage garnishment was ordered to repay the debt.',
  },
  {
    french: 'la peine capitale',
    translation: 'смертная казнь',
    translationEn: 'capital punishment, death penalty',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'La peine capitale a été abolie en France en 1981.',
    exampleRu: 'Смертная казнь была отменена во Франции в 1981 году.',
    exampleEn: 'Capital punishment was abolished in France in 1981.',
  },
  {
    french: 'la loi organique',
    translation: 'органический закон',
    translationEn: 'organic law',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6300,
    exampleFr: 'Une loi organique complète la Constitution sans la modifier.',
    exampleRu: 'Органический закон дополняет Конституцию, не изменяя её.',
    exampleEn: 'An organic law complements the Constitution without amending it.',
  },
  {
    french: 'le droit de recours',
    translation: 'право на обжалование',
    translationEn: 'right of appeal',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5600,
    exampleFr: 'Le droit de recours garantit l\'accès à un deuxième regard judiciaire.',
    exampleRu: 'Право на обжалование гарантирует доступ к повторному судебному рассмотрению.',
    exampleEn: 'The right of appeal guarantees access to a second judicial review.',
  },
  {
    french: 'le plaignant',
    translation: 'истец, заявитель',
    translationEn: 'complainant, plaintiff',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4900,
    exampleFr: 'Le plaignant doit apporter des preuves à l\'appui de sa demande.',
    exampleRu: 'Истец должен предоставить доказательства в подтверждение своего требования.',
    exampleEn: 'The plaintiff must provide evidence to support their claim.',
  },
  {
    french: 'le témoin',
    translation: 'свидетель',
    translationEn: 'witness',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2400,
    exampleFr: 'Le témoin a prêté serment avant de déposer.',
    exampleRu: 'Свидетель принёс присягу перед дачей показаний.',
    exampleEn: 'The witness took an oath before testifying.',
  },
  {
    french: 'témoigner',
    translation: 'давать показания, свидетельствовать',
    translationEn: 'to testify, to witness',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 3300,
    exampleFr: 'Elle a témoigné pendant deux heures devant le tribunal.',
    exampleRu: 'Она давала показания в суде в течение двух часов.',
    exampleEn: 'She testified for two hours before the court.',
  },
  {
    french: 'la liberté sous caution',
    translation: 'освобождение под залог',
    translationEn: 'bail, release on bail',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5900,
    exampleFr: 'Il a été remis en liberté sous caution en attendant son procès.',
    exampleRu: 'Он был освобождён под залог в ожидании суда.',
    exampleEn: 'He was released on bail pending his trial.',
  },
  {
    french: 'le prévenu',
    translation: 'подсудимый (в уголовном деле)',
    translationEn: 'defendant (in criminal case)',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4600,
    exampleFr: 'Le prévenu a nié les faits qui lui étaient reprochés.',
    exampleRu: 'Подсудимый отрицал предъявленные ему обвинения.',
    exampleEn: 'The defendant denied the charges against him.',
  },
  {
    french: 'le récidiviste',
    translation: 'рецидивист',
    translationEn: 'repeat offender, recidivist',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6400,
    exampleFr: 'Pour un récidiviste, les peines sont automatiquement alourdies.',
    exampleRu: 'Для рецидивиста наказания автоматически ужесточаются.',
    exampleEn: 'For a repeat offender, sentences are automatically increased.',
  },
  {
    french: 'relaxer',
    translation: 'освобождать от обвинения, оправдывать',
    translationEn: 'to acquit, to discharge',
    category: 'law',
    partOfSpeech: 'verb',
    frequencyRank: 5700,
    exampleFr: 'Le tribunal a relaxé l\'accusé au bénéfice du doute.',
    exampleRu: 'Суд оправдал обвиняемого, применив принцип сомнения в его пользу.',
    exampleEn: 'The court discharged the accused giving the benefit of the doubt.',
  },
  {
    french: 'l\'amende',
    translation: 'штраф',
    translationEn: 'fine',
    category: 'law',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3400,
    exampleFr: 'L\'entreprise a écopé d\'une amende de deux millions d\'euros.',
    exampleRu: 'Компания получила штраф в размере двух миллионов евро.',
    exampleEn: 'The company was fined two million euros.',
  },
];
