import type { NewWord } from './index.js';

export const wordsB2: Omit<NewWord, 'id' | 'createdAt'>[] = [
  // ── Verbes de haute fréquence B2 ──
  { french: 'souligner', translation: 'подчёркивать', translationEn: 'to underline, to emphasize', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1201, exampleFr: 'Il faut souligner l\'importance de ce problème.', exampleRu: 'Нужно подчеркнуть важность этой проблемы.', exampleEn: 'We must underline the importance of this issue.' },
  { french: 'renoncer', translation: 'отказываться', translationEn: 'to give up, to renounce', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1202, exampleFr: 'Elle a renoncé à son projet.', exampleRu: 'Она отказалась от своего проекта.', exampleEn: 'She gave up her project.' },
  { french: 'envisager', translation: 'предусматривать, рассматривать', translationEn: 'to envisage, to consider', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1203, exampleFr: 'Nous envisageons plusieurs solutions.', exampleRu: 'Мы рассматриваем несколько решений.', exampleEn: 'We are considering several solutions.' },
  { french: 'prétendre', translation: 'утверждать, претендовать', translationEn: 'to claim, to pretend', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1204, exampleFr: 'Il prétend ne pas savoir.', exampleRu: 'Он утверждает, что не знает.', exampleEn: 'He claims not to know.' },
  { french: 'reconnaître', translation: 'признавать, узнавать', translationEn: 'to recognize, to acknowledge', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1205, exampleFr: 'Il faut reconnaître ses erreurs.', exampleRu: 'Нужно признавать свои ошибки.', exampleEn: 'One must acknowledge one\'s mistakes.' },
  { french: 'se méfier', translation: 'остерегаться, не доверять', translationEn: 'to be wary of, to distrust', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1206, exampleFr: 'Méfiez-vous des arnaques en ligne.', exampleRu: 'Остерегайтесь онлайн-мошенничества.', exampleEn: 'Beware of online scams.' },
  { french: 'nuire', translation: 'вредить, наносить ущерб', translationEn: 'to harm, to be detrimental', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1207, exampleFr: 'Le tabac nuit gravement à la santé.', exampleRu: 'Табак серьёзно вредит здоровью.', exampleEn: 'Tobacco is seriously harmful to health.' },
  { french: 'contester', translation: 'оспаривать, опровергать', translationEn: 'to contest, to challenge', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1208, exampleFr: 'Il conteste la décision du tribunal.', exampleRu: 'Он оспаривает решение суда.', exampleEn: 'He is contesting the court\'s decision.' },
  { french: 'investir', translation: 'инвестировать, вкладывать', translationEn: 'to invest', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1209, exampleFr: 'Elle a investi dans l\'immobilier.', exampleRu: 'Она вложила средства в недвижимость.', exampleEn: 'She invested in real estate.' },
  { french: 'améliorer', translation: 'улучшать', translationEn: 'to improve', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1210, exampleFr: 'Comment améliorer ses conditions de travail ?', exampleRu: 'Как улучшить условия труда?', exampleEn: 'How to improve working conditions?' },
  { french: 's\'engager', translation: 'брать на себя обязательства, вступать', translationEn: 'to commit, to engage', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1211, exampleFr: 'Il s\'est engagé à respecter les délais.', exampleRu: 'Он взял на себя обязательство соблюдать сроки.', exampleEn: 'He committed to meeting the deadlines.' },
  { french: 'témoigner', translation: 'свидетельствовать, давать показания', translationEn: 'to testify, to bear witness', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1212, exampleFr: 'Elle a témoigné en faveur de l\'accusé.', exampleRu: 'Она дала показания в пользу обвиняемого.', exampleEn: 'She testified in favor of the accused.' },
  { french: 'percevoir', translation: 'воспринимать, получать', translationEn: 'to perceive, to receive', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1213, exampleFr: 'Il perçoit bien les nuances du langage.', exampleRu: 'Он хорошо воспринимает нюансы языка.', exampleEn: 'He perceives the nuances of language well.' },
  { french: 'omettre', translation: 'упускать, пропускать', translationEn: 'to omit, to leave out', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1214, exampleFr: 'Ne pas omettre les détails importants.', exampleRu: 'Не упускать важные детали.', exampleEn: 'Don\'t omit important details.' },
  { french: 'prôner', translation: 'проповедовать, пропагандировать', translationEn: 'to advocate, to promote', level: 'B2', category: 'verbs', partOfSpeech: 'verb', gender: null, frequencyRank: 1215, exampleFr: 'Il prône le dialogue entre les cultures.', exampleRu: 'Он пропагандирует диалог между культурами.', exampleEn: 'He advocates dialogue between cultures.' },

  // ── Noms abstraits B2 ──
  { french: 'l\'enjeu', translation: 'ставка, проблема, вызов', translationEn: 'stake, issue, challenge', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1220, exampleFr: 'Les enjeux climatiques sont majeurs.', exampleRu: 'Климатические вызовы имеют огромное значение.', exampleEn: 'Climate stakes are major.' },
  { french: 'le biais', translation: 'предвзятость, уклон, косвенный путь', translationEn: 'bias, slant, way, through', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1221, exampleFr: 'Par le biais d\'internet, on peut tout acheter.', exampleRu: 'Через интернет можно купить всё.', exampleEn: 'Through the internet, you can buy anything.' },
  { french: 'la nuance', translation: 'нюанс, оттенок', translationEn: 'nuance, shade', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1222, exampleFr: 'Il faut apporter des nuances à cette analyse.', exampleRu: 'Нужно внести нюансы в этот анализ.', exampleEn: 'We need to bring nuance to this analysis.' },
  { french: 'le recul', translation: 'отступление, перспектива, дистанция', translationEn: 'setback, hindsight, distance', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1223, exampleFr: 'Avec le recul, je comprends mieux la situation.', exampleRu: 'Оглядываясь назад, я лучше понимаю ситуацию.', exampleEn: 'In hindsight, I understand the situation better.' },
  { french: 'la méfiance', translation: 'недоверие, подозрительность', translationEn: 'mistrust, distrust, suspicion', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1224, exampleFr: 'Sa méfiance envers les médias est excessive.', exampleRu: 'Его недоверие к СМИ чрезмерно.', exampleEn: 'His distrust of the media is excessive.' },
  { french: 'le paradoxe', translation: 'парадокс', translationEn: 'paradox', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1225, exampleFr: 'C\'est un paradoxe : riche mais malheureux.', exampleRu: 'Это парадокс: богатый, но несчастный.', exampleEn: 'It\'s a paradox: rich but unhappy.' },
  { french: 'l\'ère', translation: 'эра, эпоха', translationEn: 'era, age', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1226, exampleFr: 'Nous vivons dans l\'ère numérique.', exampleRu: 'Мы живём в цифровую эпоху.', exampleEn: 'We live in the digital era.' },
  { french: 'le compromis', translation: 'компромисс', translationEn: 'compromise', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1227, exampleFr: 'Trouver un compromis est essentiel en diplomatie.', exampleRu: 'Нахождение компромисса существенно в дипломатии.', exampleEn: 'Finding a compromise is essential in diplomacy.' },
  { french: 'la lacune', translation: 'пробел, упущение', translationEn: 'gap, lacuna, shortcoming', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1228, exampleFr: 'Ce rapport comporte des lacunes importantes.', exampleRu: 'В этом докладе есть важные пробелы.', exampleEn: 'This report has significant gaps.' },
  { french: 'l\'ambiguïté', translation: 'двусмысленность, неоднозначность', translationEn: 'ambiguity', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1229, exampleFr: 'Son discours est plein d\'ambiguïtés.', exampleRu: 'Его речь полна двусмысленностей.', exampleEn: 'His speech is full of ambiguities.' },
  { french: 'le consensus', translation: 'консенсус, общее согласие', translationEn: 'consensus', level: 'B2', category: 'abstract_nouns', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1230, exampleFr: 'Un consensus a été atteint après de longues négociations.', exampleRu: 'Консенсус был достигнут после долгих переговоров.', exampleEn: 'A consensus was reached after lengthy negotiations.' },

  // ── Adjectifs B2 ──
  { french: 'susceptible', translation: 'обидчивый; способный, склонный', translationEn: 'touchy; likely to, susceptible', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1240, exampleFr: 'Il est susceptible de changer d\'avis.', exampleRu: 'Он способен изменить своё мнение.', exampleEn: 'He is likely to change his mind.' },
  { french: 'pertinent', translation: 'уместный, актуальный, релевантный', translationEn: 'relevant, pertinent', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1241, exampleFr: 'Votre remarque est très pertinente.', exampleRu: 'Ваше замечание очень уместно.', exampleEn: 'Your remark is very pertinent.' },
  { french: 'ambigu', translation: 'двусмысленный, неоднозначный', translationEn: 'ambiguous', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1242, exampleFr: 'Sa réponse est ambiguë.', exampleRu: 'Его ответ двусмысленный.', exampleEn: 'His answer is ambiguous.' },
  { french: 'controversé', translation: 'спорный, неоднозначный', translationEn: 'controversial', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1243, exampleFr: 'Cette décision est très controversée.', exampleRu: 'Это решение очень спорное.', exampleEn: 'This decision is very controversial.' },
  { french: 'incontournable', translation: 'неизбежный, обязательный', translationEn: 'unavoidable, essential, must-see', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1244, exampleFr: 'C\'est un auteur incontournable du XXe siècle.', exampleRu: 'Это неизбежный автор XX века.', exampleEn: 'He is an essential author of the 20th century.' },
  { french: 'décisif', translation: 'решающий, определяющий', translationEn: 'decisive, crucial', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1245, exampleFr: 'Ce fut un moment décisif dans sa carrière.', exampleRu: 'Это был решающий момент в его карьере.', exampleEn: 'It was a decisive moment in his career.' },
  { french: 'fragile', translation: 'хрупкий, уязвимый', translationEn: 'fragile, vulnerable', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1246, exampleFr: 'L\'équilibre politique reste fragile.', exampleRu: 'Политическое равновесие остаётся хрупким.', exampleEn: 'The political balance remains fragile.' },
  { french: 'concret', translation: 'конкретный, реальный', translationEn: 'concrete, tangible', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1247, exampleFr: 'Proposez des solutions concrètes.', exampleRu: 'Предложите конкретные решения.', exampleEn: 'Propose concrete solutions.' },
  { french: 'progressif', translation: 'постепенный, прогрессивный', translationEn: 'gradual, progressive', level: 'B2', category: 'adjectives', partOfSpeech: 'adjective', gender: null, frequencyRank: 1248, exampleFr: 'Le changement sera progressif.', exampleRu: 'Изменения будут постепенными.', exampleEn: 'The change will be gradual.' },

  // ── Connecteurs et expressions B2 ──
  { french: 'néanmoins', translation: 'тем не менее, однако', translationEn: 'nevertheless, nonetheless', level: 'B2', category: 'connectors', partOfSpeech: 'adverb', gender: null, frequencyRank: 1260, exampleFr: 'C\'est difficile, néanmoins c\'est possible.', exampleRu: 'Это трудно, тем не менее возможно.', exampleEn: 'It\'s difficult, nevertheless it\'s possible.' },
  { french: 'en revanche', translation: 'зато, напротив, с другой стороны', translationEn: 'on the other hand, however, in return', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1261, exampleFr: 'Il est lent, en revanche il est précis.', exampleRu: 'Он медленный, зато точный.', exampleEn: 'He is slow, but on the other hand he is precise.' },
  { french: 'quant à', translation: 'что касается', translationEn: 'as for, regarding', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1262, exampleFr: 'Quant à moi, je pense autrement.', exampleRu: 'Что касается меня, я думаю иначе.', exampleEn: 'As for me, I think differently.' },
  { french: 'dans la mesure où', translation: 'в той мере, в какой; поскольку', translationEn: 'insofar as, to the extent that', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1263, exampleFr: 'Dans la mesure où c\'est possible, aidez-les.', exampleRu: 'В той мере, в какой это возможно, помогите им.', exampleEn: 'Insofar as it is possible, help them.' },
  { french: 'faute de', translation: 'из-за отсутствия, за неимением', translationEn: 'for lack of, due to absence of', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1264, exampleFr: 'Faute de temps, il n\'a pas pu finir.', exampleRu: 'Из-за нехватки времени он не смог закончить.', exampleEn: 'For lack of time, he couldn\'t finish.' },
  { french: 'à condition que', translation: 'при условии что', translationEn: 'provided that, on condition that', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1265, exampleFr: 'Je viendrai à condition que tu le demandes.', exampleRu: 'Я приду при условии, что ты попросишь.', exampleEn: 'I will come provided that you ask.' },
  { french: 'bien que', translation: 'хотя, несмотря на то что', translationEn: 'although, even though', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1266, exampleFr: 'Bien qu\'il soit tard, continuons.', exampleRu: 'Хотя уже поздно, давайте продолжим.', exampleEn: 'Although it\'s late, let\'s continue.' },
  { french: 'à moins que', translation: 'если только не, разве что', translationEn: 'unless', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1267, exampleFr: 'Il viendra à moins qu\'il soit malade.', exampleRu: 'Он придёт, если только не заболеет.', exampleEn: 'He will come unless he is sick.' },
  { french: 'de sorte que', translation: 'так что, чтобы, таким образом', translationEn: 'so that, in such a way that', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1268, exampleFr: 'Il a travaillé de sorte que tout soit prêt.', exampleRu: 'Он работал так, чтобы всё было готово.', exampleEn: 'He worked so that everything would be ready.' },
  { french: 'tant que', translation: 'пока, до тех пор пока', translationEn: 'as long as, while', level: 'B2', category: 'connectors', partOfSpeech: 'expression', gender: null, frequencyRank: 1269, exampleFr: 'Tant qu\'il y a de la vie, il y a de l\'espoir.', exampleRu: 'Пока есть жизнь, есть надежда.', exampleEn: 'As long as there is life, there is hope.' },

  // ── Économie et politique ──
  { french: 'le budget', translation: 'бюджет', translationEn: 'budget', level: 'B2', category: 'economy', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1280, exampleFr: 'Le budget de l\'État est en déficit.', exampleRu: 'Государственный бюджет дефицитный.', exampleEn: 'The state budget is in deficit.' },
  { french: 'la dette', translation: 'долг', translationEn: 'debt', level: 'B2', category: 'economy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1281, exampleFr: 'La dette publique atteint des niveaux records.', exampleRu: 'Государственный долг достигает рекордных уровней.', exampleEn: 'Public debt is reaching record levels.' },
  { french: 'la croissance', translation: 'рост, экономический рост', translationEn: 'growth', level: 'B2', category: 'economy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1282, exampleFr: 'La croissance économique est en baisse.', exampleRu: 'Экономический рост снижается.', exampleEn: 'Economic growth is declining.' },
  { french: 'l\'inflation', translation: 'инфляция', translationEn: 'inflation', level: 'B2', category: 'economy', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1283, exampleFr: 'L\'inflation a augmenté de 3% cette année.', exampleRu: 'Инфляция выросла на 3% в этом году.', exampleEn: 'Inflation has risen by 3% this year.' },
  { french: 'la réforme', translation: 'реформа', translationEn: 'reform', level: 'B2', category: 'politics', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1284, exampleFr: 'Une réforme du système éducatif est nécessaire.', exampleRu: 'Реформа системы образования необходима.', exampleEn: 'A reform of the education system is necessary.' },
  { french: 'le scrutin', translation: 'голосование, выборы', translationEn: 'ballot, election, vote', level: 'B2', category: 'politics', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1285, exampleFr: 'Le second tour du scrutin aura lieu dimanche.', exampleRu: 'Второй тур голосования состоится в воскресенье.', exampleEn: 'The second round of voting will take place on Sunday.' },
  { french: 'le mandat', translation: 'мандат, срок полномочий', translationEn: 'mandate, term of office', level: 'B2', category: 'politics', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1286, exampleFr: 'Le président a exercé son mandat pendant 5 ans.', exampleRu: 'Президент исполнял свои полномочия 5 лет.', exampleEn: 'The president served his mandate for 5 years.' },
  { french: 'la démocratie', translation: 'демократия', translationEn: 'democracy', level: 'B2', category: 'politics', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1287, exampleFr: 'La démocratie repose sur le droit de vote.', exampleRu: 'Демократия основывается на праве голоса.', exampleEn: 'Democracy is based on the right to vote.' },
  { french: 'le parti', translation: 'партия, сторона', translationEn: 'party, side', level: 'B2', category: 'politics', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1288, exampleFr: 'Il adhère à un parti de gauche.', exampleRu: 'Он является членом левой партии.', exampleEn: 'He belongs to a left-wing party.' },

  // ── Science et technologie ──
  { french: 'l\'algorithme', translation: 'алгоритм', translationEn: 'algorithm', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1290, exampleFr: 'Les algorithmes des réseaux sociaux influencent nos choix.', exampleRu: 'Алгоритмы социальных сетей влияют на наш выбор.', exampleEn: 'Social media algorithms influence our choices.' },
  { french: 'la donnée', translation: 'данные', translationEn: 'data', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1291, exampleFr: 'La protection des données personnelles est cruciale.', exampleRu: 'Защита персональных данных имеет решающее значение.', exampleEn: 'The protection of personal data is crucial.' },
  { french: 'l\'intelligence artificielle', translation: 'искусственный интеллект', translationEn: 'artificial intelligence', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1292, exampleFr: 'L\'intelligence artificielle transforme le marché du travail.', exampleRu: 'Искусственный интеллект меняет рынок труда.', exampleEn: 'Artificial intelligence is transforming the job market.' },
  { french: 'la cybersécurité', translation: 'кибербезопасность', translationEn: 'cybersecurity', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1293, exampleFr: 'La cybersécurité est un défi majeur du XXIe siècle.', exampleRu: 'Кибербезопасность — это главный вызов XXI века.', exampleEn: 'Cybersecurity is a major challenge of the 21st century.' },
  { french: 'l\'innovation', translation: 'инновация, нововведение', translationEn: 'innovation', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1294, exampleFr: 'L\'innovation est le moteur de la croissance.', exampleRu: 'Инновации — двигатель роста.', exampleEn: 'Innovation is the engine of growth.' },
  { french: 'le réseau', translation: 'сеть', translationEn: 'network', level: 'B2', category: 'technology', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1295, exampleFr: 'Il utilise ses réseaux professionnels.', exampleRu: 'Он использует свои профессиональные связи.', exampleEn: 'He uses his professional networks.' },

  // ── Environnement ──
  { french: 'le réchauffement climatique', translation: 'глобальное потепление', translationEn: 'global warming', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1300, exampleFr: 'Le réchauffement climatique menace la biodiversité.', exampleRu: 'Глобальное потепление угрожает биоразнообразию.', exampleEn: 'Global warming threatens biodiversity.' },
  { french: 'la biodiversité', translation: 'биоразнообразие', translationEn: 'biodiversity', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1301, exampleFr: 'La biodiversité est en danger.', exampleRu: 'Биоразнообразие под угрозой.', exampleEn: 'Biodiversity is in danger.' },
  { french: 'l\'empreinte carbone', translation: 'углеродный след', translationEn: 'carbon footprint', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1302, exampleFr: 'Réduire son empreinte carbone est un geste citoyen.', exampleRu: 'Сокращение углеродного следа — гражданский поступок.', exampleEn: 'Reducing your carbon footprint is a civic gesture.' },
  { french: 'le développement durable', translation: 'устойчивое развитие', translationEn: 'sustainable development', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1303, exampleFr: 'Le développement durable concilie économie et écologie.', exampleRu: 'Устойчивое развитие совмещает экономику и экологию.', exampleEn: 'Sustainable development reconciles economy and ecology.' },
  { french: 'l\'énergie renouvelable', translation: 'возобновляемая энергия', translationEn: 'renewable energy', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1304, exampleFr: 'Les énergies renouvelables remplacent les fossiles.', exampleRu: 'Возобновляемые источники энергии заменяют ископаемые.', exampleEn: 'Renewable energies are replacing fossil fuels.' },
  { french: 'la sécheresse', translation: 'засуха', translationEn: 'drought', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1305, exampleFr: 'La sécheresse ravage les récoltes.', exampleRu: 'Засуха уничтожает урожай.', exampleEn: 'The drought is devastating crops.' },
  { french: 'la déforestation', translation: 'обезлесение, вырубка лесов', translationEn: 'deforestation', level: 'B2', category: 'environment', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1306, exampleFr: 'La déforestation accélère le changement climatique.', exampleRu: 'Вырубка лесов ускоряет изменение климата.', exampleEn: 'Deforestation accelerates climate change.' },

  // ── Société et culture ──
  { french: 'l\'inégalité', translation: 'неравенство', translationEn: 'inequality', level: 'B2', category: 'social_issues', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1310, exampleFr: 'Les inégalités sociales se creusent.', exampleRu: 'Социальное неравенство усугубляется.', exampleEn: 'Social inequalities are widening.' },
  { french: 'l\'intégration', translation: 'интеграция', translationEn: 'integration', level: 'B2', category: 'social_issues', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1311, exampleFr: 'L\'intégration des immigrés pose des défis.', exampleRu: 'Интеграция иммигрантов создаёт трудности.', exampleEn: 'The integration of immigrants poses challenges.' },
  { french: 'la discrimination', translation: 'дискриминация', translationEn: 'discrimination', level: 'B2', category: 'social_issues', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1312, exampleFr: 'La discrimination à l\'embauche est interdite par la loi.', exampleRu: 'Дискриминация при найме запрещена законом.', exampleEn: 'Discrimination in hiring is prohibited by law.' },
  { french: 'la solidarité', translation: 'солидарность', translationEn: 'solidarity', level: 'B2', category: 'social_issues', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1313, exampleFr: 'La solidarité nationale s\'est manifestée lors de la crise.', exampleRu: 'Национальная солидарность проявилась во время кризиса.', exampleEn: 'National solidarity manifested itself during the crisis.' },
  { french: 'le patrimoine', translation: 'наследие, достояние', translationEn: 'heritage, patrimony', level: 'B2', category: 'culture', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1314, exampleFr: 'Ce monument fait partie du patrimoine mondial.', exampleRu: 'Этот памятник является частью мирового наследия.', exampleEn: 'This monument is part of the world heritage.' },
  { french: 'la laïcité', translation: 'светскость, отделение церкви от государства', translationEn: 'secularism, laicity', level: 'B2', category: 'society', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1315, exampleFr: 'La laïcité est un principe fondamental en France.', exampleRu: 'Светскость является фундаментальным принципом во Франции.', exampleEn: 'Secularism is a fundamental principle in France.' },
  { french: 'le bénévolat', translation: 'волонтёрство, добровольческий труд', translationEn: 'volunteering, voluntary work', level: 'B2', category: 'society', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1316, exampleFr: 'Il pratique le bénévolat dans une association.', exampleRu: 'Он занимается волонтёрством в организации.', exampleEn: 'He does voluntary work in an organization.' },

  // ── Santé et médecine ──
  { french: 'l\'épidémie', translation: 'эпидемия', translationEn: 'epidemic', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1320, exampleFr: 'L\'épidémie de grippe touche des milliers de personnes.', exampleRu: 'Эпидемия гриппа затрагивает тысячи людей.', exampleEn: 'The flu epidemic affects thousands of people.' },
  { french: 'la prévention', translation: 'профилактика, предупреждение', translationEn: 'prevention', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1321, exampleFr: 'La prévention est préférable au traitement.', exampleRu: 'Профилактика предпочтительнее лечения.', exampleEn: 'Prevention is better than cure.' },
  { french: 'le diagnostic', translation: 'диагноз', translationEn: 'diagnosis', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1322, exampleFr: 'Le diagnostic a été posé rapidement.', exampleRu: 'Диагноз был поставлен быстро.', exampleEn: 'The diagnosis was made quickly.' },
  { french: 'le traitement', translation: 'лечение, обработка', translationEn: 'treatment', level: 'B2', category: 'health', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1323, exampleFr: 'Le traitement dure six semaines.', exampleRu: 'Лечение длится шесть недель.', exampleEn: 'The treatment lasts six weeks.' },
  { french: 'chronique', translation: 'хронический', translationEn: 'chronic', level: 'B2', category: 'health', partOfSpeech: 'adjective', gender: null, frequencyRank: 1324, exampleFr: 'Il souffre d\'une maladie chronique.', exampleRu: 'Он страдает от хронической болезни.', exampleEn: 'He suffers from a chronic illness.' },

  // ── Droit et justice ──
  { french: 'le tribunal', translation: 'суд, трибунал', translationEn: 'court, tribunal', level: 'B2', category: 'law', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1330, exampleFr: 'L\'affaire sera jugée au tribunal correctionnel.', exampleRu: 'Дело будет рассмотрено в суде.', exampleEn: 'The case will be tried in criminal court.' },
  { french: 'le jugement', translation: 'суждение, приговор, решение суда', translationEn: 'judgment, verdict, ruling', level: 'B2', category: 'law', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1331, exampleFr: 'Le jugement sera rendu la semaine prochaine.', exampleRu: 'Решение суда будет вынесено на следующей неделе.', exampleEn: 'The verdict will be delivered next week.' },
  { french: 'la peine', translation: 'наказание, боль, труд', translationEn: 'punishment, pain, effort', level: 'B2', category: 'law', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1332, exampleFr: 'Il a écopé d\'une peine de deux ans de prison.', exampleRu: 'Он получил наказание в виде двух лет тюрьмы.', exampleEn: 'He received a two-year prison sentence.' },
  { french: 'l\'acquittement', translation: 'оправдание, оправдательный приговор', translationEn: 'acquittal', level: 'B2', category: 'law', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1333, exampleFr: 'L\'accusé a obtenu l\'acquittement.', exampleRu: 'Обвиняемый был оправдан.', exampleEn: 'The accused was acquitted.' },

  // ── Médias et communication ──
  { french: 'la désinformation', translation: 'дезинформация', translationEn: 'disinformation, fake news', level: 'B2', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1340, exampleFr: 'La désinformation se propage rapidement sur les réseaux.', exampleRu: 'Дезинформация быстро распространяется в сетях.', exampleEn: 'Disinformation spreads quickly on social media.' },
  { french: 'la liberté de la presse', translation: 'свобода прессы', translationEn: 'freedom of the press', level: 'B2', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1341, exampleFr: 'La liberté de la presse est indispensable à la démocratie.', exampleRu: 'Свобода прессы необходима для демократии.', exampleEn: 'Freedom of the press is indispensable to democracy.' },
  { french: 'l\'opinion publique', translation: 'общественное мнение', translationEn: 'public opinion', level: 'B2', category: 'media', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1342, exampleFr: 'L\'opinion publique est favorable à cette mesure.', exampleRu: 'Общественное мнение благоприятно для этой меры.', exampleEn: 'Public opinion is in favor of this measure.' },
  { french: 'le sondage', translation: 'опрос, анкетирование', translationEn: 'poll, survey', level: 'B2', category: 'media', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1343, exampleFr: 'Selon un sondage récent, la majorité approuve.', exampleRu: 'По данным недавнего опроса, большинство одобряет.', exampleEn: 'According to a recent poll, the majority approves.' },

  // ── Philosophie et pensée critique ──
  { french: 'la thèse', translation: 'тезис, диссертация', translationEn: 'thesis, dissertation', level: 'B2', category: 'academic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1350, exampleFr: 'Il soutient sa thèse de doctorat vendredi.', exampleRu: 'Он защищает свою докторскую диссертацию в пятницу.', exampleEn: 'He is defending his doctoral thesis on Friday.' },
  { french: 'l\'hypothèse', translation: 'гипотеза, предположение', translationEn: 'hypothesis, assumption', level: 'B2', category: 'academic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1351, exampleFr: 'Cette hypothèse doit être vérifiée.', exampleRu: 'Эта гипотеза должна быть проверена.', exampleEn: 'This hypothesis needs to be verified.' },
  { french: 'le raisonnement', translation: 'рассуждение, умозаключение', translationEn: 'reasoning, argument', level: 'B2', category: 'academic', partOfSpeech: 'noun', gender: 'm', frequencyRank: 1352, exampleFr: 'Son raisonnement est logique mais incomplet.', exampleRu: 'Его рассуждение логично, но неполно.', exampleEn: 'His reasoning is logical but incomplete.' },
  { french: 'la contradiction', translation: 'противоречие', translationEn: 'contradiction', level: 'B2', category: 'academic', partOfSpeech: 'noun', gender: 'f', frequencyRank: 1353, exampleFr: 'Il y a une contradiction dans votre argumentation.', exampleRu: 'В вашей аргументации есть противоречие.', exampleEn: 'There is a contradiction in your argumentation.' },
];
