export const wordsA1 = [
  // Базовые глаголы
  { french: 'être', translation: 'быть', translationEn: 'to be', category: 'verbs_basic', grammarTag: 'verbs-etre-avoir', exampleFr: 'Je suis étudiant.', exampleRu: 'Я студент.', exampleEn: 'I am a student.' },
  { french: 'avoir', translation: 'иметь', translationEn: 'to have', category: 'verbs_basic', grammarTag: 'verbs-etre-avoir', exampleFr: 'J\'ai un chat.', exampleRu: 'У меня есть кошка.', exampleEn: 'I have a cat.' },
  { french: 'aller', translation: 'идти, ехать', translationEn: 'to go', category: 'verbs_basic', grammarTag: 'verbs-aller-venir', exampleFr: 'Je vais à l\'école.', exampleRu: 'Я иду в школу.', exampleEn: 'I go to school.' },
  { french: 'faire', translation: 'делать', translationEn: 'to do, to make', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je fais mes devoirs.', exampleRu: 'Я делаю домашнее задание.', exampleEn: 'I do my homework.' },
  { french: 'dire', translation: 'говорить, сказать', translationEn: 'to say, to tell', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Il dit bonjour.', exampleRu: 'Он говорит привет.', exampleEn: 'He says hello.' },
  { french: 'pouvoir', translation: 'мочь', translationEn: 'to be able to, can', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je peux venir.', exampleRu: 'Я могу прийти.', exampleEn: 'I can come.' },
  { french: 'vouloir', translation: 'хотеть', translationEn: 'to want', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je veux du café.', exampleRu: 'Я хочу кофе.', exampleEn: 'I want some coffee.' },
  { french: 'venir', translation: 'приходить', translationEn: 'to come', category: 'verbs_basic', grammarTag: 'verbs-aller-venir', exampleFr: 'Elle vient demain.', exampleRu: 'Она придёт завтра.', exampleEn: 'She is coming tomorrow.' },
  { french: 'savoir', translation: 'знать', translationEn: 'to know (a fact)', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je sais nager.', exampleRu: 'Я умею плавать.', exampleEn: 'I know how to swim.' },
  { french: 'voir', translation: 'видеть', translationEn: 'to see', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je vois la mer.', exampleRu: 'Я вижу море.', exampleEn: 'I see the sea.' },
  { french: 'prendre', translation: 'брать, принимать', translationEn: 'to take', category: 'verbs_basic', grammarTag: 'verbes-irreguliers', exampleFr: 'Je prends le bus.', exampleRu: 'Я еду на автобусе.', exampleEn: 'I take the bus.' },
  { french: 'parler', translation: 'говорить', translationEn: 'to speak, to talk', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Je parle français.', exampleRu: 'Я говорю по-французски.', exampleEn: 'I speak French.' },
  { french: 'manger', translation: 'есть, кушать', translationEn: 'to eat', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Je mange une pomme.', exampleRu: 'Я ем яблоко.', exampleEn: 'I eat an apple.' },
  { french: 'boire', translation: 'пить', translationEn: 'to drink', category: 'verbs_basic', exampleFr: 'Il boit de l\'eau.', exampleRu: 'Он пьёт воду.', exampleEn: 'He drinks water.' },
  { french: 'dormir', translation: 'спать', translationEn: 'to sleep', category: 'verbs_basic', exampleFr: 'Je dors huit heures.', exampleRu: 'Я сплю восемь часов.', exampleEn: 'I sleep eight hours.' },
  { french: 'travailler', translation: 'работать', translationEn: 'to work', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Elle travaille ici.', exampleRu: 'Она работает здесь.', exampleEn: 'She works here.' },
  { french: 'habiter', translation: 'жить, проживать', translationEn: 'to live, to reside', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'J\'habite à Paris.', exampleRu: 'Я живу в Париже.', exampleEn: 'I live in Paris.' },
  { french: 'aimer', translation: 'любить, нравиться', translationEn: 'to love, to like', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'J\'aime le chocolat.', exampleRu: 'Мне нравится шоколад.', exampleEn: 'I like chocolate.' },
  { french: 'acheter', translation: 'покупать', translationEn: 'to buy', category: 'verbs_basic', exampleFr: 'J\'achète du pain.', exampleRu: 'Я покупаю хлеб.', exampleEn: 'I buy bread.' },
  { french: 'lire', translation: 'читать', translationEn: 'to read', category: 'verbs_basic', exampleFr: 'Je lis un livre.', exampleRu: 'Я читаю книгу.', exampleEn: 'I read a book.' },
  { french: 'écrire', translation: 'писать', translationEn: 'to write', category: 'verbs_basic', exampleFr: 'J\'écris une lettre.', exampleRu: 'Я пишу письмо.', exampleEn: 'I write a letter.' },
  { french: 'écouter', translation: 'слушать', translationEn: 'to listen', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'J\'écoute la radio.', exampleRu: 'Я слушаю радио.', exampleEn: 'I listen to the radio.' },
  { french: 'regarder', translation: 'смотреть', translationEn: 'to watch, to look', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Je regarde la télé.', exampleRu: 'Я смотрю телевизор.', exampleEn: 'I watch TV.' },
  { french: 'entrer', translation: 'входить', translationEn: 'to enter', category: 'verbs_basic', exampleFr: 'Il entre dans la salle.', exampleRu: 'Он входит в зал.', exampleEn: 'He enters the room.' },
  { french: 'sortir', translation: 'выходить', translationEn: 'to go out', category: 'verbs_basic', exampleFr: 'Je sors du bureau.', exampleRu: 'Я выхожу из офиса.', exampleEn: 'I leave the office.' },
  { french: 'rentrer', translation: 'возвращаться домой', translationEn: 'to return home', category: 'verbs_basic', exampleFr: 'Je rentre à la maison.', exampleRu: 'Я возвращаюсь домой.', exampleEn: 'I go back home.' },
  { french: 'arriver', translation: 'приезжать, прибывать', translationEn: 'to arrive', category: 'verbs_basic', exampleFr: 'Le train arrive à 10h.', exampleRu: 'Поезд прибывает в 10 часов.', exampleEn: 'The train arrives at 10.' },
  { french: 'partir', translation: 'уходить, уезжать', translationEn: 'to leave, to depart', category: 'verbs_basic', exampleFr: 'Je pars demain.', exampleRu: 'Я уезжаю завтра.', exampleEn: 'I leave tomorrow.' },
  { french: 'chercher', translation: 'искать', translationEn: 'to look for', category: 'verbs_basic', exampleFr: 'Je cherche mes clés.', exampleRu: 'Я ищу свои ключи.', exampleEn: 'I look for my keys.' },
  { french: 'trouver', translation: 'находить', translationEn: 'to find', category: 'verbs_basic', exampleFr: 'J\'ai trouvé mon sac.', exampleRu: 'Я нашёл свою сумку.', exampleEn: 'I found my bag.' },
  { french: 'donner', translation: 'давать', translationEn: 'to give', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Je donne un cadeau.', exampleRu: 'Я даю подарок.', exampleEn: 'I give a gift.' },
  { french: 'demander', translation: 'спрашивать, просить', translationEn: 'to ask', category: 'verbs_basic', exampleFr: 'Je demande l\'addition.', exampleRu: 'Я прошу счёт.', exampleEn: 'I ask for the bill.' },
  { french: 'appeler', translation: 'звонить, называть', translationEn: 'to call', category: 'verbs_basic', exampleFr: 'Je t\'appelle ce soir.', exampleRu: 'Я позвоню тебе вечером.', exampleEn: 'I will call you tonight.' },
  { french: 'ouvrir', translation: 'открывать', translationEn: 'to open', category: 'verbs_basic', exampleFr: 'J\'ouvre la fenêtre.', exampleRu: 'Я открываю окно.', exampleEn: 'I open the window.' },
  { french: 'fermer', translation: 'закрывать', translationEn: 'to close', category: 'verbs_basic', exampleFr: 'Ferme la porte.', exampleRu: 'Закрой дверь.', exampleEn: 'Close the door.' },
  { french: 'mettre', translation: 'класть, надевать', translationEn: 'to put, to wear', category: 'verbs_basic', exampleFr: 'Je mets mon manteau.', exampleRu: 'Я надеваю пальто.', exampleEn: 'I put on my coat.' },
  { french: 'porter', translation: 'носить, нести', translationEn: 'to carry, to wear', category: 'verbs_basic', exampleFr: 'Elle porte une robe.', exampleRu: 'Она носит платье.', exampleEn: 'She wears a dress.' },
  { french: 'jouer', translation: 'играть', translationEn: 'to play', category: 'verbs_basic', grammarTag: 'verbs-present-regular', exampleFr: 'Les enfants jouent.', exampleRu: 'Дети играют.', exampleEn: 'The children play.' },
  { french: 'nager', translation: 'плавать', translationEn: 'to swim', category: 'verbs_basic', exampleFr: 'Je nage dans la piscine.', exampleRu: 'Я плаваю в бассейне.', exampleEn: 'I swim in the pool.' },
  { french: 'courir', translation: 'бегать', translationEn: 'to run', category: 'verbs_basic', exampleFr: 'Je cours le matin.', exampleRu: 'Я бегаю утром.', exampleEn: 'I run in the morning.' },

  // Семья
  { french: 'la famille', translation: 'семья', translationEn: 'family', category: 'family', exampleFr: 'Ma famille est grande.', exampleRu: 'Моя семья большая.', exampleEn: 'My family is big.' },
  { french: 'la mère', translation: 'мать', translationEn: 'mother', category: 'family', exampleFr: 'Ma mère est médecin.', exampleRu: 'Моя мать — врач.', exampleEn: 'My mother is a doctor.' },
  { french: 'le père', translation: 'отец', translationEn: 'father', category: 'family', exampleFr: 'Mon père travaille.', exampleRu: 'Мой отец работает.', exampleEn: 'My father works.' },
  { french: 'la sœur', translation: 'сестра', translationEn: 'sister', category: 'family', exampleFr: 'J\'ai une sœur.', exampleRu: 'У меня есть сестра.', exampleEn: 'I have a sister.' },
  { french: 'le frère', translation: 'брат', translationEn: 'brother', category: 'family', exampleFr: 'Mon frère est grand.', exampleRu: 'Мой брат высокий.', exampleEn: 'My brother is tall.' },
  { french: 'la fille', translation: 'дочь, девочка', translationEn: 'daughter, girl', category: 'family', exampleFr: 'Ma fille a cinq ans.', exampleRu: 'Моей дочери пять лет.', exampleEn: 'My daughter is five years old.' },
  { french: 'le fils', translation: 'сын', translationEn: 'son', category: 'family', exampleFr: 'Mon fils aime le foot.', exampleRu: 'Мой сын любит футбол.', exampleEn: 'My son likes football.' },
  { french: 'les parents', translation: 'родители', translationEn: 'parents', category: 'family', exampleFr: 'Mes parents habitent Lyon.', exampleRu: 'Мои родители живут в Лионе.', exampleEn: 'My parents live in Lyon.' },
  { french: 'les enfants', translation: 'дети', translationEn: 'children', category: 'family', exampleFr: 'Les enfants jouent dehors.', exampleRu: 'Дети играют на улице.', exampleEn: 'The children play outside.' },
  { french: 'le mari', translation: 'муж', translationEn: 'husband', category: 'family', exampleFr: 'Mon mari est gentil.', exampleRu: 'Мой муж добрый.', exampleEn: 'My husband is kind.' },
  { french: 'la femme', translation: 'жена, женщина', translationEn: 'wife, woman', category: 'family', exampleFr: 'Ma femme est infirmière.', exampleRu: 'Моя жена — медсестра.', exampleEn: 'My wife is a nurse.' },
  { french: 'le grand-père', translation: 'дедушка', translationEn: 'grandfather', category: 'family', exampleFr: 'Mon grand-père a 70 ans.', exampleRu: 'Моему дедушке 70 лет.', exampleEn: 'My grandfather is 70 years old.' },
  { french: 'la grand-mère', translation: 'бабушка', translationEn: 'grandmother', category: 'family', exampleFr: 'Ma grand-mère cuisine bien.', exampleRu: 'Моя бабушка хорошо готовит.', exampleEn: 'My grandmother cooks well.' },
  { french: 'l\'oncle', translation: 'дядя', translationEn: 'uncle', category: 'family', exampleFr: 'Mon oncle habite Bordeaux.', exampleRu: 'Мой дядя живёт в Бордо.', exampleEn: 'My uncle lives in Bordeaux.' },
  { french: 'la tante', translation: 'тётя', translationEn: 'aunt', category: 'family', exampleFr: 'Ma tante est sympa.', exampleRu: 'Моя тётя приятная.', exampleEn: 'My aunt is nice.' },
  { french: 'le cousin', translation: 'двоюродный брат', translationEn: 'cousin (male)', category: 'family', exampleFr: 'Mon cousin joue au tennis.', exampleRu: 'Мой двоюродный брат играет в теннис.', exampleEn: 'My cousin plays tennis.' },
  { french: 'la cousine', translation: 'двоюродная сестра', translationEn: 'cousin (female)', category: 'family', exampleFr: 'Ma cousine est étudiante.', exampleRu: 'Моя двоюродная сестра — студентка.', exampleEn: 'My cousin is a student.' },
  { french: 'le bébé', translation: 'младенец', translationEn: 'baby', category: 'family', exampleFr: 'Le bébé dort.', exampleRu: 'Младенец спит.', exampleEn: 'The baby is sleeping.' },
  { french: 'l\'ami', translation: 'друг', translationEn: 'friend', category: 'family', exampleFr: 'C\'est mon ami.', exampleRu: 'Это мой друг.', exampleEn: 'This is my friend.' },
  { french: 'le voisin', translation: 'сосед', translationEn: 'neighbour', category: 'family', exampleFr: 'Mon voisin est sympa.', exampleRu: 'Мой сосед приятный.', exampleEn: 'My neighbour is nice.' },

  // Еда и напитки
  { french: 'le pain', translation: 'хлеб', translationEn: 'bread', category: 'food', exampleFr: 'Je mange du pain.', exampleRu: 'Я ем хлеб.', exampleEn: 'I eat bread.' },
  { french: 'le beurre', translation: 'масло', translationEn: 'butter', category: 'food', exampleFr: 'Du pain avec du beurre.', exampleRu: 'Хлеб с маслом.', exampleEn: 'Bread with butter.' },
  { french: 'le fromage', translation: 'сыр', translationEn: 'cheese', category: 'food', exampleFr: 'J\'aime le fromage.', exampleRu: 'Я люблю сыр.', exampleEn: 'I love cheese.' },
  { french: 'le lait', translation: 'молоко', translationEn: 'milk', category: 'food', exampleFr: 'Un verre de lait.', exampleRu: 'Стакан молока.', exampleEn: 'A glass of milk.' },
  { french: 'l\'eau', translation: 'вода', translationEn: 'water', category: 'food', exampleFr: 'Je bois de l\'eau.', exampleRu: 'Я пью воду.', exampleEn: 'I drink water.' },
  { french: 'le café', translation: 'кофе', translationEn: 'coffee', category: 'food', exampleFr: 'Un café, s\'il vous plaît.', exampleRu: 'Кофе, пожалуйста.', exampleEn: 'A coffee, please.' },
  { french: 'le thé', translation: 'чай', translationEn: 'tea', category: 'food', exampleFr: 'Je prends du thé.', exampleRu: 'Я выпью чаю.', exampleEn: 'I will have some tea.' },
  { french: 'le jus', translation: 'сок', translationEn: 'juice', category: 'food', exampleFr: 'Du jus d\'orange.', exampleRu: 'Апельсиновый сок.', exampleEn: 'Orange juice.' },
  { french: 'le vin', translation: 'вино', translationEn: 'wine', category: 'food', exampleFr: 'Un verre de vin rouge.', exampleRu: 'Бокал красного вина.', exampleEn: 'A glass of red wine.' },
  { french: 'la bière', translation: 'пиво', translationEn: 'beer', category: 'food', exampleFr: 'Une bière, merci.', exampleRu: 'Пиво, спасибо.', exampleEn: 'A beer, thank you.' },
  { french: 'la pomme', translation: 'яблоко', translationEn: 'apple', category: 'food', exampleFr: 'Une pomme rouge.', exampleRu: 'Красное яблоко.', exampleEn: 'A red apple.' },
  { french: 'la banane', translation: 'банан', translationEn: 'banana', category: 'food', exampleFr: 'Je mange une banane.', exampleRu: 'Я ем банан.', exampleEn: 'I eat a banana.' },
  { french: 'l\'orange', translation: 'апельсин', translationEn: 'orange', category: 'food', exampleFr: 'Une orange fraîche.', exampleRu: 'Свежий апельсин.', exampleEn: 'A fresh orange.' },
  { french: 'la tomate', translation: 'помидор', translationEn: 'tomato', category: 'food', exampleFr: 'Une salade de tomates.', exampleRu: 'Салат из помидоров.', exampleEn: 'A tomato salad.' },
  { french: 'la carotte', translation: 'морковь', translationEn: 'carrot', category: 'food', exampleFr: 'Des carottes râpées.', exampleRu: 'Тёртая морковь.', exampleEn: 'Grated carrots.' },
  { french: 'la pomme de terre', translation: 'картофель', translationEn: 'potato', category: 'food', exampleFr: 'Des pommes de terre frites.', exampleRu: 'Жареный картофель.', exampleEn: 'Fried potatoes.' },
  { french: 'le poulet', translation: 'курица', translationEn: 'chicken', category: 'food', exampleFr: 'Du poulet rôti.', exampleRu: 'Жареная курица.', exampleEn: 'Roast chicken.' },
  { french: 'le poisson', translation: 'рыба', translationEn: 'fish', category: 'food', exampleFr: 'J\'aime le poisson.', exampleRu: 'Я люблю рыбу.', exampleEn: 'I like fish.' },
  { french: 'la viande', translation: 'мясо', translationEn: 'meat', category: 'food', exampleFr: 'De la viande grillée.', exampleRu: 'Жареное мясо.', exampleEn: 'Grilled meat.' },
  { french: 'l\'œuf', translation: 'яйцо', translationEn: 'egg', category: 'food', exampleFr: 'Des œufs brouillés.', exampleRu: 'Яичница-болтунья.', exampleEn: 'Scrambled eggs.' },
  { french: 'le sucre', translation: 'сахар', translationEn: 'sugar', category: 'food', exampleFr: 'Du café sans sucre.', exampleRu: 'Кофе без сахара.', exampleEn: 'Coffee without sugar.' },
  { french: 'le sel', translation: 'соль', translationEn: 'salt', category: 'food', exampleFr: 'Passe-moi le sel.', exampleRu: 'Передай мне соль.', exampleEn: 'Pass me the salt.' },
  { french: 'le gâteau', translation: 'торт, пирог', translationEn: 'cake', category: 'food', exampleFr: 'Un gâteau au chocolat.', exampleRu: 'Шоколадный торт.', exampleEn: 'A chocolate cake.' },
  { french: 'la soupe', translation: 'суп', translationEn: 'soup', category: 'food', exampleFr: 'Une soupe de légumes.', exampleRu: 'Овощной суп.', exampleEn: 'Vegetable soup.' },
  { french: 'la salade', translation: 'салат', translationEn: 'salad', category: 'food', exampleFr: 'Une salade verte.', exampleRu: 'Зелёный салат.', exampleEn: 'A green salad.' },
  { french: 'le sandwich', translation: 'бутерброд', translationEn: 'sandwich', category: 'food', exampleFr: 'Un sandwich au jambon.', exampleRu: 'Бутерброд с ветчиной.', exampleEn: 'A ham sandwich.' },
  { french: 'le dessert', translation: 'десерт', translationEn: 'dessert', category: 'food', exampleFr: 'Qu\'est-ce qu\'il y a comme dessert ?', exampleRu: 'Что на десерт?', exampleEn: 'What is there for dessert?' },
  { french: 'le petit-déjeuner', translation: 'завтрак', translationEn: 'breakfast', category: 'food', exampleFr: 'Je prends mon petit-déjeuner.', exampleRu: 'Я завтракаю.', exampleEn: 'I have breakfast.' },
  { french: 'le déjeuner', translation: 'обед', translationEn: 'lunch', category: 'food', exampleFr: 'On déjeune ensemble ?', exampleRu: 'Пообедаем вместе?', exampleEn: 'Shall we have lunch together?' },
  { french: 'le dîner', translation: 'ужин', translationEn: 'dinner', category: 'food', exampleFr: 'Le dîner est prêt.', exampleRu: 'Ужин готов.', exampleEn: 'Dinner is ready.' },
  { french: 'le restaurant', translation: 'ресторан', translationEn: 'restaurant', category: 'food', exampleFr: 'On va au restaurant.', exampleRu: 'Мы идём в ресторан.', exampleEn: 'We go to the restaurant.' },

  // Дом
  { french: 'la maison', translation: 'дом', translationEn: 'house', category: 'house', exampleFr: 'J\'habite dans une maison.', exampleRu: 'Я живу в доме.', exampleEn: 'I live in a house.' },
  { french: 'l\'appartement', translation: 'квартира', translationEn: 'apartment', category: 'house', exampleFr: 'Un appartement au centre.', exampleRu: 'Квартира в центре.', exampleEn: 'An apartment in the centre.' },
  { french: 'la chambre', translation: 'комната, спальня', translationEn: 'room, bedroom', category: 'house', exampleFr: 'Ma chambre est petite.', exampleRu: 'Моя комната маленькая.', exampleEn: 'My room is small.' },
  { french: 'la cuisine', translation: 'кухня', translationEn: 'kitchen', category: 'house', exampleFr: 'Je cuisine dans la cuisine.', exampleRu: 'Я готовлю на кухне.', exampleEn: 'I cook in the kitchen.' },
  { french: 'le salon', translation: 'гостиная', translationEn: 'living room', category: 'house', exampleFr: 'On regarde la télé au salon.', exampleRu: 'Мы смотрим телевизор в гостиной.', exampleEn: 'We watch TV in the living room.' },
  { french: 'la salle de bains', translation: 'ванная комната', translationEn: 'bathroom', category: 'house', exampleFr: 'La salle de bains est libre.', exampleRu: 'Ванная свободна.', exampleEn: 'The bathroom is free.' },
  { french: 'les toilettes', translation: 'туалет', translationEn: 'toilet', category: 'house', exampleFr: 'Où sont les toilettes ?', exampleRu: 'Где туалет?', exampleEn: 'Where is the toilet?' },
  { french: 'la porte', translation: 'дверь', translationEn: 'door', category: 'house', exampleFr: 'Ferme la porte.', exampleRu: 'Закрой дверь.', exampleEn: 'Close the door.' },
  { french: 'la fenêtre', translation: 'окно', translationEn: 'window', category: 'house', exampleFr: 'Ouvre la fenêtre.', exampleRu: 'Открой окно.', exampleEn: 'Open the window.' },
  { french: 'le lit', translation: 'кровать', translationEn: 'bed', category: 'house', exampleFr: 'Je fais mon lit.', exampleRu: 'Я застилаю кровать.', exampleEn: 'I make my bed.' },
  { french: 'la table', translation: 'стол', translationEn: 'table', category: 'house', exampleFr: 'La table est ronde.', exampleRu: 'Стол круглый.', exampleEn: 'The table is round.' },
  { french: 'la chaise', translation: 'стул', translationEn: 'chair', category: 'house', exampleFr: 'Assieds-toi sur la chaise.', exampleRu: 'Сядь на стул.', exampleEn: 'Sit on the chair.' },
  { french: 'le canapé', translation: 'диван', translationEn: 'sofa, couch', category: 'house', exampleFr: 'Je lis sur le canapé.', exampleRu: 'Я читаю на диване.', exampleEn: 'I read on the sofa.' },
  { french: 'l\'armoire', translation: 'шкаф', translationEn: 'wardrobe, cupboard', category: 'house', exampleFr: 'Mes habits sont dans l\'armoire.', exampleRu: 'Мои вещи в шкафу.', exampleEn: 'My clothes are in the wardrobe.' },
  { french: 'le réfrigérateur', translation: 'холодильник', translationEn: 'refrigerator, fridge', category: 'house', exampleFr: 'Le lait est au réfrigérateur.', exampleRu: 'Молоко в холодильнике.', exampleEn: 'The milk is in the fridge.' },
  { french: 'la télévision', translation: 'телевизор', translationEn: 'television, TV', category: 'house', exampleFr: 'J\'allume la télévision.', exampleRu: 'Я включаю телевизор.', exampleEn: 'I turn on the TV.' },
  { french: 'le téléphone', translation: 'телефон', translationEn: 'phone', category: 'house', exampleFr: 'Mon téléphone sonne.', exampleRu: 'Мой телефон звонит.', exampleEn: 'My phone is ringing.' },
  { french: 'l\'ordinateur', translation: 'компьютер', translationEn: 'computer', category: 'house', exampleFr: 'Je travaille sur l\'ordinateur.', exampleRu: 'Я работаю за компьютером.', exampleEn: 'I work on the computer.' },
  { french: 'le jardin', translation: 'сад', translationEn: 'garden', category: 'house', exampleFr: 'Je jardine le week-end.', exampleRu: 'Я занимаюсь садом в выходные.', exampleEn: 'I garden at the weekend.' },
  { french: 'l\'étage', translation: 'этаж', translationEn: 'floor, storey', category: 'house', exampleFr: 'J\'habite au troisième étage.', exampleRu: 'Я живу на третьем этаже.', exampleEn: 'I live on the third floor.' },

  // Город и транспорт
  { french: 'la ville', translation: 'город', translationEn: 'city, town', category: 'transport', exampleFr: 'Paris est une grande ville.', exampleRu: 'Париж — большой город.', exampleEn: 'Paris is a big city.' },
  { french: 'la rue', translation: 'улица', translationEn: 'street', category: 'transport', exampleFr: 'Je traverse la rue.', exampleRu: 'Я перехожу улицу.', exampleEn: 'I cross the street.' },
  { french: 'la route', translation: 'дорога', translationEn: 'road', category: 'transport', exampleFr: 'La route est longue.', exampleRu: 'Дорога длинная.', exampleEn: 'The road is long.' },
  { french: 'le bus', translation: 'автобус', translationEn: 'bus', category: 'transport', exampleFr: 'Je prends le bus.', exampleRu: 'Я еду на автобусе.', exampleEn: 'I take the bus.' },
  { french: 'le métro', translation: 'метро', translationEn: 'metro, subway', category: 'transport', exampleFr: 'Je prends le métro.', exampleRu: 'Я еду на метро.', exampleEn: 'I take the metro.' },
  { french: 'le train', translation: 'поезд', translationEn: 'train', category: 'transport', exampleFr: 'Le train est en retard.', exampleRu: 'Поезд опаздывает.', exampleEn: 'The train is late.' },
  { french: 'la voiture', translation: 'машина', translationEn: 'car', category: 'transport', exampleFr: 'Je vais en voiture.', exampleRu: 'Я еду на машине.', exampleEn: 'I go by car.' },
  { french: 'le vélo', translation: 'велосипед', translationEn: 'bicycle, bike', category: 'transport', exampleFr: 'Je fais du vélo.', exampleRu: 'Я езжу на велосипеде.', exampleEn: 'I ride a bike.' },
  { french: 'l\'avion', translation: 'самолёт', translationEn: 'plane', category: 'transport', exampleFr: 'Je prends l\'avion.', exampleRu: 'Я лечу на самолёте.', exampleEn: 'I take the plane.' },
  { french: 'la gare', translation: 'вокзал', translationEn: 'train station', category: 'transport', exampleFr: 'Je suis à la gare.', exampleRu: 'Я на вокзале.', exampleEn: 'I am at the train station.' },
  { french: 'l\'aéroport', translation: 'аэропорт', translationEn: 'airport', category: 'transport', exampleFr: 'L\'aéroport est loin.', exampleRu: 'Аэропорт далеко.', exampleEn: 'The airport is far.' },
  { french: 'la station', translation: 'станция', translationEn: 'station', category: 'transport', exampleFr: 'Quelle station ?', exampleRu: 'Какая станция?', exampleEn: 'Which station?' },
  { french: 'l\'arrêt', translation: 'остановка', translationEn: 'stop', category: 'transport', exampleFr: 'L\'arrêt de bus est là.', exampleRu: 'Автобусная остановка здесь.', exampleEn: 'The bus stop is here.' },
  { french: 'le billet', translation: 'билет', translationEn: 'ticket', category: 'transport', exampleFr: 'J\'achète un billet.', exampleRu: 'Я покупаю билет.', exampleEn: 'I buy a ticket.' },
  { french: 'le taxi', translation: 'такси', translationEn: 'taxi', category: 'transport', exampleFr: 'Je prends un taxi.', exampleRu: 'Я беру такси.', exampleEn: 'I take a taxi.' },
  { french: 'l\'hôtel', translation: 'отель', translationEn: 'hotel', category: 'transport', exampleFr: 'Je dors à l\'hôtel.', exampleRu: 'Я сплю в отеле.', exampleEn: 'I sleep at the hotel.' },
  { french: 'le magasin', translation: 'магазин', translationEn: 'shop, store', category: 'transport', exampleFr: 'Je vais au magasin.', exampleRu: 'Я иду в магазин.', exampleEn: 'I go to the shop.' },
  { french: 'la banque', translation: 'банк', translationEn: 'bank', category: 'transport', exampleFr: 'Je vais à la banque.', exampleRu: 'Я иду в банк.', exampleEn: 'I go to the bank.' },
  { french: 'la poste', translation: 'почта', translationEn: 'post office', category: 'transport', exampleFr: 'Je vais à la poste.', exampleRu: 'Я иду на почту.', exampleEn: 'I go to the post office.' },
  { french: 'la pharmacie', translation: 'аптека', translationEn: 'pharmacy, chemist', category: 'transport', exampleFr: 'Je vais à la pharmacie.', exampleRu: 'Я иду в аптеку.', exampleEn: 'I go to the pharmacy.' },
  { french: 'l\'hôpital', translation: 'больница', translationEn: 'hospital', category: 'transport', exampleFr: 'Je vais à l\'hôpital.', exampleRu: 'Я иду в больницу.', exampleEn: 'I go to the hospital.' },
  { french: 'l\'école', translation: 'школа', translationEn: 'school', category: 'transport', exampleFr: 'Je vais à l\'école.', exampleRu: 'Я иду в школу.', exampleEn: 'I go to school.' },
  { french: 'le parc', translation: 'парк', translationEn: 'park', category: 'transport', exampleFr: 'Je me promène dans le parc.', exampleRu: 'Я гуляю в парке.', exampleEn: 'I walk in the park.' },
  { french: 'le supermarché', translation: 'супермаркет', translationEn: 'supermarket', category: 'transport', exampleFr: 'Je fais les courses au supermarché.', exampleRu: 'Я делаю покупки в супермаркете.', exampleEn: 'I do shopping at the supermarket.' },

  // Тело и здоровье
  { french: 'la tête', translation: 'голова', translationEn: 'head', category: 'body', exampleFr: 'J\'ai mal à la tête.', exampleRu: 'У меня болит голова.', exampleEn: 'I have a headache.' },
  { french: 'les yeux', translation: 'глаза', translationEn: 'eyes', category: 'body', exampleFr: 'Elle a les yeux bleus.', exampleRu: 'У неё голубые глаза.', exampleEn: 'She has blue eyes.' },
  { french: 'le nez', translation: 'нос', translationEn: 'nose', category: 'body', exampleFr: 'Il a un grand nez.', exampleRu: 'У него большой нос.', exampleEn: 'He has a big nose.' },
  { french: 'la bouche', translation: 'рот', translationEn: 'mouth', category: 'body', exampleFr: 'Ouvre la bouche.', exampleRu: 'Открой рот.', exampleEn: 'Open your mouth.' },
  { french: 'l\'oreille', translation: 'ухо', translationEn: 'ear', category: 'body', exampleFr: 'J\'ai mal à l\'oreille.', exampleRu: 'У меня болит ухо.', exampleEn: 'My ear hurts.' },
  { french: 'les dents', translation: 'зубы', translationEn: 'teeth', category: 'body', exampleFr: 'Je me brosse les dents.', exampleRu: 'Я чищу зубы.', exampleEn: 'I brush my teeth.' },
  { french: 'le bras', translation: 'рука (от плеча)', translationEn: 'arm', category: 'body', exampleFr: 'Il a le bras cassé.', exampleRu: 'У него сломана рука.', exampleEn: 'His arm is broken.' },
  { french: 'la main', translation: 'кисть руки', translationEn: 'hand', category: 'body', exampleFr: 'Donne-moi la main.', exampleRu: 'Дай мне руку.', exampleEn: 'Give me your hand.' },
  { french: 'la jambe', translation: 'нога (от бедра)', translationEn: 'leg', category: 'body', exampleFr: 'J\'ai mal à la jambe.', exampleRu: 'У меня болит нога.', exampleEn: 'My leg hurts.' },
  { french: 'le pied', translation: 'стопа', translationEn: 'foot', category: 'body', exampleFr: 'J\'ai mal au pied.', exampleRu: 'У меня болит стопа.', exampleEn: 'My foot hurts.' },
  { french: 'le dos', translation: 'спина', translationEn: 'back', category: 'body', exampleFr: 'J\'ai mal au dos.', exampleRu: 'У меня болит спина.', exampleEn: 'My back hurts.' },
  { french: 'le ventre', translation: 'живот', translationEn: 'stomach, belly', category: 'body', exampleFr: 'J\'ai mal au ventre.', exampleRu: 'У меня болит живот.', exampleEn: 'My stomach hurts.' },
  { french: 'le cœur', translation: 'сердце', translationEn: 'heart', category: 'body', exampleFr: 'J\'ai mal au cœur.', exampleRu: 'Меня тошнит.', exampleEn: 'I feel sick.' },
  { french: 'la gorge', translation: 'горло', translationEn: 'throat', category: 'body', exampleFr: 'J\'ai mal à la gorge.', exampleRu: 'У меня болит горло.', exampleEn: 'I have a sore throat.' },
  { french: 'le médecin', translation: 'врач', translationEn: 'doctor', category: 'body', exampleFr: 'Je vois le médecin.', exampleRu: 'Я иду к врачу.', exampleEn: 'I see the doctor.' },
  { french: 'le médicament', translation: 'лекарство', translationEn: 'medicine, medication', category: 'body', exampleFr: 'Je prends un médicament.', exampleRu: 'Я принимаю лекарство.', exampleEn: 'I take medicine.' },
  { french: 'la maladie', translation: 'болезнь', translationEn: 'illness, disease', category: 'body', exampleFr: 'C\'est une maladie grave.', exampleRu: 'Это серьёзная болезнь.', exampleEn: 'It is a serious illness.' },
  { french: 'la fièvre', translation: 'температура, жар', translationEn: 'fever', category: 'body', exampleFr: 'J\'ai de la fièvre.', exampleRu: 'У меня температура.', exampleEn: 'I have a fever.' },
  { french: 'fatigué', translation: 'усталый', translationEn: 'tired', category: 'body', exampleFr: 'Je suis très fatigué.', exampleRu: 'Я очень устал.', exampleEn: 'I am very tired.' },
  { french: 'malade', translation: 'больной', translationEn: 'sick, ill', category: 'body', exampleFr: 'Je suis malade.', exampleRu: 'Я болен.', exampleEn: 'I am sick.' },

  // Одежда
  { french: 'les vêtements', translation: 'одежда', translationEn: 'clothes', category: 'clothes', exampleFr: 'J\'achète des vêtements.', exampleRu: 'Я покупаю одежду.', exampleEn: 'I buy clothes.' },
  { french: 'le pantalon', translation: 'брюки', translationEn: 'trousers, pants', category: 'clothes', exampleFr: 'Un pantalon noir.', exampleRu: 'Чёрные брюки.', exampleEn: 'Black trousers.' },
  { french: 'la chemise', translation: 'рубашка', translationEn: 'shirt', category: 'clothes', exampleFr: 'Une chemise blanche.', exampleRu: 'Белая рубашка.', exampleEn: 'A white shirt.' },
  { french: 'la robe', translation: 'платье', translationEn: 'dress', category: 'clothes', exampleFr: 'Une belle robe rouge.', exampleRu: 'Красивое красное платье.', exampleEn: 'A beautiful red dress.' },
  { french: 'la jupe', translation: 'юбка', translationEn: 'skirt', category: 'clothes', exampleFr: 'Une jupe courte.', exampleRu: 'Короткая юбка.', exampleEn: 'A short skirt.' },
  { french: 'le pull', translation: 'свитер', translationEn: 'sweater, jumper', category: 'clothes', exampleFr: 'Un pull chaud.', exampleRu: 'Тёплый свитер.', exampleEn: 'A warm sweater.' },
  { french: 'le manteau', translation: 'пальто', translationEn: 'coat', category: 'clothes', exampleFr: 'Un manteau d\'hiver.', exampleRu: 'Зимнее пальто.', exampleEn: 'A winter coat.' },
  { french: 'la veste', translation: 'пиджак, куртка', translationEn: 'jacket, blazer', category: 'clothes', exampleFr: 'Une veste en cuir.', exampleRu: 'Кожаная куртка.', exampleEn: 'A leather jacket.' },
  { french: 'les chaussures', translation: 'обувь', translationEn: 'shoes', category: 'clothes', exampleFr: 'Des chaussures confortables.', exampleRu: 'Удобная обувь.', exampleEn: 'Comfortable shoes.' },
  { french: 'les chaussettes', translation: 'носки', translationEn: 'socks', category: 'clothes', exampleFr: 'Des chaussettes blanches.', exampleRu: 'Белые носки.', exampleEn: 'White socks.' },
  { french: 'le chapeau', translation: 'шляпа, шапка', translationEn: 'hat', category: 'clothes', exampleFr: 'Un chapeau rouge.', exampleRu: 'Красная шляпа.', exampleEn: 'A red hat.' },
  { french: 'l\'écharpe', translation: 'шарф', translationEn: 'scarf', category: 'clothes', exampleFr: 'Une écharpe en laine.', exampleRu: 'Шерстяной шарф.', exampleEn: 'A wool scarf.' },
  { french: 'les gants', translation: 'перчатки', translationEn: 'gloves', category: 'clothes', exampleFr: 'Des gants chauds.', exampleRu: 'Тёплые перчатки.', exampleEn: 'Warm gloves.' },
  { french: 'le sac', translation: 'сумка', translationEn: 'bag', category: 'clothes', exampleFr: 'Un grand sac.', exampleRu: 'Большая сумка.', exampleEn: 'A big bag.' },
  { french: 'le t-shirt', translation: 'футболка', translationEn: 't-shirt', category: 'clothes', exampleFr: 'Un t-shirt blanc.', exampleRu: 'Белая футболка.', exampleEn: 'A white t-shirt.' },

  // Цвета
  { french: 'rouge', translation: 'красный', translationEn: 'red', category: 'colors', exampleFr: 'Une voiture rouge.', exampleRu: 'Красная машина.', exampleEn: 'A red car.' },
  { french: 'bleu', translation: 'синий, голубой', translationEn: 'blue', category: 'colors', exampleFr: 'Le ciel est bleu.', exampleRu: 'Небо синее.', exampleEn: 'The sky is blue.' },
  { french: 'vert', translation: 'зелёный', translationEn: 'green', category: 'colors', exampleFr: 'L\'herbe est verte.', exampleRu: 'Трава зелёная.', exampleEn: 'The grass is green.' },
  { french: 'jaune', translation: 'жёлтый', translationEn: 'yellow', category: 'colors', exampleFr: 'Un citron jaune.', exampleRu: 'Жёлтый лимон.', exampleEn: 'A yellow lemon.' },
  { french: 'blanc', translation: 'белый', translationEn: 'white', category: 'colors', exampleFr: 'La neige est blanche.', exampleRu: 'Снег белый.', exampleEn: 'The snow is white.' },
  { french: 'noir', translation: 'чёрный', translationEn: 'black', category: 'colors', exampleFr: 'Un chat noir.', exampleRu: 'Чёрный кот.', exampleEn: 'A black cat.' },
  { french: 'gris', translation: 'серый', translationEn: 'grey', category: 'colors', exampleFr: 'Un ciel gris.', exampleRu: 'Серое небо.', exampleEn: 'A grey sky.' },
  { french: 'rose', translation: 'розовый', translationEn: 'pink', category: 'colors', exampleFr: 'Des fleurs roses.', exampleRu: 'Розовые цветы.', exampleEn: 'Pink flowers.' },
  { french: 'orange', translation: 'оранжевый', translationEn: 'orange', category: 'colors', exampleFr: 'Un fruit orange.', exampleRu: 'Оранжевый фрукт.', exampleEn: 'An orange fruit.' },
  { french: 'violet', translation: 'фиолетовый', translationEn: 'purple, violet', category: 'colors', exampleFr: 'Une robe violette.', exampleRu: 'Фиолетовое платье.', exampleEn: 'A purple dress.' },
  { french: 'marron', translation: 'коричневый', translationEn: 'brown', category: 'colors', exampleFr: 'Des yeux marron.', exampleRu: 'Карие глаза.', exampleEn: 'Brown eyes.' },

  // Числа
  { french: 'un / une', translation: 'один / одна', translationEn: 'one', category: 'numbers', exampleFr: 'J\'ai un frère.', exampleRu: 'У меня один брат.', exampleEn: 'I have one brother.' },
  { french: 'deux', translation: 'два', translationEn: 'two', category: 'numbers', exampleFr: 'J\'ai deux chats.', exampleRu: 'У меня два кота.', exampleEn: 'I have two cats.' },
  { french: 'trois', translation: 'три', translationEn: 'three', category: 'numbers', exampleFr: 'Trois enfants.', exampleRu: 'Три ребёнка.', exampleEn: 'Three children.' },
  { french: 'quatre', translation: 'четыре', translationEn: 'four', category: 'numbers', exampleFr: 'Quatre saisons.', exampleRu: 'Четыре времени года.', exampleEn: 'Four seasons.' },
  { french: 'cinq', translation: 'пять', translationEn: 'five', category: 'numbers', exampleFr: 'Cinq minutes.', exampleRu: 'Пять минут.', exampleEn: 'Five minutes.' },
  { french: 'six', translation: 'шесть', translationEn: 'six', category: 'numbers', exampleFr: 'Six heures du matin.', exampleRu: 'Шесть часов утра.', exampleEn: 'Six in the morning.' },
  { french: 'sept', translation: 'семь', translationEn: 'seven', category: 'numbers', exampleFr: 'Sept jours par semaine.', exampleRu: 'Семь дней в неделю.', exampleEn: 'Seven days a week.' },
  { french: 'huit', translation: 'восемь', translationEn: 'eight', category: 'numbers', exampleFr: 'Huit personnes.', exampleRu: 'Восемь человек.', exampleEn: 'Eight people.' },
  { french: 'neuf', translation: 'девять', translationEn: 'nine', category: 'numbers', exampleFr: 'Neuf euros.', exampleRu: 'Девять евро.', exampleEn: 'Nine euros.' },
  { french: 'dix', translation: 'десять', translationEn: 'ten', category: 'numbers', exampleFr: 'Dix minutes.', exampleRu: 'Десять минут.', exampleEn: 'Ten minutes.' },
  { french: 'vingt', translation: 'двадцать', translationEn: 'twenty', category: 'numbers', exampleFr: 'Vingt ans.', exampleRu: 'Двадцать лет.', exampleEn: 'Twenty years old.' },
  { french: 'trente', translation: 'тридцать', translationEn: 'thirty', category: 'numbers', exampleFr: 'Trente euros.', exampleRu: 'Тридцать евро.', exampleEn: 'Thirty euros.' },
  { french: 'cent', translation: 'сто', translationEn: 'one hundred', category: 'numbers', exampleFr: 'Cent personnes.', exampleRu: 'Сто человек.', exampleEn: 'One hundred people.' },
  { french: 'mille', translation: 'тысяча', translationEn: 'one thousand', category: 'numbers', exampleFr: 'Mille euros.', exampleRu: 'Тысяча евро.', exampleEn: 'One thousand euros.' },

  // Время
  { french: 'aujourd\'hui', translation: 'сегодня', translationEn: 'today', category: 'time', exampleFr: 'Aujourd\'hui il fait beau.', exampleRu: 'Сегодня хорошая погода.', exampleEn: 'Today the weather is nice.' },
  { french: 'demain', translation: 'завтра', translationEn: 'tomorrow', category: 'time', exampleFr: 'À demain !', exampleRu: 'До завтра!', exampleEn: 'See you tomorrow!' },
  { french: 'hier', translation: 'вчера', translationEn: 'yesterday', category: 'time', exampleFr: 'Hier, j\'étais malade.', exampleRu: 'Вчера я был болен.', exampleEn: 'Yesterday I was sick.' },
  { french: 'maintenant', translation: 'сейчас', translationEn: 'now', category: 'time', exampleFr: 'Je suis occupé maintenant.', exampleRu: 'Сейчас я занят.', exampleEn: 'I am busy now.' },
  { french: 'ce matin', translation: 'этим утром', translationEn: 'this morning', category: 'time', exampleFr: 'Ce matin, j\'ai couru.', exampleRu: 'Этим утром я бегал.', exampleEn: 'This morning I ran.' },
  { french: 'ce soir', translation: 'сегодня вечером', translationEn: 'tonight, this evening', category: 'time', exampleFr: 'On se voit ce soir.', exampleRu: 'Увидимся сегодня вечером.', exampleEn: 'We see each other tonight.' },
  { french: 'la semaine', translation: 'неделя', translationEn: 'week', category: 'time', exampleFr: 'Cette semaine.', exampleRu: 'На этой неделе.', exampleEn: 'This week.' },
  { french: 'le mois', translation: 'месяц', translationEn: 'month', category: 'time', exampleFr: 'Le mois prochain.', exampleRu: 'В следующем месяце.', exampleEn: 'Next month.' },
  { french: 'l\'année', translation: 'год', translationEn: 'year', category: 'time', exampleFr: 'Cette année.', exampleRu: 'В этом году.', exampleEn: 'This year.' },
  { french: 'l\'heure', translation: 'час, время', translationEn: 'hour, time', category: 'time', exampleFr: 'Quelle heure est-il ?', exampleRu: 'Который час?', exampleEn: 'What time is it?' },
  { french: 'la minute', translation: 'минута', translationEn: 'minute', category: 'time', exampleFr: 'Attends une minute.', exampleRu: 'Подожди минуту.', exampleEn: 'Wait a minute.' },
  { french: 'le matin', translation: 'утро', translationEn: 'morning', category: 'time', exampleFr: 'Le matin je cours.', exampleRu: 'Утром я бегаю.', exampleEn: 'In the morning I run.' },
  { french: 'l\'après-midi', translation: 'день, полдень', translationEn: 'afternoon', category: 'time', exampleFr: 'L\'après-midi je travaille.', exampleRu: 'Днём я работаю.', exampleEn: 'In the afternoon I work.' },
  { french: 'le soir', translation: 'вечер', translationEn: 'evening', category: 'time', exampleFr: 'Le soir je lis.', exampleRu: 'Вечером я читаю.', exampleEn: 'In the evening I read.' },
  { french: 'la nuit', translation: 'ночь', translationEn: 'night', category: 'time', exampleFr: 'La nuit je dors.', exampleRu: 'Ночью я сплю.', exampleEn: 'At night I sleep.' },
  { french: 'lundi', translation: 'понедельник', translationEn: 'Monday', category: 'time', exampleFr: 'Je travaille le lundi.', exampleRu: 'Я работаю по понедельникам.', exampleEn: 'I work on Mondays.' },
  { french: 'mardi', translation: 'вторник', translationEn: 'Tuesday', category: 'time', exampleFr: 'Rendez-vous mardi.', exampleRu: 'Встреча во вторник.', exampleEn: 'Meeting on Tuesday.' },
  { french: 'mercredi', translation: 'среда', translationEn: 'Wednesday', category: 'time', exampleFr: 'Mercredi après-midi.', exampleRu: 'Среда днём.', exampleEn: 'Wednesday afternoon.' },
  { french: 'jeudi', translation: 'четверг', translationEn: 'Thursday', category: 'time', exampleFr: 'On se voit jeudi.', exampleRu: 'Увидимся в четверг.', exampleEn: 'We see each other on Thursday.' },
  { french: 'vendredi', translation: 'пятница', translationEn: 'Friday', category: 'time', exampleFr: 'Vendredi soir.', exampleRu: 'Пятница вечером.', exampleEn: 'Friday evening.' },
  { french: 'samedi', translation: 'суббота', translationEn: 'Saturday', category: 'time', exampleFr: 'Le samedi matin.', exampleRu: 'Субботним утром.', exampleEn: 'Saturday morning.' },
  { french: 'dimanche', translation: 'воскресенье', translationEn: 'Sunday', category: 'time', exampleFr: 'Le dimanche je me repose.', exampleRu: 'В воскресенье я отдыхаю.', exampleEn: 'On Sunday I rest.' },
  { french: 'janvier', translation: 'январь', translationEn: 'January', category: 'time', exampleFr: 'En janvier il fait froid.', exampleRu: 'В январе холодно.', exampleEn: 'In January it is cold.' },
  { french: 'février', translation: 'февраль', translationEn: 'February', category: 'time', exampleFr: 'Février est court.', exampleRu: 'Февраль короткий.', exampleEn: 'February is short.' },
  { french: 'mars', translation: 'март', translationEn: 'March', category: 'time', exampleFr: 'En mars c\'est le printemps.', exampleRu: 'В марте — весна.', exampleEn: 'In March it is spring.' },
  { french: 'avril', translation: 'апрель', translationEn: 'April', category: 'time', exampleFr: 'En avril, il pleut.', exampleRu: 'В апреле идёт дождь.', exampleEn: 'In April it rains.' },
  { french: 'mai', translation: 'май', translationEn: 'May', category: 'time', exampleFr: 'Mai est un beau mois.', exampleRu: 'Май — красивый месяц.', exampleEn: 'May is a beautiful month.' },
  { french: 'juin', translation: 'июнь', translationEn: 'June', category: 'time', exampleFr: 'En juin il fait chaud.', exampleRu: 'В июне тепло.', exampleEn: 'In June it is warm.' },
  { french: 'juillet', translation: 'июль', translationEn: 'July', category: 'time', exampleFr: 'Juillet est le mois des vacances.', exampleRu: 'Июль — месяц каникул.', exampleEn: 'July is the holiday month.' },
  { french: 'août', translation: 'август', translationEn: 'August', category: 'time', exampleFr: 'En août je pars en vacances.', exampleRu: 'В августе я уезжаю в отпуск.', exampleEn: 'In August I go on holiday.' },
  { french: 'septembre', translation: 'сентябрь', translationEn: 'September', category: 'time', exampleFr: 'La rentrée en septembre.', exampleRu: 'Начало учёбы в сентябре.', exampleEn: 'Back to school in September.' },
  { french: 'octobre', translation: 'октябрь', translationEn: 'October', category: 'time', exampleFr: 'Octobre est coloré.', exampleRu: 'Октябрь красочный.', exampleEn: 'October is colourful.' },
  { french: 'novembre', translation: 'ноябрь', translationEn: 'November', category: 'time', exampleFr: 'Novembre est triste.', exampleRu: 'Ноябрь грустный.', exampleEn: 'November is gloomy.' },
  { french: 'décembre', translation: 'декабрь', translationEn: 'December', category: 'time', exampleFr: 'Noël en décembre.', exampleRu: 'Рождество в декабре.', exampleEn: 'Christmas in December.' },

  // Природа и погода
  { french: 'le soleil', translation: 'солнце', translationEn: 'sun', category: 'nature', exampleFr: 'Le soleil brille.', exampleRu: 'Солнце светит.', exampleEn: 'The sun is shining.' },
  { french: 'la pluie', translation: 'дождь', translationEn: 'rain', category: 'nature', exampleFr: 'Il pleut.', exampleRu: 'Идёт дождь.', exampleEn: 'It is raining.' },
  { french: 'la neige', translation: 'снег', translationEn: 'snow', category: 'nature', exampleFr: 'Il neige.', exampleRu: 'Идёт снег.', exampleEn: 'It is snowing.' },
  { french: 'le vent', translation: 'ветер', translationEn: 'wind', category: 'nature', exampleFr: 'Il y a du vent.', exampleRu: 'Дует ветер.', exampleEn: 'It is windy.' },
  { french: 'le nuage', translation: 'облако', translationEn: 'cloud', category: 'nature', exampleFr: 'Un ciel nuageux.', exampleRu: 'Облачное небо.', exampleEn: 'A cloudy sky.' },
  { french: 'chaud', translation: 'тёплый, горячий', translationEn: 'hot, warm', category: 'nature', exampleFr: 'Il fait chaud.', exampleRu: 'Жарко.', exampleEn: 'It is hot.' },
  { french: 'froid', translation: 'холодный', translationEn: 'cold', category: 'nature', exampleFr: 'Il fait froid.', exampleRu: 'Холодно.', exampleEn: 'It is cold.' },
  { french: 'la mer', translation: 'море', translationEn: 'sea', category: 'nature', exampleFr: 'La mer est belle.', exampleRu: 'Море красивое.', exampleEn: 'The sea is beautiful.' },
  { french: 'la montagne', translation: 'гора', translationEn: 'mountain', category: 'nature', exampleFr: 'J\'aime la montagne.', exampleRu: 'Я люблю горы.', exampleEn: 'I love the mountains.' },
  { french: 'la forêt', translation: 'лес', translationEn: 'forest', category: 'nature', exampleFr: 'Une promenade en forêt.', exampleRu: 'Прогулка в лесу.', exampleEn: 'A walk in the forest.' },
  { french: 'le lac', translation: 'озеро', translationEn: 'lake', category: 'nature', exampleFr: 'Un lac bleu.', exampleRu: 'Синее озеро.', exampleEn: 'A blue lake.' },
  { french: 'la rivière', translation: 'река', translationEn: 'river', category: 'nature', exampleFr: 'La rivière coule.', exampleRu: 'Река течёт.', exampleEn: 'The river flows.' },
  { french: 'la plage', translation: 'пляж', translationEn: 'beach', category: 'nature', exampleFr: 'Je vais à la plage.', exampleRu: 'Я иду на пляж.', exampleEn: 'I go to the beach.' },
  { french: 'l\'arbre', translation: 'дерево', translationEn: 'tree', category: 'nature', exampleFr: 'Un grand arbre.', exampleRu: 'Большое дерево.', exampleEn: 'A big tree.' },
  { french: 'la fleur', translation: 'цветок', translationEn: 'flower', category: 'nature', exampleFr: 'De belles fleurs.', exampleRu: 'Красивые цветы.', exampleEn: 'Beautiful flowers.' },
  { french: 'l\'animal', translation: 'животное', translationEn: 'animal', category: 'nature', exampleFr: 'Quel animal ?', exampleRu: 'Какое животное?', exampleEn: 'What animal?' },
  { french: 'le chien', translation: 'собака', translationEn: 'dog', category: 'nature', exampleFr: 'Mon chien est grand.', exampleRu: 'Моя собака большая.', exampleEn: 'My dog is big.' },
  { french: 'le chat', translation: 'кошка', translationEn: 'cat', category: 'nature', exampleFr: 'Mon chat dort.', exampleRu: 'Моя кошка спит.', exampleEn: 'My cat is sleeping.' },
  { french: 'l\'oiseau', translation: 'птица', translationEn: 'bird', category: 'nature', exampleFr: 'Un oiseau chante.', exampleRu: 'Птица поёт.', exampleEn: 'A bird is singing.' },

  // Прилагательные
  { french: 'grand', translation: 'большой, высокий', translationEn: 'big, tall', category: 'adjectives', exampleFr: 'Un grand homme.', exampleRu: 'Высокий мужчина.', exampleEn: 'A tall man.' },
  { french: 'petit', translation: 'маленький', translationEn: 'small, little', category: 'adjectives', exampleFr: 'Une petite maison.', exampleRu: 'Маленький дом.', exampleEn: 'A small house.' },
  { french: 'beau / belle', translation: 'красивый / красивая', translationEn: 'beautiful, handsome', category: 'adjectives', exampleFr: 'Un beau tableau.', exampleRu: 'Красивая картина.', exampleEn: 'A beautiful painting.' },
  { french: 'bon / bonne', translation: 'хороший / хорошая', translationEn: 'good', category: 'adjectives', exampleFr: 'Un bon repas.', exampleRu: 'Хорошая еда.', exampleEn: 'A good meal.' },
  { french: 'mauvais', translation: 'плохой', translationEn: 'bad', category: 'adjectives', exampleFr: 'Un mauvais film.', exampleRu: 'Плохой фильм.', exampleEn: 'A bad film.' },
  { french: 'nouveau / nouvelle', translation: 'новый / новая', translationEn: 'new', category: 'adjectives', exampleFr: 'Un nouveau livre.', exampleRu: 'Новая книга.', exampleEn: 'A new book.' },
  { french: 'vieux / vieille', translation: 'старый / старая', translationEn: 'old', category: 'adjectives', exampleFr: 'Un vieux château.', exampleRu: 'Старый замок.', exampleEn: 'An old castle.' },
  { french: 'jeune', translation: 'молодой', translationEn: 'young', category: 'adjectives', exampleFr: 'Un jeune homme.', exampleRu: 'Молодой человек.', exampleEn: 'A young man.' },
  { french: 'long / longue', translation: 'длинный / длинная', translationEn: 'long', category: 'adjectives', exampleFr: 'Une longue route.', exampleRu: 'Длинная дорога.', exampleEn: 'A long road.' },
  { french: 'court', translation: 'короткий', translationEn: 'short', category: 'adjectives', exampleFr: 'Une jupe courte.', exampleRu: 'Короткая юбка.', exampleEn: 'A short skirt.' },
  { french: 'haut', translation: 'высокий', translationEn: 'high, tall', category: 'adjectives', exampleFr: 'Un bâtiment haut.', exampleRu: 'Высокое здание.', exampleEn: 'A tall building.' },
  { french: 'bas', translation: 'низкий', translationEn: 'low', category: 'adjectives', exampleFr: 'Un prix bas.', exampleRu: 'Низкая цена.', exampleEn: 'A low price.' },
  { french: 'rapide', translation: 'быстрый', translationEn: 'fast, quick', category: 'adjectives', exampleFr: 'Un train rapide.', exampleRu: 'Быстрый поезд.', exampleEn: 'A fast train.' },
  { french: 'lent', translation: 'медленный', translationEn: 'slow', category: 'adjectives', exampleFr: 'Marche lentement.', exampleRu: 'Иди медленно.', exampleEn: 'Walk slowly.' },
  { french: 'facile', translation: 'лёгкий, простой', translationEn: 'easy', category: 'adjectives', exampleFr: 'C\'est facile.', exampleRu: 'Это легко.', exampleEn: 'It is easy.' },
  { french: 'difficile', translation: 'трудный, сложный', translationEn: 'difficult, hard', category: 'adjectives', exampleFr: 'C\'est difficile.', exampleRu: 'Это трудно.', exampleEn: 'It is difficult.' },
  { french: 'intéressant', translation: 'интересный', translationEn: 'interesting', category: 'adjectives', exampleFr: 'Un livre intéressant.', exampleRu: 'Интересная книга.', exampleEn: 'An interesting book.' },
  { french: 'ennuyeux', translation: 'скучный', translationEn: 'boring', category: 'adjectives', exampleFr: 'Un film ennuyeux.', exampleRu: 'Скучный фильм.', exampleEn: 'A boring film.' },
  { french: 'sympa', translation: 'приятный, милый', translationEn: 'nice, pleasant', category: 'adjectives', exampleFr: 'Il est sympa.', exampleRu: 'Он приятный.', exampleEn: 'He is nice.' },
  { french: 'gentil', translation: 'добрый, любезный', translationEn: 'kind, gentle', category: 'adjectives', exampleFr: 'Elle est gentille.', exampleRu: 'Она добрая.', exampleEn: 'She is kind.' },
  { french: 'content', translation: 'довольный, счастливый', translationEn: 'happy, pleased', category: 'adjectives', exampleFr: 'Je suis content.', exampleRu: 'Я доволен.', exampleEn: 'I am happy.' },
  { french: 'triste', translation: 'грустный, печальный', translationEn: 'sad', category: 'adjectives', exampleFr: 'Elle est triste.', exampleRu: 'Она грустная.', exampleEn: 'She is sad.' },

  // Базовые слова и местоимения
  { french: 'oui', translation: 'да', translationEn: 'yes', category: 'basics', exampleFr: 'Oui, je comprends.', exampleRu: 'Да, я понимаю.', exampleEn: 'Yes, I understand.' },
  { french: 'non', translation: 'нет', translationEn: 'no', category: 'basics', grammarTag: 'negation', exampleFr: 'Non, merci.', exampleRu: 'Нет, спасибо.', exampleEn: 'No, thank you.' },
  { french: 'merci', translation: 'спасибо', translationEn: 'thank you', category: 'basics', exampleFr: 'Merci beaucoup !', exampleRu: 'Большое спасибо!', exampleEn: 'Thank you very much!' },
  { french: 's\'il vous plaît', translation: 'пожалуйста (вежливо)', translationEn: 'please', category: 'basics', exampleFr: 'Un café, s\'il vous plaît.', exampleRu: 'Кофе, пожалуйста.', exampleEn: 'A coffee, please.' },
  { french: 'bonjour', translation: 'здравствуйте, добрый день', translationEn: 'hello, good morning', category: 'basics', exampleFr: 'Bonjour, ça va ?', exampleRu: 'Добрый день, как дела?', exampleEn: 'Hello, how are you?' },
  { french: 'bonsoir', translation: 'добрый вечер', translationEn: 'good evening', category: 'basics', exampleFr: 'Bonsoir !', exampleRu: 'Добрый вечер!', exampleEn: 'Good evening!' },
  { french: 'au revoir', translation: 'до свидания', translationEn: 'goodbye', category: 'basics', exampleFr: 'Au revoir !', exampleRu: 'До свидания!', exampleEn: 'Goodbye!' },
  { french: 'excusez-moi', translation: 'извините', translationEn: 'excuse me', category: 'basics', exampleFr: 'Excusez-moi, où est la gare ?', exampleRu: 'Извините, где вокзал?', exampleEn: 'Excuse me, where is the station?' },
  { french: 'pardon', translation: 'простите', translationEn: 'sorry, pardon', category: 'basics', exampleFr: 'Pardon, je n\'ai pas compris.', exampleRu: 'Простите, я не понял.', exampleEn: 'Sorry, I did not understand.' },
  { french: 'je ne comprends pas', translation: 'я не понимаю', translationEn: 'I do not understand', category: 'basics', exampleFr: 'Je ne comprends pas le français.', exampleRu: 'Я не понимаю по-французски.', exampleEn: 'I do not understand French.' },
  { french: 'comment', translation: 'как', translationEn: 'how', category: 'basics', exampleFr: 'Comment tu t\'appelles ?', exampleRu: 'Как тебя зовут?', exampleEn: 'What is your name?' },
  { french: 'pourquoi', translation: 'почему', translationEn: 'why', category: 'basics', exampleFr: 'Pourquoi tu pleures ?', exampleRu: 'Почему ты плачешь?', exampleEn: 'Why are you crying?' },
  { french: 'quand', translation: 'когда', translationEn: 'when', category: 'basics', exampleFr: 'Quand tu arrives ?', exampleRu: 'Когда ты приедешь?', exampleEn: 'When do you arrive?' },
  { french: 'où', translation: 'где, куда', translationEn: 'where', category: 'basics', exampleFr: 'Où tu habites ?', exampleRu: 'Где ты живёшь?', exampleEn: 'Where do you live?' },
  { french: 'qui', translation: 'кто', translationEn: 'who', category: 'basics', exampleFr: 'Qui est là ?', exampleRu: 'Кто там?', exampleEn: 'Who is there?' },
  { french: 'combien', translation: 'сколько', translationEn: 'how much, how many', category: 'basics', exampleFr: 'Combien ça coûte ?', exampleRu: 'Сколько стоит?', exampleEn: 'How much does it cost?' },
  { french: 'beaucoup', translation: 'много', translationEn: 'a lot, much', category: 'basics', exampleFr: 'Merci beaucoup.', exampleRu: 'Большое спасибо.', exampleEn: 'Thank you very much.' },
  { french: 'peu', translation: 'мало, немного', translationEn: 'a little, few', category: 'basics', exampleFr: 'Un peu de lait.', exampleRu: 'Немного молока.', exampleEn: 'A little milk.' },
  { french: 'très', translation: 'очень', translationEn: 'very', category: 'basics', exampleFr: 'C\'est très bien.', exampleRu: 'Это очень хорошо.', exampleEn: 'That is very good.' },
  { french: 'aussi', translation: 'тоже, также', translationEn: 'also, too', category: 'basics', exampleFr: 'Moi aussi.', exampleRu: 'Я тоже.', exampleEn: 'Me too.' },
  { french: 'encore', translation: 'ещё', translationEn: 'again, still', category: 'basics', exampleFr: 'Encore une fois.', exampleRu: 'Ещё раз.', exampleEn: 'Once more.' },
  { french: 'toujours', translation: 'всегда', translationEn: 'always', category: 'basics', exampleFr: 'Je t\'aime toujours.', exampleRu: 'Я тебя всегда люблю.', exampleEn: 'I always love you.' },
  { french: 'jamais', translation: 'никогда', translationEn: 'never', category: 'basics', grammarTag: 'negation', exampleFr: 'Je ne fume jamais.', exampleRu: 'Я никогда не курю.', exampleEn: 'I never smoke.' },
  { french: 'souvent', translation: 'часто', translationEn: 'often', category: 'basics', exampleFr: 'Je viens souvent ici.', exampleRu: 'Я часто прихожу сюда.', exampleEn: 'I come here often.' },
  { french: 'quelquefois', translation: 'иногда', translationEn: 'sometimes', category: 'basics', exampleFr: 'Quelquefois je lis.', exampleRu: 'Иногда я читаю.', exampleEn: 'Sometimes I read.' },
  { french: 'ici', translation: 'здесь', translationEn: 'here', category: 'basics', exampleFr: 'Je suis ici.', exampleRu: 'Я здесь.', exampleEn: 'I am here.' },
  { french: 'là', translation: 'там', translationEn: 'there', category: 'basics', exampleFr: 'Il est là.', exampleRu: 'Он там.', exampleEn: 'He is there.' },
];
