// Vocabulary words found in reading texts that are missing from the main words DB.
// These are content words (nouns, verbs, adjectives) not resolvable by lemmatization.

export const wordsReading = [
  // ── A1 ───────────────────────────────────────────────────────────────────────
  { french: 'chose',        translation: 'вещь, дело',                   partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'fois',         translation: 'раз (une fois = один раз)',     partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'an',           translation: 'год',                           partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'temps',        translation: 'время; погода',                 partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'femme',        translation: 'женщина; жена',                 partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'homme',        translation: 'мужчина; человек',              partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'enfant',       translation: 'ребёнок',                       partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'maison',       translation: 'дом',                           partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'pays',         translation: 'страна',                        partOfSpeech: 'noun', level: 'A1' as const, gender: null },
  { french: 'ville',        translation: 'город',                         partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'rue',          translation: 'улица',                         partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'vie',          translation: 'жизнь',                         partOfSpeech: 'noun', level: 'A1' as const, gender: 'f' },
  { french: 'monde',        translation: 'мир, свет',                     partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'ami',          translation: 'друг',                          partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'argent',       translation: 'деньги; серебро',               partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'air',          translation: 'воздух; вид',                   partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'nom',          translation: 'имя; название',                 partOfSpeech: 'noun', level: 'A1' as const, gender: 'm' },
  { french: 'bon',          translation: 'хороший',                       partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'grand',        translation: 'большой; великий',              partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'petit',        translation: 'маленький',                     partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'nouveau',      translation: 'новый',                         partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'premier',      translation: 'первый',                        partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'dernier',      translation: 'последний; прошлый',            partOfSpeech: 'adj',  level: 'A1' as const, gender: null },
  { french: 'trouver',      translation: 'находить, считать',             partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'prendre',      translation: 'брать, принимать',              partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'parler',       translation: 'говорить, разговаривать',       partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'partir',       translation: 'уходить, уезжать',              partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'donner',       translation: 'давать, дарить',                partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'rester',       translation: 'оставаться',                    partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'arriver',      translation: 'приходить, приезжать; происходить', partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'travailler',   translation: 'работать',                      partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  { french: 'habiter',      translation: 'жить, проживать',               partOfSpeech: 'verb', level: 'A1' as const, gender: null },
  // ── A2 ───────────────────────────────────────────────────────────────────────
  { french: 'avion',        translation: 'самолёт',                       partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'voyage',       translation: 'путешествие, поездка',          partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'repas',        translation: 'еда, приём пищи',               partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'raison',       translation: 'причина; разум; правота',       partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'idée',         translation: 'идея, мысль',                   partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'langue',       translation: 'язык (речь); язык (орган)',     partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'nombre',       translation: 'число, количество',             partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'numéro',       translation: 'номер',                         partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'tradition',    translation: 'традиция',                      partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'valeur',       translation: 'ценность; стоимость',           partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'risque',       translation: 'риск',                          partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'problème',     translation: 'проблема',                      partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'offre',        translation: 'предложение (товар/услуга)',     partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'peau',         translation: 'кожа',                          partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'herbe',        translation: 'трава, зелень',                 partOfSpeech: 'noun', level: 'A2' as const, gender: 'f' },
  { french: 'signe',        translation: 'знак, признак',                 partOfSpeech: 'noun', level: 'A2' as const, gender: 'm' },
  { french: 'prochain',     translation: 'следующий, ближайший',          partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'différent',    translation: 'разный, отличный',              partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'difficile',    translation: 'трудный, сложный',              partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'important',    translation: 'важный',                        partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'unique',       translation: 'уникальный, единственный',      partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'traditionnel', translation: 'традиционный',                  partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'social',       translation: 'социальный, общественный',      partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'local',        translation: 'местный, локальный',            partOfSpeech: 'adj',  level: 'A2' as const, gender: null },
  { french: 'publier',      translation: 'публиковать',                   partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'commencer',    translation: 'начинать(ся)',                   partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'chercher',     translation: 'искать',                        partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'passer',       translation: 'проходить; проводить (время)',  partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'montrer',      translation: 'показывать',                    partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'utiliser',     translation: 'использовать',                  partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'choisir',      translation: 'выбирать',                      partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'permettre',    translation: 'позволять, разрешать',          partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'laisser',      translation: 'оставлять; позволять',          partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  { french: 'tenir',        translation: 'держать; проводить',            partOfSpeech: 'verb', level: 'A2' as const, gender: null },
  // ── B1 ───────────────────────────────────────────────────────────────────────
  { french: 'accord',       translation: 'согласие; договор (d\'accord = ладно)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'ampleur',      translation: 'масштаб, размах',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'biais',        translation: 'предвзятость; канал (par le biais de = через)', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'cadre',        translation: 'рамки; обстановка; руководитель', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'carbone',      translation: 'углерод, углекислый газ',       partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'carrière',     translation: 'карьера; карьер',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'cause',        translation: 'причина; дело (борьбы)',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'changement',   translation: 'изменение, перемена',           partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'citoyenneté',  translation: 'гражданство',                   partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'communauté',   translation: 'сообщество, община',            partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'conflit',      translation: 'конфликт',                      partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'conscience',   translation: 'сознание, осознанность, совесть', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'construction', translation: 'строительство, построение',     partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'conviction',   translation: 'убеждение',                     partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'covoiturage',  translation: 'совместные поездки, карпулинг', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'culture',      translation: 'культура',                      partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'décision',     translation: 'решение',                       partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'domaine',      translation: 'область, сфера, домен',         partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'emploi',       translation: 'работа, занятость; употребление', partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'enquête',      translation: 'расследование; опрос',          partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'entreprise',   translation: 'предприятие, компания',          partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'environnement',translation: 'окружающая среда, среда',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'erreur',       translation: 'ошибка',                        partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'espace',       translation: 'пространство, место',           partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'gaspillage',   translation: 'расточительство, трата',        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'génération',   translation: 'поколение',                     partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'habitant',     translation: 'житель, обитатель',             partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'intelligence', translation: 'интеллект, разум',              partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'interdiction', translation: 'запрет',                        partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'islam',        translation: 'ислам',                         partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'laïcité',      translation: 'светскость, принцип отделения церкви от государства', partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'limite',       translation: 'предел, граница',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'masse',        translation: 'масса, множество',              partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'modèle',       translation: 'модель, образец',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'obstacle',     translation: 'препятствие, помеха',           partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'opportunité',  translation: 'возможность, шанс',             partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'outil',        translation: 'инструмент, средство',          partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'phénomène',    translation: 'явление, феномен',              partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'profession',   translation: 'профессия',                     partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'qualité',      translation: 'качество',                      partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'relation',     translation: 'отношение, связь',              partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'religion',     translation: 'религия',                       partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'séparation',   translation: 'разделение, отделение',         partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'secteur',      translation: 'сектор, отрасль',               partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'système',      translation: 'система',                       partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'tendance',     translation: 'тенденция, тренд',              partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'tension',      translation: 'напряжение, напряжённость',     partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'territoire',   translation: 'территория',                    partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'tourisme',     translation: 'туризм',                        partOfSpeech: 'noun', level: 'B1' as const, gender: 'm' },
  { french: 'voile',        translation: 'вуаль, хиджаб; парус',         partOfSpeech: 'noun', level: 'B1' as const, gender: null },
  { french: 'zone',         translation: 'зона, район',                   partOfSpeech: 'noun', level: 'B1' as const, gender: 'f' },
  { french: 'accessible',   translation: 'доступный, доступный',          partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'climatique',   translation: 'климатический',                 partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'collectif',    translation: 'коллективный',                  partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'culturel',     translation: 'культурный',                    partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'global',       translation: 'глобальный, всемирный',         partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'historique',   translation: 'исторический',                  partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'individuel',   translation: 'индивидуальный, личный',        partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'international',translation: 'международный',                 partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'professionnel',translation: 'профессиональный',              partOfSpeech: 'adj',  level: 'B1' as const, gender: null },
  { french: 'adapter',      translation: 'адаптировать, приспосабливать', partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'adopter',      translation: 'принимать, усваивать',          partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'concilier',    translation: 'примирять, совмещать',          partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'encadrer',     translation: 'контролировать, регулировать',  partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'garantir',     translation: 'гарантировать',                 partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'interdire',    translation: 'запрещать',                     partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'protéger',     translation: 'защищать',                      partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'réduire',      translation: 'сокращать, уменьшать',          partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'représenter',  translation: 'представлять, изображать',      partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'respecter',    translation: 'уважать, соблюдать',            partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  { french: 'gaspiller',    translation: 'расточать, тратить впустую',    partOfSpeech: 'verb', level: 'B1' as const, gender: null },
  // ── B2 ───────────────────────────────────────────────────────────────────────
  { french: 'algorithme',   translation: 'алгоритм',                      partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'diversité',    translation: 'разнообразие, многообразие',    partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'équité',       translation: 'справедливость, равенство',     partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'fraude',       translation: 'мошенничество, обман',          partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'neutralité',   translation: 'нейтралитет, нейтральность',    partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'pluralisme',   translation: 'плюрализм',                     partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'technologie',  translation: 'технология',                    partOfSpeech: 'noun', level: 'B2' as const, gender: 'f' },
  { french: 'universalisme',translation: 'универсализм',                  partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'végétarisme',  translation: 'вегетарианство',                partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'véganisme',    translation: 'веганство',                     partOfSpeech: 'noun', level: 'B2' as const, gender: 'm' },
  { french: 'islamique',    translation: 'исламский',                     partOfSpeech: 'adj',  level: 'B2' as const, gender: null },
  { french: 'médical',      translation: 'медицинский',                   partOfSpeech: 'adj',  level: 'B2' as const, gender: null },
  { french: 'numérique',    translation: 'цифровой',                      partOfSpeech: 'adj',  level: 'B2' as const, gender: null },
  { french: 'religieux',    translation: 'религиозный',                   partOfSpeech: 'adj',  level: 'B2' as const, gender: null },
  { french: 'diagnostiquer',translation: 'диагностировать',               partOfSpeech: 'verb', level: 'B2' as const, gender: null },
  { french: 'intensifier',  translation: 'усиливать, интенсифицировать',  partOfSpeech: 'verb', level: 'B2' as const, gender: null },
  { french: 'optimiser',    translation: 'оптимизировать',                partOfSpeech: 'verb', level: 'B2' as const, gender: null },
  { french: 'démocratiser', translation: 'демократизировать',             partOfSpeech: 'verb', level: 'B2' as const, gender: null },
];
