export const wordsB2Extra6 = [
  // Philosophie
  { french: 'la métaphysique', translation: 'метафизика', translationEn: 'metaphysics', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La métaphysique s\'interroge sur l\'être et l\'existence.', exampleRu: 'Метафизика задаётся вопросами о бытии и существовании.', exampleEn: 'Metaphysics questions being and existence.' },
  { french: 'l\'épistémologie', translation: 'эпистемология; теория познания', translationEn: 'epistemology', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'épistémologie étudie les fondements du savoir.', exampleRu: 'Эпистемология изучает основы знания.', exampleEn: 'Epistemology studies the foundations of knowledge.' },
  { french: 'l\'ontologie', translation: 'онтология', translationEn: 'ontology', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'ontologie pose la question de la nature de l\'être.', exampleRu: 'Онтология ставит вопрос о природе бытия.', exampleEn: 'Ontology raises the question of the nature of being.' },
  { french: 'le rationalisme', translation: 'рационализм', translationEn: 'rationalism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Descartes est un représentant du rationalisme.', exampleRu: 'Декарт — представитель рационализма.', exampleEn: 'Descartes is a representative of rationalism.' },
  { french: 'l\'empirisme', translation: 'эмпиризм', translationEn: 'empiricism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'empirisme valorise l\'expérience sensible.', exampleRu: 'Эмпиризм ценит чувственный опыт.', exampleEn: 'Empiricism values sensory experience.' },
  { french: 'le matérialisme', translation: 'материализм', translationEn: 'materialism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le matérialisme historique est au cœur du marxisme.', exampleRu: 'Исторический материализм — ядро марксизма.', exampleEn: 'Historical materialism is at the heart of Marxism.' },
  { french: 'l\'idéalisme', translation: 'идеализм', translationEn: 'idealism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Hegel a développé un idéalisme absolu.', exampleRu: 'Гегель разработал абсолютный идеализм.', exampleEn: 'Hegel developed an absolute idealism.' },
  { french: 'le pragmatisme', translation: 'прагматизм', translationEn: 'pragmatism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le pragmatisme juge les idées à leurs effets pratiques.', exampleRu: 'Прагматизм оценивает идеи по их практическим результатам.', exampleEn: 'Pragmatism judges ideas by their practical effects.' },
  { french: 'l\'existentialisme', translation: 'экзистенциализм', translationEn: 'existentialism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'existentialisme de Sartre affirme la liberté humaine.', exampleRu: 'Экзистенциализм Сартра утверждает человеческую свободу.', exampleEn: 'Sartre\'s existentialism affirms human freedom.' },
  { french: 'le nihilisme', translation: 'нигилизм', translationEn: 'nihilism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Nietzsche a décrit le nihilisme comme une crise culturelle.', exampleRu: 'Ницше описал нигилизм как культурный кризис.', exampleEn: 'Nietzsche described nihilism as a cultural crisis.' },
  { french: 'l\'utilitarisme', translation: 'утилитаризм', translationEn: 'utilitarianism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'utilitarisme vise le plus grand bonheur du plus grand nombre.', exampleRu: 'Утилитаризм стремится к наибольшему счастью наибольшего числа людей.', exampleEn: 'Utilitarianism aims for the greatest happiness of the greatest number.' },
  { french: 'la dialectique', translation: 'диалектика', translationEn: 'dialectics', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La dialectique hégélienne repose sur thèse-antithèse-synthèse.', exampleRu: 'Гегелевская диалектика основана на тезисе-антитезисе-синтезе.', exampleEn: 'Hegelian dialectics rests on thesis-antithesis-synthesis.' },
  { french: 'la subjectivité', translation: 'субъективность', translationEn: 'subjectivity', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Toute perception est teintée de subjectivité.', exampleRu: 'Любое восприятие окрашено субъективностью.', exampleEn: 'All perception is tinged with subjectivity.' },
  { french: 'l\'objectivité', translation: 'объективность', translationEn: 'objectivity', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'objectivité scientifique est un idéal à atteindre.', exampleRu: 'Научная объективность — это идеал, к которому стремятся.', exampleEn: 'Scientific objectivity is an ideal to strive for.' },
  { french: 'la contingence', translation: 'случайность; случайный характер', translationEn: 'contingency', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La contingence du monde est au cœur de l\'existentialisme.', exampleRu: 'Случайность мира — суть экзистенциализма.', exampleEn: 'The contingency of the world is at the heart of existentialism.' },

  // Éthique
  { french: 'la déontologie', translation: 'деонтология; профессиональная этика', translationEn: 'deontology; professional ethics', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Le médecin respecte la déontologie médicale.', exampleRu: 'Врач соблюдает медицинскую деонтологию.', exampleEn: 'The doctor respects medical ethics.' },
  { french: 'la morale', translation: 'мораль; нравственность', translationEn: 'morality; moral', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La morale kantienne impose des devoirs absolus.', exampleRu: 'Кантовская мораль предписывает абсолютные обязанности.', exampleEn: 'Kantian morality imposes absolute duties.' },
  { french: 'le relativisme moral', translation: 'моральный релятивизм', translationEn: 'moral relativism', category: 'ethics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le relativisme moral remet en cause les valeurs universelles.', exampleRu: 'Моральный релятивизм ставит под сомнение универсальные ценности.', exampleEn: 'Moral relativism questions universal values.' },
  { french: 'le dilemme', translation: 'дилемма', translationEn: 'dilemma', category: 'ethics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Face à ce dilemme éthique, la décision fut difficile.', exampleRu: 'Перед лицом этой этической дилеммы решение было трудным.', exampleEn: 'Faced with this ethical dilemma, the decision was difficult.' },
  { french: 'la vertu', translation: 'добродетель', translationEn: 'virtue', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Aristote définit la vertu comme un juste milieu.', exampleRu: 'Аристотель определяет добродетель как золотую середину.', exampleEn: 'Aristotle defines virtue as a golden mean.' },
  { french: 'le vice', translation: 'порок', translationEn: 'vice', category: 'ethics', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'avarice est considérée comme un vice capital.', exampleRu: 'Скупость считается смертным грехом.', exampleEn: 'Greed is considered a capital vice.' },
  { french: 'la responsabilité morale', translation: 'моральная ответственность', translationEn: 'moral responsibility', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La responsabilité morale suppose la liberté de choix.', exampleRu: 'Моральная ответственность предполагает свободу выбора.', exampleEn: 'Moral responsibility presupposes freedom of choice.' },
  { french: 'l\'éthique appliquée', translation: 'прикладная этика', translationEn: 'applied ethics', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La bioéthique est une branche de l\'éthique appliquée.', exampleRu: 'Биоэтика — ветвь прикладной этики.', exampleEn: 'Bioethics is a branch of applied ethics.' },

  // Sociologie
  { french: 'la stratification sociale', translation: 'социальная стратификация', translationEn: 'social stratification', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La stratification sociale détermine les inégalités.', exampleRu: 'Социальная стратификация определяет неравенство.', exampleEn: 'Social stratification determines inequalities.' },
  { french: 'la mobilité sociale', translation: 'социальная мобильность', translationEn: 'social mobility', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La mobilité sociale ascendante reste limitée.', exampleRu: 'Восходящая социальная мобильность остаётся ограниченной.', exampleEn: 'Upward social mobility remains limited.' },
  { french: 'la reproduction sociale', translation: 'социальное воспроизводство', translationEn: 'social reproduction', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Bourdieu a analysé la reproduction sociale.', exampleRu: 'Бурдьё проанализировал социальное воспроизводство.', exampleEn: 'Bourdieu analyzed social reproduction.' },
  { french: 'le capital social', translation: 'социальный капитал', translationEn: 'social capital', category: 'sociology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le capital social favorise la réussite professionnelle.', exampleRu: 'Социальный капитал способствует профессиональному успеху.', exampleEn: 'Social capital promotes professional success.' },
  { french: 'la norme sociale', translation: 'социальная норма', translationEn: 'social norm', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Les normes sociales évoluent avec le temps.', exampleRu: 'Социальные нормы меняются со временем.', exampleEn: 'Social norms evolve over time.' },
  { french: 'la déviance', translation: 'девиантность; отклонение', translationEn: 'deviance', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La déviance est définie par rapport à la norme.', exampleRu: 'Девиантность определяется относительно нормы.', exampleEn: 'Deviance is defined in relation to the norm.' },
  { french: 'la socialisation', translation: 'социализация', translationEn: 'socialization', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La socialisation primaire a lieu dans la famille.', exampleRu: 'Первичная социализация происходит в семье.', exampleEn: 'Primary socialization takes place in the family.' },
  { french: 'l\'intégration sociale', translation: 'социальная интеграция', translationEn: 'social integration', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'intégration sociale des migrants est un enjeu majeur.', exampleRu: 'Социальная интеграция мигрантов — ключевая проблема.', exampleEn: 'Social integration of migrants is a major issue.' },
  { french: 'l\'exclusion sociale', translation: 'социальная изоляция', translationEn: 'social exclusion', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'exclusion sociale fragilise les individus.', exampleRu: 'Социальная изоляция ослабляет людей.', exampleEn: 'Social exclusion makes individuals vulnerable.' },
  { french: 'la cohésion sociale', translation: 'социальная сплочённость', translationEn: 'social cohesion', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La cohésion sociale est menacée par les inégalités.', exampleRu: 'Социальная сплочённость находится под угрозой из-за неравенства.', exampleEn: 'Social cohesion is threatened by inequalities.' },
  { french: 'le lien social', translation: 'социальная связь', translationEn: 'social bond', category: 'sociology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le bénévolat renforce le lien social.', exampleRu: 'Волонтёрство укрепляет социальную связь.', exampleEn: 'Volunteering strengthens the social bond.' },
  { french: 'le communautarisme', translation: 'коммунитаризм', translationEn: 'communitarianism', category: 'sociology', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le communautarisme peut fragiliser le vivre-ensemble.', exampleRu: 'Коммунитаризм может подрывать совместное проживание.', exampleEn: 'Communitarianism can weaken social coexistence.' },
  { french: 'l\'identité culturelle', translation: 'культурная идентичность', translationEn: 'cultural identity', category: 'sociology', partOfSpeech: 'noun', gender: 'f', exampleFr: 'L\'identité culturelle se construit tout au long de la vie.', exampleRu: 'Культурная идентичность формируется на протяжении всей жизни.', exampleEn: 'Cultural identity is built throughout life.' },

  // Concepts philosophiques importants
  { french: 'l\'alibi', translation: 'алиби', translationEn: 'alibi', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'L\'accusé a fourni un alibi solide.', exampleRu: 'Обвиняемый предоставил твёрдое алиби.', exampleEn: 'The accused provided a solid alibi.' },
  { french: 'le paradoxe', translation: 'парадокс', translationEn: 'paradox', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'C\'est un paradoxe : plus on cherche le bonheur, moins on le trouve.', exampleRu: 'Это парадокс: чем больше ищешь счастье, тем меньше его находишь.', exampleEn: 'It\'s a paradox: the more you seek happiness, the less you find it.' },
  { french: 'la contradiction', translation: 'противоречие', translationEn: 'contradiction', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'Son comportement est en contradiction avec ses discours.', exampleRu: 'Его поведение противоречит его словам.', exampleEn: 'His behavior contradicts his words.' },
  { french: 'la cohérence', translation: 'последовательность; согласованность', translationEn: 'consistency; coherence', category: 'philosophy', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La cohérence du raisonnement est essentielle.', exampleRu: 'Последовательность рассуждения имеет решающее значение.', exampleEn: 'The consistency of reasoning is essential.' },
  { french: 'l\'absurde', translation: 'абсурд', translationEn: 'the absurd', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Camus a élevé l\'absurde au rang de philosophie.', exampleRu: 'Камю возвёл абсурд в ранг философии.', exampleEn: 'Camus elevated the absurd to the level of philosophy.' },
  { french: 'la liberté de conscience', translation: 'свобода совести', translationEn: 'freedom of conscience', category: 'ethics', partOfSpeech: 'noun', gender: 'f', exampleFr: 'La liberté de conscience est un droit fondamental.', exampleRu: 'Свобода совести — основное право.', exampleEn: 'Freedom of conscience is a fundamental right.' },
  { french: 'le libre arbitre', translation: 'свобода воли', translationEn: 'free will', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le libre arbitre est débattu depuis l\'Antiquité.', exampleRu: 'Свобода воли обсуждается с античности.', exampleEn: 'Free will has been debated since antiquity.' },
  { french: 'le déterminisme', translation: 'детерминизм', translationEn: 'determinism', category: 'philosophy', partOfSpeech: 'noun', gender: 'm', exampleFr: 'Le déterminisme nie la liberté humaine selon ses critiques.', exampleRu: 'По мнению критиков, детерминизм отрицает свободу человека.', exampleEn: 'Determinism denies human freedom according to its critics.' },
  { french: 'transcendant', translation: 'трансцендентный; превосходящий', translationEn: 'transcendent', category: 'philosophy', partOfSpeech: 'adjective', exampleFr: 'Pour Kant, Dieu est une idée transcendante.', exampleRu: 'По Канту, Бог — трансцендентная идея.', exampleEn: 'For Kant, God is a transcendent idea.' },
  { french: 'immanent', translation: 'имманентный; внутренний', translationEn: 'immanent', category: 'philosophy', partOfSpeech: 'adjective', exampleFr: 'Spinoza décrit Dieu comme immanent à la nature.', exampleRu: 'Спиноза описывает Бога как имманентного природе.', exampleEn: 'Spinoza describes God as immanent in nature.' },

  // Verbes philosophiques/analytiques
  { french: 'conceptualiser', translation: 'концептуализировать', translationEn: 'to conceptualize', category: 'philosophy', partOfSpeech: 'verb', exampleFr: 'Il faut conceptualiser le problème avant d\'agir.', exampleRu: 'Нужно концептуализировать проблему, прежде чем действовать.', exampleEn: 'One must conceptualize the problem before acting.' },
  { french: 'remettre en question', translation: 'ставить под сомнение', translationEn: 'to question; to challenge', category: 'philosophy', partOfSpeech: 'verb', exampleFr: 'Il remet en question toutes les certitudes établies.', exampleRu: 'Он ставит под сомнение все устоявшиеся убеждения.', exampleEn: 'He questions all established certainties.' },
  { french: 'philosopher', translation: 'философствовать', translationEn: 'to philosophize', category: 'philosophy', partOfSpeech: 'verb', exampleFr: 'On peut philosopher sur la condition humaine.', exampleRu: 'Можно философствовать о человеческом уделе.', exampleEn: 'One can philosophize about the human condition.' },

  // Adjectifs analytiques/intellectuels
  { french: 'rigoureux', translation: 'строгий; тщательный', translationEn: 'rigorous', category: 'philosophy', partOfSpeech: 'adjective', exampleFr: 'Son analyse est rigoureuse et méthodique.', exampleRu: 'Его анализ строгий и методичный.', exampleEn: 'His analysis is rigorous and methodical.' },
  { french: 'nuancé', translation: 'нюансированный; взвешенный', translationEn: 'nuanced', category: 'philosophy', partOfSpeech: 'adjective', exampleFr: 'Sa position est nuancée et difficile à résumer.', exampleRu: 'Его позиция нюансированная и её трудно кратко изложить.', exampleEn: 'His position is nuanced and hard to summarize.' },
  { french: 'ambigu', translation: 'неоднозначный; двусмысленный', translationEn: 'ambiguous', category: 'philosophy', partOfSpeech: 'adjective', exampleFr: 'Ce texte est délibérément ambigu.', exampleRu: 'Этот текст намеренно двусмысленный.', exampleEn: 'This text is deliberately ambiguous.' },
];
