// Extra A1 words to reach 500 total
export const wordsA1Extra = [
  // Профессии
  { french: 'le médecin', translation: 'врач', translationEn: 'doctor', category: 'professions', exampleFr: 'Je suis médecin.', exampleRu: 'Я врач.', exampleEn: 'I am a doctor.' },
  { french: 'l\'infirmier / l\'infirmière', translation: 'медбрат / медсестра', translationEn: 'nurse', category: 'professions', exampleFr: 'Elle est infirmière.', exampleRu: 'Она медсестра.', exampleEn: 'She is a nurse.' },
  { french: 'le professeur', translation: 'учитель, профессор', translationEn: 'teacher, professor', category: 'professions', exampleFr: 'Il est professeur.', exampleRu: 'Он учитель.', exampleEn: 'He is a teacher.' },
  { french: 'l\'étudiant', translation: 'студент', translationEn: 'student', category: 'professions', exampleFr: 'Je suis étudiant.', exampleRu: 'Я студент.', exampleEn: 'I am a student.' },
  { french: 'l\'élève', translation: 'ученик', translationEn: 'pupil', category: 'professions', exampleFr: 'C\'est un bon élève.', exampleRu: 'Это хороший ученик.', exampleEn: 'He is a good pupil.' },
  { french: 'le cuisinier', translation: 'повар', translationEn: 'cook, chef', category: 'professions', exampleFr: 'Il est cuisinier.', exampleRu: 'Он повар.', exampleEn: 'He is a cook.' },
  { french: 'le serveur', translation: 'официант', translationEn: 'waiter', category: 'professions', exampleFr: 'Le serveur arrive.', exampleRu: 'Официант подходит.', exampleEn: 'The waiter is coming.' },
  { french: 'le vendeur', translation: 'продавец', translationEn: 'salesperson', category: 'professions', exampleFr: 'Le vendeur aide.', exampleRu: 'Продавец помогает.', exampleEn: 'The salesperson helps.' },
  { french: 'le policier', translation: 'полицейский', translationEn: 'police officer', category: 'professions', exampleFr: 'Le policier patrouille.', exampleRu: 'Полицейский патрулирует.', exampleEn: 'The police officer patrols.' },
  { french: 'le conducteur', translation: 'водитель', translationEn: 'driver', category: 'professions', exampleFr: 'Le conducteur conduit bien.', exampleRu: 'Водитель хорошо ведёт машину.', exampleEn: 'The driver drives well.' },
  { french: 'le directeur', translation: 'директор', translationEn: 'director, manager', category: 'professions', exampleFr: 'Le directeur décide.', exampleRu: 'Директор решает.', exampleEn: 'The manager decides.' },
  { french: 'le secrétaire', translation: 'секретарь', translationEn: 'secretary', category: 'professions', exampleFr: 'La secrétaire répond.', exampleRu: 'Секретарь отвечает.', exampleEn: 'The secretary answers.' },
  { french: 'l\'avocat', translation: 'адвокат', translationEn: 'lawyer', category: 'professions', exampleFr: 'Mon avocat parle.', exampleRu: 'Мой адвокат говорит.', exampleEn: 'My lawyer speaks.' },
  { french: 'l\'ingénieur', translation: 'инженер', translationEn: 'engineer', category: 'professions', exampleFr: 'Il est ingénieur.', exampleRu: 'Он инженер.', exampleEn: 'He is an engineer.' },
  { french: 'l\'architecte', translation: 'архитектор', translationEn: 'architect', category: 'professions', exampleFr: 'Elle est architecte.', exampleRu: 'Она архитектор.', exampleEn: 'She is an architect.' },
  { french: 'le journaliste', translation: 'журналист', translationEn: 'journalist', category: 'professions', exampleFr: 'Le journaliste écrit.', exampleRu: 'Журналист пишет.', exampleEn: 'The journalist writes.' },
  { french: 'l\'acteur', translation: 'актёр', translationEn: 'actor', category: 'professions', exampleFr: 'C\'est un acteur célèbre.', exampleRu: 'Это известный актёр.', exampleEn: 'He is a famous actor.' },
  { french: 'le musicien', translation: 'музыкант', translationEn: 'musician', category: 'professions', exampleFr: 'Il est musicien.', exampleRu: 'Он музыкант.', exampleEn: 'He is a musician.' },
  { french: 'le sportif', translation: 'спортсмен', translationEn: 'athlete, sportsman', category: 'professions', exampleFr: 'C\'est un grand sportif.', exampleRu: 'Это великий спортсмен.', exampleEn: 'He is a great athlete.' },
  { french: 'le retraité', translation: 'пенсионер', translationEn: 'retiree, pensioner', category: 'professions', exampleFr: 'Il est retraité.', exampleRu: 'Он пенсионер.', exampleEn: 'He is retired.' },

  // Магазины и покупки
  { french: 'la boulangerie', translation: 'булочная, пекарня', translationEn: 'bakery', category: 'shopping', exampleFr: 'Je vais à la boulangerie.', exampleRu: 'Я иду в булочную.', exampleEn: 'I go to the bakery.' },
  { french: 'la boucherie', translation: 'мясная лавка', translationEn: 'butcher\'s shop', category: 'shopping', exampleFr: 'La boucherie est fermée.', exampleRu: 'Мясная лавка закрыта.', exampleEn: 'The butcher\'s shop is closed.' },
  { french: 'la librairie', translation: 'книжный магазин', translationEn: 'bookshop', category: 'shopping', exampleFr: 'J\'achète un livre à la librairie.', exampleRu: 'Я покупаю книгу в книжном.', exampleEn: 'I buy a book at the bookshop.' },
  { french: 'le marché', translation: 'рынок', translationEn: 'market', category: 'shopping', exampleFr: 'Je fais les courses au marché.', exampleRu: 'Я делаю покупки на рынке.', exampleEn: 'I shop at the market.' },
  { french: 'le prix', translation: 'цена', translationEn: 'price', category: 'shopping', exampleFr: 'Quel est le prix ?', exampleRu: 'Какова цена?', exampleEn: 'What is the price?' },
  { french: 'cher / chère', translation: 'дорогой / дорогая', translationEn: 'expensive', category: 'shopping', exampleFr: 'C\'est trop cher.', exampleRu: 'Это слишком дорого.', exampleEn: 'It is too expensive.' },
  { french: 'bon marché', translation: 'дешёвый', translationEn: 'cheap, inexpensive', category: 'shopping', exampleFr: 'C\'est bon marché.', exampleRu: 'Это дёшево.', exampleEn: 'It is cheap.' },
  { french: 'la monnaie', translation: 'сдача, мелочь', translationEn: 'change, coins', category: 'shopping', exampleFr: 'Voici la monnaie.', exampleRu: 'Вот сдача.', exampleEn: 'Here is your change.' },
  { french: 'la carte bancaire', translation: 'банковская карта', translationEn: 'bank card', category: 'shopping', exampleFr: 'Je paie par carte.', exampleRu: 'Я плачу картой.', exampleEn: 'I pay by card.' },
  { french: 'l\'argent', translation: 'деньги', translationEn: 'money', category: 'shopping', exampleFr: 'Je n\'ai pas d\'argent.', exampleRu: 'У меня нет денег.', exampleEn: 'I have no money.' },
  { french: 'l\'euro', translation: 'евро', translationEn: 'euro', category: 'shopping', exampleFr: 'Ça coûte dix euros.', exampleRu: 'Это стоит десять евро.', exampleEn: 'It costs ten euros.' },
  { french: 'payer', translation: 'платить', translationEn: 'to pay', category: 'shopping', exampleFr: 'Je paie l\'addition.', exampleRu: 'Я оплачиваю счёт.', exampleEn: 'I pay the bill.' },
  { french: 'l\'addition', translation: 'счёт (в ресторане)', translationEn: 'bill (in a restaurant)', category: 'shopping', exampleFr: 'L\'addition, s\'il vous plaît.', exampleRu: 'Счёт, пожалуйста.', exampleEn: 'The bill, please.' },
  { french: 'la taille', translation: 'размер (одежды)', translationEn: 'size (clothing)', category: 'shopping', exampleFr: 'Quelle est votre taille ?', exampleRu: 'Какой у вас размер?', exampleEn: 'What is your size?' },
  { french: 'essayer', translation: 'примерять, пробовать', translationEn: 'to try on, to try', category: 'shopping', exampleFr: 'Je peux essayer ce pull ?', exampleRu: 'Могу я примерить этот свитер?', exampleEn: 'Can I try on this sweater?' },

  // Спорт и досуг
  { french: 'le sport', translation: 'спорт', translationEn: 'sport', category: 'leisure', exampleFr: 'Je fais du sport.', exampleRu: 'Я занимаюсь спортом.', exampleEn: 'I do sport.' },
  { french: 'le football', translation: 'футбол', translationEn: 'football, soccer', category: 'leisure', exampleFr: 'Je joue au football.', exampleRu: 'Я играю в футбол.', exampleEn: 'I play football.' },
  { french: 'le tennis', translation: 'теннис', translationEn: 'tennis', category: 'leisure', exampleFr: 'Elle joue au tennis.', exampleRu: 'Она играет в теннис.', exampleEn: 'She plays tennis.' },
  { french: 'la natation', translation: 'плавание', translationEn: 'swimming', category: 'leisure', exampleFr: 'La natation est bonne.', exampleRu: 'Плавание полезно.', exampleEn: 'Swimming is good for you.' },
  { french: 'la gymnastique', translation: 'гимнастика', translationEn: 'gymnastics', category: 'leisure', exampleFr: 'Je fais de la gym.', exampleRu: 'Я занимаюсь гимнастикой.', exampleEn: 'I do gymnastics.' },
  { french: 'la musique', translation: 'музыка', translationEn: 'music', category: 'leisure', exampleFr: 'J\'écoute de la musique.', exampleRu: 'Я слушаю музыку.', exampleEn: 'I listen to music.' },
  { french: 'le cinéma', translation: 'кино', translationEn: 'cinema', category: 'leisure', exampleFr: 'On va au cinéma ?', exampleRu: 'Идём в кино?', exampleEn: 'Shall we go to the cinema?' },
  { french: 'le film', translation: 'фильм', translationEn: 'film, movie', category: 'leisure', exampleFr: 'Un beau film.', exampleRu: 'Красивый фильм.', exampleEn: 'A good film.' },
  { french: 'le livre', translation: 'книга', translationEn: 'book', category: 'leisure', exampleFr: 'Je lis un livre.', exampleRu: 'Я читаю книгу.', exampleEn: 'I read a book.' },
  { french: 'le journal', translation: 'газета', translationEn: 'newspaper', category: 'leisure', exampleFr: 'Je lis le journal.', exampleRu: 'Я читаю газету.', exampleEn: 'I read the newspaper.' },
  { french: 'la danse', translation: 'танец', translationEn: 'dance', category: 'leisure', exampleFr: 'J\'aime la danse.', exampleRu: 'Я люблю танцы.', exampleEn: 'I love dancing.' },
  { french: 'danser', translation: 'танцевать', translationEn: 'to dance', category: 'leisure', exampleFr: 'On danse ensemble ?', exampleRu: 'Потанцуем вместе?', exampleEn: 'Shall we dance together?' },
  { french: 'chanter', translation: 'петь', translationEn: 'to sing', category: 'leisure', exampleFr: 'Il chante bien.', exampleRu: 'Он хорошо поёт.', exampleEn: 'He sings well.' },
  { french: 'voyager', translation: 'путешествовать', translationEn: 'to travel', category: 'leisure', exampleFr: 'J\'aime voyager.', exampleRu: 'Я люблю путешествовать.', exampleEn: 'I love to travel.' },
  { french: 'les vacances', translation: 'каникулы, отпуск', translationEn: 'holidays, vacation', category: 'leisure', exampleFr: 'Bonnes vacances !', exampleRu: 'Хорошего отпуска!', exampleEn: 'Have a good holiday!' },
  { french: 'le week-end', translation: 'выходные', translationEn: 'weekend', category: 'leisure', exampleFr: 'Bon week-end !', exampleRu: 'Хороших выходных!', exampleEn: 'Have a good weekend!' },
  { french: 'se promener', translation: 'гулять', translationEn: 'to go for a walk', category: 'leisure', exampleFr: 'Je me promène.', exampleRu: 'Я гуляю.', exampleEn: 'I go for a walk.' },
  { french: 'se reposer', translation: 'отдыхать', translationEn: 'to rest', category: 'leisure', exampleFr: 'Je me repose.', exampleRu: 'Я отдыхаю.', exampleEn: 'I am resting.' },
  { french: 'le passe-temps', translation: 'хобби', translationEn: 'hobby', category: 'leisure', exampleFr: 'Quel est ton passe-temps ?', exampleRu: 'Какое у тебя хобби?', exampleEn: 'What is your hobby?' },
  { french: 'la fête', translation: 'праздник, вечеринка', translationEn: 'party, celebration', category: 'leisure', exampleFr: 'On fait la fête.', exampleRu: 'Мы отмечаем праздник.', exampleEn: 'We are having a party.' },

  // Школа и учёба
  { french: 'l\'université', translation: 'университет', translationEn: 'university', category: 'school', exampleFr: 'Je vais à l\'université.', exampleRu: 'Я иду в университет.', exampleEn: 'I go to university.' },
  { french: 'la classe', translation: 'класс', translationEn: 'class, classroom', category: 'school', exampleFr: 'On est en classe.', exampleRu: 'Мы на уроке.', exampleEn: 'We are in class.' },
  { french: 'le cours', translation: 'урок, курс', translationEn: 'lesson, course', category: 'school', exampleFr: 'Le cours commence.', exampleRu: 'Урок начинается.', exampleEn: 'The lesson starts.' },
  { french: 'le devoir', translation: 'домашнее задание', translationEn: 'homework', category: 'school', exampleFr: 'Je fais mes devoirs.', exampleRu: 'Я делаю уроки.', exampleEn: 'I do my homework.' },
  { french: 'l\'examen', translation: 'экзамен', translationEn: 'exam', category: 'school', exampleFr: 'J\'ai un examen demain.', exampleRu: 'У меня завтра экзамен.', exampleEn: 'I have an exam tomorrow.' },
  { french: 'la note', translation: 'оценка', translationEn: 'grade, mark', category: 'school', exampleFr: 'J\'ai une bonne note.', exampleRu: 'У меня хорошая оценка.', exampleEn: 'I have a good grade.' },
  { french: 'le stylo', translation: 'ручка', translationEn: 'pen', category: 'school', exampleFr: 'Passe-moi un stylo.', exampleRu: 'Дай мне ручку.', exampleEn: 'Pass me a pen.' },
  { french: 'le crayon', translation: 'карандаш', translationEn: 'pencil', category: 'school', exampleFr: 'J\'écris au crayon.', exampleRu: 'Я пишу карандашом.', exampleEn: 'I write with a pencil.' },
  { french: 'le cahier', translation: 'тетрадь', translationEn: 'notebook', category: 'school', exampleFr: 'Mon cahier est plein.', exampleRu: 'Моя тетрадь заполнена.', exampleEn: 'My notebook is full.' },
  { french: 'le sac à dos', translation: 'рюкзак', translationEn: 'backpack', category: 'school', exampleFr: 'Mon sac à dos est lourd.', exampleRu: 'Мой рюкзак тяжёлый.', exampleEn: 'My backpack is heavy.' },
  { french: 'apprendre', translation: 'учить, учиться', translationEn: 'to learn', category: 'school', exampleFr: 'J\'apprends le français.', exampleRu: 'Я учу французский.', exampleEn: 'I learn French.' },
  { french: 'comprendre', translation: 'понимать', translationEn: 'to understand', category: 'school', exampleFr: 'Je comprends bien.', exampleRu: 'Я хорошо понимаю.', exampleEn: 'I understand well.' },
  { french: 'répéter', translation: 'повторять', translationEn: 'to repeat', category: 'school', exampleFr: 'Répétez après moi.', exampleRu: 'Повторяйте за мной.', exampleEn: 'Repeat after me.' },
  { french: 'expliquer', translation: 'объяснять', translationEn: 'to explain', category: 'school', exampleFr: 'Le prof explique.', exampleRu: 'Учитель объясняет.', exampleEn: 'The teacher explains.' },
  { french: 'répondre', translation: 'отвечать', translationEn: 'to answer', category: 'school', exampleFr: 'Je réponds à la question.', exampleRu: 'Я отвечаю на вопрос.', exampleEn: 'I answer the question.' },
  { french: 'poser une question', translation: 'задать вопрос', translationEn: 'to ask a question', category: 'school', exampleFr: 'Je pose une question.', exampleRu: 'Я задаю вопрос.', exampleEn: 'I ask a question.' },
  { french: 'la langue', translation: 'язык', translationEn: 'language', category: 'school', exampleFr: 'Je parle deux langues.', exampleRu: 'Я говорю на двух языках.', exampleEn: 'I speak two languages.' },
  { french: 'le mot', translation: 'слово', translationEn: 'word', category: 'school', exampleFr: 'Un mot nouveau.', exampleRu: 'Новое слово.', exampleEn: 'A new word.' },
  { french: 'la phrase', translation: 'фраза, предложение', translationEn: 'sentence, phrase', category: 'school', exampleFr: 'Construis une phrase.', exampleRu: 'Составь предложение.', exampleEn: 'Build a sentence.' },
  { french: 'l\'alphabet', translation: 'алфавит', translationEn: 'alphabet', category: 'school', exampleFr: 'L\'alphabet français.', exampleRu: 'Французский алфавит.', exampleEn: 'The French alphabet.' },

  // Описание людей
  { french: 'grand / grande', translation: 'высокий / высокая', translationEn: 'tall', category: 'description', exampleFr: 'Il est grand.', exampleRu: 'Он высокий.', exampleEn: 'He is tall.' },
  { french: 'mince', translation: 'стройный, тонкий', translationEn: 'slim, thin', category: 'description', exampleFr: 'Elle est mince.', exampleRu: 'Она стройная.', exampleEn: 'She is slim.' },
  { french: 'gros / grosse', translation: 'толстый / толстая', translationEn: 'fat, big', category: 'description', exampleFr: 'Un gros chat.', exampleRu: 'Толстый кот.', exampleEn: 'A fat cat.' },
  { french: 'fort / forte', translation: 'сильный / сильная', translationEn: 'strong', category: 'description', exampleFr: 'Il est fort.', exampleRu: 'Он сильный.', exampleEn: 'He is strong.' },
  { french: 'intelligent', translation: 'умный', translationEn: 'intelligent, smart', category: 'description', exampleFr: 'Elle est intelligente.', exampleRu: 'Она умная.', exampleEn: 'She is intelligent.' },
  { french: 'timide', translation: 'застенчивый', translationEn: 'shy', category: 'description', exampleFr: 'Il est timide.', exampleRu: 'Он застенчивый.', exampleEn: 'He is shy.' },
  { french: 'drôle', translation: 'смешной, забавный', translationEn: 'funny', category: 'description', exampleFr: 'C\'est drôle.', exampleRu: 'Это смешно.', exampleEn: 'That is funny.' },
  { french: 'sérieux', translation: 'серьёзный', translationEn: 'serious', category: 'description', exampleFr: 'Il est sérieux.', exampleRu: 'Он серьёзный.', exampleEn: 'He is serious.' },
  { french: 'poli', translation: 'вежливый', translationEn: 'polite', category: 'description', exampleFr: 'Il est très poli.', exampleRu: 'Он очень вежливый.', exampleEn: 'He is very polite.' },
  { french: 'impoli', translation: 'невежливый, грубый', translationEn: 'rude, impolite', category: 'description', exampleFr: 'C\'est impoli.', exampleRu: 'Это невежливо.', exampleEn: 'That is rude.' },
  { french: 'calme', translation: 'спокойный', translationEn: 'calm', category: 'description', exampleFr: 'Reste calme.', exampleRu: 'Оставайся спокойным.', exampleEn: 'Stay calm.' },
  { french: 'actif / active', translation: 'активный / активная', translationEn: 'active', category: 'description', exampleFr: 'Elle est très active.', exampleRu: 'Она очень активная.', exampleEn: 'She is very active.' },
  { french: 'paresseux', translation: 'ленивый', translationEn: 'lazy', category: 'description', exampleFr: 'Il est paresseux.', exampleRu: 'Он ленивый.', exampleEn: 'He is lazy.' },
  { french: 'courageux', translation: 'смелый', translationEn: 'brave, courageous', category: 'description', exampleFr: 'Tu es courageux.', exampleRu: 'Ты смелый.', exampleEn: 'You are brave.' },
  { french: 'heureux', translation: 'счастливый', translationEn: 'happy', category: 'description', exampleFr: 'Je suis heureux.', exampleRu: 'Я счастлив.', exampleEn: 'I am happy.' },
  { french: 'les cheveux', translation: 'волосы', translationEn: 'hair', category: 'description', exampleFr: 'Elle a les cheveux longs.', exampleRu: 'У неё длинные волосы.', exampleEn: 'She has long hair.' },
  { french: 'blond', translation: 'светловолосый, блондин', translationEn: 'blond', category: 'description', exampleFr: 'Il est blond.', exampleRu: 'Он блондин.', exampleEn: 'He is blond.' },
  { french: 'brun', translation: 'брюнет, тёмноволосый', translationEn: 'dark-haired, brunette', category: 'description', exampleFr: 'Elle est brune.', exampleRu: 'Она брюнетка.', exampleEn: 'She has dark hair.' },
  { french: 'roux', translation: 'рыжий', translationEn: 'red-haired', category: 'description', exampleFr: 'Il est roux.', exampleRu: 'Он рыжий.', exampleEn: 'He has red hair.' },

  // Дополнительные глаголы
  { french: 'penser', translation: 'думать', translationEn: 'to think', category: 'verbs_extra', exampleFr: 'Je pense que oui.', exampleRu: 'Я думаю, что да.', exampleEn: 'I think so.' },
  { french: 'croire', translation: 'верить, думать', translationEn: 'to believe, to think', category: 'verbs_extra', exampleFr: 'Je crois que c\'est vrai.', exampleRu: 'Я думаю, это правда.', exampleEn: 'I believe it is true.' },
  { french: 'sentir', translation: 'чувствовать, пахнуть', translationEn: 'to feel, to smell', category: 'verbs_extra', exampleFr: 'Ça sent bon.', exampleRu: 'Это хорошо пахнет.', exampleEn: 'It smells good.' },
  { french: 'entendre', translation: 'слышать', translationEn: 'to hear', category: 'verbs_extra', exampleFr: 'J\'entends la musique.', exampleRu: 'Я слышу музыку.', exampleEn: 'I hear the music.' },
  { french: 'toucher', translation: 'трогать, касаться', translationEn: 'to touch', category: 'verbs_extra', exampleFr: 'Ne touche pas !', exampleRu: 'Не трогай!', exampleEn: 'Do not touch!' },
  { french: 'aider', translation: 'помогать', translationEn: 'to help', category: 'verbs_extra', exampleFr: 'Je t\'aide.', exampleRu: 'Я тебе помогаю.', exampleEn: 'I help you.' },
  { french: 'utiliser', translation: 'использовать', translationEn: 'to use', category: 'verbs_extra', exampleFr: 'J\'utilise un stylo.', exampleRu: 'Я использую ручку.', exampleEn: 'I use a pen.' },
  { french: 'choisir', translation: 'выбирать', translationEn: 'to choose', category: 'verbs_extra', exampleFr: 'Je choisis un plat.', exampleRu: 'Я выбираю блюдо.', exampleEn: 'I choose a dish.' },
  { french: 'finir', translation: 'заканчивать', translationEn: 'to finish', category: 'verbs_extra', exampleFr: 'Je finis mon travail.', exampleRu: 'Я заканчиваю работу.', exampleEn: 'I finish my work.' },
  { french: 'commencer', translation: 'начинать', translationEn: 'to start, to begin', category: 'verbs_extra', exampleFr: 'On commence maintenant.', exampleRu: 'Мы начинаем сейчас.', exampleEn: 'We start now.' },
  { french: 'continuer', translation: 'продолжать', translationEn: 'to continue', category: 'verbs_extra', exampleFr: 'Continue !', exampleRu: 'Продолжай!', exampleEn: 'Continue!' },
  { french: 'attendre', translation: 'ждать', translationEn: 'to wait', category: 'verbs_extra', exampleFr: 'J\'attends le bus.', exampleRu: 'Я жду автобус.', exampleEn: 'I wait for the bus.' },
  { french: 'rester', translation: 'оставаться', translationEn: 'to stay', category: 'verbs_extra', exampleFr: 'Je reste à la maison.', exampleRu: 'Я остаюсь дома.', exampleEn: 'I stay at home.' },
  { french: 'tomber', translation: 'падать', translationEn: 'to fall', category: 'verbs_extra', exampleFr: 'Il tombe.', exampleRu: 'Он падает.', exampleEn: 'He falls.' },
  { french: 'monter', translation: 'подниматься', translationEn: 'to go up, to climb', category: 'verbs_extra', exampleFr: 'Je monte les escaliers.', exampleRu: 'Я поднимаюсь по лестнице.', exampleEn: 'I go up the stairs.' },
  { french: 'descendre', translation: 'спускаться', translationEn: 'to go down', category: 'verbs_extra', exampleFr: 'Je descends.', exampleRu: 'Я спускаюсь.', exampleEn: 'I go down.' },
  { french: 'passer', translation: 'проходить, проводить', translationEn: 'to pass, to spend (time)', category: 'verbs_extra', exampleFr: 'Je passe la journée.', exampleRu: 'Я провожу день.', exampleEn: 'I spend the day.' },
  { french: 'suivre', translation: 'следовать, слушать курс', translationEn: 'to follow, to take a course', category: 'verbs_extra', exampleFr: 'Je suis un cours.', exampleRu: 'Я посещаю курс.', exampleEn: 'I take a course.' },
  { french: 'réserver', translation: 'бронировать', translationEn: 'to book, to reserve', category: 'verbs_extra', exampleFr: 'Je réserve une table.', exampleRu: 'Я бронирую столик.', exampleEn: 'I book a table.' },
  { french: 'remplir', translation: 'заполнять', translationEn: 'to fill in', category: 'verbs_extra', exampleFr: 'Remplis le formulaire.', exampleRu: 'Заполни форму.', exampleEn: 'Fill in the form.' },

  // Предлоги и связки
  { french: 'avec', translation: 'с (вместе)', translationEn: 'with', category: 'prepositions', exampleFr: 'Je viens avec toi.', exampleRu: 'Я иду с тобой.', exampleEn: 'I come with you.' },
  { french: 'sans', translation: 'без', translationEn: 'without', category: 'prepositions', exampleFr: 'Café sans sucre.', exampleRu: 'Кофе без сахара.', exampleEn: 'Coffee without sugar.' },
  { french: 'pour', translation: 'для, за', translationEn: 'for', category: 'prepositions', exampleFr: 'C\'est pour toi.', exampleRu: 'Это для тебя.', exampleEn: 'This is for you.' },
  { french: 'dans', translation: 'в (внутри)', translationEn: 'in, inside', category: 'prepositions', exampleFr: 'Dans la salle.', exampleRu: 'В зале.', exampleEn: 'In the room.' },
  { french: 'sur', translation: 'на', translationEn: 'on', category: 'prepositions', exampleFr: 'Sur la table.', exampleRu: 'На столе.', exampleEn: 'On the table.' },
  { french: 'sous', translation: 'под', translationEn: 'under', category: 'prepositions', exampleFr: 'Sous le lit.', exampleRu: 'Под кроватью.', exampleEn: 'Under the bed.' },
  { french: 'devant', translation: 'перед', translationEn: 'in front of', category: 'prepositions', exampleFr: 'Devant la maison.', exampleRu: 'Перед домом.', exampleEn: 'In front of the house.' },
  { french: 'derrière', translation: 'за, позади', translationEn: 'behind', category: 'prepositions', exampleFr: 'Derrière la porte.', exampleRu: 'За дверью.', exampleEn: 'Behind the door.' },
  { french: 'entre', translation: 'между', translationEn: 'between', category: 'prepositions', exampleFr: 'Entre les deux.', exampleRu: 'Между двумя.', exampleEn: 'Between the two.' },
  { french: 'à côté de', translation: 'рядом с', translationEn: 'next to', category: 'prepositions', exampleFr: 'À côté de moi.', exampleRu: 'Рядом со мной.', exampleEn: 'Next to me.' },
  { french: 'en face de', translation: 'напротив', translationEn: 'opposite, across from', category: 'prepositions', exampleFr: 'En face de la gare.', exampleRu: 'Напротив вокзала.', exampleEn: 'Opposite the station.' },
  { french: 'près de', translation: 'близко от', translationEn: 'near, close to', category: 'prepositions', exampleFr: 'Près d\'ici.', exampleRu: 'Близко отсюда.', exampleEn: 'Close to here.' },
  { french: 'loin de', translation: 'далеко от', translationEn: 'far from', category: 'prepositions', exampleFr: 'Loin de la ville.', exampleRu: 'Далеко от города.', exampleEn: 'Far from the city.' },
  { french: 'avant', translation: 'до, перед', translationEn: 'before', category: 'prepositions', exampleFr: 'Avant le déjeuner.', exampleRu: 'До обеда.', exampleEn: 'Before lunch.' },
  { french: 'après', translation: 'после', translationEn: 'after', category: 'prepositions', exampleFr: 'Après le travail.', exampleRu: 'После работы.', exampleEn: 'After work.' },
  { french: 'pendant', translation: 'во время, пока', translationEn: 'during, while', category: 'prepositions', exampleFr: 'Pendant les vacances.', exampleRu: 'Во время каникул.', exampleEn: 'During the holidays.' },
  { french: 'depuis', translation: 'с (момента), уже', translationEn: 'since, for', category: 'prepositions', exampleFr: 'Depuis deux ans.', exampleRu: 'Уже два года.', exampleEn: 'For two years.' },
  { french: 'jusqu\'à', translation: 'до (момента)', translationEn: 'until, up to', category: 'prepositions', exampleFr: 'Jusqu\'à demain.', exampleRu: 'До завтра.', exampleEn: 'Until tomorrow.' },
  { french: 'vers', translation: 'около, к (времени)', translationEn: 'towards, around (time)', category: 'prepositions', exampleFr: 'Vers midi.', exampleRu: 'Около полудня.', exampleEn: 'Around noon.' },
  { french: 'par', translation: 'через, посредством', translationEn: 'through, by', category: 'prepositions', exampleFr: 'Par ici.', exampleRu: 'Сюда / этим путём.', exampleEn: 'This way.' },

  // Дом — дополнительно
  { french: 'l\'entrée', translation: 'прихожая, вход', translationEn: 'entrance, hallway', category: 'house', exampleFr: 'L\'entrée est propre.', exampleRu: 'Прихожая чистая.', exampleEn: 'The hallway is clean.' },
  { french: 'le couloir', translation: 'коридор', translationEn: 'corridor, hallway', category: 'house', exampleFr: 'Le couloir est long.', exampleRu: 'Коридор длинный.', exampleEn: 'The corridor is long.' },
  { french: 'l\'escalier', translation: 'лестница', translationEn: 'stairs', category: 'house', exampleFr: 'Je monte l\'escalier.', exampleRu: 'Я поднимаюсь по лестнице.', exampleEn: 'I go up the stairs.' },
  { french: 'le sous-sol', translation: 'подвал', translationEn: 'basement', category: 'house', exampleFr: 'La cave est au sous-sol.', exampleRu: 'Погреб в подвале.', exampleEn: 'The cellar is in the basement.' },
  { french: 'le balcon', translation: 'балкон', translationEn: 'balcony', category: 'house', exampleFr: 'Je prends l\'air au balcon.', exampleRu: 'Я дышу свежим воздухом на балконе.', exampleEn: 'I get fresh air on the balcony.' },
  { french: 'la terrasse', translation: 'терраса', translationEn: 'terrace', category: 'house', exampleFr: 'On dîne sur la terrasse.', exampleRu: 'Мы ужинаем на террасе.', exampleEn: 'We have dinner on the terrace.' },
  { french: 'le loyer', translation: 'арендная плата', translationEn: 'rent', category: 'house', exampleFr: 'Le loyer est élevé.', exampleRu: 'Арендная плата высокая.', exampleEn: 'The rent is high.' },
  { french: 'le voisinage', translation: 'соседство, район', translationEn: 'neighbourhood', category: 'house', exampleFr: 'Le voisinage est calme.', exampleRu: 'Район спокойный.', exampleEn: 'The neighbourhood is quiet.' },
  { french: 'le micro-ondes', translation: 'микроволновка', translationEn: 'microwave', category: 'house', exampleFr: 'Je chauffe au micro-ondes.', exampleRu: 'Я разогреваю в микроволновке.', exampleEn: 'I heat it in the microwave.' },
  { french: 'la machine à laver', translation: 'стиральная машина', translationEn: 'washing machine', category: 'house', exampleFr: 'La machine à laver tourne.', exampleRu: 'Стиральная машина крутится.', exampleEn: 'The washing machine is running.' },

  // Дополнительные числа и время
  { french: 'onze', translation: 'одиннадцать', translationEn: 'eleven', category: 'numbers', exampleFr: 'Onze heures.', exampleRu: 'Одиннадцать часов.', exampleEn: 'Eleven o\'clock.' },
  { french: 'douze', translation: 'двенадцать', translationEn: 'twelve', category: 'numbers', exampleFr: 'Douze mois.', exampleRu: 'Двенадцать месяцев.', exampleEn: 'Twelve months.' },
  { french: 'quinze', translation: 'пятнадцать', translationEn: 'fifteen', category: 'numbers', exampleFr: 'Quinze minutes.', exampleRu: 'Пятнадцать минут.', exampleEn: 'Fifteen minutes.' },
  { french: 'quarante', translation: 'сорок', translationEn: 'forty', category: 'numbers', exampleFr: 'Quarante euros.', exampleRu: 'Сорок евро.', exampleEn: 'Forty euros.' },
  { french: 'cinquante', translation: 'пятьдесят', translationEn: 'fifty', category: 'numbers', exampleFr: 'Cinquante personnes.', exampleRu: 'Пятьдесят человек.', exampleEn: 'Fifty people.' },
  { french: 'soixante', translation: 'шестьдесят', translationEn: 'sixty', category: 'numbers', exampleFr: 'Soixante secondes.', exampleRu: 'Шестьдесят секунд.', exampleEn: 'Sixty seconds.' },
  { french: 'soixante-dix', translation: 'семьдесят', translationEn: 'seventy', category: 'numbers', exampleFr: 'Soixante-dix kilos.', exampleRu: 'Семьдесят килограммов.', exampleEn: 'Seventy kilos.' },
  { french: 'quatre-vingts', translation: 'восемьдесят', translationEn: 'eighty', category: 'numbers', exampleFr: 'Quatre-vingts ans.', exampleRu: 'Восемьдесят лет.', exampleEn: 'Eighty years old.' },
  { french: 'premier / première', translation: 'первый / первая', translationEn: 'first', category: 'numbers', exampleFr: 'Le premier jour.', exampleRu: 'Первый день.', exampleEn: 'The first day.' },
  { french: 'dernier / dernière', translation: 'последний / последняя', translationEn: 'last', category: 'numbers', exampleFr: 'La dernière fois.', exampleRu: 'Последний раз.', exampleEn: 'The last time.' },
  { french: 'le siècle', translation: 'век, столетие', translationEn: 'century', category: 'time', exampleFr: 'Au XXIe siècle.', exampleRu: 'В XXI веке.', exampleEn: 'In the 21st century.' },
  { french: 'la saison', translation: 'время года, сезон', translationEn: 'season', category: 'time', exampleFr: 'Quelle saison préfères-tu ?', exampleRu: 'Какое время года ты предпочитаешь?', exampleEn: 'Which season do you prefer?' },
  { french: 'le printemps', translation: 'весна', translationEn: 'spring', category: 'time', exampleFr: 'Le printemps arrive.', exampleRu: 'Весна приходит.', exampleEn: 'Spring is coming.' },
  { french: 'l\'été', translation: 'лето', translationEn: 'summer', category: 'time', exampleFr: 'En été il fait chaud.', exampleRu: 'Летом жарко.', exampleEn: 'In summer it is hot.' },
  { french: 'l\'automne', translation: 'осень', translationEn: 'autumn, fall', category: 'time', exampleFr: 'L\'automne est coloré.', exampleRu: 'Осень красочная.', exampleEn: 'Autumn is colourful.' },
  { french: 'l\'hiver', translation: 'зима', translationEn: 'winter', category: 'time', exampleFr: 'En hiver il neige.', exampleRu: 'Зимой идёт снег.', exampleEn: 'In winter it snows.' },
  { french: 'tôt', translation: 'рано', translationEn: 'early', category: 'time', exampleFr: 'Je me lève tôt.', exampleRu: 'Я встаю рано.', exampleEn: 'I get up early.' },
  { french: 'tard', translation: 'поздно', translationEn: 'late', category: 'time', exampleFr: 'Il rentre tard.', exampleRu: 'Он возвращается поздно.', exampleEn: 'He comes back late.' },
  { french: 'bientôt', translation: 'скоро', translationEn: 'soon', category: 'time', exampleFr: 'À bientôt !', exampleRu: 'До скорого!', exampleEn: 'See you soon!' },
  { french: 'longtemps', translation: 'долго', translationEn: 'for a long time', category: 'time', exampleFr: 'Depuis longtemps.', exampleRu: 'Уже давно.', exampleEn: 'For a long time.' },

  // Глаголы — базовые действия (дополнительно)
  { french: 'chercher', translation: 'искать', translationEn: 'to look for', category: 'verbs', exampleFr: 'Je cherche mes clés.', exampleRu: 'Я ищу свои ключи.', exampleEn: 'I look for my keys.' },
  { french: 'trouver', translation: 'находить', translationEn: 'to find', category: 'verbs', exampleFr: 'J\'ai trouvé mon livre.', exampleRu: 'Я нашёл свою книгу.', exampleEn: 'I found my book.' },
  { french: 'donner', translation: 'давать', translationEn: 'to give', category: 'verbs', exampleFr: 'Donne-moi un stylo.', exampleRu: 'Дай мне ручку.', exampleEn: 'Give me a pen.' },
  { french: 'prendre', translation: 'брать, принимать', translationEn: 'to take', category: 'verbs', exampleFr: 'Je prends le bus.', exampleRu: 'Я еду на автобусе.', exampleEn: 'I take the bus.' },
  { french: 'mettre', translation: 'класть, надевать', translationEn: 'to put, to wear', category: 'verbs', exampleFr: 'Mets ton manteau.', exampleRu: 'Надень пальто.', exampleEn: 'Put on your coat.' },
  { french: 'lire', translation: 'читать', translationEn: 'to read', category: 'verbs', exampleFr: 'Je lis un roman.', exampleRu: 'Я читаю роман.', exampleEn: 'I read a novel.' },
  { french: 'écrire', translation: 'писать', translationEn: 'to write', category: 'verbs', exampleFr: 'Elle écrit une lettre.', exampleRu: 'Она пишет письмо.', exampleEn: 'She writes a letter.' },
  { french: 'répondre', translation: 'отвечать', translationEn: 'to answer', category: 'verbs', exampleFr: 'Réponds à ma question.', exampleRu: 'Ответь на мой вопрос.', exampleEn: 'Answer my question.' },
  { french: 'comprendre', translation: 'понимать', translationEn: 'to understand', category: 'verbs', exampleFr: 'Tu comprends ?', exampleRu: 'Ты понимаешь?', exampleEn: 'Do you understand?' },
  { french: 'savoir', translation: 'знать (факт, умение)', translationEn: 'to know (a fact, how to)', category: 'verbs', exampleFr: 'Je sais nager.', exampleRu: 'Я умею плавать.', exampleEn: 'I know how to swim.' },
  { french: 'connaître', translation: 'знать (человека, место)', translationEn: 'to know (a person, place)', category: 'verbs', exampleFr: 'Je connais Paris.', exampleRu: 'Я знаю Париж.', exampleEn: 'I know Paris.' },
  { french: 'penser', translation: 'думать', translationEn: 'to think', category: 'verbs', exampleFr: 'Qu\'est-ce que tu penses ?', exampleRu: 'Что ты думаешь?', exampleEn: 'What do you think?' },
  { french: 'croire', translation: 'верить, думать', translationEn: 'to believe', category: 'verbs', exampleFr: 'Je crois que oui.', exampleRu: 'Я думаю, что да.', exampleEn: 'I believe so.' },
  { french: 'sentir', translation: 'чувствовать, пахнуть', translationEn: 'to feel, to smell', category: 'verbs', exampleFr: 'Ça sent bon.', exampleRu: 'Хорошо пахнет.', exampleEn: 'It smells good.' },
  { french: 'entendre', translation: 'слышать', translationEn: 'to hear', category: 'verbs', exampleFr: 'J\'entends de la musique.', exampleRu: 'Я слышу музыку.', exampleEn: 'I hear music.' },

  // Прилагательные — базовые (дополнительно)
  { french: 'propre', translation: 'чистый', translationEn: 'clean', category: 'adjectives', exampleFr: 'La maison est propre.', exampleRu: 'Дом чистый.', exampleEn: 'The house is clean.' },
  { french: 'sale', translation: 'грязный', translationEn: 'dirty', category: 'adjectives', exampleFr: 'Les mains sont sales.', exampleRu: 'Руки грязные.', exampleEn: 'The hands are dirty.' },
  { french: 'chaud', translation: 'горячий, тёплый', translationEn: 'hot, warm', category: 'adjectives', exampleFr: 'L\'eau est chaude.', exampleRu: 'Вода горячая.', exampleEn: 'The water is hot.' },
  { french: 'froid', translation: 'холодный', translationEn: 'cold', category: 'adjectives', exampleFr: 'Il fait froid.', exampleRu: 'Холодно.', exampleEn: 'It is cold.' },
  { french: 'rapide', translation: 'быстрый', translationEn: 'fast, quick', category: 'adjectives', exampleFr: 'Le train est rapide.', exampleRu: 'Поезд быстрый.', exampleEn: 'The train is fast.' },
  { french: 'lent', translation: 'медленный', translationEn: 'slow', category: 'adjectives', exampleFr: 'Il marche lentement.', exampleRu: 'Он идёт медленно.', exampleEn: 'He walks slowly.' },
  { french: 'facile', translation: 'лёгкий, простой', translationEn: 'easy', category: 'adjectives', exampleFr: 'C\'est facile.', exampleRu: 'Это легко.', exampleEn: 'It is easy.' },
  { french: 'difficile', translation: 'трудный, сложный', translationEn: 'difficult', category: 'adjectives', exampleFr: 'C\'est difficile.', exampleRu: 'Это трудно.', exampleEn: 'It is difficult.' },

  // Транспорт
  { french: 'le vélo', translation: 'велосипед', translationEn: 'bicycle, bike', category: 'transport', exampleFr: 'Je fais du vélo.', exampleRu: 'Я езжу на велосипеде.', exampleEn: 'I ride a bike.' },
  { french: 'la moto', translation: 'мотоцикл', translationEn: 'motorbike', category: 'transport', exampleFr: 'Il roule en moto.', exampleRu: 'Он ездит на мотоцикле.', exampleEn: 'He rides a motorbike.' },
  { french: 'l\'avion', translation: 'самолёт', translationEn: 'plane', category: 'transport', exampleFr: 'On prend l\'avion.', exampleRu: 'Мы летим на самолёте.', exampleEn: 'We take the plane.' },
  { french: 'le bateau', translation: 'лодка, корабль', translationEn: 'boat, ship', category: 'transport', exampleFr: 'Le bateau arrive.', exampleRu: 'Корабль прибывает.', exampleEn: 'The boat arrives.' },
  { french: 'le taxi', translation: 'такси', translationEn: 'taxi', category: 'transport', exampleFr: 'Je prends un taxi.', exampleRu: 'Я беру такси.', exampleEn: 'I take a taxi.' },
  { french: 'la gare', translation: 'вокзал', translationEn: 'train station', category: 'transport', exampleFr: 'Je suis à la gare.', exampleRu: 'Я на вокзале.', exampleEn: 'I am at the train station.' },
  { french: 'l\'aéroport', translation: 'аэропорт', translationEn: 'airport', category: 'transport', exampleFr: 'L\'aéroport est loin.', exampleRu: 'Аэропорт далеко.', exampleEn: 'The airport is far.' },

  // Покупки и деньги
  { french: 'la monnaie', translation: 'сдача, мелочь', translationEn: 'change, coins', category: 'shopping', exampleFr: 'Gardez la monnaie.', exampleRu: 'Оставьте сдачу.', exampleEn: 'Keep the change.' },
  { french: 'le billet', translation: 'банкнота, билет', translationEn: 'banknote, ticket', category: 'shopping', exampleFr: 'Un billet de vingt euros.', exampleRu: 'Банкнота в двадцать евро.', exampleEn: 'A twenty euro note.' },
  { french: 'la caisse', translation: 'касса', translationEn: 'checkout, till', category: 'shopping', exampleFr: 'Je passe à la caisse.', exampleRu: 'Я иду к кассе.', exampleEn: 'I go to the checkout.' },
  { french: 'la carte bancaire', translation: 'банковская карта', translationEn: 'bank card', category: 'shopping', exampleFr: 'Je paie par carte.', exampleRu: 'Я плачу картой.', exampleEn: 'I pay by card.' },
  { french: 'le reçu', translation: 'чек, квитанция', translationEn: 'receipt', category: 'shopping', exampleFr: 'Voici votre reçu.', exampleRu: 'Вот ваш чек.', exampleEn: 'Here is your receipt.' },
  { french: 'gratuit', translation: 'бесплатный', translationEn: 'free (no charge)', category: 'shopping', exampleFr: 'C\'est gratuit.', exampleRu: 'Это бесплатно.', exampleEn: 'It is free.' },
  { french: 'cher', translation: 'дорогой', translationEn: 'expensive', category: 'shopping', exampleFr: 'C\'est trop cher.', exampleRu: 'Это слишком дорого.', exampleEn: 'It is too expensive.' },
  { french: 'pas cher', translation: 'недорогой, дешёвый', translationEn: 'cheap, not expensive', category: 'shopping', exampleFr: 'C\'est pas cher.', exampleRu: 'Это недорого.', exampleEn: 'It is not expensive.' },
  { french: 'la promotion', translation: 'акция, скидка', translationEn: 'sale, discount', category: 'shopping', exampleFr: 'Il y a une promotion.', exampleRu: 'Есть акция.', exampleEn: 'There is a sale.' },
];
