export const wordsA2Extra6 = [
  // === TRAVEL & TRANSPORT ===
  { french: 'enregistrement', translation: 'регистрация (на рейс)', translationEn: 'check-in', category: 'travel_transport', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2100, exampleFr: "L'enregistrement ouvre deux heures avant le départ.", exampleRu: 'Регистрация открывается за два часа до отправления.', exampleEn: 'Check-in opens two hours before departure.' },
  { french: 'annulation', translation: 'отмена, аннулирование', translationEn: 'cancellation', category: 'travel_transport', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2110, exampleFr: "L'annulation du vol nous a causé des problèmes.", exampleRu: 'Отмена рейса создала нам проблемы.', exampleEn: 'The flight cancellation caused us problems.' },
  { french: 'terminal', translation: 'терминал (аэропорта)', translationEn: 'terminal', category: 'travel_transport', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2120, exampleFr: 'Notre vol part du terminal 2.', exampleRu: 'Наш рейс отправляется из терминала 2.', exampleEn: 'Our flight leaves from terminal 2.' },
  { french: 'escale', translation: 'пересадка, остановка', translationEn: 'stopover, layover', category: 'travel_transport', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2130, exampleFr: "Il y a une escale d'une heure à Amsterdam.", exampleRu: 'В Амстердаме пересадка на один час.', exampleEn: 'There is a one-hour stopover in Amsterdam.' },

  // === MEDIA & MODERN LIFE ===
  { french: 'blog', translation: 'блог', translationEn: 'blog', category: 'media_modern', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2140, exampleFr: 'Elle écrit un blog sur la cuisine française.', exampleRu: 'Она ведёт блог о французской кухне.', exampleEn: 'She writes a blog about French cuisine.' },
  { french: 'podcast', translation: 'подкаст', translationEn: 'podcast', category: 'media_modern', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2150, exampleFr: 'Je télécharge des podcasts pour apprendre le français.', exampleRu: 'Я скачиваю подкасты, чтобы учить французский.', exampleEn: 'I download podcasts to learn French.' },
  { french: 'réseau social', translation: 'социальная сеть', translationEn: 'social network', category: 'media_modern', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2160, exampleFr: 'Les réseaux sociaux occupent beaucoup de notre temps.', exampleRu: 'Социальные сети занимают много нашего времени.', exampleEn: 'Social networks take up a lot of our time.' },
  { french: 'streaming', translation: 'стриминг, потоковое вещание', translationEn: 'streaming', category: 'media_modern', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2170, exampleFr: "Je regarde des films en streaming le week-end.", exampleRu: 'По выходным я смотрю фильмы в стриминге.', exampleEn: 'I watch films by streaming on weekends.' },
  { french: 'influenceur', translation: 'инфлюенсер, блогер', translationEn: 'influencer', category: 'media_modern', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2180, exampleFr: 'Cet influenceur a des millions d\'abonnés.', exampleRu: 'У этого инфлюенсера миллионы подписчиков.', exampleEn: 'This influencer has millions of followers.' },
  { french: 'notification', translation: 'уведомление', translationEn: 'notification', category: 'media_modern', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2190, exampleFr: 'Je reçois trop de notifications sur mon téléphone.', exampleRu: 'Я получаю слишком много уведомлений на телефон.', exampleEn: 'I receive too many notifications on my phone.' },
  { french: 'commenter', translation: 'комментировать', translationEn: 'to comment', category: 'media_modern', partOfSpeech: 'verb', frequencyRank: 2200, exampleFr: "Les internautes commentent les articles en ligne.", exampleRu: 'Пользователи интернета комментируют статьи онлайн.', exampleEn: 'Internet users comment on articles online.' },

  // === RELATIONSHIPS ===
  { french: 'jalousie', translation: 'ревность, зависть', translationEn: 'jealousy, envy', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2210, exampleFr: 'La jalousie peut détruire une relation.', exampleRu: 'Ревность может разрушить отношения.', exampleEn: 'Jealousy can destroy a relationship.' },
  { french: 'trahison', translation: 'предательство', translationEn: 'betrayal, treason', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2220, exampleFr: 'Il a du mal à pardonner cette trahison.', exampleRu: 'Ему трудно простить это предательство.', exampleEn: 'He finds it hard to forgive this betrayal.' },
  { french: 'loyauté', translation: 'верность, лояльность', translationEn: 'loyalty, faithfulness', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2230, exampleFr: 'La loyauté est une qualité précieuse entre amis.', exampleRu: 'Верность — ценное качество между друзьями.', exampleEn: 'Loyalty is a precious quality between friends.' },
  { french: 'affection', translation: 'привязанность, нежность', translationEn: 'affection, fondness', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2240, exampleFr: "Elle montre beaucoup d'affection envers ses enfants.", exampleRu: 'Она проявляет большую нежность к своим детям.', exampleEn: 'She shows a lot of affection towards her children.' },
  { french: 'admiration', translation: 'восхищение', translationEn: 'admiration', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2250, exampleFr: 'Je ressens une grande admiration pour ce musicien.', exampleRu: 'Я испытываю огромное восхищение этим музыкантом.', exampleEn: 'I feel great admiration for this musician.' },
  { french: 'solidarité', translation: 'солидарность', translationEn: 'solidarity', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2260, exampleFr: 'La solidarité entre voisins est importante.', exampleRu: 'Солидарность между соседями важна.', exampleEn: 'Solidarity among neighbours is important.' },
  { french: 'entraide', translation: 'взаимопомощь', translationEn: 'mutual help, cooperation', category: 'relationships', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2270, exampleFr: "L'entraide est la base d'une bonne équipe.", exampleRu: 'Взаимопомощь — основа хорошей команды.', exampleEn: 'Mutual help is the foundation of a good team.' },
  { french: 'soutien', translation: 'поддержка', translationEn: 'support, backing', category: 'relationships', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2280, exampleFr: 'Merci pour votre soutien dans cette période difficile.', exampleRu: 'Спасибо за вашу поддержку в этот трудный период.', exampleEn: 'Thank you for your support during this difficult period.' },

  // === NUMBERS & STATISTICS ===
  { french: 'fraction', translation: 'дробь, часть', translationEn: 'fraction', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2290, exampleFr: 'Une fraction représente une partie du tout.', exampleRu: 'Дробь представляет часть от целого.', exampleEn: 'A fraction represents a part of the whole.' },
  { french: 'pourcentage', translation: 'процент', translationEn: 'percentage', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2300, exampleFr: 'Quel pourcentage des élèves a réussi l\'examen ?', exampleRu: 'Какой процент учеников сдал экзамен?', exampleEn: 'What percentage of students passed the exam?' },
  { french: 'proportion', translation: 'пропорция, доля', translationEn: 'proportion, share', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2310, exampleFr: 'La proportion de femmes au travail augmente.', exampleRu: 'Доля женщин на работе растёт.', exampleEn: 'The proportion of women at work is increasing.' },
  { french: 'taux', translation: 'ставка, уровень, показатель', translationEn: 'rate, level', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2320, exampleFr: 'Le taux de chômage a baissé cette année.', exampleRu: 'В этом году уровень безработицы снизился.', exampleEn: 'The unemployment rate fell this year.' },
  { french: 'chiffre', translation: 'цифра, число', translationEn: 'figure, digit, number', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2330, exampleFr: 'Les chiffres montrent une hausse des ventes.', exampleRu: 'Цифры показывают рост продаж.', exampleEn: 'The figures show a rise in sales.' },
  { french: 'statistique', translation: 'статистика', translationEn: 'statistics, statistic', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2340, exampleFr: "Selon les statistiques, la population vieillit.", exampleRu: 'По статистике, население стареет.', exampleEn: 'According to statistics, the population is ageing.' },
  { french: 'hausse', translation: 'рост, повышение', translationEn: 'rise, increase', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2350, exampleFr: "On observe une hausse des prix en ce moment.", exampleRu: 'Сейчас наблюдается рост цен.', exampleEn: 'We observe a rise in prices at the moment.' },
  { french: 'baisse', translation: 'снижение, падение', translationEn: 'fall, drop, decrease', category: 'numbers_stats', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2360, exampleFr: 'Il y a une baisse du nombre de touristes.', exampleRu: 'Наблюдается снижение числа туристов.', exampleEn: 'There is a fall in the number of tourists.' },
  { french: 'augmenter', translation: 'увеличивать(ся), расти', translationEn: 'to increase, to grow', category: 'numbers_stats', partOfSpeech: 'verb', frequencyRank: 2370, exampleFr: 'Les températures augmentent chaque année.', exampleRu: 'Температуры растут с каждым годом.', exampleEn: 'Temperatures increase every year.' },
  { french: 'diminuer', translation: 'уменьшать(ся), снижаться', translationEn: 'to decrease, to reduce', category: 'numbers_stats', partOfSpeech: 'verb', frequencyRank: 2380, exampleFr: 'Le budget a été diminué de 10 %.', exampleRu: 'Бюджет был сокращён на 10%.', exampleEn: 'The budget was reduced by 10%.' },
  { french: 'doubler', translation: 'удваивать(ся)', translationEn: 'to double', category: 'numbers_stats', partOfSpeech: 'verb', frequencyRank: 2390, exampleFr: "Le nombre d'utilisateurs a doublé en un an.", exampleRu: 'Количество пользователей удвоилось за год.', exampleEn: 'The number of users doubled in a year.' },
  { french: 'diviser', translation: 'делить, разделять', translationEn: 'to divide, to split', category: 'numbers_stats', partOfSpeech: 'verb', frequencyRank: 2400, exampleFr: 'On divise la somme en parts égales.', exampleRu: 'Мы делим сумму на равные части.', exampleEn: 'We divide the amount into equal parts.' },

  // === FORMAL CONNECTORS ===
  { french: 'toutefois', translation: 'тем не менее, однако', translationEn: 'however, nevertheless', category: 'connectors_formal', partOfSpeech: 'adverb', frequencyRank: 2410, exampleFr: 'Ce projet est ambitieux ; toutefois, il est réalisable.', exampleRu: 'Этот проект амбициозен, тем не менее он выполним.', exampleEn: 'This project is ambitious; however, it is feasible.' },
  { french: "d'une part", translation: 'с одной стороны', translationEn: 'on one hand', category: 'connectors_formal', partOfSpeech: 'adverb', frequencyRank: 2420, exampleFr: "D'une part, c'est pratique ; d'autre part, c'est cher.", exampleRu: 'С одной стороны, это удобно; с другой — дорого.', exampleEn: "On one hand, it's convenient; on the other, it's expensive." },
  { french: 'notamment', translation: 'в частности, особенно', translationEn: 'notably, in particular', category: 'connectors_formal', partOfSpeech: 'adverb', frequencyRank: 2430, exampleFr: 'Plusieurs villes, notamment Paris, ont des vélos en libre-service.', exampleRu: 'В нескольких городах, в частности в Париже, есть прокат велосипедов.', exampleEn: 'Several cities, notably Paris, have bike-sharing.' },
  { french: 'veuillez', translation: 'пожалуйста (формально)', translationEn: 'please (formal), kindly', category: 'connectors_formal', partOfSpeech: 'verb', frequencyRank: 2440, exampleFr: 'Veuillez vous asseoir, je vous en prie.', exampleRu: 'Пожалуйста, присаживайтесь.', exampleEn: 'Please be seated, I beg you.' },

  // === ADVANCED VERBS ===
  { french: 'obtenir', translation: 'получить, добиться', translationEn: 'to obtain, to get', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2450, exampleFr: "J'ai obtenu mon diplôme l'année dernière.", exampleRu: 'В прошлом году я получил диплом.', exampleEn: 'I obtained my degree last year.' },
  { french: 'résoudre', translation: 'решать (проблему), разрешать', translationEn: 'to solve, to resolve', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2460, exampleFr: "Il faut résoudre ce problème rapidement.", exampleRu: 'Эту проблему нужно решить быстро.', exampleEn: 'This problem must be solved quickly.' },
  { french: 'contribuer', translation: 'вносить вклад, способствовать', translationEn: 'to contribute', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2470, exampleFr: 'Chacun peut contribuer à la protection de l\'environnement.', exampleRu: 'Каждый может внести вклад в защиту окружающей среды.', exampleEn: 'Everyone can contribute to environmental protection.' },
  { french: 'réaliser', translation: 'осуществлять, понимать, создавать', translationEn: 'to realize, to achieve, to make', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2480, exampleFr: "Il a réalisé son rêve de voyager autour du monde.", exampleRu: 'Он осуществил мечту объехать весь мир.', exampleEn: 'He realized his dream of travelling around the world.' },
  { french: 'exiger', translation: 'требовать', translationEn: 'to demand, to require', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2490, exampleFr: 'Ce travail exige beaucoup de concentration.', exampleRu: 'Эта работа требует большой концентрации.', exampleEn: 'This work requires a lot of concentration.' },
  { french: 'reprendre', translation: 'возобновлять, забирать обратно', translationEn: 'to resume, to take back', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2500, exampleFr: 'Les cours reprennent lundi après les vacances.', exampleRu: 'После каникул занятия возобновляются в понедельник.', exampleEn: 'Classes resume on Monday after the holidays.' },
  { french: 'attirer', translation: 'привлекать, притягивать', translationEn: 'to attract, to draw', category: 'verbs_advanced', partOfSpeech: 'verb', frequencyRank: 2510, exampleFr: 'Cette exposition attire beaucoup de visiteurs.', exampleRu: 'Эта выставка привлекает много посетителей.', exampleEn: 'This exhibition attracts many visitors.' },

  // === ENVIRONMENT ===
  { french: 'réchauffement', translation: 'потепление', translationEn: 'warming', category: 'environment_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2520, exampleFr: 'Le réchauffement climatique est une menace mondiale.', exampleRu: 'Глобальное потепление — мировая угроза.', exampleEn: 'Global warming is a worldwide threat.' },
  { french: 'biodiversité', translation: 'биоразнообразие', translationEn: 'biodiversity', category: 'environment_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2530, exampleFr: 'Il faut protéger la biodiversité des forêts tropicales.', exampleRu: 'Необходимо защищать биоразнообразие тропических лесов.', exampleEn: 'We must protect the biodiversity of tropical forests.' },
  { french: 'extinction', translation: 'вымирание, исчезновение', translationEn: 'extinction', category: 'environment_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2540, exampleFr: 'De nombreuses espèces sont menacées d\'extinction.', exampleRu: 'Многим видам грозит вымирание.', exampleEn: 'Many species are threatened with extinction.' },
  { french: 'empreinte carbone', translation: 'углеродный след', translationEn: 'carbon footprint', category: 'environment_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2550, exampleFr: 'Réduire son empreinte carbone est essentiel.', exampleRu: 'Снизить свой углеродный след — это необходимо.', exampleEn: 'Reducing your carbon footprint is essential.' },
  { french: 'durabilité', translation: 'устойчивость, экологичность', translationEn: 'sustainability', category: 'environment_extra', partOfSpeech: 'noun', gender: 'f', frequencyRank: 2560, exampleFr: 'La durabilité est au cœur de ce projet.', exampleRu: 'Устойчивость лежит в основе этого проекта.', exampleEn: 'Sustainability is at the heart of this project.' },
  { french: 'combustible', translation: 'топливо, горючее', translationEn: 'fuel, combustible', category: 'environment_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2570, exampleFr: 'Les combustibles fossiles polluent beaucoup.', exampleRu: 'Ископаемое топливо сильно загрязняет.', exampleEn: 'Fossil fuels pollute a lot.' },
  { french: 'pétrole', translation: 'нефть', translationEn: 'oil, petroleum', category: 'environment_extra', partOfSpeech: 'noun', gender: 'm', frequencyRank: 2580, exampleFr: 'Le pétrole est une ressource non renouvelable.', exampleRu: 'Нефть — невозобновляемый ресурс.', exampleEn: 'Oil is a non-renewable resource.' },
];
