export const wordsB2Extra12 = [
  // ── Presse écrite ──
  {
    french: 'la une',
    translation: 'первая полоса; главная новость',
    translationEn: 'front page, headline',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3500,
    exampleFr: 'L\'affaire a fait la une de tous les journaux.',
    exampleRu: 'Это дело появилось на первых полосах всех газет.',
    exampleEn: 'The affair made the front page of every newspaper.',
  },
  {
    french: 'le fait divers',
    translation: 'происшествие (мелкая хроника)',
    translationEn: 'miscellaneous news item, human interest story',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4800,
    exampleFr: 'Le fait divers a été repris par toutes les chaînes télévisées.',
    exampleRu: 'Это происшествие осветили все телеканалы.',
    exampleEn: 'The human interest story was picked up by all TV channels.',
  },
  {
    french: 'l\'éditorial',
    translation: 'передовица, редакционная статья',
    translationEn: 'editorial, leading article',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4300,
    exampleFr: 'L\'éditorial du journal condamne la décision du gouvernement.',
    exampleRu: 'Передовица газеты осуждает решение правительства.',
    exampleEn: 'The newspaper\'s editorial condemns the government\'s decision.',
  },
  {
    french: 'la chronique',
    translation: 'колонка, обозрение',
    translationEn: 'column, chronicle',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3200,
    exampleFr: 'Sa chronique hebdomadaire est très appréciée des lecteurs.',
    exampleRu: 'Его еженедельная колонка пользуется большой любовью читателей.',
    exampleEn: 'His weekly column is greatly appreciated by readers.',
  },
  {
    french: 'le dossier',
    translation: 'досье, спецвыпуск (в журналистике)',
    translationEn: 'special report, feature',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2100,
    exampleFr: 'Le magazine a publié un dossier complet sur la crise du logement.',
    exampleRu: 'Журнал опубликовал полное досье о жилищном кризисе.',
    exampleEn: 'The magazine published a comprehensive feature on the housing crisis.',
  },
  {
    french: 'la revue de presse',
    translation: 'обзор прессы',
    translationEn: 'press review',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5200,
    exampleFr: 'La revue de presse du matin résume les grandes actualités.',
    exampleRu: 'Утренний обзор прессы суммирует главные новости.',
    exampleEn: 'The morning press review summarises the main news.',
  },
  // ── Professionnels des médias ──
  {
    french: 'le rédacteur en chef',
    translation: 'главный редактор',
    translationEn: 'editor-in-chief',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4600,
    exampleFr: 'Le rédacteur en chef a validé l\'enquête avant publication.',
    exampleRu: 'Главный редактор утвердил расследование перед публикацией.',
    exampleEn: 'The editor-in-chief approved the investigation before publication.',
  },
  {
    french: 'le journaliste d\'investigation',
    translation: 'журналист-расследователь',
    translationEn: 'investigative journalist',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Le journaliste d\'investigation a passé un an sur ce dossier.',
    exampleRu: 'Журналист-расследователь провёл год над этим делом.',
    exampleEn: 'The investigative journalist spent a year on this case.',
  },
  {
    french: 'le grand reporter',
    translation: 'специальный корреспондент',
    translationEn: 'senior foreign correspondent',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5400,
    exampleFr: 'Le grand reporter a couvert dix conflits armés en trente ans.',
    exampleRu: 'За тридцать лет спецкор освещал десять вооружённых конфликтов.',
    exampleEn: 'The senior correspondent covered ten armed conflicts in thirty years.',
  },
  {
    french: 'le correspondant',
    translation: 'корреспондент',
    translationEn: 'correspondent',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3700,
    exampleFr: 'Notre correspondant à Moscou nous donne les dernières informations.',
    exampleRu: 'Наш корреспондент в Москве сообщает последние новости.',
    exampleEn: 'Our correspondent in Moscow gives us the latest news.',
  },
  {
    french: 'le pigiste',
    translation: 'внештатный журналист (фрилансер)',
    translationEn: 'freelance journalist',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'De plus en plus de journalistes travaillent comme pigistes.',
    exampleRu: 'Всё больше журналистов работают на вольных хлебах.',
    exampleEn: 'More and more journalists work as freelancers.',
  },
  {
    french: 'le porte-parole',
    translation: 'пресс-секретарь, официальный представитель',
    translationEn: 'spokesperson, spokesman',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3400,
    exampleFr: 'Le porte-parole du gouvernement a démenti ces informations.',
    exampleRu: 'Официальный представитель правительства опроверг эти сведения.',
    exampleEn: 'The government spokesperson denied this information.',
  },
  {
    french: 'le chroniqueur',
    translation: 'обозреватель, колумнист',
    translationEn: 'columnist, commentator',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4900,
    exampleFr: 'Le chroniqueur politique est connu pour ses prises de position tranchées.',
    exampleRu: 'Политический обозреватель известен своими острыми позициями.',
    exampleEn: 'The political commentator is known for his sharp views.',
  },
  // ── Pratiques journalistiques ──
  {
    french: 'la liberté éditoriale',
    translation: 'редакционная свобода',
    translationEn: 'editorial freedom',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5800,
    exampleFr: 'La liberté éditoriale est menacée quand un actionnaire impose ses choix.',
    exampleRu: 'Редакционная свобода оказывается под угрозой, когда акционер навязывает свои предпочтения.',
    exampleEn: 'Editorial freedom is threatened when a shareholder imposes their choices.',
  },
  {
    french: 'le droit de réponse',
    translation: 'право на ответ',
    translationEn: 'right of reply',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5600,
    exampleFr: 'Toute personne mise en cause a un droit de réponse.',
    exampleRu: 'Любое лицо, которого касается публикация, имеет право на ответ.',
    exampleEn: 'Any person implicated has a right of reply.',
  },
  {
    french: 'la source protégée',
    translation: 'защищённый источник информации',
    translationEn: 'protected source',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6200,
    exampleFr: 'Un journaliste peut refuser de révéler une source protégée.',
    exampleRu: 'Журналист вправе отказаться раскрывать защищённый источник.',
    exampleEn: 'A journalist can refuse to reveal a protected source.',
  },
  {
    french: 'l\'exclusivité',
    translation: 'эксклюзив',
    translationEn: 'exclusive, scoop',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4200,
    exampleFr: 'Le journal a obtenu l\'exclusivité de l\'interview.',
    exampleRu: 'Газета получила эксклюзивное право на интервью.',
    exampleEn: 'The newspaper obtained the exclusive interview.',
  },
  {
    french: 'l\'embargo',
    translation: 'эмбарго (на публикацию до срока)',
    translationEn: 'embargo (news embargo)',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4400,
    exampleFr: 'Le communiqué était sous embargo jusqu\'au lendemain matin.',
    exampleRu: 'Пресс-релиз был под эмбарго до следующего утра.',
    exampleEn: 'The press release was under embargo until the following morning.',
  },
  {
    french: 'le scoop',
    translation: 'сенсационная новость, эксклюзив',
    translationEn: 'scoop, exclusive story',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5000,
    exampleFr: 'Ce scoop lui a valu le prix du meilleur journaliste de l\'année.',
    exampleRu: 'Этот эксклюзив принёс ему звание лучшего журналиста года.',
    exampleEn: 'This scoop earned him the best journalist of the year award.',
  },
  {
    french: 'couvrir',
    translation: 'освещать (событие)',
    translationEn: 'to cover (an event)',
    category: 'media',
    partOfSpeech: 'verb',
    frequencyRank: 2200,
    exampleFr: 'Cinquante journalistes ont couvert le sommet du G20.',
    exampleRu: 'Пятьдесят журналистов освещали саммит G20.',
    exampleEn: 'Fifty journalists covered the G20 summit.',
  },
  {
    french: 'diffuser',
    translation: 'транслировать, распространять',
    translationEn: 'to broadcast, to disseminate',
    category: 'media',
    partOfSpeech: 'verb',
    frequencyRank: 3000,
    exampleFr: 'La chaîne a diffusé le documentaire en prime time.',
    exampleRu: 'Телеканал транслировал документальный фильм в прайм-тайм.',
    exampleEn: 'The channel broadcast the documentary in prime time.',
  },
  // ── Analyse des médias ──
  {
    french: 'le parti pris',
    translation: 'предвзятость, пристрастность',
    translationEn: 'bias, partiality',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4100,
    exampleFr: 'Le lecteur doit être conscient du parti pris de chaque journal.',
    exampleRu: 'Читатель должен осознавать предвзятость каждого издания.',
    exampleEn: 'The reader must be aware of each newspaper\'s bias.',
  },
  {
    french: 'le sensationnalisme',
    translation: 'сенсационализм',
    translationEn: 'sensationalism',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5500,
    exampleFr: 'Le sensationnalisme nuit à la crédibilité journalistique.',
    exampleRu: 'Сенсационализм подрывает журналистское доверие.',
    exampleEn: 'Sensationalism damages journalistic credibility.',
  },
  {
    french: 'le cadrage',
    translation: 'фрейминг, подача материала',
    translationEn: 'framing (media)',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5700,
    exampleFr: 'Le cadrage d\'un sujet influence la perception du lecteur.',
    exampleRu: 'Подача темы влияет на восприятие читателя.',
    exampleEn: 'The framing of a story influences the reader\'s perception.',
  },
  {
    french: 'l\'autocensure',
    translation: 'самоцензура',
    translationEn: 'self-censorship',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5900,
    exampleFr: 'La pression des annonceurs peut conduire à l\'autocensure.',
    exampleRu: 'Давление рекламодателей может приводить к самоцензуре.',
    exampleEn: 'Advertiser pressure can lead to self-censorship.',
  },
  {
    french: 'la propagande',
    translation: 'пропаганда',
    translationEn: 'propaganda',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3300,
    exampleFr: 'La propagande d\'État manipule les faits pour servir un récit officiel.',
    exampleRu: 'Государственная пропаганда искажает факты, служа официальной нарративной.',
    exampleEn: 'State propaganda manipulates facts to serve an official narrative.',
  },
  {
    french: 'viral',
    translation: 'вирусный (о контенте)',
    translationEn: 'viral (content)',
    category: 'media',
    partOfSpeech: 'adjective',
    frequencyRank: 4700,
    exampleFr: 'Cette vidéo est devenue virale en moins de vingt-quatre heures.',
    exampleRu: 'Это видео стало вирусным менее чем за двадцать четыре часа.',
    exampleEn: 'This video went viral in less than twenty-four hours.',
  },
  {
    french: 'le buzz',
    translation: 'ажиотаж в сети',
    translationEn: 'buzz, online hype',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5100,
    exampleFr: 'La campagne a créé un énorme buzz sur les réseaux sociaux.',
    exampleRu: 'Кампания вызвала огромный ажиотаж в социальных сетях.',
    exampleEn: 'The campaign created a huge buzz on social media.',
  },
  // ── Communication institutionnelle ──
  {
    french: 'le communiqué de presse',
    translation: 'пресс-релиз',
    translationEn: 'press release',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4500,
    exampleFr: 'L\'entreprise a publié un communiqué de presse pour démentir les rumeurs.',
    exampleRu: 'Компания опубликовала пресс-релиз, чтобы опровергнуть слухи.',
    exampleEn: 'The company issued a press release to deny the rumours.',
  },
  {
    french: 'la conférence de presse',
    translation: 'пресс-конференция',
    translationEn: 'press conference',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3600,
    exampleFr: 'Le ministre a donné une conférence de presse pour expliquer sa position.',
    exampleRu: 'Министр провёл пресс-конференцию, чтобы объяснить свою позицию.',
    exampleEn: 'The minister held a press conference to explain his position.',
  },
  {
    french: 'l\'e-réputation',
    translation: 'онлайн-репутация, е-репутация',
    translationEn: 'online reputation',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 6500,
    exampleFr: 'Une crise peut détruire l\'e-réputation d\'une marque en quelques heures.',
    exampleRu: 'Кризис способен уничтожить онлайн-репутацию бренда за несколько часов.',
    exampleEn: 'A crisis can destroy a brand\'s online reputation within hours.',
  },
  {
    french: 'le lobbying',
    translation: 'лоббирование',
    translationEn: 'lobbying',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 4800,
    exampleFr: 'Le lobbying des groupes pharmaceutiques influence les décisions sanitaires.',
    exampleRu: 'Лоббирование фармацевтических групп влияет на санитарные решения.',
    exampleEn: 'Pharmaceutical lobbying influences health policy decisions.',
  },
  {
    french: 'la tribune',
    translation: 'трибуна; статья с авторской позицией',
    translationEn: 'opinion piece, tribune',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3000,
    exampleFr: 'Cent intellectuels ont signé une tribune dans Le Monde.',
    exampleRu: 'Сто интеллектуалов подписали статью в газете Le Monde.',
    exampleEn: 'A hundred intellectuals signed an opinion piece in Le Monde.',
  },
  {
    french: 'le traitement médiatique',
    translation: 'медийное освещение',
    translationEn: 'media coverage',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5300,
    exampleFr: 'Le traitement médiatique de l\'affaire a été jugé partial.',
    exampleRu: 'Медийное освещение этого дела было признано предвзятым.',
    exampleEn: 'The media coverage of the affair was deemed partial.',
  },
  {
    french: 'l\'audience',
    translation: 'аудитория; рейтинг (тв)',
    translationEn: 'audience, ratings',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2500,
    exampleFr: 'Cette émission réunit la plus grande audience de la chaîne.',
    exampleRu: 'Эта передача собирает самую большую аудиторию телеканала.',
    exampleEn: 'This show attracts the channel\'s largest audience.',
  },
  {
    french: 'le taux d\'audience',
    translation: 'рейтинг (доля аудитории)',
    translationEn: 'audience share, ratings',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 5200,
    exampleFr: 'Le taux d\'audience du journal télévisé a chuté de dix pour cent.',
    exampleRu: 'Рейтинг вечерних новостей упал на десять процентов.',
    exampleEn: 'The TV news ratings dropped by ten per cent.',
  },
  {
    french: 'la prime time',
    translation: 'прайм-тайм',
    translationEn: 'prime time',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5600,
    exampleFr: 'Le débat présidentiel sera diffusé en prime time.',
    exampleRu: 'Президентские дебаты будут транслироваться в прайм-тайм.',
    exampleEn: 'The presidential debate will be broadcast in prime time.',
  },
  {
    french: 'l\'antenne',
    translation: 'эфир (в фразе «être à l\'antenne»)',
    translationEn: 'airwaves, on air',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3800,
    exampleFr: 'La chaîne a perdu son autorisation d\'émettre sur l\'antenne.',
    exampleRu: 'Телеканал лишился разрешения выходить в эфир.',
    exampleEn: 'The channel lost its broadcasting licence.',
  },
  {
    french: 'le présentateur',
    translation: 'ведущий (теле/радио)',
    translationEn: 'presenter, anchor',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 3500,
    exampleFr: 'Le présentateur du journal a annoncé sa démission en direct.',
    exampleRu: 'Ведущий новостей объявил о своей отставке в прямом эфире.',
    exampleEn: 'The news anchor announced his resignation live on air.',
  },
  {
    french: 'le fil d\'actu',
    translation: 'лента новостей',
    translationEn: 'news feed, news stream',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6000,
    exampleFr: 'Parcourir le fil d\'actu dès le matin est une habitude pour beaucoup.',
    exampleRu: 'Просматривать ленту новостей с утра — привычка многих.',
    exampleEn: 'Scrolling through the news feed first thing in the morning is a habit for many.',
  },
  {
    french: 'médiatique',
    translation: 'медийный',
    translationEn: 'media-friendly, high-profile',
    category: 'media',
    partOfSpeech: 'adjective',
    frequencyRank: 4000,
    exampleFr: 'C\'est un événement très médiatique qui attire tous les projecteurs.',
    exampleRu: 'Это очень медийное событие, привлекающее всеобщее внимание.',
    exampleEn: 'It\'s a very high-profile event that attracts all the spotlights.',
  },
  {
    french: 'la prise de position',
    translation: 'занятие позиции; заявление позиции',
    translationEn: 'taking a stand, position statement',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 4600,
    exampleFr: 'Sa prise de position courageuse lui a valu de nombreuses critiques.',
    exampleRu: 'Его смелое заявление позиции повлекло за собой множество критических откликов.',
    exampleEn: 'His courageous stand earned him many criticisms.',
  },
  {
    french: 'la rectification',
    translation: 'опровержение, исправление (в прессе)',
    translationEn: 'correction, retraction',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5400,
    exampleFr: 'Le journal a publié une rectification suite à l\'erreur factuelle.',
    exampleRu: 'Газета опубликовала опровержение после фактической ошибки.',
    exampleEn: 'The newspaper published a correction following the factual error.',
  },
  {
    french: 'l\'investigation',
    translation: 'журналистское расследование',
    translationEn: 'investigation, investigative reporting',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3100,
    exampleFr: 'L\'investigation a mis six mois à révéler le scandale.',
    exampleRu: 'Журналистское расследование потребовало шести месяцев, чтобы вскрыть скандал.',
    exampleEn: 'The investigation took six months to uncover the scandal.',
  },
  {
    french: 'l\'angle',
    translation: 'угол зрения, ракурс (материала)',
    translationEn: 'angle (journalistic approach)',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2800,
    exampleFr: 'L\'angle choisi par le journaliste oriente toute la lecture de l\'article.',
    exampleRu: 'Выбранный журналистом угол подачи определяет всё восприятие статьи.',
    exampleEn: 'The angle chosen by the journalist shapes the entire reading of the article.',
  },
  {
    french: 'la mise en page',
    translation: 'вёрстка, макет',
    translationEn: 'layout, page layout',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 5100,
    exampleFr: 'La mise en page aérée facilite la lecture de l\'article.',
    exampleRu: 'Воздушная вёрстка облегчает чтение статьи.',
    exampleEn: 'The open layout makes the article easier to read.',
  },
  {
    french: 'le portrait',
    translation: 'портрет (жанр материала о человеке)',
    translationEn: 'profile (journalistic feature about a person)',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 2000,
    exampleFr: 'Ce portrait du chef d\'État a été très controversé.',
    exampleRu: 'Этот портрет главы государства вызвал большие споры.',
    exampleEn: 'This profile of the head of state was highly controversial.',
  },
  {
    french: 'publier',
    translation: 'публиковать',
    translationEn: 'to publish',
    category: 'media',
    partOfSpeech: 'verb',
    frequencyRank: 2300,
    exampleFr: 'La rédaction a décidé de ne pas publier l\'article pour des raisons légales.',
    exampleRu: 'Редакция решила не публиковать статью по юридическим соображениям.',
    exampleEn: 'The editorial team decided not to publish the article for legal reasons.',
  },
  {
    french: 'la censure',
    translation: 'цензура',
    translationEn: 'censorship',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 3200,
    exampleFr: 'La censure gouvernementale viole le principe de liberté d\'expression.',
    exampleRu: 'Государственная цензура нарушает принцип свободы слова.',
    exampleEn: 'Government censorship violates the principle of freedom of expression.',
  },
  {
    french: 'l\'infotainment',
    translation: 'инфотейнмент (смесь информации и развлечения)',
    translationEn: 'infotainment',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'm',
    frequencyRank: 6800,
    exampleFr: 'L\'infotainment brouille la frontière entre journalisme et divertissement.',
    exampleRu: 'Инфотейнмент размывает границу между журналистикой и развлечением.',
    exampleEn: 'Infotainment blurs the line between journalism and entertainment.',
  },
  {
    french: 'la rumeur',
    translation: 'слух, слухи',
    translationEn: 'rumour',
    category: 'media',
    partOfSpeech: 'noun',
    gender: 'f',
    frequencyRank: 2700,
    exampleFr: 'La rumeur s\'est propagée à une vitesse impressionnante sur internet.',
    exampleRu: 'Слух распространился с впечатляющей скоростью в интернете.',
    exampleEn: 'The rumour spread at an impressive speed on the internet.',
  },
];
