export const writingPromptsData = [
  // ─── A1: Carte postale ────────────────────────────────────────────────────
  {
    slug: 'a1-postcard-paris',
    titleRu: 'Открытка из Парижа',
    titleEn: 'Postcard from Paris',
    level: 'A1' as const,
    writingType: 'postcard' as const,
    promptFr: 'Vous êtes à Paris pour la première fois. Écrivez une carte postale à un(e) ami(e). Dites où vous êtes, ce que vous voyez et si vous aimez Paris.',
    promptRu: 'Вы впервые в Париже. Напишите открытку другу. Скажите, где вы находитесь, что видите и нравится ли вам Париж.',
    promptEn: 'You are in Paris for the first time. Write a postcard to a friend. Say where you are, what you see, and whether you like Paris.',
    tipsRu: [
      'Начните с "Salut !" или "Bonjour !"',
      'Используйте глагол être: "Je suis à Paris"',
      'Используйте il y a: "Il y a beaucoup de touristes"',
      'Закончите: "Bises !" или "À bientôt !"',
    ],
    tipsEn: [
      'Start with "Salut !" or "Bonjour !"',
      'Use the verb être: "Je suis à Paris"',
      'Use il y a: "Il y a beaucoup de touristes"',
      'End with: "Bises !" or "À bientôt !"',
    ],
    minWords: 30,
    maxWords: 50,
    requiredElements: ['greeting', 'location', 'description', 'closing'],
  },
  {
    slug: 'a1-postcard-holidays',
    titleRu: 'Открытка с каникул',
    titleEn: 'Holiday postcard',
    level: 'A1' as const,
    writingType: 'postcard' as const,
    promptFr: 'Vous êtes en vacances à la mer. Écrivez une carte postale à votre famille. Dites le temps qu\'il fait et une activité que vous aimez faire.',
    promptRu: 'Вы отдыхаете у моря. Напишите открытку семье. Расскажите о погоде и об одном занятии, которое вам нравится.',
    promptEn: 'You are on holiday by the sea. Write a postcard to your family. Describe the weather and one activity you enjoy.',
    tipsRu: [
      'Погода: "Il fait beau / chaud / soleil"',
      'Занятия: "Je nage", "Je mange des glaces"',
      'Выразите эмоцию: "C\'est super !", "J\'adore !"',
    ],
    tipsEn: [
      'Weather: "Il fait beau / chaud / soleil"',
      'Activities: "Je nage", "Je mange des glaces"',
      'Express emotion: "C\'est super !", "J\'adore !"',
    ],
    minWords: 30,
    maxWords: 50,
    requiredElements: ['weather', 'activity', 'emotion'],
  },

  // ─── A1: Message court ────────────────────────────────────────────────────
  {
    slug: 'a1-message-late',
    titleRu: 'Сообщение: опоздаю',
    titleEn: 'Message: I\'m running late',
    level: 'A1' as const,
    writingType: 'message' as const,
    promptFr: 'Vous êtes en retard pour un rendez-vous avec un(e) ami(e). Écrivez un message pour expliquer pourquoi vous êtes en retard et à quelle heure vous arrivez.',
    promptRu: 'Вы опаздываете на встречу с другом. Напишите сообщение, объясните причину опоздания и укажите, во сколько приедете.',
    promptEn: 'You are late for a meeting with a friend. Write a message explaining why you are late and when you will arrive.',
    tipsRu: [
      'Извинитесь: "Désolé(e) !"',
      'Объясните: "Le bus est en retard", "Je travaille encore"',
      'Скажите когда: "J\'arrive à 15h"',
    ],
    tipsEn: [
      'Apologise: "Désolé(e) !"',
      'Explain: "Le bus est en retard", "Je travaille encore"',
      'Say when: "J\'arrive à 15h"',
    ],
    minWords: 35,
    maxWords: 55,
    requiredElements: ['apology', 'reason', 'time'],
  },
  {
    slug: 'a1-message-meeting',
    titleRu: 'Сообщение: встреча на выходных',
    titleEn: 'Message: weekend plan',
    level: 'A1' as const,
    writingType: 'message' as const,
    promptFr: 'Vous voulez voir un(e) ami(e) ce week-end. Écrivez un message pour proposer une activité, un jour et une heure.',
    promptRu: 'Вы хотите увидеться с другом на выходных. Напишите сообщение с предложением занятия, дня и времени.',
    promptEn: 'You want to see a friend this weekend. Write a message to suggest an activity, day and time.',
    tipsRu: [
      'Предложите: "Tu veux... ?" или "On peut... ?"',
      'Укажите день: "samedi", "dimanche"',
      'Используйте вопросительные слова: "Qu\'est-ce que tu fais ?"',
    ],
    tipsEn: [
      'Suggest: "Tu veux... ?" or "On peut... ?"',
      'Specify day: "samedi", "dimanche"',
      'Use question words: "Qu\'est-ce que tu fais ?"',
    ],
    minWords: 35,
    maxWords: 60,
    requiredElements: ['suggestion', 'day', 'time'],
  },

  // ─── A1: Description ──────────────────────────────────────────────────────
  {
    slug: 'a1-description-famille',
    titleRu: 'Описание семьи',
    titleEn: 'Family description',
    level: 'A1' as const,
    writingType: 'description' as const,
    promptFr: "Décrivez votre famille. Présentez chaque personne (nom, âge, profession) et dites ce qu'elle aime faire.",
    promptRu: 'Опишите свою семью. Представьте каждого члена (имя, возраст, профессия) и расскажите, что они любят делать.',
    promptEn: 'Describe your family. Introduce each member (name, age, job) and say what they like to do.',
    tipsRu: [
      'Используйте: "Mon père s\'appelle...", "Ma mère a... ans"',
      'Профессии: "Il est médecin / Elle est professeure"',
      'Хобби: "Il aime le sport", "Elle adore lire"',
      'Связывайте: "et", "aussi"',
    ],
    tipsEn: [
      'Use: "Mon père s\'appelle...", "Ma mère a... ans"',
      'Jobs: "Il est médecin / Elle est professeure"',
      'Hobbies: "Il aime le sport", "Elle adore lire"',
      'Connect: "et", "aussi"',
    ],
    minWords: 50,
    maxWords: 80,
    requiredElements: ['names', 'ages', 'professions', 'hobbies'],
  },
  {
    slug: 'a1-description-chambre',
    titleRu: 'Описание комнаты',
    titleEn: 'Room description',
    level: 'A1' as const,
    writingType: 'description' as const,
    promptFr: "Décrivez votre chambre. Dites où elle se trouve, ce qu'il y a dedans (meubles, objets, couleurs) et pourquoi vous l'aimez.",
    promptRu: 'Опишите свою комнату. Скажите, где она находится, что в ней есть (мебель, вещи, цвета) и почему она вам нравится.',
    promptEn: 'Describe your room. Say where it is, what is in it (furniture, objects, colours) and why you like it.',
    tipsRu: [
      'Локация: "Ma chambre est au premier étage"',
      'Мебель: "Il y a un lit, une table, une chaise"',
      'Цвета: "Les murs sont blancs"',
      'Чувства: "J\'aime ma chambre parce que..."',
    ],
    tipsEn: [
      'Location: "Ma chambre est au premier étage"',
      'Furniture: "Il y a un lit, une table, une chaise"',
      'Colours: "Les murs sont blancs"',
      'Feelings: "J\'aime ma chambre parce que..."',
    ],
    minWords: 40,
    maxWords: 70,
    requiredElements: ['location', 'furniture', 'colours', 'opinion'],
  },
  {
    slug: 'a1-description-journee',
    titleRu: 'Моя обычная неделя',
    titleEn: 'My typical week',
    level: 'A1' as const,
    writingType: 'description' as const,
    promptFr: 'Décrivez une journée typique de votre semaine. Dites ce que vous faites le matin, à midi et le soir.',
    promptRu: 'Опишите обычный день недели. Расскажите, что вы делаете утром, в обед и вечером.',
    promptEn: 'Describe a typical weekday. Say what you do in the morning, at noon and in the evening.',
    tipsRu: [
      'Время: "À sept heures, je me lève"',
      'Глаголы: "prendre le petit-déjeuner", "aller au travail", "rentrer"',
      'Связки: "puis", "ensuite", "enfin"',
      'Закончите вечером: "Je me couche à..."',
    ],
    tipsEn: [
      'Time: "À sept heures, je me lève"',
      'Verbs: "prendre le petit-déjeuner", "aller au travail", "rentrer"',
      'Connectors: "puis", "ensuite", "enfin"',
      'End with evening: "Je me couche à..."',
    ],
    minWords: 50,
    maxWords: 80,
    requiredElements: ['morning', 'noon', 'evening', 'time_indicators'],
  },
  {
    slug: 'a1-message-restaurant',
    titleRu: 'Сообщение: предложение поужинать',
    titleEn: 'Message: dinner suggestion',
    level: 'A1' as const,
    writingType: 'message' as const,
    promptFr: "Vous voulez dîner au restaurant avec un(e) ami(e). Écrivez un message pour proposer un restaurant. Dites quel restaurant, quand et à quelle heure.",
    promptRu: 'Вы хотите поужинать в ресторане с другом. Напишите сообщение с предложением: какой ресторан, когда и во сколько.',
    promptEn: 'You want to have dinner at a restaurant with a friend. Write a message suggesting one: which restaurant, when and at what time.',
    tipsRu: [
      'Предложение: "Tu veux dîner au restaurant ?"',
      'Конкретно: "Au restaurant italien rue Victor Hugo"',
      'Время: "Vendredi soir, à vingt heures"',
      'Конец: "Dis-moi si tu es libre !"',
    ],
    tipsEn: [
      'Suggestion: "Tu veux dîner au restaurant ?"',
      'Specifics: "Au restaurant italien rue Victor Hugo"',
      'Time: "Vendredi soir, à vingt heures"',
      'Closing: "Dis-moi si tu es libre !"',
    ],
    minWords: 35,
    maxWords: 55,
    requiredElements: ['suggestion', 'place', 'day_time'],
  },

  // ─── A2: Lettre informelle ────────────────────────────────────────────────
  {
    slug: 'a2-letter-birthday',
    titleRu: 'Приглашение на день рождения',
    titleEn: 'Birthday invitation',
    level: 'A2' as const,
    writingType: 'letter_informal' as const,
    promptFr: 'Vous organisez une fête pour votre anniversaire. Écrivez une lettre à un(e) ami(e) pour l\'inviter. Donnez les informations : date, heure, lieu et ce qu\'il/elle doit apporter.',
    promptRu: 'Вы организуете вечеринку по случаю дня рождения. Напишите письмо другу с приглашением. Укажите дату, время, место и что нужно принести.',
    promptEn: 'You are organising a birthday party. Write a letter to a friend inviting them. Include date, time, place and what they should bring.',
    tipsRu: [
      'Начало: "Cher / Chère [prénom],"',
      'Приглашение: "Je t\'invite à...", "Tu peux venir ?"',
      'Детали: "La fête est le... à... chez moi"',
      'Конец: "J\'espère que tu peux venir !", "Bisous,"',
    ],
    tipsEn: [
      'Opening: "Cher / Chère [prénom],"',
      'Invitation: "Je t\'invite à...", "Tu peux venir ?"',
      'Details: "La fête est le... à... chez moi"',
      'Closing: "J\'espère que tu peux venir !", "Bisous,"',
    ],
    minWords: 80,
    maxWords: 120,
    requiredElements: ['salutation', 'invitation', 'date_time_place', 'closing'],
  },
  {
    slug: 'a2-letter-holidays',
    titleRu: 'Письмо о каникулах',
    titleEn: 'Letter about holidays',
    level: 'A2' as const,
    writingType: 'letter_informal' as const,
    promptFr: 'Vous revenez de vacances. Écrivez une lettre à un(e) ami(e) pour raconter vos vacances : où vous êtes allé(e), ce que vous avez fait et ce que vous avez aimé ou pas aimé.',
    promptRu: 'Вы вернулись с каникул. Напишите письмо другу: расскажите, куда ездили, что делали, что понравилось и что нет.',
    promptEn: 'You have returned from holiday. Write a letter to a friend: tell them where you went, what you did, what you liked and didn\'t like.',
    tipsRu: [
      'Используйте passé composé: "J\'ai visité", "Nous sommes allés"',
      'Выражайте мнение: "J\'ai adoré...", "Je n\'ai pas aimé..."',
      'Связки: "D\'abord... ensuite... finalement"',
      'Задайте вопрос в конце: "Et toi, tu as passé un bon été ?"',
    ],
    tipsEn: [
      'Use passé composé: "J\'ai visité", "Nous sommes allés"',
      'Express opinions: "J\'ai adoré...", "Je n\'ai pas aimé..."',
      'Connectors: "D\'abord... ensuite... finalement"',
      'Ask a question at the end: "Et toi, tu as passé un bon été ?"',
    ],
    minWords: 80,
    maxWords: 120,
    requiredElements: ['passé_composé', 'opinion', 'connectors'],
  },
  {
    slug: 'a2-letter-recommendation',
    titleRu: 'Рекомендация фильма',
    titleEn: 'Film recommendation',
    level: 'A2' as const,
    writingType: 'letter_informal' as const,
    promptFr: 'Vous avez vu un film que vous aimez beaucoup. Écrivez à un(e) ami(e) pour lui recommander ce film. Décrivez l\'histoire et dites pourquoi vous avez aimé.',
    promptRu: 'Вы посмотрели фильм, который вам очень понравился. Напишите другу с рекомендацией: опишите сюжет и объясните, почему он вам понравился.',
    promptEn: 'You have seen a film you love. Write to a friend recommending it. Describe the story and say why you liked it.',
    tipsRu: [
      'Представьте фильм: "J\'ai regardé un film fantastique..."',
      'Опишите сюжет в настоящем: "L\'histoire parle de..."',
      'Дайте причины: "parce que", "car"',
      'Рекомендуйте: "Je te conseille de regarder..."',
    ],
    tipsEn: [
      'Introduce film: "J\'ai regardé un film fantastique..."',
      'Describe plot in present: "L\'histoire parle de..."',
      'Give reasons: "parce que", "car"',
      'Recommend: "Je te conseille de regarder..."',
    ],
    minWords: 80,
    maxWords: 110,
    requiredElements: ['passé_composé', 'description', 'opinion', 'recommendation'],
  },

  // ─── A2: Email ────────────────────────────────────────────────────────────
  {
    slug: 'a2-email-hotel',
    titleRu: 'Email в отель',
    titleEn: 'Email to a hotel',
    level: 'A2' as const,
    writingType: 'email' as const,
    promptFr: 'Vous voulez réserver une chambre dans un hôtel. Écrivez un email pour demander les informations nécessaires : prix, disponibilité, petit-déjeuner inclus, etc.',
    promptRu: 'Вы хотите забронировать номер в отеле. Напишите email с запросом информации: цена, наличие мест, включён ли завтрак и т.д.',
    promptEn: 'You want to book a room at a hotel. Write an email asking for information: price, availability, breakfast included, etc.',
    tipsRu: [
      'Начните: "Madame, Monsieur," (немного формальнее)',
      'Запросите: "Pourriez-vous me donner des informations sur..."',
      'Задавайте вопросы: "Est-ce que le petit-déjeuner est inclus ?"',
      'Конец: "Dans l\'attente de votre réponse, cordialement,"',
    ],
    tipsEn: [
      'Open: "Madame, Monsieur," (slightly formal)',
      'Request: "Pourriez-vous me donner des informations sur..."',
      'Ask questions: "Est-ce que le petit-déjeuner est inclus ?"',
      'Close: "Dans l\'attente de votre réponse, cordialement,"',
    ],
    minWords: 80,
    maxWords: 120,
    requiredElements: ['formal_greeting', 'questions', 'formal_closing'],
  },

  // ─── A2: Description ──────────────────────────────────────────────────────
  {
    slug: 'a2-description-room',
    titleRu: 'Описание комнаты',
    titleEn: 'Description of a room',
    level: 'A2' as const,
    writingType: 'description' as const,
    promptFr: 'Décrivez votre chambre ou votre salon. Parlez des meubles, des couleurs et de ce que vous aimez dans cette pièce.',
    promptRu: 'Опишите свою комнату или гостиную. Расскажите о мебели, цветах и о том, что вам нравится в этой комнате.',
    promptEn: 'Describe your bedroom or living room. Talk about the furniture, colours and what you like about this room.',
    tipsRu: [
      'Расположение: "Dans ma chambre, il y a...", "Sur le mur..."',
      'Цвета: "Les murs sont blancs", "un canapé bleu"',
      'Мнение: "J\'aime ma chambre parce que..."',
      'Прилагательные: grand, petit, moderne, confortable',
    ],
    tipsEn: [
      'Location: "Dans ma chambre, il y a...", "Sur le mur..."',
      'Colours: "Les murs sont blancs", "un canapé bleu"',
      'Opinion: "J\'aime ma chambre parce que..."',
      'Adjectives: grand, petit, moderne, confortable',
    ],
    minWords: 60,
    maxWords: 100,
    requiredElements: ['furniture', 'colours', 'opinion'],
  },
  {
    slug: 'a2-description-person',
    titleRu: 'Описание человека',
    titleEn: 'Description of a person',
    level: 'A2' as const,
    writingType: 'description' as const,
    promptFr: 'Décrivez une personne importante pour vous (un ami, un membre de la famille). Parlez de son apparence physique et de son caractère.',
    promptRu: 'Опишите важного для вас человека (друга, члена семьи). Расскажите о его внешности и характере.',
    promptEn: 'Describe an important person in your life (a friend, a family member). Talk about their appearance and personality.',
    tipsRu: [
      'Внешность: "Il/Elle est grand(e), Il/Elle a les yeux..."',
      'Характер: "Il/Elle est sympa, drôle, généreux/généreuse"',
      'Почему важен: "Je l\'aime parce que..."',
      'Избегайте повторений: используйте "aussi", "de plus"',
    ],
    tipsEn: [
      'Appearance: "Il/Elle est grand(e), Il/Elle a les yeux..."',
      'Personality: "Il/Elle est sympa, drôle, généreux/généreuse"',
      'Why important: "Je l\'aime parce que..."',
      'Avoid repetition: use "aussi", "de plus"',
    ],
    minWords: 60,
    maxWords: 100,
    requiredElements: ['appearance', 'personality', 'opinion'],
  },
  {
    slug: 'a2-description-ville-natale',
    titleRu: 'Мой родной город',
    titleEn: 'My hometown',
    level: 'A2' as const,
    writingType: 'description' as const,
    promptFr: "Présentez votre ville natale. Décrivez son emplacement, sa taille, ses lieux principaux, son ambiance et expliquez ce que vous aimez ou n'aimez pas chez elle.",
    promptRu: 'Расскажите о вашем родном городе. Опишите его расположение, размер, главные места и атмосферу, и объясните, что вам нравится или не нравится.',
    promptEn: 'Describe your hometown. Tell its location, size, main places, atmosphere and explain what you like or dislike about it.',
    tipsRu: [
      'Локация: "Ma ville se trouve dans le nord de..."',
      'Размер: "C\'est une petite/grande ville d\'environ 50 000 habitants"',
      'Места: "Il y a un château, un marché, plusieurs parcs"',
      'Мнение: "J\'aime sa tranquillité, mais il manque..."',
    ],
    tipsEn: [
      'Location: "Ma ville se trouve dans le nord de..."',
      'Size: "C\'est une petite/grande ville d\'environ 50 000 habitants"',
      'Places: "Il y a un château, un marché, plusieurs parcs"',
      'Opinion: "J\'aime sa tranquillité, mais il manque..."',
    ],
    minWords: 100,
    maxWords: 140,
    requiredElements: ['location', 'size', 'places', 'opinion'],
  },
  {
    slug: 'a2-email-apology',
    titleRu: 'Email с извинениями',
    titleEn: 'Apology email',
    level: 'A2' as const,
    writingType: 'email' as const,
    promptFr: "Vous n'avez pas pu venir à un rendez-vous important avec un(e) ami(e). Écrivez un email pour vous excuser. Expliquez ce qui s'est passé et proposez de vous rattraper.",
    promptRu: 'Вы не смогли прийти на важную встречу с другом. Напишите email с извинениями: объясните, что случилось, и предложите загладить вину.',
    promptEn: "You couldn't make an important meeting with a friend. Write an email to apologise: explain what happened and offer to make it up.",
    tipsRu: [
      'Начните с извинений: "Je suis vraiment désolé(e) pour hier..."',
      'Объясните в passé composé: "Mon train a eu du retard", "Je suis tombé(e) malade"',
      'Предложите: "Est-ce qu\'on peut se voir samedi à la place ?"',
      'Закройте мягко: "Encore une fois, je suis désolé(e). À bientôt j\'espère."',
    ],
    tipsEn: [
      'Start with apology: "Je suis vraiment désolé(e) pour hier..."',
      'Explain in passé composé: "Mon train a eu du retard", "Je suis tombé(e) malade"',
      'Offer: "Est-ce qu\'on peut se voir samedi à la place ?"',
      'Close softly: "Encore une fois, je suis désolé(e). À bientôt j\'espère."',
    ],
    minWords: 80,
    maxWords: 120,
    requiredElements: ['apology', 'explanation', 'proposal', 'closing'],
  },

  // ─── B1: Lettre formelle ──────────────────────────────────────────────────
  {
    slug: 'b1-letter-complaint',
    titleRu: 'Жалоба в ресторан',
    titleEn: 'Complaint to a restaurant',
    level: 'B1' as const,
    writingType: 'letter_formal' as const,
    promptFr: 'Vous avez dîné dans un restaurant et vous n\'êtes pas satisfait(e) du service et de la nourriture. Écrivez une lettre de réclamation au directeur du restaurant.',
    promptRu: 'Вы поужинали в ресторане и остались недовольны обслуживанием и едой. Напишите письмо-жалобу директору ресторана.',
    promptEn: 'You had dinner at a restaurant and were not satisfied with the service and food. Write a complaint letter to the restaurant manager.',
    tipsRu: [
      'Начало: "Madame, Monsieur,"',
      'Представьтесь: "Je me permets de vous écrire au sujet de..."',
      'Опишите проблему с деталями',
      'Потребуйте: "Je vous demande de...", "J\'exige..."',
      'Конец: "Dans l\'attente de votre réponse, veuillez recevoir, Madame/Monsieur, mes salutations distinguées."',
    ],
    tipsEn: [
      'Opening: "Madame, Monsieur,"',
      'Introduce: "Je me permets de vous écrire au sujet de..."',
      'Describe the problem with details',
      'Request: "Je vous demande de...", "J\'exige..."',
      'Closing: "Dans l\'attente de votre réponse, veuillez recevoir, Madame/Monsieur, mes salutations distinguées."',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['formal_greeting', 'problem_description', 'request', 'formal_closing'],
  },
  {
    slug: 'b1-letter-course-info',
    titleRu: 'Запрос информации о курсах',
    titleEn: 'Information request about courses',
    level: 'B1' as const,
    writingType: 'letter_formal' as const,
    promptFr: 'Vous souhaitez vous inscrire à des cours de français dans une école de langues. Écrivez une lettre pour demander des informations sur les cours, les horaires et les prix.',
    promptRu: 'Вы хотите записаться на курсы французского языка. Напишите письмо с запросом информации о курсах, расписании и ценах.',
    promptEn: 'You wish to enrol in French language courses at a language school. Write a letter requesting information about the courses, schedule and prices.',
    tipsRu: [
      'Conditionnel вежливости: "Je souhaiterais", "Pourriez-vous"',
      'Задайте конкретные вопросы параграфами',
      'Укажите ваш уровень и цели: "Je suis débutant(e)..."',
    ],
    tipsEn: [
      'Conditional for politeness: "Je souhaiterais", "Pourriez-vous"',
      'Ask specific questions by paragraph',
      'State your level and goals: "Je suis débutant(e)..."',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['formal_greeting', 'request_details', 'questions', 'formal_closing'],
  },

  // ─── B1: Blog article ─────────────────────────────────────────────────────
  {
    slug: 'b1-blog-travel',
    titleRu: 'Статья в блог о путешествии',
    titleEn: 'Blog article about a trip',
    level: 'B1' as const,
    writingType: 'blog_article' as const,
    promptFr: 'Vous avez visité une ville qui vous a beaucoup impressionné(e). Écrivez un article de blog pour recommander cette ville aux autres voyageurs. Parlez des lieux incontournables, de la cuisine et de l\'ambiance.',
    promptRu: 'Вы посетили город, который произвёл на вас большое впечатление. Напишите статью в блог с рекомендацией этого города другим путешественникам. Расскажите о достопримечательностях, кухне и атмосфере.',
    promptEn: 'You visited a city that greatly impressed you. Write a blog article recommending it to other travellers. Talk about must-see places, food and atmosphere.',
    tipsRu: [
      'Захватывающий заголовок и вступление-крючок',
      'Структура: достопримечательности / еда / советы',
      'Связки: "En ce qui concerne...", "D\'une part... d\'autre part..."',
      'Финальная рекомендация: "Je vous conseille vivement..."',
    ],
    tipsEn: [
      'Catchy title and hook introduction',
      'Structure: sights / food / tips',
      'Connectors: "En ce qui concerne...", "D\'une part... d\'autre part..."',
      'Final recommendation: "Je vous conseille vivement..."',
    ],
    minWords: 160,
    maxWords: 220,
    requiredElements: ['title', 'introduction', 'structured_paragraphs', 'connectors', 'recommendation'],
  },
  {
    slug: 'b1-blog-technology',
    titleRu: 'Блог: технологии в жизни',
    titleEn: 'Blog: technology in daily life',
    level: 'B1' as const,
    writingType: 'blog_article' as const,
    promptFr: 'Écrivez un article de blog sur la place de la technologie dans votre vie quotidienne. Parlez des avantages et des inconvénients de l\'utilisation des smartphones et des réseaux sociaux.',
    promptRu: 'Напишите статью в блог о роли технологий в вашей повседневной жизни. Расскажите о плюсах и минусах использования смартфонов и соцсетей.',
    promptEn: 'Write a blog article about the role of technology in your daily life. Discuss the advantages and disadvantages of using smartphones and social media.',
    tipsRu: [
      'Вступление: "De nos jours, les technologies occupent une place importante..."',
      'Плюсы: "D\'un côté...", "Premièrement..."',
      'Минусы: "D\'un autre côté...", "Cependant...", "Néanmoins..."',
      'Личная позиция в заключении',
    ],
    tipsEn: [
      'Introduction: "De nos jours, les technologies occupent une place importante..."',
      'Pros: "D\'un côté...", "Premièrement..."',
      'Cons: "D\'un autre côté...", "Cependant...", "Néanmoins..."',
      'Personal position in conclusion',
    ],
    minWords: 160,
    maxWords: 220,
    requiredElements: ['introduction', 'advantages', 'disadvantages', 'connectors', 'conclusion'],
  },

  // ─── B1: Essay ────────────────────────────────────────────────────────────
  {
    slug: 'b1-essay-sport',
    titleRu: 'Эссе: спорт обязателен?',
    titleEn: 'Essay: is sport compulsory?',
    level: 'B1' as const,
    writingType: 'essay' as const,
    promptFr: 'Dans votre école, une nouvelle règle oblige tous les élèves à faire du sport trois fois par semaine. Êtes-vous pour ou contre cette règle ? Donnez votre avis et justifiez-le avec des arguments.',
    promptRu: 'В вашей школе ввели новое правило: все ученики обязаны заниматься спортом три раза в неделю. Вы за или против? Выразите своё мнение и подкрепите его аргументами.',
    promptEn: 'Your school has introduced a new rule requiring all students to do sport three times a week. Are you for or against this rule? Give your opinion with arguments.',
    tipsRu: [
      'Чёткая позиция с самого начала: "Je pense que..." / "À mon avis..."',
      'Минимум 2 аргумента с примерами',
      'Используйте: "En effet", "Par exemple", "De plus", "Cependant"',
      'Заключение: подтвердите позицию + перспектива',
    ],
    tipsEn: [
      'Clear position from the start: "Je pense que..." / "À mon avis..."',
      'At least 2 arguments with examples',
      'Use: "En effet", "Par exemple", "De plus", "Cependant"',
      'Conclusion: restate position + perspective',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['opinion', 'arguments', 'examples', 'connectors', 'conclusion'],
  },
  {
    slug: 'b1-essay-internet',
    titleRu: 'Эссе: интернет — хорошо или плохо?',
    titleEn: 'Essay: is the internet good or bad?',
    level: 'B1' as const,
    writingType: 'essay' as const,
    promptFr: 'Internet a transformé notre façon de vivre. Pensez-vous que l\'internet a plus d\'avantages ou d\'inconvénients ? Rédigez un texte argumenté en donnant des exemples précis.',
    promptRu: 'Интернет изменил наш образ жизни. Считаете ли вы, что у интернета больше плюсов или минусов? Напишите аргументированный текст с конкретными примерами.',
    promptEn: 'The internet has transformed the way we live. Do you think the internet has more advantages or disadvantages? Write an argumentative text with specific examples.',
    tipsRu: [
      'Структура: тезис → аргументы → контраргументы → вывод',
      'Используйте: "bien que", "même si", "pourtant"',
      'Конкретные примеры из жизни усиливают аргументы',
    ],
    tipsEn: [
      'Structure: thesis → arguments → counterarguments → conclusion',
      'Use: "bien que", "même si", "pourtant"',
      'Concrete real-life examples strengthen arguments',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['thesis', 'arguments', 'counterarguments', 'connectors', 'conclusion'],
  },
  {
    slug: 'b1-essay-city-vs-country',
    titleRu: 'Эссе: город или деревня?',
    titleEn: 'Essay: city or countryside?',
    level: 'B1' as const,
    writingType: 'essay' as const,
    promptFr: 'Préférez-vous habiter en ville ou à la campagne ? Expliquez votre choix en donnant au moins trois arguments et des exemples de votre vie quotidienne.',
    promptRu: 'Вы предпочитаете жить в городе или в деревне? Объясните свой выбор, приведя не менее трёх аргументов и примеров из повседневной жизни.',
    promptEn: 'Do you prefer to live in a city or in the countryside? Explain your choice with at least three arguments and examples from your daily life.',
    tipsRu: [
      'Три аргумента = три абзаца',
      'Используйте: "Premièrement", "Deuxièmement", "Enfin"',
      'Сравнения: "La ville est plus... que la campagne"',
    ],
    tipsEn: [
      'Three arguments = three paragraphs',
      'Use: "Premièrement", "Deuxièmement", "Enfin"',
      'Comparisons: "La ville est plus... que la campagne"',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['position', 'three_arguments', 'comparatives', 'conclusion'],
  },

  // ─── B1: Narrative ────────────────────────────────────────────────────────
  {
    slug: 'b1-narrative-funny-day',
    titleRu: 'Рассказ: смешной день',
    titleEn: 'Narrative: a funny day',
    level: 'B1' as const,
    writingType: 'narrative' as const,
    promptFr: 'Racontez une journée amusante ou inattendue que vous avez vécue. Décrivez ce qui s\'est passé, comment vous vous sentiez et ce que vous avez appris de cette expérience.',
    promptRu: 'Расскажите о весёлом или неожиданном дне, который вы пережили. Опишите, что произошло, как вы себя чувствовали и чему научил вас этот опыт.',
    promptEn: 'Tell the story of a funny or unexpected day you experienced. Describe what happened, how you felt and what you learned from this experience.',
    tipsRu: [
      'Используйте imparfait для описания (фон): "Il faisait beau..."',
      'Используйте passé composé для действий: "J\'ai rencontré..."',
      'Диалоги оживляют рассказ',
      'Хронология: "ce matin-là", "soudain", "quelques heures plus tard"',
    ],
    tipsEn: [
      'Use imparfait for description (background): "Il faisait beau..."',
      'Use passé composé for actions: "J\'ai rencontré..."',
      'Dialogue brings a story to life',
      'Chronology: "ce matin-là", "soudain", "quelques heures plus tard"',
    ],
    minWords: 150,
    maxWords: 200,
    requiredElements: ['imparfait', 'passé_composé', 'emotions', 'chronological_connectors'],
  },

  // ─── B2: Essai argumentatif ───────────────────────────────────────────────
  {
    slug: 'b2-essay-social-media',
    titleRu: 'Эссе: соцсети и общество',
    titleEn: 'Essay: social media and society',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: 'Les réseaux sociaux ont-ils transformé positivement ou négativement les relations humaines ? Rédigez un essai argumenté en vous appuyant sur des exemples concrets et en envisageant différents points de vue.',
    promptRu: 'Положительно или отрицательно соцсети изменили человеческие отношения? Напишите аргументированное эссе, опираясь на конкретные примеры и рассматривая разные точки зрения.',
    promptEn: 'Have social media transformed human relationships positively or negatively? Write an argumentative essay using concrete examples and considering different perspectives.',
    tipsRu: [
      'Структура DELF B2: introduction (accroche + problématique + annonce du plan) → développement (2 parties) → conclusion (bilan + ouverture)',
      'Subjonctif: "Bien que les réseaux sociaux permettent...", "Il est indéniable que..."',
      'Nuance: "Certes... mais...", "Il convient néanmoins de..."',
      'Registre soutenu: éviter "je pense", préférer "il semble que", "force est de constater"',
    ],
    tipsEn: [
      'DELF B2 structure: introduction (hook + question + plan) → development (2 parts) → conclusion (summary + opening)',
      'Subjunctive: "Bien que les réseaux sociaux permettent...", "Il est indéniable que..."',
      'Nuance: "Certes... mais...", "Il convient néanmoins de..."',
      'Formal register: avoid "je pense", prefer "il semble que", "force est de constater"',
    ],
    minWords: 250,
    maxWords: 400,
    requiredElements: ['hook', 'problematique', 'two_parts', 'subjonctif', 'nuance', 'conclusion_ouverture'],
  },
  {
    slug: 'b2-essay-education',
    titleRu: 'Эссе: нужна ли реформа образования?',
    titleEn: 'Essay: is educational reform needed?',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: 'Certains pensent que le système éducatif actuel doit être profondément réformé pour préparer les jeunes aux défis du XXIe siècle. Partagez-vous ce point de vue ? Développez votre argumentation.',
    promptRu: 'Некоторые считают, что нынешняя система образования нуждается в глубокой реформе, чтобы подготовить молодёжь к вызовам XXI века. Разделяете ли вы эту точку зрения? Развейте свою аргументацию.',
    promptEn: 'Some believe the current education system needs profound reform to prepare young people for the challenges of the 21st century. Do you share this view? Develop your argument.',
    tipsRu: [
      'Начните с факта или цифры: "Selon une étude récente..."',
      'Thesis statement в конце введения',
      'Counterarguments strengthen the essay: "On pourrait objecter que..."',
      'Лексика: réforme, compétences, innovation pédagogique, numérique',
    ],
    tipsEn: [
      'Open with a fact or figure: "Selon une étude récente..."',
      'Thesis statement at end of introduction',
      'Counterarguments strengthen the essay: "On pourrait objecter que..."',
      'Vocabulary: réforme, compétences, innovation pédagogique, numérique',
    ],
    minWords: 250,
    maxWords: 400,
    requiredElements: ['hook', 'thesis', 'arguments', 'counterarguments', 'formal_register', 'conclusion'],
  },
  {
    slug: 'b2-essay-environment',
    titleRu: 'Эссе: экологический кризис',
    titleEn: 'Essay: ecological crisis',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: 'Face à l\'urgence climatique, certains estiment que les individus doivent changer radicalement leurs habitudes de consommation, tandis que d\'autres pensent que ce sont les gouvernements et les entreprises qui doivent agir. Quelle est votre position ?',
    promptRu: 'Перед лицом климатической угрозы одни считают, что люди должны кардинально изменить потребительские привычки, другие — что действовать должны правительства и компании. Какова ваша позиция?',
    promptEn: 'Faced with the climate emergency, some argue individuals must radically change their consumption habits, while others think governments and companies must act. What is your position?',
    tipsRu: [
      'Обе стороны дискуссии → диалектическая структура',
      'Лексика: transition énergétique, empreinte carbone, développement durable',
      'Subjonctif в придаточных: "bien que chaque geste compte..."',
      'Ouverture: задайте вопрос о будущем',
    ],
    tipsEn: [
      'Both sides of debate → dialectical structure',
      'Vocabulary: transition énergétique, empreinte carbone, développement durable',
      'Subjunctive in clauses: "bien que chaque geste compte..."',
      'Opening: pose a question about the future',
    ],
    minWords: 250,
    maxWords: 400,
    requiredElements: ['dialectical_structure', 'both_perspectives', 'subjonctif', 'environment_vocab', 'conclusion_ouverture'],
  },

  // ─── B2: Lettre formelle ──────────────────────────────────────────────────
  {
    slug: 'b2-letter-editor',
    titleRu: 'Письмо в редакцию',
    titleEn: 'Letter to the editor',
    level: 'B2' as const,
    writingType: 'letter_formal' as const,
    promptFr: 'Vous avez lu un article dans un journal qui défend une position avec laquelle vous n\'êtes pas d\'accord. Écrivez une lettre à la rédaction pour exprimer votre désaccord et présenter votre point de vue.',
    promptRu: 'Вы прочитали статью в газете, с позицией которой не согласны. Напишите письмо в редакцию, выразив своё несогласие и представив свою точку зрения.',
    promptEn: 'You read a newspaper article you disagree with. Write a letter to the editor expressing your disagreement and presenting your point of view.',
    tipsRu: [
      'Начало: "Monsieur le Rédacteur en chef," + чёткая ссылка на статью',
      'Вежливое несогласие: "Je me permets cependant de nuancer ces propos..."',
      'Аргументы с доказательствами',
      'Конец: "Je vous prie d\'agréer, Monsieur, l\'expression de mes salutations distinguées."',
    ],
    tipsEn: [
      'Opening: "Monsieur le Rédacteur en chef," + clear reference to article',
      'Polite disagreement: "Je me permets cependant de nuancer ces propos..."',
      'Arguments with evidence',
      'Closing: "Je vous prie d\'agréer, Monsieur, l\'expression de mes salutations distinguées."',
    ],
    minWords: 250,
    maxWords: 350,
    requiredElements: ['formal_greeting', 'article_reference', 'polite_disagreement', 'arguments', 'very_formal_closing'],
  },

  // ─── B2: Narrative ────────────────────────────────────────────────────────
  {
    slug: 'b2-narrative-turning-point',
    titleRu: 'Рассказ: момент, изменивший жизнь',
    titleEn: 'Narrative: a life-changing moment',
    level: 'B2' as const,
    writingType: 'narrative' as const,
    promptFr: 'Racontez un événement ou une rencontre qui a changé votre façon de voir le monde. Soignez la narration, les descriptions et les émotions. Vous pouvez utiliser des faits réels ou fictifs.',
    promptRu: 'Расскажите о событии или встрече, которые изменили ваш взгляд на мир. Уделите внимание повествованию, описаниям и эмоциям. Можно использовать реальные или вымышленные факты.',
    promptEn: 'Tell the story of an event or encounter that changed your outlook on the world. Pay attention to narration, descriptions and emotions. You may use real or fictional events.',
    tipsRu: [
      'Начните in medias res (с середины действия)',
      'Богатое описание: imparfait для фона, passé simple/composé для действий',
      'Внутренний монолог передаёт эмоции',
      'Финал: трансформация — кем стал рассказчик',
    ],
    tipsEn: [
      'Start in medias res (in the middle of the action)',
      'Rich description: imparfait for background, passé simple/composé for actions',
      'Interior monologue conveys emotions',
      'Ending: transformation — who the narrator became',
    ],
    minWords: 250,
    maxWords: 400,
    requiredElements: ['vivid_description', 'imparfait_passé', 'emotions', 'narrative_arc', 'transformation'],
  },

  // ─── B2: Essai argumentatif (extras) ───────────────────────────────────────
  {
    slug: 'b2-essay-teletravail',
    titleRu: 'Удалённая работа: будущее или иллюзия?',
    titleEn: 'Remote work: future or illusion?',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: "Depuis la pandémie, le télétravail s'est généralisé dans de nombreux secteurs. Pour certains, c'est une avancée majeure ; pour d'autres, une perte de lien social et de cohésion d'équipe. Le télétravail représente-t-il le modèle d'organisation du futur ? Rédigez un essai argumenté en présentant plusieurs perspectives avant d'exposer la vôtre.",
    promptRu: 'После пандемии удалённая работа стала нормой во многих сферах. Для одних это шаг вперёд, для других — потеря социальных связей и командного духа. Является ли удалёнка моделью организации будущего? Напишите эссе, рассмотрев несколько точек зрения и обозначив свою.',
    promptEn: 'Since the pandemic, remote work has spread across many sectors. For some, it is a major advance; for others, a loss of social bonds and team cohesion. Does remote work represent the organisational model of the future? Write an argumentative essay presenting several perspectives before stating your own.',
    tipsRu: [
      'Введение: контекст пандемии + ваш тезис',
      'Один абзац — плюсы (гибкость, экономия времени)',
      'Второй абзац — минусы (изоляция, переработки)',
      'Третий абзац — нюансы (отрасли, типы должностей)',
      'Заключение: ваша позиция + перспектива',
      'Связки: "d\'une part", "néanmoins", "toutefois", "en définitive"',
    ],
    tipsEn: [
      'Introduction: pandemic context + your thesis',
      'One paragraph on benefits (flexibility, saved commute time)',
      'One paragraph on drawbacks (isolation, overwork)',
      'One paragraph on nuances (sectors, role types)',
      'Conclusion: your position + outlook',
      'Connectors: "d\'une part", "néanmoins", "toutefois", "en définitive"',
    ],
    minWords: 250,
    maxWords: 400,
    requiredElements: ['multi_perspective', 'connectors', 'thesis', 'examples', 'conclusion'],
  },
  {
    slug: 'b2-essay-ia-creativite',
    titleRu: 'ИИ и творчество: угроза или инструмент?',
    titleEn: 'AI and creativity: threat or tool?',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: "L'intelligence artificielle générative produit désormais textes, images et musiques d'une qualité qui rivalise parfois avec celle des œuvres humaines. Selon vous, l'IA constitue-t-elle une menace pour la création artistique ou un nouvel outil au service des artistes ? Argumentez en mobilisant des exemples concrets.",
    promptRu: 'Генеративный ИИ создаёт тексты, изображения и музыку качества, порой соперничающего с человеческим. По-вашему, ИИ — угроза художественному творчеству или новый инструмент в руках художников? Аргументируйте, опираясь на конкретные примеры.',
    promptEn: 'Generative AI now produces texts, images and music of a quality that sometimes rivals human work. In your view, does AI constitute a threat to artistic creation or a new tool at the service of artists? Argue your case with concrete examples.',
    tipsRu: [
      'Введение: бурное развитие генеративного ИИ + ваш центральный вопрос',
      'Контр-аргумент: чем ИИ может угрожать художникам',
      'Аргумент: как художники уже используют ИИ как инструмент',
      'Нюанс: вопросы авторства, обучения моделей на чужих работах',
      'Заключение: ваша позиция и почему',
      'Используйте: subjonctif ("bien que", "à condition que"), conditionnel',
    ],
    tipsEn: [
      'Introduction: rapid AI rise + your central question',
      'Counter-argument: how AI may threaten artists',
      'Argument: how artists already use AI as a tool',
      'Nuance: authorship issues, training on others\' work',
      'Conclusion: your position and why',
      'Use: subjonctif ("bien que", "à condition que"), conditionnel',
    ],
    minWords: 280,
    maxWords: 400,
    requiredElements: ['examples', 'counter_argument', 'nuance', 'subjonctif', 'conclusion'],
  },
  {
    slug: 'b2-essay-tradition-modernite',
    titleRu: 'Традиции против современности',
    titleEn: 'Tradition vs modernity',
    level: 'B2' as const,
    writingType: 'essay' as const,
    promptFr: "Dans un monde qui évolue à toute vitesse, certaines traditions disparaissent ou se transforment. Faut-il s'efforcer de préserver les traditions, ou les laisser évoluer librement avec la société ? Rédigez un essai en illustrant votre propos d'exemples tirés de la culture, de la cuisine, de la langue ou des pratiques sociales.",
    promptRu: 'В быстро меняющемся мире некоторые традиции исчезают или преобразуются. Стоит ли стараться сохранять традиции или позволить им свободно эволюционировать вместе с обществом? Напишите эссе, проиллюстрировав вашу мысль примерами из культуры, кухни, языка или социальных практик.',
    promptEn: 'In a rapidly changing world, some traditions vanish or transform. Should we strive to preserve traditions, or let them evolve freely with society? Write an essay illustrating your point with examples from culture, cuisine, language or social practices.',
    tipsRu: [
      'Введение: рамка вопроса + ваш тезис',
      'Аргумент за сохранение: идентичность, преемственность, наследие',
      'Контр-аргумент: вред окостеневших традиций, право общества меняться',
      'Синтез: какие традиции стоит сохранять, а какие — пересматривать',
      'Примеры: гастрономия UNESCO, феминизация языка, праздники',
      'Связки уровня B2: "à supposer que", "pourvu que", "loin de"',
    ],
    tipsEn: [
      'Introduction: framing of the question + your thesis',
      'Pro-preservation: identity, continuity, heritage',
      'Counter: harm of frozen traditions, society\'s right to change',
      'Synthesis: which traditions to keep, which to rethink',
      'Examples: UNESCO gastronomy, language féminisation, holidays',
      'B2-level connectors: "à supposer que", "pourvu que", "loin de"',
    ],
    minWords: 280,
    maxWords: 400,
    requiredElements: ['thesis', 'counter_argument', 'synthesis', 'examples', 'subjonctif'],
  },
];
